libopenstorage/stork

specs/stork-deployment.yaml

Fixes #19 
Verified on v1.8.0 kubernetes cluster.

Fix RBAC permissions for stork-account on ConfigMaps

---

drivers/volume/portworx/portworx.go

Portworx driver: Check for source not being nil during inspect

---

drivers/volume/portworx/portworx.go
pkg/snapshot/snapshotprovisioner.go

- When creating snapshots users need to provide comma seperated regexes
with "stork/snapshot-restore-namespaces" annotaion to specify which
namespaces the snapshot can be restored to
- When creating PVC from snapshots, if a snapshot exists in another
namespace, the snapshot namespace should be specified with
"stork/snapshot-source-namespace" annotation
Issue #71

Add support to restore snapshots to different namespaces

---

vendor/github.com/portworx/sched-ops/k8s/k8s.go
vendor/vendor.json

Update sched-ops vendor so that snapshot validation will continue even if the first validate fails

---

drivers/volume/portworx/portworx.go
pkg/snapshot/rule/rule.go
test/integration_test/specs/mysql-3d-snap/px-presnap-rule.yaml

1) Don't send the background termination channel if there are no background commands
2) Handle situations where there could be more than one background actions and the first one has a single pod
Fixes #131

Background command fixes

---

drivers/volume/volume.go
pkg/extender/extender.go
pkg/monitor/monitor.go
test/integration_test/common_test.go

Also updated test verification

 Update health monitor to also use better node matching logic

---

drivers/volume/mock/mock.go
drivers/volume/volume.go
pkg/extender/extender.go
pkg/extender/extender_test.go
pkg/monitor/monitor.go
test/integration_test/common_test.go

This is for environments like K8s on DC/OS where the kubelet is running
in a containerized environment and has a different hostname than the physical
node
Need to make some more changes in the integration test to match the node correctly when verifying the scheduled node. Will submit that as a separate change.

When matching nodes check for internalIP incase hostnames are different

---

Makefile

According to this stackoverflow post:
https://stackoverflow.com/questions/52784861/cannot-install-golint-package-wrong-import-path
the import path of golint is here:
https://github.com/golang/lint#installation
and changed recently due to this:
due to this: https://github.com/golang/lint/commit/9a272034dedb2a3ed05231d5604ce17fb40f0e58

Fix import path of golint

---

pkg/snapshot/rule/rule.go

This fixes a `go vet` error with golang 1.11.1:
```
pkg/snapshot/rule/rule.go:427: Warnf format %v reads arg #3, but call has 2 args
make: *** [vet] Error 2
```

Add missing argument to logrus.Warnf

---

drivers/volume/portworx/portworx.go
pkg/monitor/monitor.go

The pvc name can exists across multiple namespaces
Also use task id to match status instead of volumename

[Portworx] Add namespace to migration task Id

---

.travis.yml

go 1.11.2 has more improvements to `go vet`, so use that for travis

Update golang version in travis to 1.11.2

---

pkg/initializer/initializer.go

- pkg/initializer/initializer.go:140:9: assigning the result of this type assertion to a variable (switch obj := obj.(type)) could eliminate the following type assertions:

fix new gosimple checks

---

pkg/apis/stork/v1alpha1/groupvolumesnapshot.go
pkg/apis/stork/v1alpha1/zz_generated.deepcopy.go
pkg/groupsnapshot/controllers/groupsnapshot.go
pkg/snapshot/provisioner.go

This is required so that we can use snapshots across namespaces ( https://docs.portworx.com/portworx-install-with-kubernetes/storage-operations/create-snapshots/snaps-single-pvc/#creating-snapshots-across-namespaces)

propagate group snap annotations to child volumesnapshots

---

drivers/volume/portworx/portworx.go
pkg/groupsnapshot/controllers/groupsnapshot.go

If any cloudsnap has failed, the get status API should not fail. Rather it should return the failed tasks in the response so controller can log an event and then reset and retry the group snapshot.
The PR also handles all failed cloud snapshot statues (stopped and aborted).

Return status for failed cloudsnapshots

---

Gopkg.lock
test/integration_test/common_test.go
test/integration_test/snapshot_test.go
test/integration_test/specs/group-cloud-snap-load/fio-pods.yaml
test/integration_test/specs/group-cloud-snap-load/group-cloud-snap.yaml
test/integration_test/specs/group-cloud-snap-load/pvcs.yaml
test/integration_test/specs/group-cloud-snap-load/sc.yaml
vendor/github.com/portworx/sched-ops/k8s/k8s.go

On stork:2.1.0-rc1, this catches the group snapshot issue with failure
```
=== RUN   TestMain/Snapshot/groupSnapshotTest
time="2019-02-17T00:04:18Z" level=info msg="[group-cloud-snap-load] Created Group snapshot: load-snapshot-cloud"
time="2019-02-17T00:04:18Z" level=info msg="[group-cloud-snap-load] Created PVC: vol1"
time="2019-02-17T00:04:18Z" level=info msg="[group-cloud-snap-load] Created PVC: vol2"
time="2019-02-17T00:04:18Z" level=info msg="[group-cloud-snap-load] Created PVC: vol3"
time="2019-02-17T00:04:18Z" level=info msg="[group-cloud-snap-load] Found existing storage class: portworx-repl2"
time="2019-02-17T00:04:18Z" level=info msg="[group-cloud-snap-load] Created Pod: loadvolumes1"
time="2019-02-17T00:04:19Z" level=info msg="[group-cloud-snap-load] Created Pod: loadvolumes2" …
```

 Add test to load volumes while group cloudsnap is being done

---

pkg/groupsnapshot/controllers/groupsnapshot.go

**Does this PR need a release note?:** yes
```release-note
Allow users to update the restore namespaces for a group volume snapshot after it was created
```

Allow users to update restore namespaces

---

pkg/apis/stork/v1alpha1/groupvolumesnapshot.go
pkg/groupsnapshot/controllers/groupsnapshot.go
test/integration_test/specs/group-cloud-snap-load/group-cloud-snap.yaml

The PR adds a new field maxRetries in the group volume snapshot spec that allows users to set a max retry count if a group snapshot fails. 
By default, the max retries is 0 and hence the controller will mark the group snapshot as failed if it's fails after it was triggered.
```release-note
Don't retry by default if a group snapshot fails after it is triggered. Allows users to set max retry count.
```

Add support for configurable retry count

---

Gopkg.lock
pkg/migration/controllers/migration.go
vendor/k8s.io/kubernetes/pkg/registry/core/service/allocator/BUILD
vendor/k8s.io/kubernetes/pkg/registry/core/service/allocator/bitmap.go
vendor/k8s.io/kubernetes/pkg/registry/core/service/allocator/interfaces.go
vendor/k8s.io/kubernetes/pkg/registry/core/service/allocator/utils.go
vendor/k8s.io/kubernetes/pkg/registry/core/service/portallocator/BUILD
vendor/k8s.io/kubernetes/pkg/registry/core/service/portallocator/allocator.go
vendor/k8s.io/kubernetes/pkg/registry/core/service/portallocator/operation.go

Bug
Re-migrating a svc fails when a node port is defined. We should be able to re-create the svc in this scenario
No
```release-note
Fixed continuous migration of service objects with NodePort defined
```
2.1

 Recreate service during migration for conflicting node port

---

pkg/apis/stork/v1alpha1/migration.go
pkg/apis/stork/v1alpha1/zz_generated.deepcopy.go
pkg/migration/controllers/migration.go
pkg/storkctl/migration.go
pkg/storkctl/migrationschedule.go

Bug
The `includeVolumes` field was defaulting to `false` if not specified in the spec
Yes
No
Yes, 2.1

Update bool in migration specs to pointers so that we can set defaults

---

drivers/volume/portworx/portworx.go
pkg/migration/controllers/migration.go
test/integration_test/migration_test.go
test/integration_test/specs/cassandra/cassandra.yaml
test/integration_test/specs/label-selector-migration/migration.yaml

feature
Adds support to use label selectors during migration
The label selector field present in the CRD is implemented
```release-note
Added support to use label selectors during migration
```
No

Add support to use labels to select resources during migration

---

pkg/extender/extender.go
pkg/extender/extender_test.go

Bug (Related to #291)
If there are no replicas online for a PVC the pod should not get scheduled, since it will not be able to mount the volume anyways. This change returns an error from the `Filter` request to prevent scheduling such pods till atleast one node with the replica comes back online
No
```release-note
Extender will now return an error if no replicas for a volume are online. This will prevent pods from getting scheduled if they can not use a PVC.
```
2.1

Extender: Return error if no replicas are online for a volume

---

pkg/apis/stork/v1alpha1/migrationschedule.go
pkg/apis/stork/v1alpha1/zz_generated.deepcopy.go
pkg/migration/controllers/migrationschedule.go
pkg/storkctl/migrationschedule.go
pkg/storkctl/migrationschedule_test.go

Also update storkctl for the flag
api-change
Added a flag to suspend migration schedules. Users don't need to delete the schedule to disable it
It is enabled by default.
Yes
Updated Spec:
```
kind: MigrationSchedule
metadata:
name: mysqlmigrationschedule
namespace: mysql
spec:
template:
spec:
clusterPair: remotecluster
includeResources: true
startApplications: false
namespaces:
- mysql
schedulePolicyName: testpolicy
suspend: false
```
Output of `storkctl`
```
$ storkctl get migrationschedule getmigrationschedulestatustest
NAME                             POLICYNAME   CLUSTERPAIR    SUSPEND   LAST-SUCCESS-TIME …
```

Add suspend flag to migrationschedule spec

---

test/integration_test/extender_test.go
test/integration_test/specs/mysql-repl-1/mysql.yaml

bug
>feature
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
We need to start PX on the node where it was stopped
no
no
2.1

Add node start and create separate storageclass for pvcownership test

---

test/integration_test/migration_test.go

- Sleep before checking for error message for invalid schedule. There could be
an error because the policy was not found since they are applied in a different
order. The next reconciliation will be after a minute
- Rollover to the next month/year when finding the right day
Integration-test fix
No
No
No

Fixes for migration schedule tests

---

Gopkg.lock
pkg/migration/controllers/migration.go
vendor/github.com/portworx/sched-ops/k8s/k8s.go

Feature
Adds support for migrating additional types of resources
No
```release-note
Added support to migrate following resources 
* DaemonSets
* ServiceAccounts (except default)
* ClusterRoles (if used in the namespace)
* ClusterRoleBindings (if used in the namespace)
```
No

Migrate additional resources

---

test/integration_test/migration_test.go

Adding 31 days for the monthly schedule test can cause the schedule to be
skipped for months with 30 days since the date of the month will be one ahead
Failing-test
No
No
No

Fix bumping time in migration schedule test

---

Gopkg.lock
Makefile
drivers/volume/mock/mock.go
pkg/monitor/monitor.go
pkg/monitor/monitor_test.go
test/integration_test/health_monitor_test.go
test/integration_test/specs/mysql-ss/mysql-ss.yaml

feature
unit-test
When kubelet is down on a node, pods go into node lost (< 1.13) or terminating (> 1.13) state. By default, for statefulsets, new pods aren't created. This results in manual recovery for operators.
This PR adds a monitor for pods in such a state and force deletes them so that a new replacement pod is spun up.
```release-note
Add support to force delete pods in unknown state that can happen when kubelet goes down on a node.
```
no

Add monitor for pods in unknown state

---

pkg/apis/stork/v1alpha1/migration.go
pkg/apis/stork/v1alpha1/zz_generated.deepcopy.go
pkg/migration/controllers/migration.go
pkg/storkctl/migration.go
pkg/storkctl/migration_test.go
pkg/storkctl/migrationschedule.go
pkg/storkctl/migrationschedule_test.go

Also display elapesed time using storkctl
Enhancement
Helps display more user friendly info for migration
Yes, adds a FinishTimestamp in migration status and displays migration times with `storkctl`
```release-note
* Added FinishTimestamp field in Migration status
* `storkctl` now displays elapsed time for migration and migrationschedule objects
```
No

Store finish timestamp for migration

---

pkg/storkctl/create.go
pkg/storkctl/delete.go
pkg/storkctl/get.go
pkg/storkctl/groupsnapshot.go
pkg/storkctl/groupsnapshot_test.go

Fixes #226
feature
unit-test
**What this PR does / why we need it**: Add storkctl support for group snapshots
**Does this PR change a user-facing CRD or CLI?**:  yes
create
```
storkctl create groupsnapshots --help
Create a group snapshot
Usage:
storkctl create groupsnapshots [flags]
Aliases:
groupsnapshots, groupsnapshot
Flags:
-h, --help                        help for groupsnapshots
--maxRetries int              Number of times to retry the groupvolumesnapshot on failure
--opts strings                Comma-separated list of options to provide to the storage driver. These are in the format key1=value1,key2=value2. e.g portworx/snapshot-type=cloud
--postExecRule string         Rule to run after executing …
```

storkctl support for group snapshots

---

drivers/volume/portworx/portworx.go

>bug
GetClusterID for portworx will return an error if it gets an empty clusterID.
No
No
No

Portworx: Return an error when clusterID is empty

---

drivers/volume/portworx/portworx.go
pkg/clusterdomains/controllers/clusterdomainstatus.go

>bug
- cluster.Uuid is not implemented on Portworx REST client. Use cluster.Enumerate to get the clusterID
- Ignore already exists error while creating ClusterDomainsStatus
No
No
No

ClusterDomains controller changes.

---

cmd/stork/stork.go
pkg/extender/extender.go
pkg/extender/extender_test.go

Improvement
No
```release-note
Added events for pods in case of scheduling failure from the extender
```
2.2 and 2.1

Add events to pod from extender in case of errors

---

test/integration_test/snapshot_test.go

Gives it enough time to wait for the trigger and status to be updated
Failing test
No
No
2.2

Increase wait time in snapshotschedule test

---

Gopkg.lock
cmd/stork/stork.go
pkg/migration/controllers/migration.go
pkg/migration/migration.go
pkg/monitor/monitor.go
pkg/resourcecollector/clusterrole.go
pkg/resourcecollector/persistentvolume.go
pkg/resourcecollector/persistentvolumeclaim.go
pkg/resourcecollector/resourcecollector.go
pkg/resourcecollector/secret.go
pkg/resourcecollector/service.go
pkg/resourcecollector/serviceaccount.go
vendor/github.com/portworx/sched-ops/k8s/k8s.go

Can be used by other modules to get unstructured objects from a namepsace
and matching label selectors
Cleanup
Refactored code so that same code can be shared by multiple modules
No
No
No

Move resource collection logic from migration controller

---

Gopkg.lock
vendor/github.com/portworx/sched-ops/k8s/k8s.go

Bug
Fixes a memory leak when watches are re-established
No
```release-note
Fixed a memory leak when watches are re-established
```
2.2

Vendor update for sched-ops

---

pkg/clusterdomains/controllers/clusterdomainstatus.go

>bug
Prints a log line when the cluster domain controller fails to fetch cluster domain info from the driver.
No
No
No

Print an error log when the controller fails to fetch cluster domain info

---

pkg/clusterdomains/controllers/clusterdomainstatus.go

Bug
The clusterdomain lists weren't bein checked correctly
No
```release-note
Fixed comparing cluster domains to see if an update is required in the status
```
2.2 (For 2.2.3)

Fix matching of clusterdomain list

---

cmd/stork/stork.go
pkg/dbg/dbg.go

SIGUSR1 can be used to dump memory and goroutine info
SIGUSR2 can be used to toggle collection of cpuprofile
Enhancement
No
```release-note
Add signal handlers to dump memory info for debugging
```

Add debug package to dump profiles

---

pkg/storkctl/migration.go

Bug
No
```release-note
Storkctl: Activating DeploymentConfig for migrations
```
2.2

Add deploymentconfig to activate migrations for storkctl

---

pkg/schedule/schedule.go
pkg/schedule/schedule_test.go

Also added UT
Bug
The schedule would not get triggered if the current time was exactly at the next trigger time
No
```release-note
Fixed schedules not getting triggered if the current time is exactly at next trigger time
```
2.2 (For 2.2.3)

Fix schedule to trigger if next trigger is exactly at current time

---

drivers/volume/portworx/portworx.go
pkg/migration/controllers/migration.go

Enhancement
No
```release-note
* Optimized migrations for clusterrole and clusterrolebindings
* For clusterrolebindings using the object that we are iterating over
* For clusterrole, getting a list of crbs initially and using that to check if migration
is required
* Skipping migration of `deployer` and `builder` service accounts which are automatically created
on  OCP
```
No, PR is for 2.2 branch since code has changed in master for 2.3. Will create a separate PR for master.

Optimize migrations for clusterrole and clusterrolebindings

---

drivers/volume/portworx/portworx.go
pkg/apis/stork/v1alpha1/clusterdomainsstatus.go
pkg/clusterdomains/controllers/clusterdomainstatus.go
pkg/clusterdomains/controllers/clusterdomainupdate.go
pkg/migration/controllers/migrationschedule.go
pkg/migration/migration.go
pkg/storkctl/clusterdomainsstatus.go
pkg/storkctl/clusterdomainsstatus_test.go

Enhancement
Migrations should be stopped if the local domain isn't active.
Adds `localDomain` in ClusterDomainStatus
Local domain is also printed when checking the status with `storkctl`
```release-note
* Migration schedules will now be suspended if the local domain is inactive
* Updated `storkctl` to print local cluster domain
```
2.2

 Suspend migration schedules if the local clusterdomain is inactive

---

pkg/resourcecollector/clusterrole.go
pkg/resourcecollector/resourcecollector.go
pkg/resourcecollector/serviceaccount.go

For clusterrole, get a list of crbs initially and use that to check if migration
is required
Also skip deployer and builder service accounts which are automatically created
on  OCP
Enhancement
No
Use from #381 
No, #381 already merged for 2.2

Optimize migrations for clusterrole

---

pkg/schedule/schedule.go
pkg/schedule/schedule_test.go
pkg/storkctl/migrationschedule.go
pkg/storkctl/migrationschedule_test.go

Also update strokctl to use a default policy for migration schedule
Enhancement
No
```release-note
* Added some default schedule policies:
* default-migration-policy: Triggers after every minute
* default-interval-policy: Triggers after every hour. Retains last 10
* default-daily-policy: Triggers every day at 12:00am. Retains last 7
* default-weekly-policy: Triggers every Sunday@12:00am. Retains last 4
* default-monthly-policy: Triggers every 15th day of the month at 12:00am. Retains last 12.
```
2.2

Create some default schedule policies

---

pkg/storkctl/migration.go
pkg/storkctl/migration_test.go

Enhancement
Yes, updates output of `storkctl get migrations`
```release-note
storkctl now prints `N/A` when volumes or resources are not being migrated
```
2.2

Print N/A for volumes and resources when not migrating them

---

pkg/storkctl/clusterdomainupdate.go
pkg/storkctl/clusterdomainupdate_test.go

>feature
This PR adds wait option to `storkctl activate clusterdomain`, making command as sync operation
Yes, storkctl activate/deactivate were returning success msg, just because the CRD was created. 
```release-note
To wait for cluster domain update operation result, please provide --wait/-w flag to 
storkctl activate/deactivate clusterdomain -w
```

Add wait poll support for storkctl activate/deactivae cluster-domain

---

pkg/storkctl/migration.go
pkg/storkctl/migration_test.go

> enhancement
Add wait support for storkctl ```create migrations```
Yes, with -w/wait option to storkctl create migration,  user can wait till operation completes
eg output :-
```
STAGE		STATUS
Volumes		InProgress
Volumes		InProgress
Final		Failed
Migration ngnixmigration14 failed
```
```release-note
```
yes

Add wait options for storkctl create migrations

---

Gopkg.lock
Gopkg.toml

Signed-off-by: Aditya Dani <aditya@portworx.com>
>cleanup
Update the dep versions for portworx/sched-ops and portworx/torpedo packages.
No
No
Yes - 2.2

Update dep versions for sched-ops and torpedo packages

---

drivers/volume/portworx/portworx.go
pkg/apis/stork/v1alpha1/clusterdomainsstatus.go

>bug
Portworx Driver
- Change the GetClusterDomains API to not return an error when it fails to fetch the volume list
- Add a new status SyncStatusUnknown
No
Yes
```release-note
Add a new SyncStatus Unknown when the driver fails to fetch the storage sync status
```
Yes - 2.2

Portworx ClusterDomainsStatus: Do not fail on volume enumerate errors.

---

Makefile
drivers/volume/portworx/portworx.go
pkg/migration/controllers/migration.go
pkg/migration/controllers/migrationschedule.go

Enhancement
No
```release-note
* Migrations will be marked as Failed if the local cluster domain is inactive
* Updated migration behavior for PVs
* Setting reclaim policy to Retain if volumes aren't being migrated
* Updating PV if it already exists instead of deleting and creating
```
No, this is for 2.2 branch. Will send separate PR for master since code has changed there.

Fail migrations if domain is inactive

---

Gopkg.lock
pkg/storkctl/create.go
pkg/storkctl/delete.go
pkg/storkctl/get.go
pkg/storkctl/snapshot.go
pkg/storkctl/snapshot_test.go
vendor/github.com/portworx/sched-ops/k8s/k8s.go

>feature
>unit-test
PR add storctl support for in place volume restore. Consecutive PR for  https://github.com/libopenstorage/stork/pull/353
yes, add support for `volumesnapshotrestore` crd in storkctl.
```release-note
```

Add storcktl cmd for volumesnapshotrestore crd's

---

drivers/volume/portworx/portworx.go

>bug
If the Portworx driver doesn't find the ports it needs in the k8s service, fail the initialization. These ports on the service are required for the Portworx driver to function. So it's safer to explicitly fail the init if the ports are missing.
no
```release-note
Fixed an issue where Portworx driver would attempt to make API calls to a non-existing portworx service port.
```
**Does this change need to be cherry-picked to a release branch?**: 2.1.3, 2.2.5

[Portworx] Fail Portworx driver init if service doesn't have required ports

---

Makefile

Also update version to 2.2.5
Cleanup
No
No
No

Remove gosimple as it is no longer available

---

pkg/applicationmanager/controllers/applicationbackup.go

It can return errors which should be reported back
Bug
No
No
No

When uploading objects don't close writer async

---

drivers/volume/portworx/portworx.go
pkg/snapshot/controllers/snapshotschedule.go

Values in labels have a smaller length limit and the info should be an
annotation anyways
Fixes #415
Bug
No
```release-note
Fixed issue with failing scheduled snapshots if the snapshot schedule name was longer than 64 characters
```
2.2

Store snapshot schedule info in annotations instead of labels

---

pkg/storkctl/clusterpair.go
pkg/storkctl/clusterpair_test.go

Bug
Yes, adds validation for name and namespace for `storkctl generate clusterpair` command
```release-note
* Added validation for `name` and `namespace` in the clusterpair generated with `storkctl generate clusterpair`
```
2.2

Validate name and namespace when generating clusterpair

---

drivers/volume/portworx/portworx.go
pkg/snapshot/controllers/snapshotrestore.go

>bug
- Fixes HA update failure for restore objects
- Added restoreAPICallBackoff  in case time require to detach volume is more
- Use updated PVC for marking/unmarking annotation
- Handle restore failed stage
No
2.0.3

Bug fixes for In-place volumesnapshot restore controller

---

test/integration_test/specs/cassandra/cassandra.yaml

The older version has a bug which could lead to an empty commit log file
which causes issues during restart
No
No
No

Update cassandra version in integration test

---

test/integration_test/test-deploy.sh

Add escape characters for quotes in the enable cluster domain flag
no
no
no

Fix flag for enabling cluster domain tests in integration tests.

---

test/integration_test/test-deploy.sh

Enable cluster domain environment variables should be a string for stork-test pod
no
no
no

Add quotes to the enable cluster domain flag.

---

.travis.yml

Build update
Updating go version to fix a vulnerability in the older version
No
```release-note
Update go version to 1.11.13 to fix [vulnerabilities](https://thenewstack.io/netflix-discovers-severe-kubernetes-http-2-vulnerabilities/) that were recently discovered
```
2.2

Update go version for travis build

---

drivers/volume/mock/mock.go
drivers/volume/volume.go
pkg/monitor/monitor.go
pkg/monitor/monitor_test.go

Bug
It is possible for the storage driver to return information for 2 nodes with the
same IP if a new node was re-using the IP from a node that was removed.
In that case the health monitor would incorrectly determine that the storage
driver was offline on the node.
This change removes offline nodes with duplicate IPs
No
```release-note
Fixed issue in health monitor to ignore duplicate node IPs which would cause pods to be deleted from nodes where storage was online
```
2.2

Add check in monitor to skip duplicate offline nodes with same IP

---

pkg/applicationmanager/controllers/applicationrestore.go
pkg/applicationmanager/controllers/backupsync.go

This was causing backups to be deleted by the k8s because the owner,
which is the backup schedule, won't be present on remote cluster
Bug
No
No
No

Remove owner ref from synced backups

---

specs/stork-deployment.yaml

It picks up the defaults from k8s 1.10 onwards
No
2.2, 2.1

Don't set predicates or priorities for scheduler

---

pkg/migration/controllers/migration.go
pkg/resourcecollector/serviceaccount.go

>bug
We don't maintain link between secrets while migrating `default` service account. This PR check and update imagepullSecrets for default service account
No
yes

Migrate image pull secrets associated with default service account

---

test/integration_test/applicationbackup_test.go

In case of an existing secret, the new secret object might have null values, including it's name
no
no
no

Use name from the existing secret object as new obj might be nil.

---

test/integration_test/clusterdomain_test.go
test/integration_test/common_test.go
test/integration_test/specs/cassandra-clusterdomain-migration/migration.yaml

Switch cluster domain migration test to cassandra from mysql
no
no
no

Use cassandra instead of mysql for clusterdomain migration.

---

drivers/volume/portworx/portworx.go
pkg/migration/controllers/migration.go

Also remove noisy log message
Bug
No
```release-note
Fixed issue during migration when an application didn't have annotations. This would cause failures when trying to add the replica count as an annotation
```
Yes, 2.2, but need to make separate changes since code has changed

Create annotations for app during migration if it doesn't exist

---

test/integration_test/applicationbackup_test.go

Need to set kubeconfig to source cluster after backup sync controller test.
no
no
no

Reset remote config

---

drivers/volume/mock/mock.go
pkg/monitor/monitor.go
pkg/monitor/monitor_test.go

>bug
* Need to make sure VolumeAttachment is ours before deleting
No
No
2.3.0

Check ownership of VolumeAttachment before deleting

---

Gopkg.lock
pkg/storkctl/snapshot.go
pkg/storkctl/snapshot_test.go
vendor/github.com/portworx/sched-ops/k8s/k8s.go

>bug
Fix volume count for volumesnapshotrestore 
Yes
Earlier volumesnapshotrestore output always show volume to be restore as zero. This PR changes volume count as per volume which are undergoing in place restore
eg.
```
[#vsrestore]# ./storkctl get volumesnapshotrestore
NAME                         SOURCE-SNAPSHOT             SOURCE-SNAPSHOT-NAMESPACE   STATUS       VOLUMES   CREATED
mysql-snap-group-inrestore   mysql-group-localsnapshot   default                     Successful   2         16 Sep 19 04:38 PDT
```

Correct volume count for storkctl snaprestore output

---

test/integration_test/clusterdomain_test.go

We found in cluster domain tests, that even after scaling down the cassandra stateful set, the pods were still running. By adding this extra check, we will make sure that the stateful set is completely scaled down before we migrate cassandra.
No
No
No

Check the scale factor of the application after scaling it down.

---

test/integration_test/applicationbackup_test.go

It serves 2 purposes:
1. We will delete all apps created as part of the test
2. Also tests "Retain" policy for application backups. 
no
no
no

Use retain policy for label selector test.

---

cmd/stork/stork.go
drivers/volume/portworx/portworx.go
pkg/applicationmanager/controllers/applicationbackup.go

Added the message that it is deprecated
Bug
No
```release-note
`migration-admin-namespace` parameter for stork has been deprecated. Please use `admin-namespace` instead.
```
2.3

Add the old parameter for cluster-admin-namespace

---

pkg/migration/controllers/migration.go
pkg/migration/controllers/migrationschedule.go

- Don't cancel migrations that are in Final stage
- Don't update migration schedule after prune if the object wasn't updated
Bug
No
```release-note
Optimized some operations for migration and migrationschedule to reduce K8s API calls
```
2.3

Some optimizations for migration

---

pkg/schedule/schedule.go

Previously if the mock time config map was not created we would end up using the
empty config map to start the watch
No
No
2.3

Use created config map for watch on mock time

---

test/integration_test/common_test.go

Update test flag parsing which was broken in go 1.13

---

specs/stork-deployment.yaml
specs/stork-scheduler.yaml

Also add csinodes permission for scheduler clusterrole,
required for k8s 1.16 onwards
>bug
>feature
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
```release-note
```

Update spec version for deployments

---

test/integration_test/common_test.go
test/integration_test/stork-test-pod.yaml
test/integration_test/test-deploy.sh

The stork volume driver used in integration tests needs to be parameterized.
This way we can support other drivers as well.
No
No
No

Parameterize stork volume driver for integration tests.

---

drivers/volume/portworx/portworx.go

>bug
HA update api need `pool uuids` passed in as `Nodes` of Replicasets
for starting restore we do the same
https://github.com/libopenstorage/stork/blob/d9e7b18d2bd63597f699b818f404b80070307856/drivers/volume/portworx/portworx.go#L1108
no
no
2.3.0

pass poolids to Nodeid for ha update api

---

test/integration_test/snapshot_restore_test.go

Currently snap restore tests won't be skipped if required, when running individually.
no
no
no

Ability to skip restore tests even when running individually.

---

test/integration_test/snapshot_restore_test.go
test/integration_test/snapshot_test.go

Currently, inplace restore tests don't wait on volume snaps to complete before proceeding to
volume restore
no
no
no

Wait for snapshot to complete in in-place restore tests

---

drivers/volume/portworx/portworx.go
pkg/snapshot/controllers/snapshotrestore.go

>bug
Px driver restore api is async, we need to wait till volume is in restore state before deleting restore snap objects
no
no
2.3
Integration test run:
```
time="2019-11-26T08:54:53Z" level=info msg="[mysql-cloudsnap-group-restore] Validated destroy of Deployment: mysql"
time="2019-11-26T08:54:53Z" level=info msg="[mysql-cloudsnap-group-restore] Destroyed group snapshot: mysql-group-cloudsnapshot"
time="2019-11-26T08:54:53Z" level=info msg="[mysql-cloudsnap-group-restore] Destroyed PVC: mysql-data-1"
time="2019-11-26T08:54:53Z" level=info …
```

[portworx] Wait for volume restore api to complete

---

Gopkg.lock
cmd/stork/stork.go
pkg/apis/stork/v1alpha1/migration.go
pkg/apis/stork/v1alpha1/zz_generated.deepcopy.go
pkg/applicationmanager/controllers/applicationbackup.go
pkg/applicationmanager/controllers/applicationclone.go
pkg/migration/controllers/migration.go
pkg/resourcecollector/clusterrole.go
pkg/resourcecollector/persistentvolume.go
pkg/resourcecollector/persistentvolumeclaim.go
pkg/resourcecollector/resourcecollector.go
vendor/github.com/portworx/sched-ops/k8s/k8s.go

**What type of PR is this?**\
>feature
With this user can able to cleanup deleted objects from destination during migration
yes, we have `AllowCleaningResources` flag to cleanup resources
no
yes, 2.30

Cleanup deleted objects from destination during migration

---

test/integration_test/migration_test.go
test/integration_test/specs/mysql-migration-schedule-interval/migrationschedule.yaml

Add integration test for migration cleanup feature #522 
no
no
2.3.0
Jenkins run:
```
Scheduler Status:  Next retry in: 10s
19:50:21 2019/11/22 14:20:21 Failed to validate custom spec : remoteclusterpair of type *v1alpha1.ClusterPair due to err: Storage Status:  	 Scheduler Status:  Next retry in: 10s
19:50:31 time="2019-11-22T14:20:31Z" level=info msg="[mysql-1-pvc] Validated ClusterPair: remoteclusterpair"
19:50:31 time="2019-11-22T14:20:31Z" level=info …
```

add integration test for migration cleanup feature

---

drivers/volume/portworx/portworx.go
pkg/clusterdomains/controllers/clusterdomainstatus.go
pkg/migration/controllers/migration.go
pkg/migration/controllers/migrationschedule.go
pkg/storkctl/common.go

>bug
Ensure px driver has 2.3.2 version for in place cloud snapshot restore feature
no
no
2.3.0

[portworx] bump px version for in place restore feature

---

drivers/volume/portworx/portworx.go

bug
The stork secrets implementation was lost in a recent vendor update. Openstorage now depends on lsecrets.Instance for all secrets calls. See the following in openstorage:
https://github.com/libopenstorage/openstorage/blob/7b164ed8270276bd627dca7e787ae8470db9b50c/pkg/auth/secrets/secrets.go#L40-L62
No
```release-note
NONE
```
Next patch release. This has been in master since
https://github.com/libopenstorage/stork/commit/dc4974e1cb9ac0abeeb7e90f8bae038fbd02bd1e
so, whichever release branches this commit is in.

Add stork secrets implementation based on lsecrets.Instance()

---

Gopkg.lock
pkg/migration/controllers/migration.go
pkg/resourcecollector/resourcecollector.go
pkg/storkctl/migration.go
pkg/storkctl/migration_test.go
vendor/github.com/portworx/sched-ops/k8s/k8s.go

Enhancement
No
```release-note
Added support to collect CRs during migration and application backup. Currently supports IBPPeer, IBPConsole, IBPOrdere and IBPCA
```
Yes, 2.3

Add support for some CRDs to resourcecollector

---

pkg/migration/controllers/clusterpair.go
pkg/migration/controllers/migration.go

Bug
No
```release-note
Fixed issue where the wrong namespace was being used when checking the admin cluster pair during migration
```
2.3

Use correct namespace when checking status of adminClusterPair

---

drivers/volume/azure/azure.go

Use it during restore so that it can be restored across resource groups
Bug
No
No
No

[Azure] Store the resource group for volumes during snapshot

---

.travis.yml
pkg/applicationmanager/controllers/applicationbackupschedule.go
pkg/migration/controllers/migration.go
pkg/migration/controllers/migrationschedule.go

Bug
No
```release-note
* The defaults are now set in the MigrationScheduleSpec if not provided
* The default ReclaimPolicy for ApplicationBackupSchedule has been changed to `Retain` so that the backups don't get deleted when the schedule object is deleted
```
2.3

Set defaults for the spec in migration schedule

---

drivers/volume/portworx/portworx.go
pkg/resourcecollector/resourcecollector.go

Bug
No
```release-note
- Portworx: Don't migrate volumes that have the skipResource annotation. Previously the PVC would not get migrated but the volume was still migrated
```
2.3

[Portworx] Don't migrate volumes which have the skipResource annotation

---

pkg/resourcecollector/resourcecollector.go

Bug
No
```release-note
Fixed an issue with ApplicationRestore where some objects (like Ingress) could not be restored because an invalid name was being used for the object type
```
2.3

Get the correct pluralized name of resources for the dynamic client

---

pkg/apis/stork/v1alpha1/applicationbackup.go
pkg/apis/stork/v1alpha1/applicationrestore.go
pkg/applicationmanager/controllers/applicationbackup.go
pkg/applicationmanager/controllers/applicationrestore.go

Improvement
Yes, Status is updated, no backward compatibility issue
```
* The status for `ApplicationBackup` and `ApplicationRestore` now has an overall status reason field
```
2.3

Add a reason field for the overall backup and restore status

---

test/integration_test/test-deploy.sh

For Ubuntu base images need 'jq' when running integration tests
no
no
2.3

Add apt-get install jq for ubuntu base images

---

test/integration_test/applicationbackup_test.go

Set allconfig currently gets set to blank
no
no
2.3

Set all configmap after default config map is correctly set

---

test/integration_test/Dockerfile
test/integration_test/common_test.go
test/integration_test/test-deploy.sh

When running integration tests on cloud platforms need to init auth plugins
no
no
2.3

Import k8s client auth in integration tests

---

pkg/schedule/cache.go
pkg/schedule/schedule.go

Improvement
```release-note
Added a cache for SchedulePolicy object to reduce calls to kube-apiserver
```
2.3

Add cache to for schedule policy

---

test/integration_test/applicationbackup_test.go
test/integration_test/common_test.go
test/integration_test/test-deploy.sh

In case of azure backups, stork needs env vars as used in px-azure secret in PX
no
no
2.3

For azure backups add env variables from px-azure secret

---

pkg/snapshot/controllers/snapshotrestore.go

>bug
We keep adding volume entries into restore status in case of failure, this PR fix adding duplicate volume to snapshot restore status
No
yes, 2.3.3
**Example Restore output**:
```
NAME                         SOURCE-SNAPSHOT             SOURCE-SNAPSHOT-NAMESPACE   STATUS   VOLUMES   CREATED
mysql-snap-group-inrestore   mysql-group-cloudsnapshot   default                              1         25 Mar 20 23:05 PDT
Wed Mar 25 23:11:40 PDT 2020
```
**kubectl describe volumesnapshotrestore.stork.libopenstorage.org/mysql-snap-group-inrestore**
```
Name: …
```

Avoid adding duplicate volume to restore status

---

test/integration_test/migration_backup_test.go

Reset kubeconfig to source cluster after every loop in the mig-backup test
no
no
2.3

Explicitly reset kubeconfig after every migration-backup loop

---

cmd/stork/stork.go

>bug
Skip starting web hook controller, if storage driver is not provided
no
no
2.4.0

Don't start webhook controller if driver is empty

---

drivers/volume/portworx/portworx.go
pkg/snapshot/controllers/snapshotschedule.go

Bug
No
```release-note
Fixed issue in `VolumeSnapshotSchedule` where the status could erroneously be set to `Failed` if there was an error while fetching the `VolumeSnapshot` 
```
2.4

Snap fixes

---

drivers/volume/portworx/portworx.go
pkg/applicationmanager/controllers/applicationbackup.go

Multiple updates were failing because of conflicts. Fetching latest object
before updating in pre exec path
Also if the pre exec rule fails the backup will be marked as Failed instead of
retrying
Bug
No
```release-note
Fixed handling of error during Pre-Exec rule in `ApplicationBackup`
```
2.4

Fix pre exec rule failure in application backup

---

drivers/volume/aws/aws.go
drivers/volume/azure/azure.go
drivers/volume/gcp/gcp.go
drivers/volume/portworx/portworx.go
drivers/volume/volume.go
pkg/applicationmanager/controllers/applicationrestore.go

This allows the Portworx driver to specify any secrets that it might require to
be created before starting the volume restore.
No-op in the other drivers for now.
Bug
No
```release-note
[Portworx] Fixed issue with restoring volumes that required Kubernetes secrets
```
2.3, 2.4

Allow drivers to return resources that should be restored before volumes

---

drivers/volume/aws/aws.go
drivers/volume/azure/azure.go
drivers/volume/gcp/gcp.go
drivers/volume/portworx/portworx.go

The init will be tried again when the APIs are called if init had failed
Bug
No
No
2.4

Don't block driver registration if init fails

---

test/integration_test/stork-test-pod.yaml
test/integration_test/test-deploy.sh

Added awscli support to stork-test container for EKS backup tests
no
no
2.3, 2.4

Add env variables for aws access to stork-test

---

Gopkg.lock
pkg/apis/stork/v1alpha1/applicationclone.go
pkg/apis/stork/v1alpha1/applicationrestore.go
pkg/apis/stork/v1alpha1/migration.go
pkg/apis/stork/v1alpha1/zz_generated.deepcopy.go
pkg/applicationmanager/controllers/applicationbackup.go
pkg/applicationmanager/controllers/applicationclone.go
pkg/applicationmanager/controllers/applicationrestore.go
pkg/migration/controllers/migration.go
pkg/resourcecollector/job.go
pkg/resourcecollector/resourcecollector.go
vendor/k8s.io/kubernetes/pkg/util/slice/BUILD
vendor/k8s.io/kubernetes/pkg/util/slice/slice.go

Since jobs might not be idempotent, restoring/cloning/migrating them are
optional. They will always be backed up
Enhancement
Yes, it adds `includeOptionalResourceTypes` field to Migration, ApplicationClone and ApplicationRestore specs
```release-note
Added support to optionally migrate, clone, and restore `Jobs`. This can be done by specifying `Jobs` in the `includeOptionalResourceTypes` field in the specs. This is made optional since jobs might not be idempotent.
```
2.4

Collect jobs from resource collector

---

specs/stork-deployment.yaml
specs/stork-scheduler.yaml

bug
The metadata.initializers field has been deprecated since Kubernetes
1.13, and has been completely removed in 1.16. So, when using a
Kubernetes version >=1.16, this errors out while creating the
deployment.
Fix this by just removing the key in stork-deployment.yaml and
stork-scheduler.yaml.
no
no
no

specs: remove initializers field from specs

---

specs/stork-scheduler.yaml

>bug
While trying to deploy stork on a k8s cluster with version 1.18, we
noticed that some permission errors came up when deploying the scheduler.
This fixes the yaml to work for k8s 1.18.
no
```release-note
```
no

fix stork-scheduler RBAC role for Kubernetes 1.18

---

Dockerfile
pkg/apis/stork/v1alpha1/backuplocation.go

Enhancement
Adds `storageClass` in the s3Config in `BackupLocation` CRD
```release-note
Users can now specify the S3 storage class to be used for backups
```
2.4

Add storageclass to s3 config in BackupLocation

---

cmd/stork/stork.go

>bug
Allow user to enable/disable stork Webhook controller
yes, while deploying stork user can mention webhook=false/true to enable disable Webhooks controller
```
- command:
- /stork
- --driver=pxd
- --verbose
- --leader-elect=true
- --health-monitor-interval=120
- --webhook=true
```
no
2.4.2

add flag to enable/disable webhook controller

---

cmd/stork/stork.go
drivers/volume/portworx/portworx.go
drivers/volume/volume.go
pkg/monitor/monitor.go
pkg/monitor/monitor_test.go

Bug
* [Portworx] Map node status None to Online
* Add events when deleting pods from health monitor
No
```release-note
* [Portworx] Fix issue with mapping node status which could cause pods to be deleted from the HealthMonitor when not required
* Added events to the pod when deleting them from the HealthMonitor
```
2.4

Updates for health monitor

---

cmd/stork/stork.go
pkg/webhookadmission/webhook.go

> enhancement
Skip updating application scheduler to stork based on annotations. If stork started with `webhook-skip-resources` flag , we will skip updating scheduler for resources with `webhook-skip-resources` annotation 
no
no
yes, 2.4.3

Disable auto-updating app scheduler as stork for app based on annotations

---

drivers/volume/portworx/portworx.go

bug
>feature
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
```release-note
```

Cluster pair should work with auth enabled Portworx

---

Gopkg.lock
pkg/apis/stork/v1alpha1/applicationregistration.go
pkg/apis/stork/v1alpha1/register.go
pkg/applicationmanager/applicationmanager.go
pkg/applicationmanager/controllers/applicationbackup.go
pkg/applicationmanager/controllers/applicationregistration.go
pkg/applicationmanager/controllers/applicationrestore.go
pkg/migration/controllers/migration.go
pkg/resourcecollector/resourcecollector.go
pkg/storkctl/applicationregistration.go
pkg/storkctl/applicationregistration_test.go
pkg/storkctl/get.go
pkg/storkctl/migration.go
vendor/github.com/portworx/sched-ops/k8s/apps/statefulsets.go
vendor/github.com/portworx/sched-ops/k8s/stork/applicationregistration.go
vendor/github.com/portworx/sched-ops/k8s/stork/stork.go

>feature
Add support in stork to migration/backup/restore generic CRDs
no
```release-note
support in stork to migration/backup/restore generic CRDs. Users has to register their CRD's via ApplicationRegistration CRs. 
```
yes, 2.4.2
Note: depends on PR #653

Support generic CRD migration, backup/restore

---

pkg/applicationmanager/controllers/applicationregistration.go
pkg/migration/controllers/migration.go
pkg/resourcecollector/resourcecollector.go

>bug
Fix for restore fails with - resourceVersion should not be set on objects to be created
no
no
yes, 2.4

Set resource version to empty before applying restored objects

---

cmd/stork/stork.go

>bug
Disable Webhooks controller on start
no
none
2.4

disable webhook controller by default

---

pkg/applicationmanager/controllers/applicationbackup.go
pkg/snapshot/controllers/snapshotschedule.go

>bug
We don't pass pre/post exec rule to snapshot for volumesnapshotschedules. This PR handles pre/post exec rule for snapshotschedules
- It also fix deletion of crd.json file on ApplicationBackup delete if retention policy is `Delete`
```release-note
```

handle pre/post exec rule for volumesnapshotschedules

---

pkg/resourcecollector/resourcecollector.go

>bug
use resourcecollector k8sclient instead of schedop client to list crd resources
no
no
2.4.3

use resourcecollector k8sclient instead of schedop client to list crd resources

---

pkg/resourcecollector/resourcecollector.go

bug (stor-241)
Sometimes, the deleted resources are automaticaly getting created by controller during restore. This make the wait loop of 2 mints to be run for those resource. This indirectly makes the px-backup to Timeout. So, instead of waiting for the re-created resources, Added fix to not to wait for the re-created resources in DeleteResources API.
no
no
Need to check.
Testing:
Tested the fix with the gitlab runner application. While restoring with --replace option, check that couple of  resources where re-create before the actual restore. Verify the debug statement …

Added fix to not to wait for the re-created resources in DeleteResources API.

---

test/integration_test/common_test.go

Need to create new buckets in the cloud for every integration test. This is required because if we have a single bucket
for all application backups done as part of the test, on syncing from that bucket we get numerous backups on the synced cluster. We need to avoid the above scenario.
no
no
no

Create new bucket for stork integration tests

---

Gopkg.lock
pkg/storkctl/applicationbackup.go
pkg/storkctl/applicationbackup_test.go
pkg/storkctl/applicationbackupschedule.go
pkg/storkctl/applicationclone.go
pkg/storkctl/applicationclone_test.go
pkg/storkctl/applicationrestore.go
pkg/storkctl/applicationrestore_test.go
pkg/storkctl/clusterdomainsstatus.go
pkg/storkctl/clusterdomainupdate.go
pkg/storkctl/clusterdomainupdate_test.go
pkg/storkctl/clusterpair.go
pkg/storkctl/factory.go
pkg/storkctl/migration.go
pkg/storkctl/migration_test.go
pkg/storkctl/migrationschedule.go
pkg/storkctl/snapshot.go
pkg/storkctl/watch.go
vendor/github.com/portworx/sched-ops/k8s/stork/stork.go
vendor/k8s.io/client-go/tools/watch/informerwatcher.go
vendor/k8s.io/client-go/tools/watch/retrywatcher.go
vendor/k8s.io/client-go/tools/watch/until.go

>enhancement
Adds Enhancement to storkctl migration options
- add option to allow validating migration spec
- add watch option to storkctl stork resources
- accept storage option for clusterpair
yes
Validate : 
```
Checking Migration Namespaces....Ok
Checking ClusterPair Status....Ok
Checking PreExec Rule....Missing
Checking PostExec Rule....Missing
All Ready!!
```
no
2.4

Improve storkctl migration interface

---

pkg/apis/stork/v1alpha1/applicationregistration.go
pkg/applicationmanager/controllers/applicationregistration.go
pkg/migration/controllers/migration.go
pkg/storkctl/applicationregistration.go
pkg/storkctl/migration.go

>enhancement
Allow string type option to be set for crd migration. 
yes, in case of string type we will display value in `storkctl get appreg` 
```
NAME        KIND                       CRD-NAME                 VERSION    SUSPEND-OPTIONS                       KEEP-STATUS
weblogic    Domain                     weblogic.oracle          v8         spec.serverStartPolicy,string,NEVER   false
```
yes
yes, 2.4.4

allow string type for appreg suspend option

---

pkg/apis/stork/v1alpha1/rule.go
pkg/applicationmanager/controllers/applicationbackup.go
pkg/rule/rule.go

Add support to pass in * to select all namespaces to backup
Update Rule spec to take in container name
This is required since a pod could have multiple containers and we
need to know which one we should run the commands in
Adds container field to Rule spec
```release-note
* Added support to specify * as a wildcard to select all namespaces in ApplicationBackup spec
* Added container name in Rule spec. This is required if you have multiple containers in a pod and want to select a container to run the command in.
```
No

Add support to pass in * to select all namespaces to backup and update rule to take container name

---

pkg/resourcecollector/resourcecollector.go

The group in the resource is empty, need to set it to core before comparing
Bug
No
No

ResourceCollector: When checking for resources set group name for core

---

pkg/objectstore/s3/s3.go

AWS SDK fetches correct endpoint based on provided region
Enhancement
AWS SDK supports fetching of correct endpoints based on region provided if the user passes an empty endpoint.
This makes the user experience better wherein they need to remember different endpoints for different regions.
No
No
No

Passing empty endpoint to AWS objectstore operations

---

drivers/volume/azure/azure.go

Bug fix
Backup/Restore size for azure volumes are not shown as currently, it was populating for in-progress backups. Moved the same to fetch once the backup is completed.
No
No
No

Fix to populate backup and restore size for azure volumes

---

drivers/volume/aws/aws.go
drivers/volume/azure/azure.go
drivers/volume/gcp/gcp.go
drivers/volume/portworx/portworx.go
pkg/apis/stork/v1alpha1/applicationbackup.go
pkg/apis/stork/v1alpha1/applicationrestore.go
pkg/applicationmanager/controllers/applicationbackup.go
pkg/applicationmanager/controllers/applicationrestore.go

Enhancement
Portworx supports incremental backups wherein the only incremental backup is taken which occupies less size. As part of this PR, actual size (only size of backup data written) is captured. For other cloud providers, this would be the same as the total size of the backup.
No
No
No

Adding actual backup size in backup volume info

---

pkg/applicationmanager/controllers/applicationregistration.go
pkg/webhookadmission/webhook.go
vendor/github.com/portworx/sched-ops/k8s/apiextensions/crds.go

>enhancement
- Detect all registered crd on k8s server and create application registration resource fo all of them
- Add debug logs in Webhooks controller
no
yes, 
```ApplicationRegistration resources are now created for all CRD's found on k8s server.  So backup and restore of CR does not require any additional step of registering CR with stork. 
Note: For migration, user has to add `suspendOption` to disable/enable CRs on migrations
```
2.5.0
Example Output: 
```
NAME                       KIND                       CRD-NAME                 VERSION    SUSPEND-OPTIONS …
```

Create application registration CR for all crds found on system

---

pkg/apis/stork/v1alpha1/applicationbackup.go
pkg/apis/stork/v1alpha1/zz_generated.deepcopy.go
pkg/applicationmanager/controllers/applicationbackup.go
pkg/applicationmanager/controllers/applicationclone.go
pkg/applicationmanager/controllers/applicationrestore.go
pkg/migration/controllers/migration.go
pkg/resourcecollector/persistentvolume.go
pkg/resourcecollector/resourcecollector.go

Feature
Yes, adds `IncludeResources` in ApplicationBackup and ApplicationBackupSchedule
```release-note
Added support to specify which resource to backup using ApplicationBackup. By default all resources in the namespace will be backed up
```
2.5

Add support to specify resources during application backup

---

pkg/applicationmanager/controllers/applicationrestore.go

Bug
During restore, Continuing with next namespace creation, if current ns already exists.
N.A
2.5
**Tested the following use case:**
Backuped up default, mysql-ns1, mysql-ns2 namespaces.
Restored with following namespace map from px-backup. 
namespace-mapping default=default,mysql-ns1=mysql-ns1,mysql-ns2=mysql-ns22
Here default and mysql-ns1 namespace was already existed on the cluster.
With out fix, mysql-ns22 was not created and not restored. 
With fix, it was created and restored.

Continuing with next namespace creation, if current ns already exists.

---

drivers/volume/portworx/portworx.go

bug
If a request is authenticated, then the resulting volumes must have
the labels pointing to the authentication information
no
2.4, 2.5

Add authentication labels to volume

---

pkg/migration/controllers/migration.go
pkg/storkctl/migrationschedule.go
pkg/storkctl/migrationschedule_test.go

>bug
Adds wait for deletion of resources before re-creating them during migration, this will avoid migration failure because of `object is in deleting state already exist` error
- Fix storkctl migration schedule issue where one unable to suspend/resume multiple migration using same clusterpair  
```
MigrationSchedule test-1 suspended successfully
MigrationSchedule test-2 suspended successfully
NAME     POLICYNAME                 CLUSTERPAIR   SUSPEND   LAST-SUCCESS-TIME   LAST-SUCCESS-DURATION
test-1   default-migration-policy   testpair      true
test-2   default-migration-policy   testpair      true
MigrationSchedule test-1 resumed successfully
MigrationSchedule test-2 resumed successfully
NAME     POLICYNAME …
```

Wait for resource deletion before re-creating during migration

---

pkg/resourcecollector/resourcecollector.go

bug
Currently the label selector are not getting applied for clusterRole, clusterRoleBinding and ServiceAccount resources in resourceCollector.GetResources(). Because of that these resources are getting included in backup, even if they do not have the labels.
No
N.A.
2.5 branch

Applying label selector for clusterRole, clusterRoleBinding and ServiceAccount resources.

---

test/integration_test/Dockerfile

Update go version for integration test container to 1.13.1
no
no
yes

Update go version to 1.13.1 for integration test container

---

Gopkg.lock
test/integration_test/Dockerfile
test/integration_test/applicationbackup_test.go
test/integration_test/common_test.go
test/integration_test/snapshot_test.go
vendor/github.com/portworx/torpedo/LICENSE
vendor/github.com/portworx/torpedo/drivers/scheduler/k8s/k8s.go
vendor/github.com/portworx/torpedo/drivers/scheduler/scheduler.go
vendor/github.com/portworx/torpedo/drivers/volume/common.go
vendor/github.com/portworx/torpedo/drivers/volume/portworx/portworx.go
vendor/github.com/portworx/torpedo/drivers/volume/portworx/schedops/k8s-schedops.go
vendor/github.com/portworx/torpedo/drivers/volume/volume.go

For auth-enabled runs when not using custom method to create CRDs,  we need to add security annotations.
no
no
no

Add security annotations to CRDs for auth-runs

---

pkg/applicationmanager/controllers/applicationbackup.go
test/integration_test/Dockerfile

enchancement
Submitting the volume StartBackup in a batch count of ten.
This way, we will update the volume backup status frequently to the CR content.
No
No
2.4?
Verified the fix on Bhavan's setup.

Submitting the volume StartBackup in a batch count of ten.

---

pkg/resourcecollector/persistentvolumeclaim.go

bug
For non-CSI drivers, restore PVC is failing because we error out if we cannot find the PV for a given PVC.
No
No
No

Fix for non-CSI PVC restore not erroring out

---

pkg/applicationmanager/controllers/applicationbackup.go
test/integration_test/Dockerfile

- This way, we will update the volume backup status
frequently to the CR content.

[Cherry pick 2.5]: Submiiting the volume StartBackup in a batch count of ten.

---

pkg/resourcecollector/persistentvolume.go
pkg/resourcecollector/persistentvolumeclaim.go
pkg/resourcecollector/resourcecollector.go

bug
Fixes a check in PVC pre-apply that was causing the PVC VolumeName to not be set.
No
```release-note
none - unreleased
```
2.6.0

Don't skip VolumeName update on CSI driver check failure

---

drivers/volume/csi/csi.go
pkg/apis/stork/v1alpha1/applicationbackup.go
pkg/applicationmanager/controllers/applicationbackup.go

bug
Reworks csi.GetBackupStatus to make sure we ensure all VS objects are deleted before marking as success.
No
No
No

[CSI] Add check to make sure VolumeSnapshot and VSC are cleaned up

---

drivers/volume/aws/aws.go
drivers/volume/azure/azure.go
drivers/volume/csi/csi.go
drivers/volume/gcp/gcp.go
drivers/volume/linstor/linstor.go
drivers/volume/mock/mock.go
drivers/volume/portworx/portworx.go
drivers/volume/volume.go
pkg/applicationmanager/controllers/applicationbackup.go
pkg/applicationmanager/controllers/applicationclone.go
pkg/monitor/monitor.go
pkg/pvcwatcher/pvcwatcher.go
pkg/resourcecollector/persistentvolume.go
pkg/resourcecollector/persistentvolumeclaim.go
pkg/webhookadmission/webhook.go

Without this, if the resource collector is called for a remote cluster it tries
to fetch objects from the local cluster
Bug
No
No
No

Use client from resource collector when checking for PVC ownership

---

pkg/migration/controllers/migrationschedule.go

Some resources might always fail to be migrated, this causes the status for all
PartialSuccess migrations to be saved. Only need to keep the last one in this
case
Bug
No
No
No

Prune migrations even for PartialSuccess

---

drivers/volume/aws/aws.go

Bug
Reports EKS volume size in bytes instead of GiB
No
No
For 2.5

Reporting volume size in bytes for EKS

---

drivers/volume/csi/csi.go
pkg/resourcecollector/resourcecollector.go

bug
* Some CSI providers require specific VSClass parameters. We should not delete the VSClass as the user may have added their driver-specific settings. We will only update the VSClass to have the retain policy, as that is required for backups. We will still create the VSClass if it does not exist.
* Skip vs object in includeObject (to hide from UI and ignore in backups)
* add namespace mapping support
* add CSI restore timeout
No
No
No

[CSI] Namespace mapping, skip VS obj in includeObject, and UID fix

---

Gopkg.lock
pkg/applicationmanager/controllers/applicationregistration.go
pkg/migration/controllers/migration.go
pkg/storkctl/common_test.go
pkg/storkctl/factory.go
pkg/storkctl/migration.go
vendor/github.com/portworx/sched-ops/k8s/apiextensions/crds.go
vendor/github.com/portworx/sched-ops/k8s/batch/batch.go
vendor/github.com/portworx/sched-ops/k8s/batch/cron.go

>enhancement
This PR adds support for disable/enable cronjob object once migrated to remote cluster
no
yes
```release-note
Adds support for disabling cronjob object upon migration to remote cluster.  One can now activate/deactivate cronjob object as well using `storkctl activate/deactivate migration <migration_namespace>`
```
yes, 2.6.0 (or any early release before 2.6.0)
Output: 
```
NAME                  SCHEDULE      SUSPEND   ACTIVE   LAST SCHEDULE   AGE
cronjob.batch/hello   */1 * * * *   True      0        <none>          75s
Updated suspend option for cronjob …
```

Allow disabling/enabling cronjob object after migration

---

drivers/volume/csi/csi.go
pkg/applicationmanager/controllers/applicationrestore.go
pkg/resourcecollector/persistentvolume.go
pkg/resourcecollector/persistentvolumeclaim.go
pkg/resourcecollector/resourcecollector.go

bug
* Adds replacement policy support
* Fixes resource collector bug that caused PreRestoreObjects to a reference to all objects.
* Fixes volumesnapshot skip code
* Fixes restore size in UI
No
No
No

[CSI] Add support for Replace Policy and bug fixes

---

drivers/volume/csi/csi.go
pkg/applicationmanager/controllers/applicationrestore.go
pkg/resourcecollector/resourcecollector.go

bug
* When a restore is issued through PX-Backup, it creates a backup in the namespace and cleans it up when finished. There was some race where the cleanup was failing to find the backup object to cleanup the VS objects.
* This PR makes the cleanup independent of the backup object, by only cleaning up objects associated with the given restore UID.
* Uses PVC size for backup/restore info sizes
* Fix VolumeSnapshot skip check to not look at group
No
No
No

[CSI] Restore cleanup without backup obj and various fixes

---

drivers/volume/csi/csi.go
pkg/applicationmanager/controllers/applicationbackup.go

>bug
- Added retry logic, when CR updates fails for Inprogress status.
- Also return VolumenInfo list in the case of failure in GetBackupStatus implementation in CSI driver.
no
no
2.6
Testing:
Running all-namespace backup schedule on Bhavana's Pure setup with 30 retain. Once only cycle of 30 backup is complete, will update the result.

Added retry logic, when CR updates fails for Inprogress status.

---

drivers/volume/csi/csi.go
pkg/applicationmanager/controllers/applicationbackup.go

-Added retry logic, when CR updates fails for Inprogress status.
- Also return VolumenInfo list in the case of failure in GetBackupStatus implementation in CSI driver.

[Cherry-pick 2.6] Added retry logic, when CR updates fails for Inprogress status.

---

drivers/volume/csi/csi.go

>bug
Avoid including non-csi volume as part of csi's GetBackupStatus API.
no
no
2.6
**Testing:**
Tested on the OCP cluster setup, where we saw the issue.

Avoid including non-csi volume as part of csi's GetBackupStatus API.

---

drivers/volume/csi/csi.go
pkg/apis/stork/v1alpha1/applicationbackup.go
pkg/applicationmanager/controllers/applicationbackup.go

bug
Removes the cleanup checks to improve the reliability of backup status.
No
No
2.6

[CSI] Remove cleanup checks for GetBackupStatus

---

Gopkg.lock
cmd/stork/stork.go
pkg/metrics/applicationbackup.go
pkg/metrics/applicationbackup_test.go
pkg/metrics/applicationclone.go
pkg/metrics/applicationclone_test.go
pkg/metrics/applicationrestore.go
pkg/metrics/applicationrestore_test.go
pkg/metrics/clusterpair.go
pkg/metrics/clusterpair_test.go
pkg/metrics/metrics.go
pkg/metrics/metrics_test.go
pkg/metrics/migration.go
pkg/metrics/migration_test.go
vendor/github.com/portworx/sched-ops/k8s/batch/batch.go
vendor/github.com/portworx/sched-ops/k8s/stork/applicationbackuprestore.go
vendor/github.com/portworx/sched-ops/k8s/stork/applicationclone.go
vendor/github.com/portworx/sched-ops/k8s/stork/clusterdomains.go
vendor/github.com/portworx/sched-ops/k8s/stork/clusterpair.go
vendor/github.com/portworx/sched-ops/k8s/stork/migration.go
vendor/github.com/portworx/sched-ops/k8s/stork/stork.go

>enhancement
Add prometheus metrics for stork controllers
- application backup, restore and clone
- cluster pair and migration
no
yes
```release-note
Added prometheus metrics support for stork controllers which includes -
- application backup, restore and clone
- cluster pair and migration
```
2.6.1

Add prometheus metrics for application backup and restore CRs

---

pkg/applicationmanager/controllers/applicationbackup.go

bug
Added retry logic, while updating the ApplicationBackupStageApplications status to CR.
If the CR update fails, we retry for 10 times with 10 sec delay.
No.
No.
Yes, 2.6 branch.
**Testing:**
Tested it on Bhavana's setup, where the error was reproduce. With retry fix, the backup completed succesfully. Most the retry was successful in second try.

Added retry logic, while updating the ApplicationBackupStageApplications status to CR.

---

Gopkg.lock
pkg/applicationmanager/controllers/applicationrestore.go
pkg/k8sutils/k8sutils.go
pkg/migration/controllers/migration.go
pkg/storkctl/migration.go
vendor/github.com/portworx/sched-ops/k8s/core/pods.go

>bug
Allow CRDs using apiextenstion v1 api to migrate/backup/restore. Fix replica count issue for crds with `int` as suspendValue
no
np
2.6.1

Fix crd migration issue for api extensionV1 crds

---

pkg/applicationmanager/controllers/applicationrestore.go
pkg/migration/controllers/migration.go

- migration: err check crd reg before validating crds
>bug
Since there is no way to determine crd apiversion downloaded from source cluster, add retry crd registration logic
for crd with apiversion `apiextenstion/v1`
no
no
2.6.1

retry v1 crd registration while doing app restore

---

pkg/applicationmanager/controllers/applicationrestore.go

Namespace is already being mapped to the destination
Bug
No
2.6

Don't check for namespace mapping again when finding objects to delete

---

pkg/applicationmanager/controllers/applicationbackup.go

bug
GetResources takes more time, if we have more number of namespaces in namespace list. This make backup looks to be hang as the CR is not updated. This makes the px-backup to mark the backup as failed with timeout error.
So, submitting it in batches and in between each batch, we will updating the LastUpdateTimestamp in backup CR to show that backup is progressing and avoid timeout failure.
No
No
Yes, to 2.6 branch.
**Testing:
Testcase1: ( To make sure that new logic does not add any extra time.)**
Increased the timeout value to 2 hours in px-backup.
Added 750 namespaces. …

stor:335 Adding batch processing logic in passing namespace list to the GetResources API of resourceCollector pkg

---

Makefile

Signed-off-by: Rohit-PX <rohit.kulk@gmail.com>
cleanup
Explicitly specify `GOO=linux` so the right container is built even when developing from other OSes like Mac OS / Windows
no
no
2.6

Explicitly add linux as the GOOS

---

drivers/volume/portworx/portworx.go

Bug
Temporarily fix to set backup size to zero when fetching of backupsize fails in Portworx. Once porx fixes the issue, the same would be reverted back.  Today few of the backups (incremental) timeouts fetching size which leads to backup failure.
No
No
Yes to 2.6 branch

[Portworx]: Setting backup size to zero on failure when fetching size

---

pkg/migration/controllers/migration.go

> enhancement
In case of volume only migration, only underlying drivers volume are migrated and not its associated PVCs . This PR add support to migrate pvc resource as well in case of VolumeOnly migration 
no
yes
```release-note
Support of pvc object migration in case of migration spec with disable application resource migration
```
yes, 2.6.3

Create pvc objects if volumeOnly migration is enabled

---

pkg/resourcecollector/resourcecollector.go

> enhancement
Support to collect non-owner ReplicaSet objects  for backup/migration
no
yes
```release-note
Support to collect non-owner ref Replicaset object backup/migrations
```
yes, 2.6.X

add support for replicaset backup/migration

---

pkg/migration/controllers/migration.go

Bug
No
```release-note
Fixed issue during migrations where ApplicationRegistrations were being fetched for each resource causing a delay while preparing resources
```
2.6

Get ApplicationRegistrations only once when preparing resources

---

test/integration_test/Dockerfile

Fix travis build issue while making integration-test-container

Use python3 version to install libs for google-sdk

---

pkg/resourcecollector/service.go

bug
In k8s 1.20.0, we have clusterIPs field along with clusterIP for service. Currently we are reseting clusterIP alone while preparing resource to take backup. Now make clusterIPs to be nil along with clusterIP.
no
no
yes, 2.6 branch
**Testing:**
Tested on the k8s 1.20.0 and 1.14.0 cluster with wordpress app. Verified that clusterIPs and clusterIP are getting rest to nil and empty.

Updating clusterIps field of service to nil in prepareServiceResourceForCollection.

---

test/integration_test/migration_test.go
test/integration_test/snapshot_test.go

* When creating migration object using the private method, add security annotations if needed
* Skip certain migration tests until a bug is resolved.
no
no
master

Add security annotations migration create method

---

pkg/resourcecollector/configmap.go
pkg/resourcecollector/resourcecollector.go

bug
- Added logic to exclude the controlled resources from GetResources API.
- Define a list for excluding controlled resources being returned as part of 
response of resourceCollector GetResources API.
- For now added configmap kube-root-ca.crt, which was getting created
by kube-controller-manager in every namespace.
no
no
yes, to 2.6 branch.
**Testing:**
Tested with k8s 1.20.0 that GetResources API does not return the kube-root-ca.crt configMap.
```
Actual configMap in the namespace test:
[root@central-steel-drifter-0 tmp]#
[root@central-steel-drifter-0 tmp]# kubectl get …
```

Added logic to exclude the controlled resources from GetResources API.

---

test/integration_test/applicationbackup_test.go
test/integration_test/applicationclone_test.go
test/integration_test/clusterdomain_test.go
test/integration_test/cmdexecutor_test.go
test/integration_test/common_test.go
test/integration_test/extender_test.go
test/integration_test/health_monitor_test.go
test/integration_test/migration_backup_test.go
test/integration_test/migration_test.go
test/integration_test/snapshot_restore_test.go
test/integration_test/snapshot_test.go
test/integration_test/stork-test-pod.yaml
test/integration_test/test-deploy.sh

This PR will provide the ability to run stork integration test via a third independent cluster.
At the same time will allow the test pod to interact with source and destination cluster.
With this architecture, tests can reboot either source or destination cluster or both without affecting the test pod
no
no
no

Provide separate kubeconfig params for test, source and destination cluster

---

test/integration_test/test-deploy.sh

Deploying stork as part of test-deploy was commented by mistake.
no
no
no

Re-enable deploying stork as part of test-deploy script

---

test/integration_test/applicationbackup_test.go
test/integration_test/applicationclone_test.go
test/integration_test/clusterdomain_test.go
test/integration_test/cmdexecutor_test.go
test/integration_test/common_test.go
test/integration_test/extender_test.go
test/integration_test/health_monitor_test.go
test/integration_test/migration_backup_test.go
test/integration_test/migration_test.go
test/integration_test/snapshot_restore_test.go
test/integration_test/snapshot_test.go
test/integration_test/stork-test-pod.yaml
test/integration_test/test-deploy.sh

Cherry-pick of f4dec0e2027d9715022845068f3a67a4c757cc7a
no
no
no

Add separate CLI params for test, source and dest kubeconfig

---

pkg/storkctl/clusterpair.go
pkg/storkctl/create.go

>enhancement
Add new command line option to create bidirectional cluster-pairing between source and destination cluster
yes,
```
./storkctl create clusterpair testpair -nkube-system --src-kube-file ./srcfile.yaml  --dest-kube-file  ./destfile.yaml  --srcip <src_ip> --destip <dest_ip> --srctoken <src_token> --desttoken <dest_token>
ClusterPair testpair created successfully on source cluster
ClusterPair testpair created successfully on destination cluster
```
yes
```release-note
Add storkctl command to create bidirectional cluster-pair on source and destination cluster
``` …

Add storkctl option to create reverse cluster pairing

---

specs/prometheus/rule.yaml

>documentation
Add prometheus alerts for stork metrics -
- applicationbackup failed/partialsuccess
- applicationrestore failed/partialsuccess/retain
- migration failed/partialsuccess
- cluster pair failed/degraded
no
no
2.6.3

prometheus alerts for stork metrics

---

pkg/appregistration/appregistration.go

>enhancement
Add suspend option support for following CR's -
```
- perconadb
- prometheus
- rabbitmq
- kafka (strimzi)
- postgress(acid.zalan.do)
```
no
no
2.6.3

Add appreg suspend support for CR's

---

go.mod
go.sum
pkg/storkctl/migration_test.go
test/integration_test/common_test.go
test/integration_test/webhook_test.go
vendor/github.com/portworx/sched-ops/k8s/apps/daemonsets.go
vendor/github.com/portworx/sched-ops/k8s/apps/deployments.go
vendor/github.com/portworx/sched-ops/k8s/apps/replicasets.go
vendor/github.com/portworx/sched-ops/k8s/apps/statefulsets.go
vendor/github.com/portworx/sched-ops/k8s/stork/stork.go
vendor/github.com/portworx/torpedo/drivers/node/ssh/ssh.go
vendor/github.com/portworx/torpedo/drivers/scheduler/k8s/k8s.go
vendor/github.com/portworx/torpedo/drivers/scheduler/scheduler.go
vendor/modules.txt

Add Integration test which validates mysql spec with dryRun options for recent fix #802 
no
no
yes, 2.6.3
**Note** : Please review vendor/github.com/portworx/torpedo changes as well since we are not adding changes torpedo master (open PR for k8s v1.20 lib updates https://github.com/portworx/torpedo/pull/562)
Integration-test Run: 
```
=== RUN   TestSnapshotMigration
=== RUN   TestSnapshotMigration/testWebhook
=== RUN   TestSnapshotMigration/testWebhook/simpleDryRunTest
time="2021-03-25T16:39:40Z" level=info msg="[mysql-2-pvc] Created PVC: mysql-data" …
```

Integration test for stork webhook dryRun only option

---

pkg/extender/extender.go
pkg/metrics/applicationbackup.go
pkg/metrics/applicationclone.go
pkg/metrics/applicationrestore.go
pkg/metrics/clusterpair.go
pkg/metrics/migration.go
pkg/monitor/monitor.go

>cleanup
Standardize stork prometheus metrics with set prefix `stork`
no
yes
-->
```release-note
All stork prometheus metrics will now have `stork_` as prefix, eg
stork_application_backup_status, stork_migration_status, stork_hyperconverged_pods_total etc
All existing metrics will now move over to `stork_` prefix convention 
```
yes, 2.6.3

rename stork prometheus metrics with standard prefix

---

pkg/migration/controllers/migration.go
pkg/resourcecollector/resourcecollector.go

>bug
Adds pluraliser rule for prometheus CR detections during backup/restore and migration. 
no
no
2.6.3

Add pluralizer rules for prometheus crd

---

specs/stork-scheduler.yaml

bug
https://portworx.atlassian.net/browse/STOR-379
no
no
2.6

Add permissions for stork-scheduler for k8s 1.21

---

cmd/stork/stork.go
pkg/applicationmanager/applicationmanager.go
pkg/applicationmanager/controllers/applicationbackup.go

>bug
- Avoid faulty read and update of controller sdk if backup resource is already at final stage
- allow to configure backup controller rsync interval
no
yes
```
Fixed issue where CSI volumes Application backup snapshots were deleted even though backups are completed successfully 
```
2.6

Configure rsync time for application controllers

---

pkg/applicationmanager/controllers/applicationclone.go

> bug
Fix issue where application clone fails if destination namespace(clone namespace) already exists
no
```release-note
Application clone stuck if destination namespace already exists https://github.com/libopenstorage/stork/issues/826
```
yes, 2.6

stor-391: application clone fails if dest namespace

---

pkg/schedule/cache.go

>bug
Fix stor-403: use separate cache watch list for namespaced schedule policy
no
no
yes, 2.6.4

Fix namespaced schedule policy cache watch list

---

pkg/resourcecollector/resourcecollector.go
pkg/resourcecollector/resourcequota.go

Bug
- On GKE when a namespace is created by default this gets
created so no need of backing it up
No
No
Yes, 2.6.4

Skipping backing up of gke-resource-quotas

---

pkg/resourcecollector/networkpolicy.go
pkg/resourcecollector/resourcecollector.go

Enhancement
Support for  backing up NetworkPolicy and PodDisruptionBudget objects
No
No
Yes
Manul test
Applied below network policy, podDisrutpion budget and took a backup and checked resources.json file had the content
```
[root@prashanth-muck-bug-0 np]# cat networkpolicy.yml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
name: allow-all-ingress-egress
namespace: test
spec:
podSelector: {}
policyTypes:
- Ingress
- Egress
ingress:
- {}
egress:
- {}
podDisruptionBudget
[root@prashanth-muck-bug-0 np]# cat pdb.yml
apiVersion: policy/v1beta1
kind: …
```

Backing up NetworkPolicy and PodDisruptionBudget objects

---

pkg/applicationmanager/controllers/applicationbackup.go
pkg/resourcecollector/clusterrole.go
pkg/resourcecollector/resourcecollector.go

>bug
Fix issue where 
- stork does dirty update of application backup CRs
- collect service account for user with no namespace access 
no
yes
```release-note
- Fix invalid CR updates of application backup
- Dont display/collect service account for namespace where user does not have access
```
yes, 2.6

Prevent invalid CR updates for application backup

---

pkg/apis/stork/v1alpha1/applicationbackup.go
pkg/apis/stork/v1alpha1/migration.go
pkg/apis/stork/v1alpha1/zz_generated.deepcopy.go
pkg/applicationmanager/controllers/applicationbackup.go
pkg/migration/controllers/migration.go
pkg/resourcecollector/resourcecollector.go
pkg/resourcecollector/service.go
pkg/resourcecollector/serviceaccount.go

>enhancement
Add CRD option to `ApplicationBackup` and `Migration` for skipping resource field update during backup/migration operation. 
yes, User can now specify `SkipServiceUpdate` in migration/backup CR specs so that stork will not modify cluster/loadbalancer ip field during resource collections
eg.: 
```
kind: ApplicationBackup
metadata:
name: backup-mysql
namespace: mysql
spec:
backupLocation: mysql
namespaces:
- mysql
reclaimPolicy: Delete
skipServiceUpdate: true
```
yes
```release-note
Users can now specify `skipServiceUpdate` in backup/migration spec to avoid updating Loadbalancers IP/clusterIP field. Alternatively they can also …
```

Allow option to prevent resource modification during backup/migration

---

cmd/stork/stork.go
pkg/resourcecollector/resourcecollector.go

>enhancement
Allow users to configure k8s client api request stork can make for doing resource collection during backup/migration operation
yes, stork deployment now accept `k8s-api-req-limiter` parameter to configure api request stork can make with k8s server
yes
```release-note
User can configure api req limit by setting `k8s-api-req-limiter` parameter in stork deployment
```
yes, 2.6.4

Allow setting k8s client api rate limiter

---

pkg/migration/controllers/migration.go
pkg/resourcecollector/resourcecollector.go

>bug
Allow cluster-scope resource selection which belongs to namespace in `IncludeResources`
Fix nil pointer error for skipServiceUpdate flag in migration controller
bo
no
yes, 2.6

PB-1679: cluster-scope resource collection

---

pkg/applicationmanager/controllers/applicationbackup.go

bug
Backup volume count was reset to 0 due to an incorrect change that got pushed in after resolving a 3 way merge conflict.
No
No
Yes - 2.6

Fix the issues caused by git merge conflicts.

---

Makefile
pkg/appregistration/appregistration.go
pkg/extender/extender.go
pkg/migration/controllers/migration.go
pkg/resourcecollector/resourcecollector.go
test/integration_test/common_test.go

>feature
Add support to backup/migrate mongoldb community CR
Also adds integration test to verify stork version from configmap
no
no
yes, 2.6.4
*Note* :  Same Version Integration test image  has to be used for running integration test eg. integration test build on top of master will be used to validate stork:master image

Stor-423: add support to migrate mongoDB crd

---

pkg/migration/controllers/migration.go

>bug
Stork now update SA instead of recreating it now, we don't need to handle default SA seperately
no
yes, 2.6

Update service account resource instead of delete/create

---

drivers/volume/portworx/portworx.go
pkg/metrics/volumesnapshotschedule.go
pkg/webhookadmission/utils.go
pkg/webhookadmission/webhook.go

bug
Since K8s v1.10 migrated to go 1.15, self-signed certificates should have alt sub added otherwise it will fail with error - 
```
W0525 09:17:10.265434       1 dispatcher.go:170] Failed calling webhook, failing open webhook.stork.libopenstorage.org: failed calling webhook "webhook.stork.libopenstorage.org": Post "https://stork-service.kube-system.svc:443/mutate?timeout=30s": x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0
```
- Stork now creates a valid cert.
- It also creates a new k8s secret with the cert and deletes the old one. 
No
```release-note …
```

STOR-393: Add a SAN to the webhook certificate created by stork.

---

pkg/applicationmanager/controllers/applicationbackup.go

bug
Removed incorrect return statement in the backupVolumes function
No
No
2.6 
**Testing:**
Tested the failing usecase listed in the pb-1732 bug.

Removed incorrect return statement in the backupVolumes function

---

test/integration_test/common_test.go
test/integration_test/migration_test.go

A lot of integration tests are failing because cassandra apps are taking longer to come up after migration (possibly 
No
No
```
Master

Increase timeout for cassandara apps

---

test/integration_test/common_test.go

>bug
Only match stork version while starting integration tests
no
no
2.6.4

Omit checking sha for stork version checks

---

pkg/applicationmanager/controllers/applicationbackup.go

bug
STOR-438
No
No
2.6
**Testing:**
**Testcase1:**
```
namesapces: cassandra, mongo-large, px-backup
--> Selected All resourceType
--> custom resources in px-backup  (only pvc) (6)  
--> all resources in mongo-large
--> all resource in cassandra  (includes PVCs as well) (3 PVCs)
Expected pvcs count: 9 PVCs
```
**Testcase2:**
Note: Here PV and PVC count is not matching. It is the known issue PB-1782
```
namesapces: cassandra, mongo-large, px-backup
--> Selected configmap and PVC as resourceType.
--> custom resource type in the px-backup (one configmap  and all the pvcs.) (6 …
```

Added extra check such we skip volume backup only ResourcType is not empty and does not contain PVC in it

---

pkg/applicationmanager/controllers/applicationclone.go
pkg/migration/controllers/migration.go
test/integration_test/migration_test.go
test/integration_test/snapshot_restore_test.go
test/integration_test/snapshot_test.go

>enhancement
While cloning service resources stork now will empty `ports` field before creating service resource
no
yes
```release-note
ApplicationClone now set `ports` field of service to nil/empty before cloning to destination namespace
```
2.6.4
Output: 
```
NAME              SOURCE      DESTINATION      STAGE   STATUS       VOLUMES   RESOURCES   CREATED               ELAPSED
clone-cassandra   cassandra   cassandra-test   Final   Successful   3/3       8           21 Jul 21 17:43 UTC   38s
NAME        TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)    AGE
cassandra …
```

STOR-415: Remove svc ports while cloning service resources

---

pkg/migration/controllers/migration.go

>bug
With the recent changes for updating the PVC size as a part of Migrations we are now doing the following
- Update the reclaim policy on the PV to Retain
- Delete the PVC
- Recreate the PVC and PV
However due to a bug the Retain policy was not set and the volume was getting deleted.
No
No
Yes - 2.6

STOR-441: Migrations are deleting the backing PX volume.

---

go.mod
go.sum
pkg/migration/controllers/migration.go
pkg/resourcecollector/resourcecollector.go
vendor/github.com/mitchellh/hashstructure/LICENSE
vendor/github.com/mitchellh/hashstructure/README.md
vendor/github.com/mitchellh/hashstructure/hashstructure.go
vendor/github.com/mitchellh/hashstructure/include.go
vendor/modules.txt

> enhancement
Recreate service only if its been changed on primary/source cluster
no
yes
```release-note
Stork will not recreate service on destination/DR cluster if it's not changed on primary cluster during migration
```
yes, 2.6.4-*

Stor 389: migration recreate svc only if its been updated on source cluster

---

drivers/volume/portworx/portworx.go
pkg/migration/controllers/migration.go

>bug
In case of px driver node down wait for px node to come online for in-place restore to succeed 
no
yes
yes

[portworx] wait for driver to come online in case of in-place restore

---

pkg/apis/stork/v1alpha1/applicationbackup.go
pkg/apis/stork/v1alpha1/applicationbackupschedule.go

Data mover feature
```
stor-458: Added following changes in stork CRD for data mover feature.
- Added backupType in ApplicationBackup and ApplicationBackupSchedule
CR definitions.
- Added storageClass in ApplicationBackupVolumeInfo definition.
```
**ApplicationBackup CR:**
backupType - to set the backup type as "Generic" or "Normal"
storageClass - added this in volumeInfo struct, to store the storageClass used for the PVC. It will be later used in generic restore operation.
**ApplicationBackupSchedule CR:**
backupType - to set the backup type as "Generic" or "Normal"
Yes. Will add proper release Note details in the ticket.
**Does this …

stor-458: Added following changes in stork CRD for data mover feature.

---

go.mod
go.sum
pkg/apis/stork/v1alpha1/applicationbackup.go
pkg/apis/stork/v1alpha1/applicationbackupschedule.go
pkg/applicationmanager/applicationmanager.go
pkg/applicationmanager/controllers/applicationbackup.go
pkg/applicationmanager/controllers/applicationbackupschedule.go
pkg/applicationmanager/controllers/applicationclone.go
pkg/applicationmanager/controllers/applicationregistration.go
pkg/applicationmanager/controllers/applicationrestore.go
pkg/clusterdomains/controllers/clusterdomainstatus.go
pkg/clusterdomains/controllers/clusterdomainupdate.go
pkg/groupsnapshot/controllers/groupsnapshot.go
pkg/k8sutils/k8sutils.go
pkg/metrics/metrics_test.go
pkg/migration/controllers/clusterpair.go
pkg/migration/controllers/migration.go
pkg/migration/controllers/migrationschedule.go
pkg/rule/rule.go
pkg/schedule/schedule.go
pkg/snapshot/controllers/snapshot.go
pkg/snapshot/controllers/snapshotrestore.go
pkg/snapshot/controllers/snapshotschedule.go
pkg/version/version.go
vendor/github.com/kubernetes-incubator/external-storage/snapshot/pkg/client/client.go
vendor/github.com/portworx/sched-ops/k8s/apiextensions/apiextensions.go
vendor/github.com/portworx/sched-ops/k8s/apiextensions/crds.go
vendor/github.com/portworx/sched-ops/k8s/apiextensions/crds_v1beta1.go
vendor/k8s.io/code-generator/generate-internal-groups.sh
vendor/modules.txt

>enhancement
From 1.22 k8s version, v1alpha/v1beta crds are deprecated. This PR add supports for registering stork crds as v1
no
yes
```release-note
Update stork crds to V1 
```
yes, 2.6.6
**Note:**
vendor PR's need to be merged and re-vendor before closing this - 
https://github.com/libopenstorage/external-storage/tree/v0.20.4-openstorage-rc4 (tag is created)
https://github.com/portworx/sched-ops/pull/251 (not-needed-anymore)
with k8s version <1.22 https://jenkins.portworx.dev/job/Stork/view/Stork%202.8/job/stork-2.6.3-px-2.8-rel/29/
k8s version 1.22 : 
```
--- PASS: …
```

Update stork crds to v1

---

pkg/migration/controllers/migration.go

>bug
Check svc annotation map before updating entries to svc annotation resources 
no
no
2.6.5

check destination svc annoatation before assigning keys

---

pkg/apis/stork/v1alpha1/backuplocation.go

storing generic backup repo password.
feature: Data mover (Generic backup support).
stor-467: Added genericBackupRepoKey field in backuplocation CR for
storing generic backup repo password.
Yes, the backuplocation CR will now have a field to pass the generic backup repo password.
No.
Yes, 2.7.x release.

stor-467: Added genericBackupRepoKey field in backuplocation CR for

---

pkg/apis/stork/v1alpha1/backuplocation.go

bug
Changed the field name GenericBackupRepoKey to RepositoryPassword in backuplocation CR
no
no
yes, 2.7.0

stor:468 Changed the field name GenericBackupRepoKey to RepositoryPassword in backuplocation CR

---

test/integration_test/test-deploy.sh

Need a separate parameter in integration tests for kube-scheduler version instead of relying on the k8s version. 
no
no
2.6

Add new parameter for kube-scheduler version

---

pkg/applicationmanager/controllers/applicationregistration.go
pkg/metrics/metrics.go

bug
Currently stork tries to list CR resource by V1 apis which are not supported for older k8s version like <1.13. This PR try to read crd via v1beta1 apis if v1 api list fails
no
no
2.6
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.7", GitCommit:"4683545293d792934a7a7e12f2cc47d20b2dd01b", GitTreeState:"clean", BuildDate:"2019-06-06T01:39:30Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.7", GitCommit:"4683545293d792934a7a7e12f2cc47d20b2dd01b", …
```

Allow list of crd via v1beta1 apis

---

drivers/volume/csi/csi.go

>bug
Fix `stor-485` where completed backup of csi volumes got omitted from list
no
no
no

stor-485: add completed backup volume to backup list

---

drivers/volume/csi/csi.go

>bug
For the CSI driver
- Skip the volumes which are not CSI PVCs in CSI driver restore path.
No
```release-note
ApplicationRestore could fail if there is a mix of CSI and non CSI PVCs with error "snapshot content not found". 
```
Yes - 2.7

STOR-499: ApplicationRestores fail if there is a mix of CSI PVCs and non CSI PVCs

---

drivers/volume/csi/csi.go

>bug
Currently CSI driver uploads all of snapshot CR to Objectstore and delete once done. This causes issue when other non px backup is still in progress & all CSI volume backup is completed, CSI driver will still look at snapshot which is deleted previously and cause application backup to fail. As separate clean up task we should introduce API for driver to clean-up post backup operation, since handling everything in `GetBackupStatus` is prone to error
no
no
2.7

csidriverfix: handle completed backups

---

pkg/applicationmanager/controllers/applicationbackup.go
pkg/applicationmanager/controllers/applicationrestore.go
pkg/storkctl/migration.go

>bug
Fixes -
```
stor-444: Update FinishTimestamp for failed ApplicationBackups
stor-448: Update labels & annot of namespace based on replace policy
stor-443: Update activate/deactivate message for crds
```
no
yes
```release-note
stor-444: Update FinishTimestamp for failed ApplicationBackups
stor-448: Update labels & annot of namespace based on replace policy
stor-443: Correct activate/deactivate migration messages for crds
```
<!--
2.7.0

STOR-444: Update FinishTimestamp for failed ApplicationBackups

---

pkg/extender/extender.go

bug
- Certain storage providers like Portworx proxy volumes or Portworx direct access volumes
do not have the volumeInfo.DataNodes populated. Do not filter out the request for
such volumes.
No
```release-note
If a storage provider does not have the concept of replica nodes for a volume do not error out the filter request while scheduling pods using such storage provider's volumes.
```
Yes - 2.7

STOR-483: Skip filtering for volumes which do not have DataNodes populated

---

pkg/storkctl/clusterdomainupdate.go
pkg/storkctl/clusterdomainupdate_test.go

>bug
- Check if the input domain is part of the existing cluster domains. If it is not
fail the activate/deactivate command.
No
```release-note
storkctl clusterdomain commands would silently fail if the provided input domain was an invalid one. Now storkctl will fail the operation if the input cluster domain is not one of the stork detected cluster domains.
```
Yes - 2.7

STOR-425: Do not silently fail cluster domain update commands for invalid domain

---

drivers/volume/kdmp/kdmp.go
go.mod
go.sum
vendor/github.com/aquilax/truncate/.gitignore
vendor/github.com/aquilax/truncate/.travis.yml
vendor/github.com/aquilax/truncate/LICENSE
vendor/github.com/aquilax/truncate/README.md
vendor/github.com/aquilax/truncate/go.mod
vendor/github.com/aquilax/truncate/truncate.go
vendor/modules.txt

bug.
pb-1908
no
no
2.7?
Note: There is a dependent PR in kdmp where these labels will be used. 
https://github.com/portworx/kdmp/pull/62

pb-1908: Added backup and restore CR name and pvc name in the dataexport CR.

---

drivers/volume/kdmp/kdmp.go

>bug
- In KDMP driver, before a restore operation is started the driver checks if the PVC is in ready state. The check was incorrect since it only checked if VolumeName was populated. Some CSI drivers populate the volume name but the PVC status could still be in Pending state.
- Check for both pvc.Spec.VolumeName is not empty and the PVC status is in Bound state.
No
No
No

KDMP: Before starting a restore check if destination PVC is in Bound state

---

drivers/volume/portworx/portworx.go
go.mod
go.sum
vendor/github.com/libopenstorage/openstorage/api/spec/spec_handler.go
vendor/modules.txt

>feature
This change allows backing up a Portworx volume of a particular storage class
and properties, and restore that volume with a different storage class.
For ex. Backup a volume with HALevel=2 and restore it with HALevel=1
- Parse the storage class mapping from restore spec and find if a mapping
for the current PVC's storage class is found.
- If found, fetch the actual contents of storage class and parse them into
a RestoreVolumeSpec.
- Invoke the CloudBackupRestore API with this RestoreVolumeSpec.
No
```release-note
Add support for backing up a Portworx volume with a particular storage class
and properties, and restore it with a …
```

Portworx: Parse the storage class mapping while restoring a volume.

---

pkg/applicationmanager/controllers/applicationbackup.go

bug
stor-529: Calling cleanupResources as part of finalizer handlers in applicationbackup controller code.
no
no
no
**Testing:** 
With change tried four backups from px-backup and verified that data export CR are getting deleted properly.

stor-529: Calling cleanupResources as part of finalizer handlers in applicationbackup controller code.

---

drivers/volume/aws/aws.go
drivers/volume/azure/azure.go
drivers/volume/csi/csi.go
drivers/volume/gcp/gcp.go
drivers/volume/kdmp/kdmp.go
drivers/volume/linstor/linstor.go
drivers/volume/portworx/portworx.go
drivers/volume/volume.go

>feature
- Create an ordered list of drivers defined in STORK. For every PVC
stork will check these drivers can handle this PVC. If all the drivers
fail the last one in the list - KDMP will pick it up.
- The goal is KDMP should handle all kinds of PVCs for all the different
workflows that stork supports.
- This also means that for currently non-supported APIs by KDMP driver
the respective operation will fail if none of the other drivers support that PVC.
No
No
No

Modified the decision making process for choosing a driver for a PVC.

---

drivers/volume/kdmp/kdmp.go
go.mod
go.sum
pkg/apis/stork/v1alpha1/applicationbackup.go
vendor/github.com/portworx/kdmp/pkg/apis/kdmp/v1alpha1/dataexport.go
vendor/github.com/portworx/kdmp/pkg/controllers/dataexport/reconcile.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiabackup/kopiabackup.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiabackup/kopiabackuplive.go
vendor/github.com/portworx/kdmp/pkg/drivers/options.go
vendor/modules.txt

bug
stor-545: Added provisioner and volumesnapshot fields in applicationbackup CR.
no
no
2.8
Testing:
ApplicationBackup CR:
```
Status:             InProgress
Total Size:         0
Trigger Timestamp:  2021-11-02T16:51:32Z
Volumes:
Options:                      <nil>
Actual Size:                  120861181
Backup ID:                    5018c04eb784902b997bdba8da2b95bc
Driver Name:                  kdmp
Namespace:                    mysql-6
Persistent Volume Claim:      pxcentral-mysql-pvc
Persistent Volume Claim UID:  588851a3-f5db-48aa-86c7-3e8057abe2ce
Provisioner: …
```

stor-545: Added provisioner and volumesnapshot fields in applicationbackup CR.

---

go.mod
go.sum
pkg/snapshotter/snapshotter_csi.go
vendor/github.com/portworx/kdmp/pkg/controllers/dataexport/reconcile.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiabackup/kopiabackup.go
vendor/github.com/portworx/kdmp/pkg/drivers/utils/utils.go
vendor/modules.txt

bug
```
pb-1988: Added alreadyExists check for creation of volumeSnapshot and
PVC creation
- While deleting the snapshot CRs, setting the proper retain
value. For latest snapshot, retain will be set true, so that local
snapshot will be retained. For other snapshots, it will be set
false, so that both the CR and local snapshot files are also
will be deleted
```
no
no
2.8
**Related kdmp PR:**
https://github.com/portworx/kdmp/pull/96

   pb-1988: Added alreadyExists check for creation of volumeSnapshot and     PVC creation

---

drivers/volume/csi/csi.go

bug
stor-514: Added checks such that pure FB and vsphere PVC will be defaulted to kdmp driver for snapshot.
no
no
2.8

stor-544: Added checks such that pure FB and vsphere PVC will be defaulted to kdmp driver for snapshot.

---

go.mod
go.sum
vendor/modules.txt

Vendor changes for openstorage
when i vendor the stork to px-backup, it is changing the openstorage repo version to older version that does not have the changes done by @ram-infrac to make the VerifyRule as public. So updating it to latest version of release9.1 branch.
https://github.com/libopenstorage/openstorage/commit/1c90dd1f3a9036df229094290cfa08e1652b27ec
no
no
no

vendor changes for openstorage repo from release-9.1 branch.

---

drivers/volume/aws/aws.go
drivers/volume/azure/azure.go
drivers/volume/csi/csi.go
drivers/volume/gcp/gcp.go
drivers/volume/kdmp/kdmp.go
drivers/volume/portworx/portworx.go
drivers/volume/volume.go
go.mod
go.sum
pkg/applicationmanager/controllers/applicationrestore.go
vendor/github.com/portworx/kdmp/pkg/apis/kdmp/v1alpha1/dataexport.go
vendor/github.com/portworx/kdmp/pkg/controllers/dataexport/reconcile.go
vendor/modules.txt

>bug
>feature
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
pvc creation for kdmp drivers has been moved to kdmp controller.

[STOR-551]: pvc creation for kdmp restore should happen in kdmp controller.

---

drivers/volume/aws/aws.go
drivers/volume/azure/azure.go
drivers/volume/csi/csi.go
drivers/volume/gcp/gcp.go
drivers/volume/kdmp/kdmp.go
drivers/volume/linstor/linstor.go
drivers/volume/mock/mock.go
drivers/volume/portworx/portworx.go
drivers/volume/volume.go
pkg/applicationmanager/controllers/applicationbackup.go

-Bug
Fixed crash when taking backup of Pure-block and Portworx Volumes
No
No
yes, 2.8
```
prashanthkumar@prashanthkumar--MacBookPro16 pso % k get pvc -npb-1
NAME                  STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
pxcentral-mysql-pvc   Bound    pvc-9d1638e9-4095-46a7-b5f7-c50711e4648b   10Gi       RWO            pure-block     3h7m
prashanthkumar@prashanthkumar--MacBookPro16 pso % k get pvc -npx-backup
NAME                                                      STATUS   VOLUME …
```

stor-547: Fixing crash when taking a backup of CSI and PXD vols

---

drivers/volume/kdmp/kdmp.go

>bug
>feature
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
Putting required fields in application backup CR to use it during restore.
```release-note
```
```
volumebackup sample
"volumes" : [
{
"name" : "pvc-a5c70bbc-f938-413b-b5da-d5a0a875245a",
"namespace" : "dmysql",
"backupId" : "c63f721394c77162ab0b2662245a1db3",
"status" : {
"status" : "Success",
"reason" : "Backup successful for volume"
},
"driverName" : "kdmp",
"totalSize" : "120861181",
"storageClass" : …
```

Putting the volumesnapshot class and backupUID in volume info as these are required in restore.

---

drivers/volume/volume.go

bug
```
pb-2003: added ordered way of classifying the driver in GetPVDriver api
GetPVDriver is used in the resource restore path and we try to
avoid CSI pvc applied again. Since ordered list is not used in
this function, some it ended up in kdmp driver and ended in
partial success.
```
no
no
yes 2.8
Testing
:

pb-2003: added ordered way of classifying the driver in GetPVDriver api

---

drivers/volume/kdmp/kdmp.go

bug
```
pb-2015: remove the storage-class and storage-provisioner annotation
from pvc while restore it.
- Even though we updated the spec.storageclass of the pvc to the
new storage class from the storage class, while restoring
,it was not getting bound. The k8s was referring to the old
storage class from the annotation and pvc was struck in
pending state.
```
no
no
yes, to 2.8 branch 
Testing:
```
root@ip-70-0-97-59:~# kubectl  get all -n efs-pxd
NAME                           READY   STATUS    RESTARTS   AGE
pod/jenkins-56d74cb6fc-5gdz6   1/1     Running   0          26s …
```

pb-2015: remove the storage-class and storage-provisioner annotation from pvc while restore it.

---

drivers/volume/kdmp/kdmp.go

bug
```
pb-2020: Added check in assigning SnapshotStorageClass in dataexport CR.
- Assigng the SnapshotStorageClass in DE CR only when
LocalSnapshotRestore is true, in which case, we will try the
local snapshot restore.
```
no
no
yes 2.8
Testing:
1) created a backup of FA volume with offload to S3 option. It was kdmp backup with local snapshot.
2) Triggered a restore to px-replicated storage class. Since it is a different provisioner, it should select the local restore and move directly to the kopia restore.

pb-2020: Added check in assigning SnapshotStorageClass in dataexport CR.

---

pkg/applicationmanager/controllers/applicationrestore.go

>bug
>feature
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
```release-note
```
** Test **
`2030-restore` is the restore with the fix.

[PB-2030]: pv/pvc should be included as resources in kdmp restore list.

---

pkg/applicationmanager/controllers/applicationbackup.go

bug
pb-2061: removed the incorrect error handling while calling runtimeclient.ObjectKeyFromObject function.
This makes the invalid rule command execution during backup to hang.
no
no
2.8
Testing:

pb-2061: removed the incorrect error handling while calling runtimeclient.ObjectKeyFromObject function.

---

drivers/volume/csi/csi.go
drivers/volume/kdmp/kdmp.go
pkg/snapshotter/snapshotter_csi.go

>improvement
- If the SnapshotClassName is set as "default" or "Default"
let Kubernetes handle the snapshot class selection. It wil use
the default snapshot class set by the admin for that CSI provider.
- Do not create stork-* volume snapshot class on startup if a snapshot
class for the CSI driver already exists.
No
Yes
```release-note
STORK will not create a VolumeSnapshot class if there already exists one for the CSI provider.
```
Yes - 2.8

STOR-528: CSI VolumeSnapshotClass fixes

---

cmd/stork/stork.go

Enhancement
- user can set env MARKET_PLACE=aws to specify the stork being deployed on
AWS marketplace so that appropriate kopia executor image is picked from
market place repository
No
No
Yes, 2.8
Manual test
1. Set the following env in stork deployment spec
```
env:
- name: MARKET_PLACE
value: aws
```
2. Deployed stork and could see kopia executor image is pointing to marketplace repository
```
kubectl describe cm kdmp-config -nkube-system
Name:         kdmp-config
Namespace:    kube-system
Labels:       <none>
Annotations:  <none>
Data
====
KDMP_BACKUP_JOB_LIMIT:
----
5 …
```

Adding env variable to specify market place deployment

---

pkg/applicationmanager/controllers/applicationrestore.go

- Bug
As part of the restore, skip those ns which are not part of source ns mapping as part of restore ns mapping provided. 
No
No
Yes, 2.8

Skipping namespaces which are not part of restore ns mapping

---

pkg/resourcecollector/clusterrole.go

>bug
Collect clusterrolebiding subjects if SA is missing on destination cluster
no
no
2.8

PB-2079: collect clusterrolebinding subjects if sa is not found

---

pkg/resourcecollector/clusterrole.go

\**What type of PR is this?**
>bug
Revert permission based cluster-role/binding listing and collection, this was causing to  restore of rolebinding/clusterrolebinding with empty `subjects`
no
no
2.8

revert clusterrolebinding collection based on user access to SA

---

drivers/volume/kdmp/kdmp.go
pkg/snapshotter/snapshotter_csi.go

bug
no
no
2.8
Tested the fix on ocp setup of QA.

pb-2101: Fixed the issue in isCSISnapshotClassRequired function such that for non CSI volumes, it will directly go the kdmp backup

---

drivers/volume/kdmp/kdmp.go
pkg/applicationmanager/controllers/applicationclone.go
pkg/applicationmanager/controllers/applicationrestore.go
pkg/resourcecollector/persistentvolume.go
pkg/resourcecollector/resourcecollector.go

Bug
- As part of the restore, fetch the driver from the vol info instead of calling GetPVDriver()
- Removed volume.kubernetes.io/selected-node annotation from the PVC spec or else Azure PVC
always tries to get bounded to the same node which might not be present
No
No
Yes
Manual test
1. Took a backup on Azure useast region
2. Tried to restore the backup to uswest region cluster
3. Backup was successful
Content fof PV onbaackup cluster
```
ka get pv pvc-f959288c-1393-4955-914b-0c4480361c36 -oyaml
apiVersion: v1
kind: PersistentVolume
metadata:
annotations: …
```

Fixing kdmp restore across Azure regions

---

drivers/volume/kdmp/kdmp.go

bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
Avoiding readding the volumesnapshot name in each backupstatus call.
```release-note
Issue:
User Impact:
Resolution
```
** Test **
GetBackupstatus was called multiple times during the backup of following 2 volumes.

[PB-2094]: Preventing readding of volumesnapshotname in the applicationrestore CR.

---

drivers/volume/kdmp/kdmp.go

bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
As volumesnapshotclass name and pvc name can contain ".", using "," as the delimeter for forming the composite string for volumesnapshot.
```release-note
Issue:
User Impact:
Resolution
```
Tested:
1.Backup
2.Restore
3.Delete
backup
restore

[PB-2104]: Using "," as the delimiter for the composite string of volumesnapshot.

---

drivers/volume/volume.go

> bug
pb-2110: Fixed the issue in return value of IsCSIDriverWithoutSnapshotSupport api for non-csi case
no
no
yes, 2.8
Testing:
- Tested it on the QA system where it was failing. Now backup went through for azure file SC.
```
[root@ip-70-0-76-117 ~]# kubectl describe sc azurefile
Name:                  azurefile
IsDefaultClass:        No
Annotations:           <none>
Provisioner:           kubernetes.io/azure-file
Parameters:            skuName=Standard_LRS
AllowVolumeExpansion:  True
MountOptions:
mfsymlinks
actimeo=30
ReclaimPolicy:      Delete
VolumeBindingMode: …
```

pb-2110: Fixed the issue in return value of IsCSIDriverWithoutSnapshotSupport api for non-csi case

---

go.mod
go.sum
vendor/github.com/portworx/kdmp/pkg/controllers/dataexport/dataexport.go
vendor/modules.txt

>bug
>feature
improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
vendoring in kdmp changes for reading dataexport CR using schedops api.
```release-note
Issue:
User Impact:
Resolution
```

vendoring in latest kdmp.

---

drivers/volume/volume.go
pkg/snapshotter/snapshotter_csi.go

>bug
```
pb-2116: Added kubernetes.io/azure-file provison in
csiDriverWithoutSnapshotSupport
- moved the check to pv.Spec.CSI secion in CreateSnapshot up,
immediately after getting the pv content.
- Added a note to mention that filestore.csi.storage.gke.io gke
filestore support snapshot.
```
no
no
2.8 release branch

pb-2116: Added kubernetes.io/azure-file provison in csiDriverWithoutSnapshotSupport 

---

drivers/volume/kdmp/kdmp.go

>bug
```
pb-2113: Setting storageclass to nil in pvc, if it is empty.
- The default storageclass configured on the setup, will be
picked up, only when the storageclass is not set.
- Emptystring as pvc storageclass will not select
the default storageclass configured on the cluster.
```
No
No
2.8 release branch
**Testing:**
- Now the default storageclass is selected.
- The failure is because of access-mode issue, which is a known issue.
- Some cleanup in error message is needed in kdmp controller. Will raise a kdmp PR seperately.
**Note:**
```
root@ip-70-0-97-59:~# kubectl …
```

pb-2113: Setting storageclass to nil in pvc, if it is empty.

---

drivers/volume/kdmp/kdmp.go

>bug
pb-2125: Added check for nil SC in getRestorePVCs
no
no
2.8
Testing: 
In Tripti's setup, the pvc in the cassandra namespace was not having SC in the spec but had SC in the annotation. Because of that when she selected default option in the restore, we end up in nil SC. 
So added nil check where we are checking for empty SC.
```
[root@ip-70-0-76-117 ~]# kubectl get pvc cassandra-data-cassandra-0 -n cassandra -o yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
annotations:
pv.kubernetes.io/bind-completed: "yes"
pv.kubernetes.io/bound-by-controller: "yes" …
```

pb-2125: Added check for nil SC in getRestorePVCs

---

pkg/applicationmanager/controllers/applicationclone.go
pkg/applicationmanager/controllers/applicationrestore.go
pkg/resourcecollector/persistentvolumeclaim.go
pkg/resourcecollector/resourcecollector.go

>bug
During an ApplicationRestore, if the storage class mapping was provided, stork would not set the new
storage class on the destination side where the PVC was being restored
- If the storage class mapping is set on ApplicationRestore on the PVC's
source storage class is found in this mapping, then on the destination cluster where
the PVC is being recreated set the new storage class obtained from this mapping.
No
```release-note
Improvement: STORK now supports choosing a different storage class for a PVC which is being restored using the ApplicationRestore CR. This is …
```

Set the new storage class on the PVC during ApplicationRestore

---

pkg/applicationmanager/controllers/applicationrestore.go

Bug
As part of restore if a user selects a few PVC's to be restored, filter the
non-selected PVCs from includeResource map. This is applicable for
the case where Retain is selected.
No
No
yes, 2.8
Screen shot with fix
Backup Object
Restore object with single PVC succeeded

Select only PVC's from includeResource if provided

---

pkg/snapshotter/snapshotter_csi.go

bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
In case of restores from csi snapshot if the pvc is in pending state but storage class volumebindingmode is set as
WaitForFirstConsumer, restore status is declared successful.
```release-note
Issue: If csi restore fails with timeout because pvc was remaining in pending state waiting for the first consumer.
User Impact:
Resolution: Now the pvc restore status will be successful which will in turn get consumed by the app.
```
**Does this …

[PB-2133]: Checking for waitforfirstConsumer if pvc's storage class has that set as volumebindingmode.

---

pkg/migration/controllers/clusterpair.go

bug
Stork will try to create a clusterpair if there are ANY storage options provided, and our docs suggest adding 'mode: DisasterRecovery'. Which causes the storage status to ERROR in a Metro DR pair, when it should be notProvided. I made it so we only attempt to create a pair if a token is provided.
no
no
no

STOR-516 only try to create a clusterpair if a token is provided

---

pkg/resourcecollector/persistentvolumeclaim.go

bug
pb-2151: Added check to make sure zone array is not empty in preparePVCResourceForApply.
For kdmp, we will not have zones set. So added check for the zone array before accessing it.
No
No
2.8

pb-2151: Added check to make sure zone array is not empty in preparePVCResourceForApply

---

drivers/volume/volume.go

bug
pb-2156: Added logic to default to KDMP for OCP rdb and cephfs provisioner.
no
Yes
```release-note
Issue: On some OCP setup, we hit timeout for clone(restore) operation.
User Impact: User will not be able to take backup on OCP setup.
Resolution: For now, default to generic, if it is OCP provisioner.
```
2.8 branch
**Testing:**
Testing on the OCP that it is default to the KDMP directly.

pb-2156: Added logic to default to KDMP for OCP rdb and cephfs provisioner

---

pkg/resourcecollector/role.go

bug
pb-2157: retaining the rolebinding subjects if the namespace is not set during restore.
no
Issue: subject of rolebinding that does not have namespaces were not getting restored.
User Impact: Subjects in the rolebinding are missing after restore.
Resolution: Currently retaining the subject if they do not have namespace
2.8
```
source namespace:
[root@central-legend-seed-0 ~]# kubectl  describe  rolebindings px-backup-role-binding -n central
Name:         px-backup-role-binding
Labels:       app.kubernetes.io/component=px-backup
app.kubernetes.io/instance=px-central …
```

pb-2157: retaining the rolebinding subjects if the namespace is not set during restore.

---

drivers/volume/kdmp/kdmp.go
drivers/volume/volume.go

Skipping zone checks for EFS provisioner for  generic backup/restore paths
No
Not needed as EFS support is coming in as part of this release
Yes, 2.8
Test results in the bug

Skipping zone checks for EFS provisioner for  generic backup/restore paths

---

pkg/snapshotter/snapshotter_csi.go

>bug
feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
If volumebindingmode is WaitForFirstConsumer, in case of csi/generic volume drivers we create the pvc from the local snapshot in case of restore. Now a temp job has been added just to mount the pvc and do nothing more so that we have a real PV associated with the pvc once the volume restore is declared as successful.
```release-note
Issue: Generic backup and restore was failing if volume binding mode was WaitForFirstConsumer and if the …
```

[PB-2148]: Implementing job framework to make pvc bound in case of waitforfirstconsumer case for generic backups.

---

pkg/resourcecollector/role.go

>bug
```
pb-2162: Added fixes for backup/restore on ocp environment.
- Including system:openshift:scc rolebinding in the backup
- Added privileged scc for job role.
```
No
No
2.8 branch.

pb-2162: Added fixes for backup/restore on ocp environment.

---

drivers/volume/portworx/portworx.go

>improvement
* Operator with security enabled generates tokens with jwt issuer as `operator.portworx.io` 
* Need to add support for this jwt issuer when initializing portworx volume driver
* Without this support stork defaults to `stork.openstorage.io` which results in failures when inspecting volumes/snapshots,
e.g https://jenkins.portworx.dev/job/Stork/job/stork-2.7-px-2.9-csi-security/16/console
no
2.8

Add support for openstorage.portworx.io as jwt issuer

---

cmd/stork/stork.go
pkg/migration/controllers/migration.go
pkg/migration/migration.go

improvement
Use go routines to parallelize applying resources during migration for improved performance
New int arg for stork "migration-max-threads" (default 4)
```release-note
Issue: 
New "migration-max-threads" arg for stork (default 4) allowing parallel application of  kubernetes resources during migration.
User Impact:
Improved migration performance for large number of kubernetes resources.
```
no
**RESULTS**
1k config maps on 4 core vms
1 thread: 15m
10 thread: 15m
So far no difference, could be the type of resources I used, they are very small, or the VM cluster …

STOR-573 apply updatedObjects in parallel during migration

---

pkg/migration/controllers/migration.go
test/integration_test/migration_test.go
test/integration_test/specs/cassandra/portworx/px-sc.yaml
test/integration_test/specs/mysql-1-pvc/portworx/px-sc.yaml

>bug
From stork 2.6.4 onwards SC field for migrated pvcs has been removed. For migrated pvcs user can't perform resize 
operation since SC is missing. This PR keep SC field for migrated pvc and ensure pvc resize changes on source also reflects on DR 
Note: Stork does not support migration of StorageClass, if SC is missing on destination cluster one needs to create it to perform resize pvc operation
no
yes
```release-note
Issue: Unable to resize migrated pvcs
User Impact: From stork 2.6.4 onwards SC field for migrated pvcs has been removed to support pvc size reflection on DR site. For migrated pvcs user can't perform resize operation since …
```

STOR-538: Keep storage class name for migrated pvcs

---

pkg/snapshot/controllers/snapshotschedule.go

>bug
Make sure `volumesnapshotschedule` snapshot status always in-sync with `volumesnapshots` triggered by it 
no
yes
```release-note
Issue: SnapshotSchedule have incorrect sync status with snapshot triggered if underlying driver went offline at time of SnapshotCreate API call 
User Impact: SnapshotSchedule will have Error status but Snapshot object would have successful status for same snapshot
Resolution: Fixed issue to make volumesnapshotschedule and volumesnapshot object status always in-sync
```
yes, 2.9.0

Always sync volumesnapshotschedule and volumesnapshot status

---

.travis.yml
pkg/appregistration/appregistration.go

>bug
Allow PerconaXtraDBCluster to shut-down gracefully via `spec.Pause` option -
https://www.percona.com/doc/kubernetes-operator-for-pxc/pause.html
no
```release-note
Issue: Incorrect suspendOption provided PerconaXtraDBCluster CR, causing not to shut-down all pods created by cluster via storkctl activate/deactivate migration cmd
User Impact: Unable to activate/deactivate PerconaXtraDBCluster cluster gracefully 
Resolution: Since PerconaXtraDBCluster has multiple child server, proper way to gracefully shutdown it is via `spec.Pause` path. User either can change appreg option for PerconaXtraDBCluster or delete entry and allow stork to …
```

Update PerconaXtraDBCluster suspend option to gracefully shutdown cluster

---

pkg/apis/stork/v1alpha1/applicationregistration.go
pkg/appregistration/appregistration.go
pkg/migration/controllers/migration.go
pkg/storkctl/migration.go

>enhancement
This PR add support for providing multiple suspend option for single CR via `customsuspendoption`
yes
```
kind: ApplicationRegistration
metadata:
name: perconadb
resources:
- customSuspendOptions:
- path: spec.haproxy.enabled
type: bool
value: "false"
group: pxc.percona.com
keepStatus: false
kind: PerconaXtraDBCluster
podsPath: ""
suspendOptions:
path: spec.pxc.size
type: int
value: ""
version: v1
```
yes
```release-note
Issue: Support child server activate/deactivate for CR resources
User Impact: Unable to migrate CR's that requires multiple suspend  path for child servers in …
```

PWX:22836 - Support child server activate/deactivate for CR resources

---

test/integration_test/extender_test.go
test/integration_test/migration_test.go
test/integration_test/specs/mysql-migration-schedule-interval-autosuspend/migrationschedule.yaml
test/integration_test/specs/mysql-migration-schedule-interval-autosuspend/schedulepolicy.yaml

Fix integration tests 
```
pvcResizeTest - wait for next migration schedule to trigger
driverNodeTest - Adjust pods reschdule time with updated health monitor timeout
pvcOwnershipTest - use correct storage-provisioner annotation
pvcResizeTest - wait for 2 migration to trigger
suspendMigrationTest - add autosuspend:true to migration schedule specs
```
no
no
no
jenkins job :
migration test - 
```
http://jenkins.pwx.dev.purestorage.com/job/Stork/job/stork-dev-test-2/33/console
http://jenkins.pwx.dev.purestorage.com/job/Stork/job/stork-dev-test-2/30/console …
```

pwx-22958: Fix faling integration-test

---

pkg/applicationmanager/controllers/applicationbackup.go
pkg/k8sutils/k8sutils.go
pkg/rule/rule.go

>bug
```
pb-2172: Added fixes related to handling of rule command executor image.
- Added CMD-EXECUTOR-IMAGE-REGISTRY and CMD-EXECUTOR-IMAGE-REGISTRY-SECRET environment variable
to get the custom regitry name and secret for rule command executor pod image.
- Added the annotation to get the image registry secret value,
if some one pass the custom image registry value as annotation in the rule CR.
- Added logic to take the image registry name and secret value
from the stork deployment if the both the env and rule annotation is missing.
- Also, add a fix to fail the backup and delete the rule command
executor pod, if the rule command executor pod is struck in Pending phase for more
than five minutes. Some times, it gets …
```

pb-2172: Added fixes related to handling of rule command executor image.

---

test/integration_test/common_test.go
test/integration_test/extender_test.go
test/integration_test/migration_failover_failback_test.go
test/integration_test/migration_test.go

- Put all migration tests under one suite
- Fix bi-directional migration test to write kubeconfig changes to different directory, so that 
consecutive tests will not fail while scanning specDir
no
Jenkins job : http://jenkins.pwx.dev.purestorage.com/job/Stork/view/Stork%202.9-dev%20%20C7/job/stork-master-px-2.10-all-tests/

Allow to run complete integration suite

---

drivers/volume/kdmp/kdmp.go
go.mod
go.sum
pkg/k8sutils/k8sutils.go
pkg/snapshotter/snapshotter_csi.go
vendor/github.com/portworx/kdmp/pkg/apis/kdmp/v1alpha1/dataexport.go
vendor/github.com/portworx/kdmp/pkg/controllers/dataexport/reconcile.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiabackup/kopiabackup.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiabackup/kopiabackuplive.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiadelete/kopiadelete.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiamaintenance/kopiamaintenance.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiarestore/kopiarestore.go
vendor/github.com/portworx/kdmp/pkg/drivers/options.go
vendor/github.com/portworx/kdmp/pkg/drivers/utils/utils.go
vendor/github.com/portworx/sched-ops/k8s/apps/statefulsets.go
vendor/github.com/portworx/sched-ops/k8s/core/pods.go
vendor/github.com/portworx/torpedo/drivers/scheduler/k8s/k8s.go
vendor/modules.txt

bug
```
pb-2219: Add changes to use the registry name and image secret for kopia
executor from stork deployment spec.
- Add GetStorkPodNamespace to get the stork pod namespace, even
if it is not installed in the kube-system.
```
No
```release-note
Issue: In the current releases, customer need to configure the kopia executor image registry and secret details in the configmap after installing the stork.
User Impact: User need to configure the registy and image secret in the configmap separately.
Resolution: Now these details will be picked up from the strok deployment spec. If it is different registry for kopia executor, customer need to set …
```

Pb 2219: Add changes to use the registry name and image secret for kopia executor from stork deployment spec.

---

pkg/migration/controllers/clusterpair.go
pkg/migration/controllers/migration.go
pkg/migration/controllers/migrationschedule.go

>bug
PWX-23117: Raise an event if Migration/MigrationSchedule object is pointing to an invalid or a non-existed ClusterPair
PWX-23215: Set the elapsed time for Volumes or Resources only if they are getting migrated. 
No
```release-note
Improvement: Stork will now raise an event when a Migration or a MigrationSchedule object is referring to a non-existed or invalid ClusterPair
```
Yes - 2.9

PWX-23117, PWX-23215: Multiple 2.9.0 fixes

---

pkg/applicationmanager/controllers/applicationbackupschedule.go
pkg/objectstore/azure/azure.go
pkg/objectstore/common/common.go
pkg/objectstore/google/google.go
pkg/objectstore/objectstore.go
pkg/objectstore/s3/s3.go

>bug
```
pb-2179: Added changes required for the supporting object lock for backupschedule deletion.
- Adding the "object-lock-retention-period" annotation to the
applicationbackup CR created by applicationbackupschedule in stork
- This retention period annotation value will be used in the backupscync
logic to update the retention period of the synced backup object.
- Added GetObjLockInfo in stork objectstore as it needs to be called in
stork as well as px-backup
```
no
no ( From stork, we are not claiming the object lock support, So nothing need to documented.)
Currently …

pb-2179: Added changes required for the supporting object lock for backupschedule deletion.

---

pkg/objectstore/s3/s3.go

>bug
```
pb-2241: fixed a nil pointer access in GetObjLockInfo function.
```
no
no
no
**Testing:**
Verified the fix with px-backup code by creating backuplocation with portworx colo lab minio that does not support objectlock.

pb-2241: fixed a nil pointer access in GetObjLockInfo function.

---

drivers/volume/portworx/portworx.go
pkg/migration/controllers/clusterpair.go

>bug
Allow scheduling decision for pods using FA/FB pvcs
no
```release-note
Issue: Unable to recognise storage driver for FA/FB pvc
User Impact:  Pods using FA/FB backed pvcs getting scheduled on non-px nod
Resolution: Pods using FA/FB backed pvcs will now allowed to be scheduled by stork scheduler
```
yes, 2.9
Extender integration job: http://jenkins.pwx.dev.purestorage.com/job/Stork/job/stork-dev-test/118/consoleFull

PWX-23244: Allow pods using FA/FB pvcs in scheduling decisions

---

pkg/objectstore/azure/azure.go
pkg/objectstore/google/google.go

>bug
```
pb-2260: Return default objLockInfo struct instead of error for gke and azure bucket in GetObjLockInfo
```
no
no
no
Testing:
Before fix:
After fix:

pb-2260: Return default objLockInfo struct instead of error for gke and azure bucket in GetObjLockInfo

---

cmd/stork/stork.go
pkg/applicationmanager/controllers/applicationbackupschedule.go
pkg/k8sutils/k8sutils.go

- Created a configMap related to object lock which can be used for altering
the incremental count of schedule backups.
- Implemented the following logic, if the retention period is altered in
between two scheduled backup, then backup will fail for an invalid
retention period
bug
bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
**What this PR does / why we need it**: In case of schedule backup we need to fail the backup if in case user alters the S3 bucket's retention period. In addition we should check every time if the future schedule backup is abiding to minimal retention …

pb-2259: Fail the schedule-backup for an invalid retention period

---

drivers/volume/aws/aws.go
drivers/volume/azure/azure.go
drivers/volume/gcp/gcp.go
go.mod
go.sum
pkg/apis/stork/v1alpha1/backuplocation.go
test/integration_test/webhook_test.go
vendor/github.com/portworx/sched-ops/k8s/stork/backuplocation.go
vendor/github.com/portworx/torpedo/drivers/scheduler/scheduler.go
vendor/modules.txt

> improvement
Backuplocation CR will now have credentials which will be used for taking snapshot and restoring volumes for different cloud vendors.
```release-note
Issue: Stork uses NodeRoleInstance instead of user specified IAM user cloud credentials for taking backup and restoring
User Impact: User IAM in cloud credential associated with the cluster in px-backup is not getting respected
Resolution: User IAM in cloud credential associated with the cluster in px-backup can be utilised 
```
Test:
====
1. Tested in EKS cluster with backup, restore and backupschedule (updated in PB-2194)
2. Tested in AKS cluster with backup, restore and …

[PB-2194]: backuplocation object to have crdential info associated with the cluster.

---

Dockerfile

>bug
Upgrade openssl libs to latest for RHEL 8 Ubi image for CVE reported `CVE-2022-0778`
no
no
yes,2.9

Upgrade openssl libs

---

Makefile
pkg/applicationmanager/controllers/applicationbackupschedule.go

bug
pb-2266
No
All add the release note in px-backup as we are not claiming the generic backup from stork.
No

pb-2266: Adding backupType in the applicationbackup CR created by schedule backups.

---

drivers/volume/aws/aws.go
drivers/volume/azure/azure.go
drivers/volume/gcp/gcp.go

bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
This fix has 2 purposes.With the support cluster credentials in a secret,
it is required for
1. Backward compatibility
2. When the IAM or SA does not have permission to create secret.
```release-note
Issue:
User Impact:
Resolution
```
*Test*
Have tested with px-backup 2.1.2 and px-backup master with the stork fix on AKS cluster.

[PB-2270]: Initializing cred values from backuplocation only if cluster secret is provided.

---

drivers/volume/aws/aws.go

>bug
pb-2288: ebsVolume.Size is size in GiB, So converting it to bytes.
No
```release-note
Issue: The restore size for EBS volumes was displaying incorrectly
User Impact: It will be confusing for user as the restore is less than the backup size for EBS volume.
Resolution: Fixed to correct restore size for EBS volume
```
yes, to 2.10 branch
Testing:

pb-2288: ebsVolume.Size is size in GiB, So converting it to bytes.

---

pkg/k8sutils/k8sutils.go

>bug
```
pb-2293: add logic to extract registry that container extra directories
with in it for rule cmd executor.
```
no
No, planning to add a seperate section in the air-gapped documentation.
2.10 branch.

pb-2293: add logic to extract registry that container extra directories with in it for rule cmd executor.

---

pkg/applicationmanager/controllers/applicationbackupschedule.go

The scheduled failed backup which is created for object-locked bucket
need to set retention period appropriately. This helps px-backup to
delete them when auto-delete flag enabled in px-backup.
bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
**What this PR does / why we need it**: For a failed scheduled backup, specifically for object-locked backup , the retention period need to be set appropriately. This helps in auto deletion of failed backup if opted in schedule policies. …

pb-2325: Set retention period for object-locked Failed backup

---

pkg/applicationmanager/controllers/applicationbackupschedule.go
pkg/k8sutils/k8sutils.go

When a scheduled backup failed due to insufficient retention period then
user need to be aware of minimum retention period to be set via error
message.
bug
**What this PR does / why we need it**: User need to know about the minimum retention period required when a scheduled backup fails due to insufficient retention period set on the S3 bucket. 
**Does this PR change a user-facing CRD or CLI?**:No
**Is a release note needed?**:No
```release-note
Issue:
User Impact:
Resolution
```
**Unit test**
Below screen shot shows the same

pb-2298: minimum retention period added to error msg of failed backup

---

drivers/volume/csi/csi.go
pkg/version/version.go

CSIDriver V1beta1 API support is removed from k8s1.22 verson.
This caused certain DS to initiliazed nil and caused crash for CSI based
backup. Added adequet check and called appropriate APIs of CSI driver.
bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
**What this PR does / why we need it**: the CSIdriver v1beta1 APIs are removed for k8s-1.22 and beyond. this caused v1beta1 based APIs to fail and make certain data structure nil initialised and eventually a crash in stork. This specifically happens for CSI driver based backups 
**Does this PR change a user-facing CRD or …

pb-2324: CSIDriver V1 version API needed for k8s 1.22 and beyond

---

pkg/k8sutils/k8sutils.go

>bug
```
pb-2330: Made fix to support image name to have custom repo as well for cmdexecutor image
```
no
Planning to add seperate documentation for the custom image in air-gapped environment.
2.10

pb-2330: Made fix to support image name to have custom repo as well for cmdexecutor image

---

pkg/rule/rule.go

>bug
```
pb-2330: remove the portworx repo name from default defaultCmdExecutorImage to support custom repo
```
no
no. Planning to added separate section in px-backup documentation.
yes, 2.10

pb-2330: remove the portworx repo name from default defaultCmdExecutorImage to support custom repo

---

pkg/rule/rule.go

>bug
pb-2360
no
More details regarding the custom image require for air-gapped env is getting document in px-backup documentation.
2.10

pb-2360: Using GetStorkPodNamespace api for cmdexecutor  image extraction as well.

---

drivers/volume/kdmp/kdmp.go

bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
If pvc name is small (less than 8 chars), during cleanup after  generic restore, stork crashes.
no
-->
no
```
*Test*
Tested the restore of a cephfs volume having pvc name of 6 chars. 
Updated PB-2365

PB-2365: Use pvcUID instead of name while creating dataexport CR during generic backup cleanup.

---

drivers/volume/kdmp/kdmp.go

>bug
pr-2081
no
yes
```release-note
Issue: Restore of the PVC spec from the backup, which was taken with datasource pointing to volume snapshot will fail ad volume snapshot will not be present.
User Impact: Restore of PVC spec with datasource point to volumesnapshot will fail.
Resolution: Reseting the datasource field before store, so that new details of volume will be updated during restore.
```
2.10

pb-2081: In kdmp case, resetting the Datasource field of pvc for restore

---

.travis.yml
pkg/objectstore/s3/s3.go

Handle error code "NoSuchBucket" while fetching object lock info for a
AWS S3 based bucket.
bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
**What this PR does / why we need it**: When a user creates a backuplocation object without validation flag set then code fails to fetch the object lock info for the bucket as the bucket wouldn't have created during validation process. Hence "NoSuchBucket" error is discounted in the object lock info fetch logic. It enables stork to create the bucket in later point in time. This is found in integration test for AWS S3 bucket. This issue …

pb-2371: Handle non-existent bucket scenario for object-lock

---

pkg/apis/stork/v1alpha1/migration.go
pkg/migration/controllers/migration.go

improvement
* In a migration schedule, if  a namespace that is present in the migration schedule is deleted, then we throw an error and fail subsequently triggered migrations
* This results in stoppage of migrations for namespaces that are still present and which the user would like to be migrated
Improvement can be as below:
* Even if a deleted namespace is present in a migration schedule, add warning messages but proceed with migration of other namespaces.
* Add flag in the migration schedule spec to proceed with migrations for other namespaces even if some namespaces are deleted. …

Skip deleted namespaces from a migration schedule

---

specs/stork-deployment.yaml
specs/stork-scheduler.yaml
test/integration_test/test-deploy.sh

>enhancement
      From kuberentes deprecated version 1.22 onward `schduler-name` flag is depreacted, now custom scheduler needs to be registered via `KubeSchedulerConfiguration` . </p>
This PR add doc spec changes needed for stork-scheduler with 1.22 kube-scheduler image
k8s changelog : https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.22.md#changelog-since-v1210
no
yes
```release-note
Issue: Stork-scheduler pods are unable to come up on k8s 1.22 with image scheduler image `k8s.gcr.io/kube-scheduler-amd64:1.22`
User Impact: User has to use older k8s scheduler image on k8s 1.22 version
Resolution: Customer can use …
```

Stork scheduler support with k8s 1.22

---

pkg/migration/controllers/migration.go
pkg/resourcecollector/datavolume.go
pkg/resourcecollector/resourcecollector.go
pkg/resourcecollector/virtualmachine.go
pkg/resourcecollector/virtualmachineinstance.go

>improvement
Support VM object migration. Ensure all of child CR and volumes migrated properly
no
yes
```release-note
Issue: kube-virt VM object migration is partial successful
User Impact: Users has to do manual intervention to successfully start VM on DR site
Resolution:  stork can migrate and manage kube-virt VM resources activation/deactivation
```
2.11

PWX-23582: VM object migration support

---

pkg/appregistration/appregistration.go
pkg/storkctl/factory.go
pkg/storkctl/migration.go

>enhancement
This PR add support to set  QPS & Burst rate for storkctl command.
yes
```
real	0m0.844s
user	0m0.176s
sys	0m0.046s
```
yes
```release-note
Issue: storkctl activate takes too much time 
User Impact:  Activate/Deactivate migrated apps takes too much time
Resolution: storkctl now accept qps and burst rate for limiting k8s api queries 
```
yes, 2.11

PWX-23579 : Allow setting QPS & Burst rate for storkctl command

---

pkg/migration/controllers/migration.go

bug
https://portworx.atlassian.net/browse/PWX-24190
Volume migration elapsed time is incorrectly showing total time, want to match start/volume migration finish timestamps
no
no
2.11

PWX-24190 Fix elapsed volume migration time when completed

---

pkg/appregistration/appregistration.go
pkg/migration/controllers/migration.go

> bug
Stork Migration controller list all of k8s resources for migrating volume only resources, with this PR migration controller will only collect resources resources required for volume only migration
no
yes
```release-note
Issue: Stork Migration controller list all k8s resources for `volumeOnly` Migration
User Impact: Resource Migration taking too much time for `volumeOnly` Migration
Resolution: Stork now only list pvc and pv required for driver volume migration
```
2.11
Integration job: https://jenkins.pwx.dev.purestorage.com/job/Stork/view/Stork%202.11-dev%20%20C7/job/s …

Do not list all k8s resources for volumeonly migration

---

cmd/cmdexecutor/cmdexecutor.go

improvement
This PR adds `-selector` and `-namespace` flags. These flags provide user with another way to specify the list of pods where to run the command. 
The `-selector` and `-namespace` args cannot be combined with the `-pod` args as this flag already requires the namespace to be included (`-pod my-namespace/my-pod`).
The behavior of the `selector` is intended to be similar [to the one in `kubectl` itself](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#list-and-watch-filtering).
**Example usage**: 
```shell
cmdexecutor -cmd <cmd> -taskid <taskid> -namespace my-namespace -selector label1=value1,label2=value2
```
Yes, without breaking …

DS-2051: Add `selector` and `namespace` args.

---

drivers/volume/portworx/portworx.go

>improvement
- Portworx now supports Pure FA direct access volumes. 
- The portworx driver should treat these volumes as Portworx volumes in scheduling decisions. 
No
Yes
-->
```release-note
Improvement: Portworx FA DirectAccess volumes will now be considered in stork scheduling decisions.
```
Yes - 2.11
** Testing Notes **
Pinned a pod using FA DA volume on a node which has no Portworx installed. Pod is in pending state with the following events
```
Events:
Type     Reason            Age                From   Message
----     ------            ----               ---- …
```

PWX-24000: Treat pure backend block volumes as Portworx volumes

---

drivers/volume/csi/csi.go
go.mod
go.sum
pkg/snapshotter/snapshotter_csi.go
pkg/version/version.go
vendor/github.com/portworx/kdmp/pkg/controllers/dataexport/reconcile.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiabackup/kopiabackup.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiabackup/kopiabackuplive.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiadelete/kopiadelete.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiamaintenance/kopiamaintenance.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiarestore/kopiarestore.go
vendor/github.com/portworx/kdmp/pkg/drivers/options.go
vendor/github.com/portworx/kdmp/pkg/drivers/utils/utils.go
vendor/github.com/portworx/kdmp/pkg/version/version.go
vendor/modules.txt

pb-2328: Support both v1 & v1beta1 version of volumeSnapshot feature
- Added support for V1 VolumeSnapshot APIs which is GA from
kubernetes 1.20 version.
**What type of PR is this?** BUG
bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
**What this PR does / why we need it**: From k8s 1.20 onwards the volumesnapshot feature is promoted to GA, hence we need to support corresponding APIs at the same time maintain backward compatibility with v1beta1 till it is removed in future version. 
**Does this PR change a user-facing CRD or CLI?**: It doesn't change any existing CRDs rather expects user to installs new …

pb2328: Support both v1beta1 and v1 for CSI volume snapshot APIs

---

cmd/stork/stork.go
pkg/snapshotter/snapshotter_csi.go

Added a configMap which can alter the snapshot timeout period this helps
in addressing OCS cluster issues wherein it takes genuinely more time.
bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
**What this PR does / why we need it**: In certain OCP version the local snapshot takes a lot of time to complete it hence we need to keep the timeout configurable. So that user can experiment with it based on the OCP version and types of Node config it is running the OCP setup. 
**Is a release note needed?**: NO
**Does this change …

pb-2037: Making snapshot timeout configurable

---

Makefile
pkg/apis/stork/v1alpha1/migration.go
pkg/migration/controllers/migration.go
pkg/resourcecollector/networkpolicy.go
pkg/resourcecollector/resourcecollector.go

>improvement
Stork collect only network policies which does not have CIDR set, This PR add option to  collect all network policies regardless of CIDR check
yes, MigrationSchedule/Migration spec now has `skipNetworkPolicyCheck` option to ignore network policies check
```
kind: MigrationSchedule
metadata:
name: mysql-migration-schedule-weekly-invalid
spec:
schedulePolicyName: default-interval-policy
template:
spec:
clusterPair: test-dr
includeResources: true
startApplications: false
skipNetworkPolicyCheck: true
namespaces:
- test-dr
```
yes
```release-note
Issue: Stork only collect network policy …
```

add options to collect all network policy

---

Makefile
pkg/apis/stork/v1alpha1/clusterpair.go
pkg/applicationmanager/controllers/applicationbackup.go
pkg/applicationmanager/controllers/applicationclone.go
pkg/migration/controllers/migration.go
pkg/resourcecollector/networkpolicy.go
pkg/resourcecollector/pod.go
pkg/resourcecollector/resourcecollector.go
pkg/storkctl/clusterpair.go
pkg/storkctl/groupsnapshot.go
pkg/storkctl/groupsnapshot_test.go
pkg/utils/utils.go
test/integration_test/clusterdomain_test.go
test/integration_test/common_test.go
test/integration_test/migration_backup_test.go
test/integration_test/migration_failover_failback_test.go
test/integration_test/migration_stork_failures_test.go
test/integration_test/migration_test.go
test/integration_test/specs/mysql-enc-pvc-rancher/mysql.yaml
test/integration_test/specs/mysql-enc-pvc-rancher/portworx/px-sc.yaml
test/integration_test/specs/mysql-migration-failover-failback-rancher/migration.yaml

>feature
PlatformOptions in ClusterPair allow users to specify any configurations required for
kubernetes platform providers like Rancher / EKS / AKS etc
Currently the PlatformOptions are only being used for Rancher. Each platform can define their
own spec within this PlatformOptions.
RancherSpec:
- ProjectMappings: Allows users to configure source and target cluster projectID mappings
so that stork can apply the correct annotations on the destination project where it
is migrating the k8s resources.
- RancherSecret (FUTURE): Proposal for specifying a kubernetes secret to specify rancher api keys that would
be used to send REST APIs to Rancher endpoint for creating/deleting/getting project details
NetworkPolicy / All …

ProjectMappings for Rancher

---

pkg/objectstore/s3/s3.go

>bug
```
pb-2903: Added error handling for  GetObjLockInfo api for cloudian
objectstore.
- In the case of cloudian objectore, GetObjectLockConfiguration
api was returning ObjectLockConfigurationNotFound as error.
- So added the error check to handle ObjectLockConfigurationNotFound error as well
```
No
```release-note
Issue: Adding unlocked backuplocation from cloudian objectstore fails.
User Impact: User will not be able to using unlocked buckets as backuplocation target in px-backup
Resolution: Fixed the error handling in getting object lock configuration api.
```
Testing: …

pb-2903: Added error handling for  GetObjLockInfo api for cloudian objectstore

---

Dockerfile
Makefile
drivers/volume/aws/aws.go
drivers/volume/azure/azure.go
drivers/volume/csi/csi.go
drivers/volume/gcp/gcp.go
drivers/volume/kdmp/kdmp.go
drivers/volume/linstor/linstor.go
drivers/volume/mock/mock.go
drivers/volume/portworx/portworx.go
drivers/volume/portworx/px-statfs/px_statfs.c
drivers/volume/volume.go
pkg/k8sutils/k8sutils.go
pkg/webhookadmission/webhook.go

>feature
Live migration of KubeVirt VM fails if the VM is using
a bind-mounted sharedv4 volume. The root cause is that libvirt
uses a statfs() call to check the file system type and
incorrectly concludes that the volume is not shared.
This patch addresses this problem as described below.
We use a shared library px_statfs.so that intercepts libvirt's statfs call.
If the input path is backed by a PX volume, we change the file system
type returned by the real statfs call. This shared library is bundled with
the stork container.
If a virt-launcher pod is being created and is using a PX volume, stork's
mutating webhook creates a ConfigMap in the pod's namespace.
This configMap has 2 keys that represent the 2 files that we …

PWX-24637: mutate the virt-launcher container to intercept statfs()

---

go.mod
go.sum
test/integration_test/migration_test.go
test/integration_test/specs/endpoint-migration-schedule-interval/migrationschedule.yaml
test/integration_test/specs/endpoint-migration-schedule-interval/schedulepolicy.yaml
test/integration_test/specs/endpoint/aws/aws-sc.yaml
test/integration_test/specs/endpoint/azure/azure-sc.yaml
test/integration_test/specs/endpoint/endpoints.yaml
test/integration_test/specs/endpoint/gce/gke-sc.yaml
test/integration_test/specs/endpoint/linstor/linstor-sc.yaml
test/integration_test/specs/endpoint/mysql.yaml
test/integration_test/specs/endpoint/portworx/px-sc.yaml
test/integration_test/specs/networkpolicy-all-migration-schedule-interval/migrationschedule.yaml
test/integration_test/specs/networkpolicy-all-migration-schedule-interval/schedulepolicy.yaml
test/integration_test/specs/networkpolicy-migration-schedule-interval/migrationschedule.yaml
test/integration_test/specs/networkpolicy-migration-schedule-interval/schedulepolicy.yaml
test/integration_test/specs/networkpolicy/cidr-policy.yaml
test/integration_test/specs/networkpolicy/mysql.yaml
test/integration_test/specs/networkpolicy/networkpolicy-1.yaml
test/integration_test/specs/networkpolicy/networkpolicy-2.yaml
test/integration_test/specs/networkpolicy/portworx/px-sc.yaml
vendor/github.com/portworx/sched-ops/k8s/core/core.go
vendor/github.com/portworx/sched-ops/k8s/core/endpoints.go
vendor/github.com/portworx/sched-ops/k8s/core/networkpolicy.go
vendor/github.com/portworx/sched-ops/k8s/core/pods.go
vendor/github.com/portworx/torpedo/drivers/scheduler/k8s/k8s.go
vendor/modules.txt

Add integration test to cover migration of endpoints and network policy resource
no
no
no
**Note:** 
This PR is on top of #1108 and #1115, please review integration test commits only. Will rebase once vendor pr gets merged in
- Dependent feature pr needs to be merged first #1108 , #1115 
- vendor pr needs to be merge 
https://github.com/portworx/torpedo/pull/818
https://github.com/portworx/sched-ops/pull/282
```
ime="2022-07-05T16:41:36Z" level=info msg="[endpoint] Destroyed SchedulePolicy: migrate-every-5m"
2022/07/05 16:41:36 app mysql is not terminated …
```

Integration-test for networkpolicies and endpoints resource migration

---

test/integration_test/specs/mysql-enc-pvc-rancher/mysql.yaml

The mysql service used by Rancher migration failoverFailback test did not have the rancher label, but the test was checking if the label exists.
No
No
Yes - 2.11

Add missing rancher labels to Service spec in rancher

---

test/integration_test/px_statfs_webhook_test.go
test/integration_test/specs/test-sv4-svc-enc/portworx/px-sc.yaml
test/integration_test/specs/test-sv4-svc-enc/test-sv4-svc-enc.yaml
test/integration_test/specs/test-sv4-svc/portworx/px-sc.yaml
test/integration_test/specs/test-sv4-svc/test-sv4-svc.yaml
test/integration_test/specs/virt-launcher-sim-enc/portworx/px-sc.yaml
test/integration_test/specs/virt-launcher-sim-enc/virt-launcher-sim-enc.yaml
test/integration_test/specs/virt-launcher-sim/portworx/px-sc.yaml
test/integration_test/specs/virt-launcher-sim/virt-launcher-sim.yaml

Tests to verify that the virt-launcher pod will return "nfs" as
the file system type for regular and encrypted PX volumes.
We use "kubevirt.io: virt-launcher" label to simulate the virt-launcher pod.
Also, verify that the pods without the virt-launcher label will return
the correct FS type depending on it is a bind-mount or an nfs-mount.
no
no
2.11.2, 2.12.0
Test passed locally:
```
time="2022-07-16T01:21:05Z" level=info msg="[virt-launcher-sim-enc] Validated deployment: virt-launcher-sim-dep-enc"
time="2022-07-16T01:21:05Z" level=info msg="[test-sv4-svc] …
```

PTX-10293: added tests for the webhook changes for virt-launcher pod

---

test/integration_test/px_statfs_webhook_test.go

Rename webhook tests so that current extender jobs will run those tests.
no
no
2.11

Rename webhook tests to be picked as part of extender tests

---

drivers/volume/csi/csi.go
pkg/apis/stork/v1alpha1/backuplocation.go
pkg/applicationmanager/controllers/applicationbackup.go
pkg/applicationmanager/controllers/applicationrestore.go
pkg/applicationmanager/controllers/backupsync.go
pkg/crypto/crypto.go
pkg/snapshotter/snapshotter_csi.go

>bug
pb-2279
no
yes
```release-note
Issue: Backups were not encrypted even though the encryption was pass in the backuplocation CR.
User Impact: Users were not able to take encrypted backup.
Resolution: Fixed to take the encryption key passed in the backuplocation CR and encrypt the backup.
```
2.11 branch

Pb 2279: Added fixes to take care new EncryptionV2Key variable in     backuplocation.

---

pkg/apis/stork/v1alpha1/backuplocation.go
pkg/applicationmanager/controllers/applicationbackup.go
pkg/objectstore/nfs/nfs.go
pkg/objectstore/objectstore.go

- added NFS type to stork v1alpha1 APIs
- added objectlock specific for for NFS
- in Application controller skipped path check
>bug
feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
**What this PR does / why we need it**: This enable the px-backup backuplocation to use NFS server as a backend
```release-note
Issue:
User Impact:
Resolution
```

pb2939: enable NFS type backuplocation

---

cmd/stork/stork.go

bug
Disable px-object-controller by default [https://portworx.atlassian.net/browse/PWX-26330]
no
To enable px-object-controller, StorageCluster spec needs to be updated.
```
stork:
enabled: true
args:
px-object-controller: "true"
```
2.12

PWX-26330: Disable px-object-controller by default.

---

cmd/stork/stork.go

Which issue(s) this PR fixes 
Cherry-pick to 2.12
Closes #PWX-26307 [https://portworx.atlassian.net/browse/PWX-26307]
Special notes for your reviewer:
https://github.com/portworx/porx/pull/9762 has already been created to add support for disk encryption using customer managed key.
Customer should be able to provide Encrypt/Decrypt on their default gce account for disk encryption so that if device level kms account is not provided then
if an account.json file has been updated in the pod via GOOGLE_APPLICATION_CREDENTIALS, that service account should be used as disk encryption kms account.
If deployement is using instance gce account, that service account should be used as disk encryption kms account.

PWX-26330: (Cherry-pick) Disable px-object-controller by default.

---

pkg/storkctl/clusterpair.go

>enhancement
Enhance UX experience for setting up clusterpair - 
- user can pass in kube-config and ip (if not load-balancer) to storkctl create clusterpair cmd to create 
clusterpair in src<---->DR
yes
```
./storkctl create clusterpair testpair -nkube-system --dest-ip 10.11.x.x  --dest-kube-file ./config.yaml
Using PX-Service Endpoint of DR cluster to create clusterpair...
ClusterPair testpair created successfully on source cluster
```
NA
2.12

PWX-24851: Enhance UX experience for setting up clusterpair for async-DR

---

cmd/stork/stork.go
pkg/apis/stork/v1alpha1/migration.go
pkg/apis/stork/v1alpha1/resourcetransformation.go
pkg/migration/controllers/migration.go
pkg/migration/controllers/resourcetransformation.go
pkg/migration/migration.go
pkg/resourcecollector/resourcetransformation.go
vendor/github.com/portworx/sched-ops/k8s/stork/resourcetransformation.go
vendor/github.com/portworx/sched-ops/k8s/stork/stork.go

>feature
Add updating resource as per transformation specs
yes 
Migration spec now accept `updateResourceSpecs` param to update resource as per transformation rule before migrating 
resources.
```
kind: MigrationSchedule
metadata:
name: mysql-migration-transform-interval
spec:
schedulePolicyName: migrate-every-5m
template:
spec:
clusterPair: remoteclusterpair
includeResources: true
startApplications: false
transformSpecs:
- mysql-service-transform
namespaces:
- mysql-1-pvc-mysql-migration-transform-interval
```
Transformation CR :
```
kind : ResourceTransformation
metadata:
name: …
```

Update object to be migrated as per resource transformation specs

---

go.mod
go.sum
pkg/resourcecollector/endpoint.go
vendor/github.com/portworx/sched-ops/k8s/core/core.go
vendor/github.com/portworx/sched-ops/k8s/core/nodes.go
vendor/github.com/portworx/sched-ops/k8s/stork/resourcetransformation.go
vendor/modules.txt

>bug
Add fix for `PWX-26151: PWX-26151: Skip collection of endpoints for headless service`
no
no
2.12
```
=== RUN   TestMigration/testMigrationFailoverFailback
--- PASS: TestMigration (564.12s)
--- PASS: TestMigration/testMigration (561.05s)
--- PASS: TestMigration/testMigration/intervalScheduleCleanupTest (558.04s)
--- PASS: TestMigration/testMigrationFailoverFailback (0.06s)
PASS
DONE 6 tests in 587.369s
```

PWX-26151: Skip collection of endpoints for headless service

---

pkg/apis/stork/v1alpha1/schedulepolicy.go
pkg/applicationmanager/controllers/applicationbackupschedule.go
pkg/schedule/schedule.go
pkg/utils/utils.go

>improvement
Daily schedule policy now accept `forceFullSnapshotDay` day which will result in force full backup of volume 
yes
```
kind: VolumeSnapshotSchedule
metadata:
name: mysql-snapshot-schedule
namespace: test
annotations:
portworx/snapshot-type: cloud
spec:
schedulePolicyName: daily
suspend: false
reclaimPolicy: Delete
template:
spec:
persistentVolumeClaimName: mysql-data
```
Schedule Policy : 
```
kind: SchedulePolicy
metadata:
name: daily
policy:
daily:
time: "12:04PM"
forceFullSnapshotDay: "Monday"
```
yes
```release-note
User can specify …
```

Force full backup on specified day in daily schedule

---

pkg/applicationmanager/controllers/applicationbackup.go

>improvement
```
pb-3005: Added fix to include the CRDs even if CR is are present.
- With fix, we will include all the CRDs of a group, if one CRDs
of a particular group had a CR in the given namespace.
```
no
Yes
```
release-note
Issue: Currently we do not backup all the  CRDs of app. We backup a CRD only if there is a corresponding CR for that CRD
User Impact: Some application operator deployment expects all the CRDs to be present, even if there is no CR.
Resolution: With fix, we will include all the CRDs of a group, if one CRDs of a particular group had a CR in the given namespace.
```
**Does this change need to be cherry-picked to a …

pb-3005: Added fix to include the CRDs even if CR is are present.

---

how ed4bac3825565902733b151138c32367231e48b3
pkg/apis/stork/v1alpha1/backuplocation.go
pkg/applicationmanager/controllers/applicationbackup.go
pkg/objectstore/nfs/nfs.go
pkg/objectstore/objectstore.go

- added NFS type to stork v1alpha1 APIs
- added objectlock specific API for for NFS
- skipped bucket exist check in Application backup
controller specifically for NFS scenario
>bug
feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
**What this PR does / why we need it**: this is to enable NFS based backuplocation. 
```release-note
Issue:
User Impact:
Resolution
```

pb-2939: enable NFS type backuplocation

---

pkg/resourcecollector/resourcecollector.go
pkg/resourcecollector/webhook.go
pkg/version/version.go

>improvement
```
pb-3025: Added support to take backup of webhook
- added prepareMutatingWebHookForApply, prepareValidatingWebHookForApply,
validatingWebHookToBeCollected and mutatingWebHookToBeCollected apis
```
No
```release-note
Issue: webhook resources were not getting backed up.
User Impact: Some of the application using webhook were not coming up after restore.
Resolution: webhook are backed up based on the namespaces in the service present in the webhook
```
yes, 2.12 branch
Testing:
1) Had validatingwebhookconfiguration for the elasticsearch app.
2) Backup included …

pb-3025: Added support to take backup of webhook

---

pkg/applicationmanager/controllers/applicationbackup.go

>feature - nfs backuplocation support
```
pb-3062: Added code to create resource export CR for nfs resource backup.
```
no
no
no
**Known and TODO issues:**
- Deletion of resources in the case of failed backup is not handled in this PR in the deleteBackup function. We need delete job to take care of it.
- Have duplicated some of the utility function and constant definition from kdmp driver code. Need to clean it up by moving them to separate utility pkg and reuse it.
**Testing:**
- Verified that resourceExport CR is created as expected.
- Will do complete testing once other …

pb-3062: Added code to create resource export CR for nfs resource

---

.travis.yml

We are seeing an issue with xenial-pgdg dist not found here https://apt.postgresql.org/pub/repos/apt/dists/xenial-pgdg/.
This is causing the Travis CI to fail, as a intermediate fix we are ignoring the error which we get from apr-get update as in some cases its not ok go ahead without latest binaries. If there are any issues with required package installation they would be caught at a later stage in the run.

PTX-12986: Ignore package not found error for apt-get install

---

pkg/applicationmanager/controllers/applicationbackup.go
pkg/applicationmanager/controllers/applicationrestore.go

>bug
feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
Need to support nfs backuplocation in application restore controller for resource applying.
no
```

PB-3111: Support for nfs backuplocation in restore resources in application restore controller.

---

test/integration_test/Dockerfile

Bumped up the go version required for gotestsum package
Signed-off-by: Kesavan Thiruvenkadasamy <kthiruvenkadasamy@purestorage.com>
>bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
```release-note
Issue:
User Impact:
Resolution
```

Added changes to fix integration test container build failure

---

pkg/objectstore/s3/s3.go

>bug
```
pb--3113: Added error handling for netapp trident objstore for getting objectlock conf
```
No
```release-note
Issue: User was not able to add netapp Trident objectstore as backuplocation target in px-backup as it failed in getting objectlock configuration.
User Impact: User were not able to add netapp Trident objectstore as backuplocation target even with objectlock disabled bucket.
Resolution: Added proper error handling check for getting object lock config based on the error return by NetApp trident object store.
```
Yes
```
Testing: Validated the fix on customer …
```

pb--3113: Added error handling for netapp objstore for getting objectlock conf.

---

drivers/volume/kdmp/kdmp.go
pkg/applicationmanager/controllers/applicationbackup.go
pkg/applicationmanager/controllers/applicationrestore.go
pkg/utils/utils.go

>cleanup
```
pb-3109: moved the const definition and api between kdmp driver and applicationbackup controller code to utils pkg
```
no
no
2.12

pb-3109: moved the const definition and api between kdmp driver and applicationbackup controller code to utils pkg

---

pkg/migration/controllers/migration.go

bug
Stork would report incorrect resource migration time since it did not consider the time taken to prune deleted resources from the target cluster.
No
Yes
```release-note
Issue: Stork reported incorrect resource migration elapsed time when `purgeDeletedResources` is set on Migration.
User Impact: Resource migration elapsed time would be lesser than the actual time taken to complete the resource migraiton.
Resolution: Stork calculates the time taken to perform resource migration once it is done purging the deleted resources.
```
**Does this change need to be cherry-picked …

PWX-26900: Set the resource migration finish timestamp once pruning is done

---

drivers/volume/portworx/portworx.go
pkg/applicationmanager/controllers/applicationbackup.go

If the backuplocation type is NFS then we will take a Generic backup for any type of volume.
bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
**What this PR does / why we need it**: Even if user doesn't set kdmp-config's BACKUP-TYPE, for NFS backup location type, kdp driver will be chosen for taking backup. 
```release-note
Issue:
User Impact:
Resolution
```

Pb-3100 : Taking Genric backup if backuplocation type is NFS

---

pkg/resourcecollector/resourcecollector.go
pkg/resourcecollector/virtualmachineinstance.go

>bug
A `VirtualMachineInstanceMigration` CR gets created when a Live VM migration is triggered. Stork should not collect these objects while taking a backup or performing a migration of a namespace over cluster.
No
```release-note
Issue: Stork would try to migrate the VirtualMachineInstanceMigration CR which gets created as a part of LiveVM migration. Since this CR is specific to a cluster the migration would partially fail.
User Impact: Stork migration of VirtualMachines would partially fail
Resolution: Stork will not collect VirtualMachineInstanceMigration CRs for migrations or while taking a backup. 
```
**Does this change need to be …

PWX-27136: Do not collect VirtualMachineInstanceMigration CR.

---

pkg/resourcecollector/service.go

>bug
```
pb-3131: Added load balancer service type as well to reset the nodeport in resourcecollector.
```
no
```release-note
Issue: Load balancer service were not getting restored
User Impact: Application using load balancer need manually way of restoring the service.
Resolution: Resetting the nodport value to zero, so that during restore of load balance, it will get new available for port value."
```
2.12
**Testing:**
Took backup of px-backup namespace and restore on the small cluster with different namespace, it was successful.
```
[root@siva-whip-nose-1 ~]# kubectl  get …
```

pb-3131: Added load balancer service type as well to reset the nodeport in resourcecollector.

---

pkg/migration/controllers/migration.go

>bug
- This change partially reverts - https://github.com/libopenstorage/stork/pull/1159
- Instead of setting the migration status after purging the resources, it sets it before so that a resource migration status of "Purged" does not affect the overall migration status.
- The ResourceMigrationFinishTimestamp is still set after purging is done.
No
No
Yes - 2.12

PWX-27273: Only set the ResourceMigrationFinishTs after purging the resources

---

pkg/resourcecollector/persistentvolumeclaim.go
pkg/resourcecollector/resourcecollector.go
pkg/utils/utils.go

>bug
```
pb-3124: updated the storageclass and storage provisioner annotation, if storageclassmapping is present during restore.
```
no
```release-note
Issue: storgaclass and storage provision annotation of PVC are not updated during restore, if it is restored with storageclass mapping.
User Impact: It is confusion, whether restore happened with new storageclass from strorageclass mapping as annotation are pointing to older storageclass and storage provisioner.
Resolution: updating the annotaiton to the newer value of storageclass and storage provisioner based on the storageclass mapping.
```
**Does this change need to be cherry-picked to a …

pb-3124: updated the storageclass and storage provisioner annotation, if storageclassmapping is present during restore.

---

pkg/resourcecollector/resourcecollector.go
pkg/resourcecollector/secret.go

>bug
```
pb-3138: Resetting the serviceAccountUID annotation in the secret.
- When applying the service account, it will get a new UID.
- This UID need to be updated in the secret. Resetting the old
UID to empty string, so that k8s will update the new UID of service
account.
```
No
```release-note
Issue: The secret token for the service account was not getting applied during restore.
User Impact: Application bring fails some time, if they look for the old secret of the service account token
Resolution: Resetting the service account UID annotation of the secret, so that k8s will update the new UID of the restored service account.
```
**Does …

pb-3138: Resetting the serviceAccountUID annotation in the secret.

---

drivers/volume/portworx/portworx.go
go.mod
go.sum
pkg/snapshot/controllers/snapshot.go
pkg/snapshot/controllers/snapshotschedule.go
vendor/github.com/kubernetes-incubator/external-storage/snapshot/pkg/client/client.go
vendor/github.com/kubernetes-incubator/external-storage/snapshot/pkg/controller/snapshotter/snapshotter.go
vendor/modules.txt

>bug
External-Snapshotter list all volumesnapshotdata for each snapshotcreate() call, which causes too many call to kube-api server.  This PR add FindSnapshot() implementation for snapshotter plugin, which can filter out single volumesnapshotdata required for snapCreate request
no
yes
```release-note
Issue: Too many call to volumesnapshotdata from external-snapshotter library
User Impact: On setup like rancher, too many calls to volumesnapshotdata api causes OOM in kube-api server pods
Resolution: Implement `FindSnapshot` plugin interface in portworx driver, which can filter out single volumesnapshotdata for required volumesnapshot
``` …

PWX-24763: Implement FindSnapshot() for external snapshotter library

---

pkg/resourcecollector/persistentvolume.go
pkg/resourcecollector/persistentvolumeclaim.go
pkg/resourcecollector/resourcecollector.go
pkg/utils/utils.go

bug
```
pb-3157: Added fixes to add proper storage class and provisioner name
for PV and PVC during restore.
- Added logic to store the storage class in CurrentStorageClassName annotation for PV spec, so that it can used
during restore.
- Before applying pv spec updating correct storage class and provisioner name based of storageclass map.
```
no
It will be similar to pb-3124
2.12
Testing:
```
Testcase1:
1) Pvc having storage class name in the spec
2) PVC having volume.beta.kubernetes.io/storage-provisioner: annotation
3) PV having pv.kubernetes.io/provisioned-by annotation …
```

 pb-3157: Added fixes to add proper storage class and provisioner name for PV and PVC during restore.

---

pkg/migration/controllers/migration.go

>bug
PWX-27094:  Throws User friendly message if transformation spec is not in ready state
no
no
2.12

PWX-27094: User friendly message if transformation spec is not in ready state

---

drivers/volume/gcp/gcp.go

>bug
If a DeleteBackup is invoked on the GCE driver in succession, the backup deletion will fail.
- Do not fail CancelBackup / DeleteBackup API if a snapshot was not found.
No
```release-note
Issue: A repetitive call to delete a backup of GCE persistent disks would silently fail the backup deletion
User Impact: After deleting a backup, the kubernetes resource objects would not get deleted from the objectstore.
Resolution: Stork now handles NotFound error if returned by GCE on snapshot deletion.
```
Yes - …

PB-3150: Handle GCE snapshot NotFound error in DeleteBackup

---

pkg/resourcecollector/secret.go

>bug
```
pb-3162: Resetting secret token data for service account token before restoring
```
no
```release-note
Issue: Service account secret was not updated with latest token value.
User Impact: Token value in the service account secret is old value. Using that token will with the restored application.
Resolution: Resetting the token to empty, so that new token will be update while restoring based on new service account on restore cluster.
```
2.12

pb-3162: Resetting secret token data for service account token before restoring

---

pkg/migration/controllers/resourcetransformation.go
pkg/resourcecollector/resourcetransformation.go
pkg/schedule/schedule.go

>bug
NestedMap does not return error if spec path is not found in k8s object, causing nil entry to map. This PR add checks around for spec path provided in RT
no
no
2.12

Handle checks for resource transformation spec paths

---

pkg/apis/stork/v1alpha1/backuplocation.go

The NfsConfig structure need to have subpath and mountOption to store the value passed from px-backup as part of backuplocation object.
**What type of PR is this?** Feature
>bug
feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
**What this PR does / why we need it**: Adds sub path and mount option to nfsConfig so that NFS based backuplocation can propagate the same for further processing.
```release-note
Issue:
User Impact:
Resolution
```

pb-3159: Add subpath and nfs mount option in BL

---

Makefile

> improvement
We need to rebuild stork image to get in the latest redhat base image to fix the following vulnerabilities
CVE-2022-1292 (OpenSSL command injection)
CVE-2022-27774 (curl credential vulnerability)
No
```release-note
Following vulnerabilities are addressed in stork 2.11.5:
CVE-2022-27774
CVE-2022-1292
```
PR is based off 2.11. Vulnerability is not present in master or 2.12 branch based images.

Update version to 2.11.5

---

drivers/volume/aws/aws.go
drivers/volume/azure/azure.go
drivers/volume/csi/csi.go
drivers/volume/gcp/gcp.go
drivers/volume/kdmp/kdmp.go
drivers/volume/linstor/linstor.go
drivers/volume/mock/mock.go
drivers/volume/portworx/portworx.go
drivers/volume/volume.go
pkg/applicationmanager/controllers/applicationclone.go
pkg/migration/controllers/migration.go
pkg/resourcecollector/persistentvolume.go
pkg/resourcecollector/resourcecollector.go

>bug
pb-3174
no
```release-note
Issue: Restore of portworx volume to portworx CSI volume was not adding csi section in the PV spec
User Impact: Some of environment are identifying the restore portworx CSI volume as csi volume.
Resolution: Adding csi section details for portworx csi restored volume.
```
2.12
Testing:
Covered following cases:
1) restoring non-secure portworx volume to secure portworx csi volume.
2) restoring secure portworx volume to secure portworx csi volume.
3) restoring non-secure portworx volume to secure portworx csi volume, where the storage class was …

pb-3174: Added csi section in the case portworx volume restore.

---

drivers/volume/portworx/portworx.go

>bug
ptx-13566
no
No, it will be covered as part of pb-3174
Yes to 2.12 branch.

ptx-13566: updating the destination namespace from the namespace mapping only when the namespace in SC is templatized.

---

pkg/applicationmanager/controllers/applicationrestore.go

bug
Need to map the proper resource restore statuses for nfs restores.
```release-note
Issue:
User Impact:
Resolution
```

PB-3211: Mapping nfs resource restore statuses to stork restore statuses and update.

---

drivers/volume/aws/aws.go
drivers/volume/azure/azure.go
drivers/volume/csi/csi.go
drivers/volume/gcp/gcp.go
drivers/volume/kdmp/kdmp.go
drivers/volume/linstor/linstor.go
drivers/volume/mock/mock.go
drivers/volume/portworx/portworx.go
drivers/volume/volume.go
pkg/applicationmanager/controllers/applicationbackup.go

>bug
```
pb-3100: Added check to take kdmp backup, if it is PX volume and NFS
backuplocation.
```
No
No 
No

pb-3100: Added check to take kdmp backup, if it is PX volume and NFS

---

pkg/applicationmanager/controllers/applicationbackup.go
pkg/applicationmanager/controllers/applicationrestore.go

The image registry and namespace details are passed via CR. This is passed to JOB to determine the executor image location.
bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
**What this PR does / why we need it**: this passes the TriggereFrom and namespace detail to JOB via the NFS resource export CR. this values are used to extract the executor image details
**Does this PR change a user-facing CRD or CLI?**:No
**Is a release note needed?**: NO
```release-note
Issue:
User Impact:
Resolution
```

pb-3213: Send the triggeredFrom values to nfs specific CRs

---

.travis.yml
Makefile

Update golang version to 1.18.3
Update golang version to 1.18.3
No
No
Yes 2.12.2

Update golang version to 1.18.3

---

pkg/applicationmanager/controllers/applicationrestore.go

> bug
```
pb-3258: Added TriggeredFromxxx field for resourceExport as well
```
No
No
no

 pb-3258: Added TriggeredFromxxx field for resourceExport as well

---

pkg/applicationmanager/controllers/applicationrestore.go

Bug
`Removing setting of CR status to success before checking for all resources status`
No
No
No
Note: test result updated in the bug

pb-3306: Removing setting of CR status to success before checking for all resources status

---

drivers/volume/kdmp/kdmp.go

>bug
Removing storage provisioner and beta storage provisioner annotations from the restored pvcs for kdmp.
**Test**
Tested with restore of GKE to AKS using kdmp. Updated PB-3316.

PB-3316: Removing storageprovisioner annotation along with beta version also while restoring pvcs.

---

drivers/volume/mock/mock.go
drivers/volume/portworx/portworx.go
drivers/volume/volume.go
pkg/extender/extender.go
pkg/extender/extender_test.go
pkg/monitor/monitor_test.go

>feature
>unit-test
- Introduce a new parameter stork.libopenstorage.org/preferRemoteNodeOnly parameter to be applied to StorageClass. 
Pods using this StorageClass should only be scheduled on the nodes where volume replica nodes do not exist. This behavior should be strictly enforced.
- For Pods using SharedV4 Service  volumes, Stork should give higher score to nodes where SharedV4 Service volumes do not exist.
- Refer to PWX-24444 for further details
No
```release-note
*  Stork will try to schedule application pods using SharedV4 service volumes to run on nodes where volume replica …
```

PWX-24444: Antihyperconvergence scheduling of sharedv4 service pods

---

.travis.yml
Makefile
drivers/volume/aws/aws.go
drivers/volume/azure/azure.go
drivers/volume/csi/csi.go
drivers/volume/gcp/gcp.go
drivers/volume/kdmp/kdmp.go
drivers/volume/linstor/linstor.go
drivers/volume/mock/mock.go
drivers/volume/portworx/portworx.go
drivers/volume/volume.go
pkg/extender/extender.go
pkg/extender/extender_test.go
pkg/monitor/monitor.go
pkg/monitor/monitor_test.go

>feature
>improvement
>unit-test
Cherry pick Antihyperconvergence and CSI-Ext Pods Scheduling changes to 2.12.2
no
```release-note
*Antihyperconvergence:
Stork will try to schedule application pods using SharedV4 service volumes to run on nodes where volume replica does not exist such that it uses NFS mountpoint and when a failover happens application pods will not be restarted.
StorageClass parameter "stork.libopenstorage.org/preferRemoteNodeOnly": "true" can be used to strictly enforce this behavior.
*CSI-Ext Pods Scheduling:
Issue: 
When CSI is enabled, PVC provisioning …
```

Cherry-pick antihyperconvergence and csi pod scheduling

---

drivers/volume/aws/aws.go
drivers/volume/azure/azure.go
drivers/volume/gcp/gcp.go

For AWS , azure and GCP based volumes we will used kdmp driver to take a backup only when the the backuplocation type is NFS.
>bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
**What this PR does / why we need it**: We need to enforce teh kdmp backup for all types of volume if the backuplocation is of type NFS.
**Is a release note needed?**: No 
```release-note
Issue:
User Impact:
Resolution
```
**Does this change need to be cherry-picked to a release branch?**:  No
Unit test

pb-3320: Enforce kdmp backup for all cloud provisioner for NFS BL

---

pkg/snapshot/controllers/snapshotschedule.go

Also limiting the volumesnapshotname has been added.
improvement
Because of errored snapshots were growing once the snapshot failure on volume is seen, we need to limit the number of errored snapshots by smartly deleting the older errored snapshots.
```release-note
Issue:
User Impact:
Resolution
```
**Test**
Functional tests for this have been updated in PWX-27596.

PWX-27596: Limiting number of errored volumesnapshots in a volumesnapshotschedule.

---

cmd/stork/stork.go
drivers/volume/portworx/portworx.go
pkg/apis/stork/v1alpha1/resourcetransformation.go
pkg/cache/cache.go
pkg/client/clientset/versioned/fake/register.go
pkg/client/clientset/versioned/scheme/register.go
pkg/migration/controllers/migration.go
pkg/pvcwatcher/pvcwatcher.go
pkg/resourcecollector/resourcecollector.go
test/integration_test/migration_test.go
vendor/k8s.io/client-go/dynamic/dynamicinformer/informer.go
vendor/k8s.io/client-go/dynamic/dynamicinformer/interface.go
vendor/k8s.io/client-go/dynamic/dynamiclister/interface.go
vendor/k8s.io/client-go/dynamic/dynamiclister/lister.go
vendor/k8s.io/client-go/dynamic/dynamiclister/shim.go
vendor/modules.txt

>improvement
The GetStorageClass and ListApplicationRegistration APIs are the most frequently used by k8s APIs by stork and they end up consuming a lot of k8s api rate limiting tokens. We end up with seeing the following log messages:
```
I1122 02:46:05.347107       1 request.go:668] Waited for 2.188254327s due to client-side throttling, not priority and fairness, request: GET:https://172.30.0.1:443/apis/storage.k8s.io/v1/storageclasses/px-csi-block
I1122 02:46:15.347444       1 request.go:668] Waited for 2.193815761s due to client-side throttling, not priority and fairness, request: GET:https://172.30.0.1:443/apis/storage.k8s.io/v1/storageclasses/px-ha- …
```

PWX-27385: Add a cache for StorageClasses & ApplicationRegistration.

---

drivers/volume/csi/csi.go

When Backuplocation type is NFS, then we will use KDMP driver to take backup for CSI volumes.
>bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
**What this PR does / why we need it**: For CSI volume and NFS backuplocation we need to use KDMP driver
```release-note
Issue:
User Impact:
Resolution
```
**Does this change need to be cherry-picked to a release branch?**: No, it raised against 2.12-nfs release branch already
**Unit Test :**
Unit test details will be posted in some time..

pb-3347: Make CSI volumes to use kdmp driver for NFS BL

---

Dockerfile.cmdexecutor
Makefile

>build improvement
This PR enables the build system to use DOCK_BUILD_CNT i.e go docker build container. 
Makefile updates with docker build --pull command to enable always pull the latest base feature while building. It's usually a good practice to use it to get upstream security fixes incorporated as soon as possible (instead of using stale, potentially vulnerable images)
No
No
No

Makefile changes to enable build system to use DOCK_BUILD_CNT

---

test/integration_test/extender_test.go
test/integration_test/health_monitor_test.go

Fix integration test failures
1. extender_test : defer has function scope and uncordon was not being executed for all the nodes due to which subsequent tests were failing
2. health_monitor_test:  We have a 4 worker node config in our integration test jobs. 3 nodes to run CSI pods and one node for failover. So the logic to stop volume driver on other nodes is not needed to test failover so commented that code.
Absence of KubeSchedulerConfiguration based stork scheduler, make multiple pods to run on single node sometime and we end up stopping px on more nodes than we intended and can not find the node to failover. This can be re enabled once the …

PWX-28159: Fix health monitor and extender integration test failures

---

pkg/applicationmanager/controllers/applicationbackup.go
pkg/migration/controllers/migration.go
pkg/migration/controllers/resourcetransformation.go
pkg/resourcecollector/resourcecollector.go

>improvement
- MongoDB defines "opsmanagers" as the plural form for MongoDBOpsManager in its CRD definition.
- However the default plural set provided by k8s simply converts the Kind name "MongoDBOpsManager" to its plural form as "mongodbopsmanagers"
- This causes migrations to fail, since this object is not identified by k8s.
- Explicitly set the plural form of MongoDBOpsManager as "opsmanagers"
No
```release-note
Issue: Stork fails to apply MongoDBOpsManager objects on the target cluster since it fails with the error: "Error applying resource: the server could not find …
```

PWX-28300: Add opsmanagers as the Plural form of MongoDBOpsManager CR plural set.

---

drivers/volume/csi/csi.go
pkg/applicationmanager/controllers/applicationbackup.go
pkg/applicationmanager/controllers/applicationrestore.go
pkg/utils/utils.go

>feature
```
PB-3430: support for uploading storageclasses.json to nfs backuplocation
- For native csi driver, added support for uploading the
storageclasses.json to nfs backuplocation target
- For nfs backuplocation, the storageclasses.json will be
uploaded in the resource stage along with other resource json files,
as part of nfs executer job.
```
No
NA
No
Testing:
- Added some hack to validate the fix:
- Remove the check to default the csi to kdmp, in the case of nfs backuplocation.
- Also commented out the code to upload the snapshot.json. This will be supported in the …

PB-3430: support for uploading storageclasses.json to nfs backuplocation

---

pkg/apis/stork/v1alpha1/applicationbackup.go
pkg/apis/stork/v1alpha1/zz_generated.deepcopy.go
pkg/applicationmanager/controllers/applicationbackup.go

* PB-3397: Add Logic to support namespace label selector in the application backup controller
- These feature is supported with manual and schedule backups
- Currently Namespaces come along the application backup spec consider to be backed up, Now these namespaces are selected using the namespace selectors provided as part of the same spec at execution time.
- Filtered namespaces that to be backed up are also updated to the data-store object while reconciling.
>bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test …

PB-3397: Backed Nameapecs based on namespace label selector (#1258)

---

pkg/apis/stork/v1alpha1/backuplocation.go

Following changes are made
- NfsConfig structure name changed to NFSConfig
- MountOption to MountOptions
- Added a new variable NFSIOTimeoutInSecs
bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
**What this PR does / why we need it**: It ports the NFSConfig changes from strok master to 2.12-nfs branch.
```release-note
Issue:
User Impact:
Resolution
```

pb-3505: port changes of NfsConfig to 2.12-nfs branch

---

go.mod
go.sum
vendor/github.com/portworx/kdmp/pkg/controllers/dataexport/reconcile.go
vendor/github.com/portworx/kdmp/pkg/controllers/resourceexport/reconcile.go
vendor/github.com/portworx/kdmp/pkg/drivers/drivers.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiabackup/kopiabackup.go
vendor/github.com/portworx/kdmp/pkg/drivers/utils/utils.go
vendor/modules.txt

vendor kdmp 1.2.3 to stork 2.12-nfs
>bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
**What this PR does / why we need it**: It brings NFSConfig defination to 2.12-nfs
```release-note
Issue:
User Impact:
Resolution
```

pb-3505: vendor kdmp 1.2.3 to stork 2.12-nfs

---

Dockerfile

>improvement
Fixing libxml vulnerabilities  CVE-2022-40303 and CVE-2022-40304
no
no
no

PWX-28818: Update libxml for vulnerability fixes

---

go.sum
pkg/applicationmanager/controllers/applicationrestore.go

>bug
```
pb-3338: Added support for handling default storage class request in the
storageclass mapping
```
no
```release-note
Issue: User are not able to select the default storageclass set on the destination cluster during restore.
User Impact: User should know the storageclass name on the destination cluster and was not able to select the storageclass that was set as default on the cluster.
Resolution: User can now select "use-default-storage-class" option int he storageclass mapping and internal, it will fetch the default storageclass set on the cluster for pvc …
```

pb-3338: Added support for handling default storage class request in the storageclass mapping

---

drivers/volume/csi/csi.go
pkg/utils/utils.go

>improvement
```
pb-3447: changes to upload snapshot.json for native csi driver.
- Conveerted come of the data structure and variable to public,
so that it can be used in kdmp nfs executor job.
- snapshot.json will be uploaded in nfs executor, if
backuplocation is nfs type.
```
N.A
Will release note it as new feature.
No.
Testing:
snapshot.json from minio backuplocation:
```
{"volumeSnapshots":{"backup-aaa715bf6405-9f7465534d49":{"metadata":{"name":"backup-aaa715bf6405-9f7465534d49","namespace":"mysql-pso","uid":"4a7e8cee-7e30-4e3e-8c93-6bb5e130b84e","resourceVersion":"40101 …
```

pb-3447: changes to upload snapshot.json for native csi driver.

---

pkg/migration/controllers/migration.go
pkg/migration/controllers/migrationschedule.go
pkg/storkctl/migration.go

>improvement
With Autosuspend enabled in migrations, the decision of apps activated or deactivated in target cluster will be only decided by storkctl activate/deactivate command.
```release-note
Issue: Migration gets suspended after failback if autosuspend is enabled.
User Impact: After failback, the existing migration schedule is not getting resumed which makes the secondary cluster not synced. 
Resolution: With the fix, the primary cluster's migrationschedule will correctly detect if migration can be resumed to secondary.
```

PWX-27511: applicationactivated to be set to true as part of storkctl activate only and false as part of stockctl deactivate.

---

.travis.yml

cleanup
Change travis version so that it pushes the correct container tags for `23.2`
no
no
no

change container tags in travis to 23.2

---

pkg/applicationmanager/controllers/applicationrestore.go

>bug
```
pb-3338: Added support for handling default storage class request in the
storageclass mapping
```
no
```
Issue: User are not able to select the default storageclass set on the destination cluster during restore.
User Impact: User should know the storageclass name on the destination cluster and was not able to select the storageclass that was set as default on the cluster.
Resolution: User can now select "use-default-storage-class" option int he storageclass mapping and internal, it will fetch the default storageclass set on the cluster for pvc provisioning. 
``` …

pb-3338: Added support for handling default storage class request in the storageclass mapping.

---

drivers/volume/portworx/portworx.go

>bug
```
pb-3532: Added check to handle the cases where cache is not present.
```
no
no
23.2 and 23.2.0

pb-3532: Added check to handle the cases where cache is not present.

---

pkg/apis/stork/v1alpha1/applicationbackup.go
pkg/apis/stork/v1alpha1/applicationrestore.go
pkg/apis/stork/v1alpha1/platformcredential.go
pkg/apis/stork/v1alpha1/zz_generated.deepcopy.go
pkg/applicationmanager/applicationmanager.go
pkg/applicationmanager/controllers/applicationbackup.go
pkg/applicationmanager/controllers/applicationclone.go
pkg/applicationmanager/controllers/applicationrestore.go
pkg/resourcecollector/networkpolicy.go
pkg/resourcecollector/persistentvolume.go
pkg/resourcecollector/persistentvolumeclaim.go
pkg/resourcecollector/pod.go
pkg/resourcecollector/resourcecollector.go
pkg/utils/utils.go

What type of PR is this? feature
**What this PR does / why we need it**: Add supports to perform project mapping for rancher platform
-> Extracts the associated rancher projects from k8s resources and updates the ApplicationBackup CR
-> Based on the project mapping available in the ApplicationRestore CR, it replaces the projects IDs in the required annotations, labels , namespace selectors with the target project ID

PB-3413 - Added changes to support rancher project mapping

---

pkg/migration/controllers/migration.go

>bug
PWX-29223
Unable to migrate CRs due to "_Error applying resource: object is being deleted: kafkas.platform.confluent.io "kafka" already exists"_
no
yes
```release-note
Issue: Unable to migrate Confluent Kafka resources during failback.
User Impact: Confluent Kafka application failback unable to bring up the application
Resolution: Stork will now remove any finalizers on the CRs when deleting the resource during migration so that a new version of the resource can be recreated.
```
yes 23.3/23.2

PWX-29223: Remove finalizer when deleting CR during migration

---

pkg/applicationmanager/controllers/applicationbackup.go

> bug
```
pb-3557: Added check to return from applicationbackup handler, if stage is already final.
```
no
```release-note
Issue: Some the restore fails to restore the volumes as the applicationbackup CR get over written during restore.
User Impact: Some time the restoring of volumes faces failure.
Resolution: Added check not to process any thing on the applicationbackup CR, if it is already in final stage.
```
23.2.1

pb-3557: Added check to return from applicationbackup handler, if stage is already final.

---

pkg/applicationmanager/controllers/applicationbackup.go
pkg/resourcecollector/resourcecollector.go

>bug
```
pb-3571: Added changes to seperate mergeSupportedForResource required for rancher
```
no
release note is not needed as it is a regression got introduced by rancher project PR.
23.2.1 branch
Testing:
- Tested the restore with replace option on a already existing namespace.
- Now the restore went through fine.

pb-3571: Added changes to seperate mergeSupportedForResource required for rancher

---

pkg/migration/controllers/migration.go
pkg/migration/controllers/migrationschedule.go

>improvement
PWX-29218
no
yes
```Improvement
Stop logging unwanted migration retry events logs in migration and migrationschedule CR
```

PWX-29218: Do not log retry events during migration

---

Dockerfile
cmd/stork/stork.go
test/integration_test/Dockerfile

>bug
Add support for gke-gcloud-auth-plugin https://portworx.atlassian.net/browse/PWX-29253
no
```release-note
Added support for gke-gcloud-auth-plugin required for authenticating with GKE.
```
yes 23.2
**Notes for the reviewer**:
- PWX-29253 reports error "configuration: interactiveMode must be specified". However this error is not present when using the storkctl binary from 23.2 build. This is due to the updated K8s APIs. We do not need to set an explicit Exec.InteractiveMode
- Changing the installation directory to /usr/lib for google-cloud-sdk as it should not be …

PWX-29253: Adding support for gke-gcloud-auth-plugin

---

Dockerfile
cmd/stork/stork.go
test/integration_test/Dockerfile

>bug
Add support for gke-gcloud-auth-plugin https://portworx.atlassian.net/browse/PWX-29253
no
```release-note
Added support for gke-gcloud-auth-plugin required for authenticating with GKE.
```
yes 23.2
**Notes for the reviewer**:
- PWX-29253 reports error "configuration: interactiveMode must be specified". However this error is not present when using the storkctl binary from 23.2 build. This is due to the updated K8s APIs. We do not need to set an explicit Exec.InteractiveMode
- Changing the installation directory to /usr/lib for google-cloud-sdk as it should not be …

PWX-29253: Adding support for gke-gcloud-auth-plugin (#1312)

---

pkg/applicationmanager/controllers/applicationclone.go
pkg/applicationmanager/controllers/applicationrestore.go

**What this PR does / why we need it**: Added changes to fix nil dereferencing in PrepareResourceForApply
**Does this change need to be cherry-picked to a release branch?**: 23.2

PWX-29487 - Added changes to fix nil dereferencing in PrepareResourceForApply

---

Dockerfile

>feature
- Install oci CLI as part of stork container build.
No
Yes
```release-note
Improvement: Stork now supports ClusterPairing for OKE (Oracle Kubernetes Engine) clusters.  
```
Yes - 23.3
** Testing Notes **
Successful Cluster Pair
```
storkctl get clusterpair -n kube-system
NAME         STORAGE-STATUS   SCHEDULER-STATUS   CREATED
admin-pair   Ready            Ready              10 Mar 23 17:16 PST
```
Migrations have been running successfully since Friday: 
```
storkctl get migrationschedules -n kube-system
NAME                  POLICYNAME                CLUSTERPAIR …
```

PWX-28862: Add support for ClusterPairing on OKE clusters

---

pkg/applicationmanager/controllers/applicationbackup.go
pkg/migration/controllers/migration.go
pkg/migration/controllers/resourcetransformation.go
pkg/resourcecollector/resourcecollector.go
pkg/storkctl/migration.go

improvement
Support migrations of watson knowledge catalog crs.
```release-note
Issue: Unable to find resource of Watson knowledge catalog.
User Impact: Migration was failing for Watson knowledge catalog.
Resolution: With right plurals for the crds, now migration is successful for Watson knowledge catalog.
```

PWX-29480: Fixing plurals for WKC crds.

---

pkg/action/action.go
pkg/resourceutils/updatereplicas.go
pkg/storkctl/action.go
pkg/storkctl/migration.go
pkg/storkctl/storkctl.go

What type of PR is this?
Improvement
What this PR does / why we need it:
This PR adds a new storkctl command storkctl perform failover that uses the Action CRD to kick off the failover process.
Does this PR change a user-facing CRD or CLI?:
Yes. The change is needed as the previous storkctl activate migration command has an unobvious meaning and this change is part of the bigger effort to simplify the DR use.
Is a release note needed?:
No
Does this change need to be cherry-picked to a release branch?:
No

PWX-29462: Add storkctl command for failover

---

go.mod
go.sum
vendor/github.com/portworx/kdmp/pkg/controllers/dataexport/reconcile.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiabackup/kopiabackup.go
vendor/modules.txt

>bug
```
pb-3683: vendored the latest kdmp from 1.2.5 branch
```
no
no ( vendor changes)
23.2.1 and 23.3. branches.

pb-3683: vendored the latest kdmp from 1.2.5 branch

---

cmd/stork/stork.go
pkg/cmdexecutor/status/status.go
pkg/k8sutils/k8sutils.go
pkg/rule/rule.go

>bug
```
pb-3689: Added changes to create cmd executor pod in stork deployment
namespace.
- Added the stork deployment namespace in stork controller configmap
- Modify the cmd executor pod spec to use stork deploy namespace
and stork service account.
```
no
```release-note
Issue: Rule cmd executor pods was always created in kube-system namespace.
User Impact: User might expect not run pods in kube-system
Resolution: Moved the cmd executor pods to stork deployment namespace.
```
23.2.1 and 23.3 branches.
Testing:

pb-3689: Added changes to create cmd executor pod in stork deployment namespace.

---

drivers/volume/aws/aws.go
drivers/volume/azure/azure.go
drivers/volume/csi/csi.go
drivers/volume/gcp/gcp.go
drivers/volume/kdmp/kdmp.go
drivers/volume/linstor/linstor.go
drivers/volume/mock/mock.go
drivers/volume/portworx/portworx.go
drivers/volume/volume.go
pkg/action/action.go

feature
This PR adds an interface for `Action` to `volDriver` with a method `Failover`. It also adds implementation for `Failover` to Portworx volDriver that promotes nearsync volumes.
No
No
No

PWX-29463: Add promote method to Px

---

cmd/stork/stork.go
pkg/cache/cache.go

>bug
Fix nil panic when cache is accessed before creation.
no
no
yes 23.4.0
**RegressionTests**
https://jenkins.pwx.dev.purestorage.com/job/Stork/view/Stork%2023.2-dev%20%20C7/job/23-2-migration-k8s-1-24-0/413/parameters/

PWX-29946: Fix nil panic when cache is accessed before initialize

---

pkg/webhookadmission/webhook.go

>improvement
Stop accepting TLS1/1.1 connections in Stork Service 
https://portworx.atlassian.net/browse/PWX-29494
no 
Improvement
```release-note
Stork service will stop accepting TLS1/1.1 connections
```
yes 23.4
```
Without change:
[root@ppandey-vm-lead-fairy-1 ~]# openssl s_client -connect stork-service.kube-system:443 -tls1_1
CONNECTED(00000003)
depth=0 CN = Stork CA
verify error:num=18:self signed certificate
verify return:1
depth=0 CN = Stork CA
verify return:1
---
Certificate chain
0 s:/CN=Stork CA
i:/CN=Stork CA
---
Server certificate
-----BEGIN CERTIFICATE----- …
```

PWX-29494: Stop accepting TLS1/1.1 connections in Stork Service

---

pkg/schedule/schedule.go
pkg/schedule/schedule_test.go

improvement
As 1 minute migration policy was too aggressive, we are changing the default-migration-policy's interval to 30mins.
**Test**
Tested with fresh installation and upgrade case. 
Test results have been updated in PWX-29754

PWX-29754: Create or update the existing default-migration-policy's interval minutes to 30 instead of 1.

---

pkg/apis/stork/v1alpha1/applicationbackup.go
pkg/apis/stork/v1alpha1/applicationrestore.go
pkg/applicationmanager/controllers/applicationbackup.go
pkg/applicationmanager/controllers/applicationclone.go
pkg/applicationmanager/controllers/applicationrestore.go
pkg/client/clientset/versioned/fake/register.go
pkg/client/clientset/versioned/scheme/register.go
pkg/migration/controllers/migration.go
pkg/resourcecollector/resourcecollector.go
pkg/utils/utils.go

**What type of PR is this?** feature
>bug
feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
**What this PR does / why we need it**: This adds support for taking backup which involves large count of resources. the pb-3696 explains in detail the root cause and its solution.
**Does this PR change a user-facing CRD or CLI?**: nope
**Is a release note needed?**: yes
```release-note
Issue: Large Resource count based backup fails due to GRPC & other payload size checks
User Impact: backup with large resource count will fail
Resolution 
Stripped the resource Info from backup and restore CRs to eliminate the GRPC & etcd payload limit.
```
**Does this change need to be …

Pb 3707 large resource count support

---

pkg/migration/controllers/migration.go

>bug
For px csi volumes, the pv created directly has volumeHandle as the portworx volumeID. During migration we create the pv with volumeHandle as portworx volume Name in the secondary. During failback, even though the volume gets correctly migrated, but still the pv spec points to old volumeID as volumeHandle. 
The fix is to find this case during migration and recreate the PV with volumehandle as PV name.
```release-note
Issue: Failback to primary when app uses px csi volumes fails as the volumeHandle points to old volume ID.
User Impact: App does not come up in primary after failback.
Resolution: With the fix of …
```

PWX-30157: Recreate pv if its csi.spec.volumeHandle does not match with PV name during  migration.

---

cmd/stork/stork.go

>improvement
Increasing default k8 api qps and burst in stork for better performance.

PWX-30112: Making default k8s-api-qps value as 1000 and k8s-api-burst as 2000.

---

pkg/apis/stork/v1alpha1/applicationbackup.go
pkg/apis/stork/v1alpha1/applicationrestore.go
pkg/applicationmanager/controllers/applicationbackup.go
pkg/applicationmanager/controllers/applicationrestore.go

- the LargeResourceEnabled flag and resource count is moved for Spec section to Status section for both Application backup & Resotre CR.
**What type of PR is this?** cleanup
>bug
>feature
>improvement
cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
**What this PR does / why we need it**: We generally don't keep dynamically changing fields in CR's Spec section hence moved it to Status Section
**Does this PR change a user-facing CRD or CLI?**:  no
**Is a release note needed?**: no 
```release-note
Issue:
User Impact:
Resolution
```
**Does this change need to be cherry-picked to a release branch?**: 23.3.1
Will update the Unit test... Backup has suceeded , CUrrently restore is in …

pb-3767: Moved the LargeResource flag and Resource count to status

---

test/integration_test/migration_test.go
test/integration_test/specs/label-exclude-selector-migration/migration.yaml

Adding integration test for excludeSelector param
https://portworx.atlassian.net/browse/PWX-30127
no
yes 23.4

PWX-30127: Add test for ExcludeSelectors param in MigrationSchedule

---

pkg/applicationmanager/controllers/applicationrestore.go
pkg/k8sutils/k8sutils.go

> improvement
```
pb-3771: Added batching way of submitting the volumes for restore
- Currently add logic to submit 25 pvc in batch with delay of 20
sec for volume restore.
- This is prevent overloading to the storage controller while
creating restore volumes
```
no
No, Will added it as part of large resource support Bug.
23.3.1 branch
Testing:
Taken backup of 300 volumes from a single namespace and restore it on another cluster.
Backup:
Restore:

pb-3771: Added batching way of submitting the volumes for restore

---

pkg/apis/stork/v1alpha1/applicationrestore.go
pkg/applicationmanager/controllers/applicationbackup.go
pkg/applicationmanager/controllers/applicationrestore.go
pkg/k8sutils/k8sutils.go
pkg/resourcecollector/resourcecollector.go
pkg/utils/utils.go

- Added two field to restore CR one signifies number of already applied resource
- The other is the phase in which resource restoration process operating. It has three phases
- preparing resource
- deleting resource( only if replace is selected)
- verifying the deleted resource
- applied resource
>bug
feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
**What this PR does / why we need it**: We need to showcase of a progress bar for large resource restore. Hence we need some additional field to be updated in certain interval  in restore CR. Additionally a restore resource state is also added to signify in what state the resource process …

pb-3773: Update restore CR with restored resources & state

---

cmd/stork/stork.go
pkg/applicationmanager/controllers/applicationregistration.go
pkg/pluralmap/pluralmap.go
pkg/resourcecollector/resourcecollector.go

>improvement
For finding crd's plural for querying,  currently inflect ruleset was used.
Sometimes the crd's plural does not align with the library's rules and in that case every time a stork release is required with added exceptions. 
The current fix will find the existing crd's plurals and keep it in a global cache for further use. 
**Test**
Tested following 2 cases with migration for confluent kafka application.
1. App was installed first and stork gets installed later.
2. Stork was installed first and app gets installed later.
Details of test …

PWX-29789: Implementation of crd plural map for dynamically getting crd's plurals

---

pkg/migration/controllers/migration.go
pkg/resourcecollector/resourcecollector.go
pkg/utils/utils.go

>bug
SA deletion is not reflected on the destination cluster during migration. Migration status should also not be showing status as Purged.
no
```release-note
Issue: Incorrect migration status for service account deletion on source cluster 
User Impact: User expects service account to be deleted on destination cluster based on status while it is not supported
Resolution: Do not show purged status for resources for which merging is supported on desintation cluster
```
yes 23.5.0
**Notes**:
* Only changes required to fix this is following
```
if …
```

PWX-30319: Fix incorrect migration status with service account deletion

---

pkg/applicationmanager/controllers/applicationbackup.go
pkg/k8sutils/k8sutils.go
pkg/resourcecollector/resourcecollector.go

- In clutsers having large count of resources the resource List API in k8s takes a lot of time and that make etcd server to timeout client call. Hence a limit is added to ListOption so that only certain number of resources will be fetched with a single call
- Currently the limit is set to 500 resources at a time.
bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
**What this PR does / why we need it**: With large resource count GetResource API in resource collector package used to fail. The reason getting  large amount o resource detail via k8s API timesout. Hence we have added the limit value so that only 500 resources will be …

pb-3789: Add limit value for ListOption while getting resources

---

pkg/applicationmanager/controllers/applicationrestore.go

- In case of multi namespace scenario the show status picking the total resource count before the filteration when we restore only selective namesapces
- Hence updated the total resource count at the appropriate place so that multi namespace backup's restore with a iselective namespaces to show correct count
bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
**What this PR does / why we need it**: 
**Does this PR change a user-facing CRD or CLI?**: - In case of multi namespace scenario the show status picking the total resource count before the filteration when we restore only selective namesapces
- Hence updated the total …

pb-3798: The progress bar to show total count correctly

---

cmd/cmdexecutor/cmdexecutor.go
pkg/cmdexecutor/cmdexecutor.go
test/integration_test/cmdexecutor_test.go

improvement
This PR logs the stdout of command run by cmdexecutor on different pods to cmdexecutor logs. 
Required for [DS-4808](https://portworx.atlassian.net/browse/DS-4808)
No
No
No

DS-4808: Include stdout output in cmdexecutor logs

---

pkg/applicationmanager/controllers/applicationrestore.go
pkg/resourcecollector/resourcecollector.go

- In volume restore stage we restore resources early for kdmp driver Hence a proper channel need to be passed for the restore CR updation process.
- The path where DeletResource doesn't need CR update logic, therein the nil channel argument  should be handled gracefully.
>bug
**What this PR does / why we need it**: We need to handle the nil channel pointer in the deleteResource API. Additionally in kdmp driver we need to pass the proper channel so that restore CR can be updated timely.
**Is a release note needed?**: NO
```release-note
Issue:
User Impact:
Resolution
```
**Does this change need to be cherry-picked to a release branch?**: 23.3.1
Unit testing

pb-3801: DeletResource should handle nil channel argument

---

pkg/applicationmanager/controllers/applicationrestore.go
pkg/k8sutils/k8sutils.go

>bug
>feature
>improvement
cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
**What this PR does / why we need it**: This adds a configMap to alter the existing batch restore volume sleep interval
```release-note
Issue:
User Impact:
Resolution
```
**Does this change need to be cherry-picked to a release branch?**: 23.3.1

pb-3791: Add a config-map for batch volume restore sleep interval

---

pkg/webhookadmission/utils.go
pkg/webhookadmission/webhook.go

>bug
Remove Stork as the scheduler from Statefulsets and Deployments.
Currently we are not able to set Stork as the scheduler for Statefulsets because we rely on the PVC to be owned by Portworx. STS uses volumeClaimTemplates where PVC is not created when the webhook admission request comes to stork and schedulerName is not updated. Later when webhook admission request arrives for Pods, Stork does update the Schedulername and it works.
I believe there is no reason to update Stork as the scheduler for StatefulSets and Deployments when we have the webhook enabled for Pods. This PR is removing these webhook for Deployments and Statefulsets.
Please note that any annotation set on the Deployment or STS is not passed onto the …

PWX-30291: Removing sts and deployments from stork webhook

---

cmd/stork/stork.go
pkg/storkctl/factory.go

improvement
storkctl uses higher qps and burst 

PWX-30752: storkctl to use higher qps and burst default values.

---

pkg/storkctl/clusterpair.go

>bug
Storkctl create clusterpair doesn't honor port from cli
https://portworx.atlassian.net/browse/PWX-30356
yes
```release-note
Issue: Storkctl create clusterpair doesn't honor the port provided from CLI
User Impact: Users unable to create bi-directional clusterpairs
Resolution: Passing the port provided from CLI in the endpoints for creating cluster pair.
```
yes 23.5

PWX-30356: Storkctl create clusterpair doesn't honor port from cli

---

drivers/volume/csi/csi.go

>bug
**What this PR does / why we need it**: Fixes the for loop in cleanupSnapshotsForRestore to avoid assignment of the last entry to all keys
```release-note
Issue:
User Impact:
Resolution
```

PB-3827 - Fix loop in cleanupSnapshotsForRestore to avoid assignment of the last entry to all keys

---

cmd/stork/stork.go
pkg/applicationmanager/applicationmanager.go

>bug
Shared informer cache should be initialized for all Stork Pods.
We need to register applciation controller CRDs explicitly before initializing Cache.
no
yes 23.4
**Test**:
Migration Jenkins Job: https://jenkins.pwx.dev.purestorage.com/job/Stork/view/Stork%2023.4-dev/job/23-4-dev-migration-k8s-1-24-0/

PWX-30712: Initializing shared informer cache for all stork Pods

---

cmd/stork/stork.go
pkg/applicationmanager/applicationmanager.go

>bug
Shared informer cache should be initialized for all Stork Pods.
We need to register applciation controller CRDs explicitly before initializing Cache.
no
yes 23.4

PWX-30712: Initializing shared informer cache for all stork Pods (#1390)

---

pkg/k8sutils/k8sutils.go
pkg/rule/rule.go

>bug
Use updated cmdExecutorImage.https://portworx.atlassian.net/browse/PWX-30706
no
```release-note
Issue: Older image of Cmdexecutor was being referenced from Stork  
User Impact: Any new improvements in cmdexecuter image were not being used in Stork.
Resolution: Stork is now updated to use the same tag of cmdexecutor
```
yes 23.5

PWX-30706: Use same cmdexecutor image tag as stork

---

drivers/volume/csi/csi.go

>bug
```
pb-3831: In csi driver CancelRestore, cleaning up dangling PVC, if restore is not succeed and retain as well
```
no
```release-note
Issue: In CSI, in-place restore, the retained PVC are getting deleted after restore.
User Impact: After in-place CSI restore, the PVC stork in Terminating state and app is not usable.
Resolution: With the fix, the in-place CSI restore, the existing PVC will not deleted and remain unchanged.
```
Need decide.
Tested on NFS setup.

pb-3831: In csi driver CancelRestore, cleaning up dangling PVC, if restore is not succeed and retain as well

---

drivers/volume/portworx/portworx.go
drivers/volume/volume.go
pkg/extender/extender.go
pkg/extender/extender_test.go
pkg/monitor/monitor.go
pkg/monitor/monitor_test.go
test/integration_test/common_test.go
test/integration_test/extender_test.go
test/integration_test/health_monitor_test.go

>bug
- Introduce a new state in Stork for storage down nodes.
- Remap portworx StorageDown state to Stork's StorageDown state
- For degraded node state:
- filter out the nodes from extender requests.
- monitor should delete the pods running on them
- For storage down state:
- do not filter out such nodes.
- give a low score to nodes which are storage down.
- monitor should not delete pods running on them
No
```release-note
Issue: Stork would delete pods running on Degraded or Portworx StorageDown nodes.
User Impact: Applications would face disruption even though drivers …
```

PWX-30276: Do not delete pods running on storage down nodes.

---

pkg/apis/stork/v1alpha1/migration.go
pkg/apis/stork/v1alpha1/zz_generated.deepcopy.go
pkg/migration/controllers/migration.go
pkg/resourcecollector/resourcecollector.go

>improvement
Explicitly migrate resources even having owenreferences and owner getting migrated . 
```release-note
Issue: No single flag was available in migration CR to migrate the resources having owner references.
User Impact: Certain applications have a hard requirement of migrating the resources created by operator explicitly and they were failing to come up as certain resources were not migrated.
Resolution: Have introduced the flag `ignoreOwnerReferences` which when set will allow the resources having owner references to be picked for migration.
```
**Does this change need to be cherry-picked to a release …

PWX-30890: Introducing a bool flag ignoreOwnerReferences in migration and migrationschedule to migrate the resources having owner references too.

---

pkg/applicationmanager/controllers/applicationbackup.go

>bug
```
pb-3840: creating the resourceexport CR in the backup namesapce instead of kube-system always
```
no
na
no
**Tested backup and restore successfully.**

pb-3840: creating the resourceexport CR in the backup namesapce instead of kube-system always

---

pkg/snapshotter/snapshotter_csi.go

>bug
```
If the backed up PVC spec has both the dataSource and dataSourceRef referring to the volumensnapshot, during restore, we need to update both of them point to the same volumesnapshot. If the dataSourceRef is point to the stale volumesnapshot entry that is different from dataSource, the creation of PVC fails with below error:
error:
time="2023-05-17T09:24:37Z" level=info msg="sivakumar --- .CreatePersistentVolumeClaim failed PersistentVolumeClaim \"mysql-data\" is invalid: spec: Invalid value: field.Path{name:\"dataSource\", index:\"\", parent:(*field.Path)(0xc011eec6f0)}: must match dataSourceRef"
time="2023-05-17T09:24:37Z" level=info …
```

pb-3878: updated both the datasource and datasourcRef of pvc during restore.

---

pkg/monitor/monitor.go

>bug
Stork would delete a pod on a node which was detected Offline but which is turned Online during the exponential backoff wait. A recent change introduced this regression in 23.5
No
No - This is a regression in 23.5-dev
Yes - 23.5

PWX-31149: Use the correct node object in stork monitor.

---

pkg/applicationmanager/controllers/applicationrestore.go

>bug
```
pb-3891: updating the resourcount of restore CR in updateResourceStatus.
```
no
no
no
Currently the PV and PVC counts of CSI and kdmp resources are not getting updated in the final count.

pb-3891: updating the resourcount of restore CR in updateResourceStatus.

---

pkg/applicationmanager/controllers/applicationrestore.go

- During restore, specifically for the CSI and kdmp, the PV & PVC count is considered in total resource count
- Other than CSI, the total resource count should be obtained from resourceexport CR rather than application restore CR.
>bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
**What this PR does / why we need it**: Updates the total resource count properly in case of restore when backup contains CSI  volumes. 
```release-note
Issue:
User Impact:
Resolution
```
Unit …

pb-3807: Update resource count properly in large resource restore

---

pkg/applicationmanager/controllers/applicationrestore.go

**What this PR does / why we need it**: handle resource export estatus when its nil , so cleanup will not be made when its empty. Usually the status update happens in the initial block of resource export reconciler. (i.e status to "initial"). When status update fails due to network crunch , the RE CR may hold an empty string

PB-3882 - handle resource export status when its nil

---

test/integration_test/action_test.go
test/integration_test/common_test.go

Fix TestAction that fails because of promote call now expects sync domain to be offline
No
No
No
**Notes**
```
20:34:19 --- PASS: TestMigration (19983.11s)
20:34:19     --- PASS: TestMigration/testMigration (18090.55s)
20:34:19         --- PASS: TestMigration/testMigration/deploymentTest (416.79s)
20:34:19         --- PASS: TestMigration/testMigration/deploymentMigrationReverseTest (744.02s)
20:34:19         --- PASS: TestMigration/testMigration/statefulsetTest (496.39s)
20:34:19         --- PASS: TestMigration/testMigration/statefulsetStartAppFalseTest …
```

Fix Action test

---

drivers/volume/aws/aws.go
drivers/volume/azure/azure.go
drivers/volume/csi/csi.go
drivers/volume/gcp/gcp.go
drivers/volume/kdmp/kdmp.go
drivers/volume/linstor/linstor.go
drivers/volume/mock/mock.go
drivers/volume/portworx/portworx.go
drivers/volume/volume.go
pkg/applicationmanager/controllers/applicationclone.go
pkg/applicationmanager/controllers/applicationrestore.go
pkg/migration/controllers/migration.go
pkg/resourcecollector/persistentvolume.go
pkg/resourcecollector/resourcecollector.go

>bug
```
pb-3907: Modified UpdateMigratedPersistentVolumeSpec() to get the azure
session from the backuplocation cluster cred.
- Modified the UpdateMigratedPersistentVolumeSpec interface to
take the backuplocation name and namespace.
```
no
n.a
No
Test result, I will add it in KDMP PR, where this changes need to be vendored.

pb-3907: Modified UpdateMigratedPersistentVolumeSpec() to get the azure

---

test/integration_test/test-deploy.sh

When using sed it's neccessary to use `|` as separator instead of `\` when parsing urls, otherwise it does not work as expected.
no
no
no

use correct sed for urls

---

pkg/applicationmanager/controllers/applicationrestore.go

In case of CSI and KDMP, the volumes entries are added later. Hence the restoredResourceCount and TotalResourceCount aare updated at the end of resource restore process.
**What type of PR is this?** BUG
>bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
**What this PR does / why we need it**: This makes the restoredResource Count and Total resource count to reflect the right value upon success. ealier it shos the count without PV-PVC counts.
**Is a release note needed?**: NO
```release-note
Issue:
User Impact:
Resolution
```
**Does this change need to be cherry-picked to a release branch?**: NO
Unit Test : …

pb-3807: RestoredResourceCount to reflect pv pvc count too

---

pkg/applicationmanager/controllers/applicationbackup.go
pkg/utils/utils.go

- Certain APPs like MYSQL unlocks the tables if the session in which the DB is locked, is ended.
- We have deferred the killing of pre-exec POD till all the volume snapshot is taken thereby ensuring DB is not in inconsistent state during snapshot process
**What type of PR is this?** BUG
>bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
**What this PR does / why we need it**: Because pre-exec pod which waits for volume backup  to get over gets killed untimely it leads to data inconsistsency.  Though it has executed the necessary commands to lock & stop the IO but POD eviction unlocks the mysql App DB which triggers the inconsistency. Hence fixed the untimely …

pb-3823: Make the pre-exec cmd-executor POD session alive during snapshot process

---

pkg/snapshotter/snapshotter_csi.go

>bug
```
pb-3966: Updating the restore PVC size only when the volumesnapshot size is greater than PVC size
```
No
```release-note
Issue: CSI restore fails for some of the storage provider, when the volumesnapshot size is less the PVC size
User Impact: User will not able to do CSI restore with some storage provider.
Resolution: Fixed such the restore PVC size will be always equal to source volume size or greater then source volume size, if the volumesnapshot size is greater then the source volume size
``` …

pb-3966: Updating the restore PVC size only when the volumesnapshot size is greater than PVC size

---

pkg/migration/controllers/clusterpair.go
pkg/storkctl/clusterpair.go

improvement
1. Getting px-auth-token for auth enabled clusters.
2. Removing backuplocations creation in destination as this will be done as part of bidirectional clusterpair with storkctl.
**Test**
Test results have been updated in the ticket.

PWX-30577: Changes for getting px-auth-token for getting clusterpair token call.

---

Dockerfile

>feature
Using AAD will require using kubelogin to generate kubeconfig
no
yes
```release-note
Updated kubelogin in Stork container.
```
yes, 23.7
**Notes**
- Enabled AAD for the cluster from Azure UI and tried to generate kubeconfig from cli 
```
$az aks get-credentials --resource-group ppandey-dev2 --name ppandey-dev2
$kubectl get nodes
Unable to connect to the server: getting credentials: exec: executable kubelogin not found
It looks like you are trying to use a client-go credential plugin that is not installed.
To learn more about this feature, consult the documentation …
```

PWX-31339: Install kubelogin in stork container

---

pkg/migration/controllers/clusterpair.go
pkg/storkctl/clusterpair.go

>bug
Deletes backuplocation and secret those are created as part of clusterpair creation.
**Test**
```
➜  stork git:(PWX-31999) ✗ bin/linux/storkctl create clusterpair cp-s3-del-bl -p s3 -n kube-system --src-kube-file /tmp/dipti5.config --dest-kube-file /tmp/dipti7.config --s3-access-key ***** --s3-secret-key ****** --s3-endpoint ******  --s3-region us-east-1
Source portworx endpoint is 10.13.192.154:9001
Destination portworx endpoint is 10.13.194.128:9001
Creating Secret and Backuplocation in source cluster in namespace kube-system... …
```

PWX-31999: Deleting backuplocation and secret reference as part of clusterpair deletion.

---

pkg/migration/controllers/clusterpair.go
pkg/storkctl/clusterpair.go
pkg/utils/utils.go

>improvement
Bidirectional cluster pair improvements.
```release-note
Bidirectional clusterpair improvements with auto detecting px endpoints and px token.
```

PWX-24657: Bidirectional clusterpair improvements

---

pkg/snapshotter/snapshotter_csi.go

>bug
```
pb-4000: Increased the value of shortRetryTimeout to 5mints.
- On some of the platform, the deletion of the job pod that we
create to temporarily to bound the "waitForFirstConsumer" volumebind mode
PVC takes time.
- So increased the timeout value for the waiting for the bound
to be deleted to 5 minutes from 30 sec.
```
No
```release-note
Issue: In some cases, the bound pod deletion takes time, So current timeout value of 30 sec is not enough and backup fails.
User Impact: Some time the backup of the volume whose volume bind mode with "WaitForFirstConsumer" fails …
```

pb-4000: Increased the value of shortRetryTimeout to 5mints.

---

test/integration_test/clusterdomain_test.go
test/integration_test/common_test.go
test/integration_test/migration_test.go

* During namespace deletion that happens as part of blowup method, for negative case destination namespace does not exist so we need to skip that deletion of namespace on destination
* Fix projectID mappings in bidirectional cluster pairing in stork integration tests
* Fix cluster switching in cluster domain tests
no
no
no

skip namespace deletion during blowup, for negative cases

---

pkg/storkctl/clusterpair.go
pkg/storkctl/clusterpair_test.go
pkg/storkctl/generate.go

improvement
With storkctl create option, we can create unidirectional cluster pair.
```
git:(PWX-32230) ✗ bin/linux/storkctl create clusterpair uni-cp -p s3 -n kube-system --src-kube-file /tmp/dipti5.config --dest-kube-file /tmp/dipti7.config --s3-access-key ***** --s3-secret-key ****** --s3-endpoint ********* --s3-region us-east1 --uni-directional
Destination portworx endpoint is 10.10.100.100:9001
Fetching px token with auth token in destination cluster
Creating Secret and Backuplocation in source cluster in namespace kube-system...
Backuplocation uni-cp created on source cluster in namespace kube-system
Creating a cluster pair. Direction: …
```

PWX-32230: Supporting unidirectional clusterpair creation with storkctl create command.

---

drivers/volume/csi/csi.go
pkg/snapshotter/snapshotter_csi.go

>bug
```
pb-4093 Deleting the volumesnapshotcontent in the case of failed native
CSI backup
- Adding the vsc name in the map in CleanupBackupResources with
out any status check ( success/failure/in-progress)
- In SnapshotStatus() also removed the check for ready state to
add the volumesnapshotcontent name in the snapshotInfo. If the status
volumesnapshotcontent is present, we will add the VSC name in the snapshotInfo.
```
no
```release-note
Issue: The volumesnapshotcontent are not getting deleted when the native CSI backup fails with the timeout error.
User Impact: The …
```

pb-4093 Deleting the volumesnapshotcontent in the case of failed native CSI backup.

---

pkg/storkctl/clusterpair.go
test/integration_test/common_test.go

improvement
Modifying "google-json-key" to "google-json-key-file" to have better understanding for the input parameter that it requires a file path for input.

PWX-32496: Modifying input param "google-json-key" to "google-json-key-file" for creating clusterpair with google objectstore.

---

pkg/snapshotter/snapshotter_csi.go

>bug
```
pb-4106: added nil ptr check while accessing snapshot.Status in SnapshotStatus() api.
```
No
No, as it is regression from previous commit.
Yes to 2.7 and 2.7.1
Testing:
Validate a successful Native CSI backup with the fix.

pb-4106: added nil ptr check while accessing snapshot.Status in SnapshotStatus() api.

---

.travis.yml
Dockerfile
Makefile

>Improvement
Update golang, aws-iam-authenticator and google-cloud-sdk versions to address golang vulnerabilities.
no
Fixed several vulnerabilities resulting from 
yes 23.7
**Notes**:
* Changes will be tested as part of 23.7.0 System tests
* There is some issue in our github repo due to which following error is observed when updating to any golang version > 1.19.1. To bypass this error -buildvcs=false  has been added.
```
error obtaining VCS status: exit status 128
Use -buildvcs=false to disable VCS stamping.
```
This is probably being caused due to some issue with out …

PWX-30765: Updating golang, aws and gcloud sdk to fix vulnerabilities.

---

.travis.yml
Dockerfile
Makefile

>Improvement
Update golang, aws-iam-authenticator and google-cloud-sdk versions to address golang vulnerabilities.
no
Fixed several vulnerabilities resulting from 
yes 23.7
**Notes**:
* Changes will be tested as part of 23.7.0 System tests
* There is some issue in our github repo due to which following error is observed when updating to any golang version > 1.19.1. To bypass this error -buildvcs=false  has been added.
```
error obtaining VCS status: exit status 128
Use -buildvcs=false to disable VCS stamping.
```
This is probably being caused due to some issue with out …

Cherry-pick PWX-30765: Updating golang, aws and gcloud sdk to fix vulnerabilities

---

pkg/storkctl/clusterpair.go

improvement
Create namespaces in source and dest clusters if it does not exist as part of clusterpair creation.
**Test**
```
1. Creating bidirectional clusterpair when namespaces don’t exist in both source and dest cluster.
➜  stork git:(PWX-32573) ✗ kubectl get ns ns1
Error from server (NotFound): namespaces "ns1" not found
➜  ~ kubectl get ns ns1
Error from server (NotFound): namespaces "ns1" not found
➜  stork git:(PWX-32573) ✗ bin/linux/storkctl create clusterpair cp-ns1 -n ns1 --src-kube-file /tmp/dipti5.config --dest-kube-file …
```

PWX-32573: Creating namespaces as part of clusterpair creation if the input namespace does not exist.

---

drivers/volume/mock/mock.go
drivers/volume/portworx/portworx.go
drivers/volume/volume.go
pkg/extender/extender.go
pkg/extender/extender_test.go
pkg/monitor/monitor_test.go

>feature
* In a mixed node cluster i.e. having both Linux and Windows nodes, if scheduling request comes for a Pod which uses a volume with [winshare: true] Stork will skip scoring for those Pods(https://portworx.atlassian.net/wiki/spaces/PE/pages/2702016513/Windows+container+support#:~:text=px%2Dcsi%2Dwin%20storageclass%20%3A%20Storage%20class%20with%20%22winshare%22%3A%20%22true%22%20attribute%20to%20distinguish%20Windows%20export%20volumes)
**Note**: 
* Node affinity or taints must be set for the Windows Pod so we don't receive Linux nodes in the filter request for a Windows Pod. 
* As per confirmation on https://purestorage.slack.com/archives/G01NEU80BSA/p1690866080451719?thread_ts=1690611028.265749&cid=G01NEU80BSA …

PWX-28210: Disable filter and prioritize for Windows Pods

---

pkg/resourceutils/updatereplicas.go
pkg/storkctl/migration_test.go

improvement
storkctl activate/deactivate has to take care of the non-managed migrated replicasets.
```release-note
Issue: Migrated replicasets which were not managed by deployments could not be activated/deactivated with storkctl.
User Impact: User has to manually scale up/down the replicaset using kubectl.
Resolution: storkctl now has the capability to scale up/down the migrated replicaset as part of activate/deactivate.
```
Test:
1. Non-managed replicasets:
```
➜  ~ km get all
NAME                       DESIRED   CURRENT   READY   AGE
replicaset.apps/mysql-rs   0 …
```

PWX-32425: Non-managed Replicaset activating/deactivating with storkctl.

---

cmd/stork/stork.go
pkg/applicationmanager/controllers/applicationrestore.go

>bug
```
pb-4208: Retaining the values of user editable parameter of stork-controller-config configmap during pod restart.
```
No
Yes
```release-note
Issue: The value of large-resource related parameter, updated by user  in the stork-controller-config configmap are no retained across the stork pod restarts.
User Impact: User need to update large-resource related parameter in stork-controller-config configmap, every time when stork pods restarts.
Resolution: Retaining the user updated value of large-resource related parameter in stork-controller-config cofigmap across the …
```

pb-4208: Retaining the values of user editable parameter of stork-controller-config configmap during pod restart.

---

Dockerfile

>bug
Update aws-iam-authenticator binary to the latest version and use -Lo option.
```release-note
Issue: aws-iam-authenticator binary size was 0 in the Stork container.
User Impact: Users using Kubeconfig with aws-iam-authenticator will fail to create cluster pair on EKS
Resolution: Updated the aws-iam-authenticator and updating the curl options to make sure binary gets downloaded
```
yes, 23.7.1

PWX-32901: Update aws-iam-authenticator in Stork container

---

Dockerfile

>bug
Update aws-iam-authenticator binary to the latest version and use -Lo option.
```release-note
Issue: aws-iam-authenticator binary size was 0 in the Stork container.
User Impact: Users using Kubeconfig with aws-iam-authenticator will fail to create cluster pair on EKS
Resolution: Updated the aws-iam-authenticator and updating the curl options to make sure binary gets downloaded
```

 PWX-32901: Update aws-iam-authenticator in Stork container

---

drivers/volume/portworx/portworx.go

- Use SdkCloudBackupSizeResponse.GetSize() for portworx volumes if SdkCloudBackupSizeResponse.GetCompressedObjectBytes() is empty
Signed-off-by: Santosh Kumar Gajawada <sgajawada@purestorage.com>
bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
Using the latest stork with portworx volumes lessthan v3.0.0 will result an empty size due to unsupported response from the portworx SdkCloudBackupSizeResponse
no
```release-note
Issue: ApplicationBackupVolumeInfo size is empty.
User Impact: For the portworx volumes …
```

PB-4193: Portworx volume size issue

---

pkg/objectstore/s3/s3.go

>bug
```
pb-4241: Added ErrCodeBucketAlreadyExists check in CreateBucket to avoid logging confusing warning event in the applicationbackup CR.
```
```release-note
Issue: Warning event is logged in the applicaitonbackup CR, if the S3 bucket was already exists.
User Impact: The warning event was confusing to the user.
Resolution: Avoiding warning event if S3 objectstore gives ErrCodeBucketAlreadyExists code.
```
23.7.2 branch
**Testing:**
Before fix:
After fix the warning event is visible in …

pb-4241: Added ErrCodeBucketAlreadyExists check in CreateBucket to avoid logging confusing warning event in the applicationbackup CR.

---

drivers/volume/portworx/portworx.go

>improvement
- The name and namespace labels are provided as part of the Portworx Cloudsnap Restore request.
- The name of the PVC stays the same as it was when the backup was taken. However the namespace can change if the user decides to restore in a different namespace.
- These labels ensure Portworx driver knows which namespace the volume is getting restored to.
No
Yes
```release-note
Portworx driver will ensure the correct pvc and namespace labels are applied on the Portworx volume while restoring from an ApplicationBackup.
```
Yes - 23.8

PWX-31012: Provide the PVC namespace and name labels while restoring Portworx backup.

---

pkg/objectstore/s3/s3.go

Added the error code check for tencent objectstore while fetching object lock info.
> Uncomment only one and also add the corresponding label in the PR: Bug
bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
**What this PR does / why we need it**: tencent object store using a different error code for object lock fetching that need to added for a proper backup location addition.
```release-note
Issue:
User Impact:
Resolution
```
**Does this change need to be cherry-picked to a release branch?**: 23.7.2
Unit test:
Added the backup location with tencent credentials and validated exclusively
Taken backup and did a …

pb-4192: handle objectlock error for tencent objectstore

---

Dockerfile

>improvement
Update GCloud SDK.
Without this change: Vulnerability count = 327 https://aetos.pwx.purestorage.com/security/Stork/23-8-0-dev/2023-08-17-19-37-03-746232
With this change: Vulnerability count = 259 https://aetos.pwx.purestorage.com/security/Stork/23-8-0-dev/2023-08-24-21-21-00-059221
na
```Improvement
Update google cloud sdk to to v444.0.0 to fix vulnerabilities.
```
yes, 23.8.0

PWX-32617: Update google sdk.

---

pkg/apis/stork/v1alpha1/applicationregistration.go
pkg/migration/controllers/clusterpair.go
pkg/migration/controllers/migration.go
pkg/resourceutils/updatereplicas.go
pkg/utils/utils.go

improvement
Stashing strategy for the CR content to a configmap so that after migration with `startApplication: False` the application automatically does not get started when it is managed by a clusterwide operator.
Avoid recreating the resources during migration if there is no change to the resource content.
```release-note
Issue: Applications controlled by CR automatically gets started after migration if the operator is already up and running in a different namespace.
User Impact: Apps in destination cluster gets started which is not as per expectation with startApplication: false
Resolution: Stashing strategy for the CR content to a …
```

PWX-31470: Clusterwide operator CR migration support.

---

Makefile

bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
We should be able to load px_statfs.so on RHEL8.5 (OCP 4.12) which uses glibc 2.28. Therefore, we need to pin down the version of gcc used to build px_statfs.so.
Switched the px_statfs.so build container to gcc:10.5.0 from golang:1.19.10 which uses gcc 12.
No
```release-note
Issue: 
When using Stork versions 23.7.0 and 23.7.1, KubeVirt pods go into CrashLoopBackoff state. 
The following errors appear in the pod logs:
/usr/bin/virt-launcher-monitor: …
```

PWX-33267: use gcc 10.5.0 container to build px_statfs.so

---

Makefile

bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
Cherry-pick fix for PWX-33267 to 23.7.2 release
no
```release-note
Issue: See the main PR.
User Impact:
Resolution
```

PWX-33267: use gcc 10.5.0 container to build px_statfs.so (#1489)

---

pkg/storkctl/applicationbackup.go
pkg/storkctl/applicationbackup_test.go
pkg/storkctl/applicationrestore.go
pkg/storkctl/applicationrestore_test.go
pkg/storkctl/common.go

improvement
1. Support for backing up resources with particular resource types
2. Support for restoring a particular object
```release-note
Issue: storkctl was not supporting creating of backup for specific resource types and resources for specific resources.
User Impact: Manually it was required to add the backup and restore CRs. 
Resolution : Support for specific resource types backup and specific resource restore through storkctl is now supported.
```
**Test**
More test results have been updated in PWX-31372

PWX-31372: storkctl to support backing up specific resource types and restoring specific objects.

---

pkg/apis/stork/v1alpha1/backuplocation.go

>feature
```
pb-4278: Adding sse (s3 server side encryption) field in the s3config of
backuplocation CR.
```
It changes backuplocation CR, But do not want to call till complete implementation is available.
NA. As not pubically calling out till complete implementation is available.
23.7.2 and 23.8.0

pb-4278: Adding sse (s3 server side encryption) field in the s3config of backuplocation CR.

---

Makefile

This reverts commit ed2e76b9a86b844dbdb5f73e1d2cec5aff99bd74.
Reverting the kubevirt changes from 23.7.3.
No
No
Yes - 23.7.3

Revert "PWX-33267: use gcc 10.5.0 container to build px_statfs.so 

---

pkg/migration/controllers/migration.go

improvement
Migrating related CRDs with similar categories as some apps activation requires CRDs other than their group.
```release-note
Issue: ECK app installed with operator requires all related CRDs for starting up after migration.
User Impact: Elastic search app scaling up failed because of missing related CRD after migration.
Resolution: Related CRDs for a CR will also get migrated which will prevent the scaling up of ECK app after migration.
```
**Test**
```
In source:
[root@gejain-35-0 ~]# kubectl get crds | grep elastic …
```

PWX-30292: Migrating related CRDs to destination cluster with similar categories

---

pkg/migration/controllers/migration.go
pkg/resourceutils/updatereplicas.go

bug
storkctl activate should try to create the CR from stashed configmap, not deactivate.
**Test**
Without Fix:
➜  stork git:(PWX-30292) ✗ bin/linux/storkctl deactivate migrations -n mongodb
Updated replicas for deployment mongodb/mongodb-kubernetes-operator to 0
Updated CR for mongodbcommunity mongodb/example-mongodb
W0903 18:55:05.406178    9248 warnings.go:70] snapshot.storage.k8s.io/v1beta1 VolumeSnapshot is deprecated; use snapshot.storage.k8s.io/v1 VolumeSnapshot
**Successfully created the CRs from the stashed configmaps …

PWX-33454: storkctl deactivate should not create CR from stashed configmap.

---

Dockerfile
Makefile
drivers/volume/portworx/portworx.go
test/integration_test/px_statfs_webhook_test.go

>bug
>feature
improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
When a new virt-launcher pod is starting, update the existing px-statfs configMap, if needed.
no
no
no

 PWX-33267: update px-statfs configmap if needed

---

drivers/volume/kdmp/kdmp.go

>bug
```
pb-4365: Added already exist error for the dataexport CR creation in kdmp driver
```
No
```release-note
Issue: Sometime the backup and restore fails, if the Dataexport CR already exists.
User Impact: Backup and restore fails, if the reconciler exists rentry again with "Dataexport CR already exists"
Resolution: Added check for "Dataexport CR already exists" and continue with other volumes.
```
Yet to be decide.
Testing:
Will ask the QA team to run the failing system test again.

pb-4365: Added already exist error for the dataexport CR creation in kdmp driver

---

pkg/migration/controllers/clusterpair.go
pkg/storkctl/clusterpair.go
pkg/storkctl/clusterpair_test.go

bug
```release-note
Issue: Creating clusterpair with --unidirectional fails as objectstore info was missing in destination cluster.
User Impact: Migration using the above clusterpair will fail.
Resolution: Creating objectstore info in destination cluster for migration to succeed.
```
**Test**
`
1. Creating clusterpair with unidirectional option.
➜  stork git:(PWX-33569) ✗ ./storkctl create clusterpair uni-cp-fw -n mongodb --src-kube-file /tmp/dipti5.config --dest-kube-file /tmp/dipti7.config …

PWX-33569: Creating objectstore locations in destination cluster in unidirectional clusterpair creation with storkctl

---

test/integration_test/Dockerfile

https://portworx.atlassian.net/browse/PTX-20175
No
No
No

update stork integration test container to Go 1.17.0

---

pkg/migration/controllers/clusterpair.go

bug
Deleting a namespace can make backuplocation to delete first and it should not block the clusterpair deletion from px.
**Test**
➜  stork git:(23.7.3) ✗ kubectl delete ns test1
namespace "test1" deleted
➜  stork git:(23.7.3) ✗ kubectl get clusterpair -A
No resources found
➜  stork git:(23.7.3) ✗ kubectl get backuplocations -ntest1
No resources found in test1 namespace.
➜  stork git:(23.7.3) ✗ kubectl get secret -ntest1
No resources found in test1 namespace. …

PWX-33787: Ignore backuplocation not found error during clusterpair deletion.

---

pkg/applicationmanager/controllers/applicationbackup.go

- Restrict backup of "kube-system" in case of all namespaces i.e. *
- Restrict backup of "kube-system" in case of label-selector
- Allow backup of "kube-system" in case API is specifically passing it i.e. namsespace=kube-system in API call
>feature
This PR restricts kube-system ns backup in below scenarios.
- Restrict backup of "kube-system" in case of all namespaces i.e. *
- Restrict backup of "kube-system" in case of label-selector
no
yes
```release-note
Issue: #PB-4245
User Impact: User will not be able to backup kube-system namespace if tried with label-selector or all namespace
Resolution: If user wants to backup kube-system namespace …
```

PB-4245 :: Restrict backup of "kube-system" ns

---

drivers/volume/portworx/portworx.go
drivers/volume/volume.go
pkg/migration/controllers/clusterpair.go

>bug
The earliest clusterpair is used as reference by the later clusterpairs for each specific pair (src->dest).
Deleting that clusterpair should be blocked so that migrations using other clusterpairs can work normally and once the referencing clusterpairs get deleted, the referenced one can be deleted.
**Test**
`
➜  stork git:(23.7.3) ✗ ./storkctl create clusterpair cp1 -n test1 --src-kube-file /tmp/dipti5.config --dest-kube-file /tmp/dipti7.config --s3-access-key **** …

PWX-33827: Avoid deleting the earliest clusterpair for a pair (src ->dest).

---

test/integration_test/migration_test.go

Fixed deletion of clusterPair on destination, so that we avoid backuplocation Not found issue on source
Source deletion is working but as we skip destination deletion the clusterPair exist on destination and it complains about Backuplocation not found on source

Fixed deletion of clusterPair on destination, so that we avoid backuplocation Not found issue on source

---

pkg/extender/extender.go
pkg/extender/extender_test.go

>feature
>unit-test
-  Introduce a new parameter stork.libopenstorage.org/preferRemoteNode to be applied to a StorageClass.
- Default value of preferRemoteNode is true for pods using shared v4 service volumes and will prefer antihyperconvergence
- If value of this label is set to false, ignore preferRemoteNodeOnly flag and prefer Hyperconvergence for pods using shared v4 service volumes.
- For more details refer to [PWX-33049](https://portworx.atlassian.net/browse/PWX-33049)
No
```release-note
* New Feature
When StorageClass parameter "stork.libopenstorage.org/preferRemoteNode" is set to "false", Stork will disable anti-hyperconvergence for …
```

PWX-33049 : Adding SC parameter preferRemoteNode to disable Anti-HyperConvergence for sharedv4 service volumes

---

drivers/volume/csi/csi.go

>improvement
```
pb-4467: Added support for passing sse type in the native CSI backup path.
```
N.A
N.A
2.9.0
Testing:
- Tested native csi backup on the IBM c
luster.

pb-4467: Added support for passing sse type in the native CSI backup path

---

pkg/snapshotter/snapshotter_csi.go

>improvement ( Adding SSE support)
```
pb-4570: Added support to pass SSE type in UploadSnapshotObjects(), csi snapshotter flow.
```
No, Will add a generic Release note for SSE support.
2.9 branch
**Testing:**
Validated the KDMP+Localsnapshot on IBM cluster with SS3 enabled bucket.

pb-4570: Added support to pass SSE type in UploadSnapshotObjects(), csi snapshotter flow.

---

drivers/volume/mock/mock.go
pkg/extender/extender.go
pkg/extender/extender_test.go
pkg/monitor/monitor_test.go

Addressing the scenario where pod.Status.HostIP != vol.AttachedOn but Pod is using locally attached volume.
Also addressing some review comments from my previous PR.
In the interest of not repeating the same set of calls multiple times and making it more understandable, decision of hyperconvergence/antihyperconvergence & preferLocalAttachment have been moved inside the function but the core logic stands as is. Only major change is that the definition of **isPodUsingLocallyAttachedVolume** has changed now.
Note: 
This PR is currently to the kubevirt-test branch. Changes will be merged in Master when we decide the release version for it.

PWX-33047: Kubevirt scheduling where host and volume ips do not match

---

pkg/applicationmanager/controllers/applicationbackup.go

- Restrict backup of initial-namespaces in case of all namespaces i.e. *
- Restrict backup of initial-namespaces in case of label-selector
- Allow backup of initial-namespaces in case API is specifically passing it i.e. namsespace=kube-public in API call initial-namespaces are https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/#initial-namespaces
>improvement
```
- Restrict backup of initial-namespaces in case of all namespaces i.e. *
- Restrict backup of initial-namespaces in case of label-selector
- Allow backup of initial-namespaces in case API is specifically passing it i.e. namsespace=kube-public in API call 
initial-namespaces are …
```

PB-4069 :: Restrict initial-namespaces backup

---

pkg/storkctl/clusterpair.go
pkg/storkctl/clusterpair_test.go

bug
1. Need to accept both https/http px endpoints.
2. Need to provide default port as 80 or 443 with host names if not provided.
```release-note
Issue: https px endpoints were not working with storkctl create clusterpair.
User Impact: Migrations between clusters with ssl enabled px endpoints were not working.
Resolution: Both https and http endpoints with the scheme is now accepted as src-ep and dest-ep with storkctl create clusterpair.
```
**Test**
Tested with
1. https endpoints 
2. http endpoints
3. Endpoints without port
4. Endpoints without …

PWX-34294: storkctl need to parse https px endpoints properly, also need to assign default ports for http and https endpoints.

---

test/integration_test/kubevirt_hyperconv_test.go

Update testrail IDs for kubevirt integration tests
Tests are added in TestRail in the path : [stork.Stork Integration Tests.Kubevirt] path https://portworx.testrail.net/index.php?/suites/view/1&group_by=cases:section_id&group_order=desc&display_deleted_cases=0&group_id=9155

PWX-33060: Update testrail ids for kubevirt integration tests

---

test/integration_test/specs/storkctl-specs/schedulepolicy/custom-daily-policy.yaml
test/integration_test/specs/storkctl-specs/schedulepolicy/custom-interval-policy.yaml
test/integration_test/specs/storkctl-specs/schedulepolicy/custom-monthly-policy.yaml
test/integration_test/specs/storkctl-specs/schedulepolicy/custom-weekly-policy.yaml
test/integration_test/specs/storkctl-specs/schedulepolicy/daily-policy.yaml
test/integration_test/specs/storkctl-specs/schedulepolicy/interval-policy.yaml
test/integration_test/specs/storkctl-specs/schedulepolicy/monthly-policy.yaml
test/integration_test/specs/storkctl-specs/schedulepolicy/weekly-policy.yaml
test/integration_test/storkctl_schedulepolicy_test.go

Adds automation tests for functionality of storkctl create schedulepolicy and storkctl delete schedulepolicy
Methodology followed to test ->
1. Call the storkctl create schedulepolicy command with required params
2. Validate that successful creation message is displayed to user
3. Validate that the actual resource created is per expectations by comparing it against a SchedulePolicy yaml file
No
No
Yes, 23.10.0
Jenkins Job Link https://jenkins.pwx.dev.purestorage.com/job/Users/job/omkar/job/omkar-storkctl-schedulepolicy/lastBuild
``` …
```

PWX-32338: Validate storkctl cli for creating and deleting SchedulePolicy

---

pkg/storkctl/applicationrestore.go
pkg/storkctl/applicationrestore_test.go

>improvement
Added the param for creating applicationrestore with namespacemapping with storkctl.
```release-note
Issue: Applicationrestore created with storkctl was always restoring to namespace with same name as source.
User Impact: User could not restore to a different namespace with appliactionrestore created with storkctl.
Resolution: Storkctl now has support to accept namespace mapping as a parameter for restoring to different namespace.
```
**Test**
updated in ticket PWX-33887.

PWX-33887: storkctl to support namespacemapping during applicationrestore creation.

---

pkg/applicationmanager/controllers/applicationbackup.go

- Removed the frequent BackupId check while a volume backup is in progress It was in ang called in a tight for loop, hence made it every reconciler call interval based.
bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
**What this PR does / why we need it**: When  portworx status check doesn't retiurn any error yet the backupId for a volume Info is nil then the backup logic will attempt to query the status frequently assuming that the volume  snapshot is still in progress. This status check was happening in a tight for loop, which was making portworx overwhelm with requests. Hence rate limited it by calling it every reconciler …

PWX-33934: remove tight loop around volumeBackup status check

---

pkg/storkctl/migrationschedule.go
pkg/storkctl/migrationschedule_test.go

>improvement
>unit-test
[PWX-32199](https://portworx.atlassian.net/browse/PWX-32199)
We are updating the storkctl create migrationschedule to add support for --interval , --auto-suspend and --annotations flags.
Yes, storkctl create migrationschedules cli command is updated with new flags
```[root@ip-10-13-195-219 ~]# storkctl create migrationschedules -h
Create a migration schedule
Usage:
storkctl create migrationschedules [flags]
Aliases:
migrationschedules, migrationschedule
Flags:
--annotations stringToString    Add required annotations to the resource in comma-separated key value pairs. key1=value1,key2=value2,...  (default [])
-c, --cluster-pair string …
```

PWX-32199: Improvements to storkctl cli create migration schedule

---

pkg/resourcecollector/endpoint.go

>bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
**What this PR does / why we need it**: We need in case of all namespace backup we backup default k8s endpoint which will be already there in any cluster so stork will skip that resource and mark it as partial restore. So to avoid partial restore we skip the default endpoint
**Is a release note needed?**: yes
We are excluding the default kubernetes endpoint in default namespace to be backed up because wherever we will be doing the restore the k8s endpoint will always be there and will result in partial restore as this resource …

PB-4632: Skip Default Kubernetes Endpoint

---

pkg/resourcecollector/resourcetransformation.go

- Modify getNewValueForPath function to parse the value based on the type.
- To solve the unmarshalling error while doing the dry-run as int/bool were also parsed as string.
bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
To solve the unmarshalling error while doing the dry-run as int/bool were also parsed as string.
no
no
```release-note
Issue:
User Impact:
Resolution
```
Yes because it is a bug in the latest release stork release.
JIRA BUG: …

PB-4564: unmarshalling error when RT transform spec path type is int/bool

---

pkg/resourcecollector/resourcecollector.go

improvement
Some of the operators like postgres were not able to reconcile on the CR and create the pods if service account, roles and rolebindings were already created.
```release-note
Issue: Postgres operator throws error of serviceaccount, role and rolebindings already exist after migration.
User Impact: Unable to scale up postgres app installed via openshift operator hub after migration.
Resolution: Postgres pods came up fine after skipping the resources serviceaccount, role and rolebindings as part of resource migration if they have ownerreference set.
```
**Does this change need to be cherry-picked to a …

PWX-34118: Skip service accounts, roles and rolebindings as part of pruning of resources with ownerreferences.

---

drivers/volume/csi/csi.go
pkg/snapshotter/snapshotter_csi.go

>bug
```
pb-4887: Added fix in handling the already exists error while creating
volumesnapshotclass during restore.
- If we have csi-snapshot-webhook webhook, the creation of
volumesnapshotclass fails with different eror message for already exists error.
- So add a get call and then calling create volumesnapshot call,
if Get failed with NotFound error.
```
no
```release-note
Issue: csi based restore fails on some of the setup that had csi-snapshot-webhook admin webhook as we get different error for alreadyexist error, while creating the volumesnapshotclass resource.
User …
```

pb-4887: Added fix in handling the already exists error while creating

---

pkg/extender/extender.go

"Skipping NeedsAntiHyperconvergence volume pvc-xxxx from scoring based on hyperconvergence" doesn't see very nice and is actually confusing people. Removing NeedsAntiHyperconvergence as this is redundant. We have similar messages in the extender "Skipping volume %v from  scoring based on antihyperconvergence" so this will be consistent.
no
yes, 23.11

Updating log message for for antihyperconverged volume.

---

pkg/snapshot/controllers/snapshotschedule.go
pkg/utils/utils.go

improvement
Using patch instead of update to avoid update error like 
"SDK update error: the object has been modified; please apply your changes to the latest version and try again"
```
23.11.0
```
**Test**
Tested with 10 volumes with 10 volumesnapshotschedules with 2 min interval policy.
1. Case where number of snapshots <  retain value:
```
➜  mysql-1-pvc git:(PWX-22740) ✗ kp -n mysql2 get volumesnapshotschedule vsc1  -o yaml
kind: VolumeSnapshotSchedule
metadata:
annotations: …
```

PWX-22740: Using patch instead of update for volumesnapshotschedule update.

---

pkg/apis/stork/v1alpha1/migration.go
pkg/migration/controllers/migration.go
pkg/resourcecollector/resourcecollector.go

improvement
Supporting `excludeResourceTypes` with migration to exclude a particular kind of resources
```release-note
Issue: A particular kind of k8s resource could not be excluded with migration.
User Impact: Using labels for excluding selectors does not work in certain cases where the resource is controlled by some operator which resets the user set labels.
Resolution: With the supported excludeResourceTypes, now a certain kind of resources can be excluded from migration.
```
```
23.11.0
```
**Test**
Tests with following has been done and have been updated in the ticket. …

PWX-31058: Supporting exclude resource types in migration.

---

pkg/storkctl/migrationschedule.go
pkg/storkctl/migrationschedule_test.go

>improvement
>unit-test
Adding the remaining params which are a part of MigrationSchedule CR to storkctl create migrationschedule with validations as well.
Yes, makes the storkctl create migrationschedule command comprehensive.
```
[root@ip-10-13-197-201 ~]# storkctl create migrationschedule -h
Create a migration schedule
Usage:
storkctl create migrationschedules [flags]
Aliases:
migrationschedules, migrationschedule
Flags:
--admin-cluster-pair string            Specify the name of the admin ClusterPair used to migrate cluster-scoped resources, if the ClusterPair is present in a non-admin namespace
--annotations stringToString           Add required annotations to the …
```

[PWX-34809] Adding the remaining params to storkctl create migrationschedule

---

pkg/resourcecollector/resourcetransformation.go

- Use SetNestedStringSlice instead of SetNestedField in case of SliceResourceType to avoid stork pod crash due to a panic
bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
To fix the stork pod crash issue when ever a rt cr created with slice type with add operation
no
no
```release-note
Issue:
User Impact:
Resolution
```
Yes because it is a bug in the latest release stork release.
issue: https://portworx.atlassian.net/browse/PB-4598
unit test …

PB-4598: Fix for Stork pods crash issue if the RT CR using the a transform of type slice and operation add

---

drivers/volume/kdmp/kdmp.go
go.mod
go.sum
vendor/github.com/portworx/kdmp/pkg/controllers/dataexport/reconcile.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiabackup/kopiabackup.go
vendor/github.com/portworx/kdmp/pkg/drivers/options.go
vendor/github.com/portworx/kdmp/pkg/executor/common.go
vendor/modules.txt

>improvement
```
pb-4872: Added code to pass the storageclass value as label in the
dataexport CR.
```
no
no. This change does not affect the functionality that customer use.
```release-note
Issue:
User Impact:
Resolution
```
23.9.1 branch

Pb 4872:Added code to pass the storageclass value as label in the dataexport CR.

---

pkg/migration/controllers/migration.go

>bug
As part of existing code, when users create migrationschedule and clusterpair in the admin namespace, they have to create preExec and postExec rules in both the admin Namespace as well as the namespaces to be migrated.
We fix this inconvenience by fetching the rules from adminNamespace only. 
No
Yes, TBD
Yes, 23.11.0
Have tested the changes in a local cluster and verified the bug as well as the fix.
Validated the fix by creating the migrationSchedule in the admin namespace and migrating default namespace. For this case the rules had to be created in …

[PWX-34991] Fetching rules from migration namespace instead of namespace to migrate

---

pkg/applicationmanager/controllers/applicationbackup.go

- Added a flag to prevent postexec rule to be executed exactly once for the life time of a backup.
- deleted the entry from the map that is created in application backup controller datastructure.
>bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
**What this PR does / why we need it**: The postexec rule is getting executed many times and backups are timing out for large sizzed volume based backups.
```release-note
Issue:
User Impact:
Resolution
```
**Does this change need to be cherry-picked to a release branch?**: 23.9
Unit test done: ( …

pb-4996: prevented infinite execution of post-exec rule

---

test/integration_test/migration_features_test.go

* Stash strategy migration test keep failing, until we debug this, renaming it so it does not get run as part of the migration suite
* We will still be running it in a separate job, that way it will be easier to debug.
no
no
no

change stash strategy test name to not include it in migration suite

---

Dockerfile

>improvement
Update GCloud SDK to the latest available version.
They have updated golang version to 1.21.3 and other dependencies which will help address multiple vulnerabilities observed in https://aetos.pwx.purestorage.com/security/Stork/23-11/2023-11-28-10-57-26-333496
No
```
Update google cloud sdk to to v455.0.0 to fix vulnerabilities.
```
Yes, 23.11

update google cloud sdk to latest version

---

.travis.yml
Makefile

>improvement
```
pb-5019: upgrade the golang version to 1.21.4 to fix CVE.
```
no
Issue: Security CVE 2023-45283 with commandexecutor.
Resolution: Upgrading golang version to 1.21.4
23.9.1 and 23.11 branches

pb-5019: upgrade the golang version to 1.21.4

---

pkg/storkctl/migrationschedule.go
pkg/storkctl/migrationschedule_test.go
pkg/storkctl/schedulepolicy.go

>improvement
This PR addresses improvements requested by QA in PWX-35180, PWX-35149 and PWX-35183
1. schedule policy may get created even if migrationschedule is not created due to a failing validation. This could impact the user experience.
2. changing date-of-month flag's description in storkctl create schedulepolicy
3. creating default-migration-schedule (30 min interval) schedulepolicy incase it doesn't exist
Yes
Slightly changed the description of --date-of-month flag in storkctl create schedulepolicy
No
Yes, 23.11.0

storkctl create migrationschedule minor improvements

---

drivers/volume/portworx/portworx.go

Signed-Off-By:  Diptiranjan
bug
Fixing the crash in UpdateMigratedPersistentVolumeSpec when vInfo gets passed as nil.
no
```release-note
Issue: Cloning app with csi volumes hit stork crash.
User Impact: Users could not do app cloning if PVCs in the namespaces use portworx csi volumes
Resolution: Fixed the stork crash for app cloning with csi portworx volumes.
```
yes, 23.11
**Test**:
```
➜  stork git:(23.11) ✗ storkctl get applicationclone -n kube-system
NAME       SOURCE    DESTINATION     STAGE   STATUS       VOLUMES   RESOURCES   CREATED               ELAPSED
clone-es …
```

PWX-35276: Fixing the stork crash for csi volume cloning.

---

Dockerfile.cmdexecutor

>improvement
```
pb-5175: Upgraded the base image of cmd executor from ubi8 to ubi9
- Upgraded the base image of cmd executor from ubi8 to ubi9 as
we are hitting lib version mismatch error.
```
no
```release-note
Issue: Fixed CVE 2023-45283 because of old goland 1.19.10
User Impact: cmd executor image will have CVE  2023-45283  reported
Resolution: Upgraded the golang version to 1.21.4 and base image of cmd executor from ubi8 to ubi9
```
23.9.1 and 23.11
**Testing:**
Validated the cmd executor pod …

pb-5175: Upgraded the base image of cmd executor from ubi8 to ubi9

---

pkg/storkctl/schedulepolicy.go

>improvement
Update the --retain flag description in storkctl create schedulepolicy command
from  `--retain int  Specify how many backups triggered as part of this schedule should be retained.`
to `--retain int  For backup operations, specify how many backups triggered as part of this schedule should be retained.`
Yes
```
[root@ip-10-13-193-200 ~]# storkctl create schedulepolicy -h
Create schedule policy
Usage:
storkctl create schedulepolicy [flags]
Aliases:
schedulepolicy, sp
Flags:
--date-of-month int                Specify the date of the month when Stork should trigger the operation. (default 1)
--day-of-week string               Specify the day of the week when …
```

[PWX-35357] updating retain flag description

---

pkg/storkctl/applicationbackup.go
pkg/storkctl/common.go
pkg/storkctl/migrationschedule.go

>bug
Fix for Bug identified by QA during testing
Yes, fixes the resource Type validation in exclude-resource-types flag in storkctl create migrationschedule and storkctl create applicationbackup
No
Yes, 23.11
When trying to run the command from a devVM we were observing the below error :
```
storkctl create migrationschedule ms-ex2 -c cp --namespaces default --exclude-resource-types deployment --kubeconfig=/root/go/src/github.com/libopenstorage/stork/configs/src_53.yaml
error: error getting discoveryclient: invalid configuration: no configuration has …
```

[PWX-35181] Changing the kubeconfig used by discoveryClient

---

pkg/storkctl/migrationschedule.go

>bug
The validation added for namespace validation in storkctl create migrationschedule has a bug.
The selectors were being AND'ed instead of OR'ed
Yes updates a validation for storkctl create migrationschedule
No
Yes, 23.11

[PWX:35392] fixing the mistake made in namespace validation

---

go.mod
go.sum
vendor/github.com/portworx/kdmp/pkg/controllers/dataexport/reconcile.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiabackup/kopiabackup.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiadelete/kopiadelete.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiamaintenance/kopiamaintenance.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiarestore/kopiarestore.go
vendor/github.com/portworx/kdmp/pkg/drivers/options.go
vendor/github.com/portworx/kdmp/pkg/drivers/utils/utils.go
vendor/modules.txt

>improvement
This PR introduces a change where we can access debug level logs for kopia operations. We need the this, so that in future whenever required, we could use it to view logs in debug level.
```release-note
Issue:
User Impact:
Resolution
```
Link to PX-Backup PR related to this particular PR is: https://github.com/portworx/px-backup/pull/1407
Link to KDMP PR related to this particular PR is: https://github.com/portworx/kdmp/pull/324
Attaching some screenshots for the reference:

Pb-4844: Changes in stork for it to enable debug level log messages for kopia operations

---

test/integration_test/common_test.go
test/integration_test/dataexport_rsync_test.go
test/integration_test/specs/fio-dataexport/fio-config-map.yaml
test/integration_test/specs/fio-dataexport/fio.yaml

- The integration test comprises of 4 tests:
- Fail if destination PVC does not exist.
- Fail if source PVC is in use.
- Fail if destination PVC size is not same or greater than source PVC.
- Successful data transfer between PVCs and the usage on the destination PVC increases.
No
No
Yes - 23.10.0 - so that this test runs for the current release branch

PWX-34428: Add integration tests for DataExport with rsync.

---

test/integration_test/specs/kubevirt-templates/fedora/fedora-template-pvc-rootdisk.yaml

* The old url being used to download the template for fedora has been changed so replacing it with the new url that works
no
no
no

fix url to download fedora qcow image from

---

drivers/volume/volume.go
pkg/applicationmanager/controllers/applicationbackup.go
pkg/utils/utils.go

- check for driver ocpRbdProvisioner and ocpCephfsProvisioner removed
- IgnoreNamespaces map moved to utils
improvement
This PR ensures the volume snapshots in case of ceph/rbd provisioner is taken by csi itself rather than KDMP as overflowing of data over PVD size is fixed. It also includes enhancement of ignore namespaces for future utility.
```release-note
Issue:
User Impact:
Resolution
```

PB-4201 :: OCP snapshot routed back to ceph/rbd from kdmp

---

test/integration_test/migration_test.go

Namespace delete error should not error out if namespace does not exists in migration tests cleanup.
**Test**
https://jenkins.pwx.dev.purestorage.com/job/Stork/view/Stork%2023.11-dev/job/migration-op-k8s-1-25-0/54/

PTX-21639: Namespace delete error should not error out if namespace does not exists in migration tests cleanup.

---

pkg/storkctl/migrationschedule.go
pkg/storkctl/migrationschedule_test.go

>improvement
In case migration schedule creation is going to fail, we should skip creating custom schedulepolicy (if any) since it will be an orphan resource which will not be used.
[PWX-35476](https://portworx.atlassian.net/browse/PWX-35476)
No
No
Yes, 23.11
[PWX-35476]: https://portworx.atlassian.net/browse/PWX-35476?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PWX-35476] Skip custom schedule policy creation in case migrationschedule creation will fail

---

drivers/volume/portworx/portworx.go
test/integration_test/common_test.go
test/integration_test/extender_test.go
test/integration_test/specs/test-sv4-replica1-prefer-remote-only/portworx/px-sc.yaml
test/integration_test/specs/test-sv4-replica1-prefer-remote-only/test-sv4-svc-repl1-prefer-remote-only.yaml

Signed-Off-By:  Diptiranjan
-    Fix for correctly updating the volume labels from the locator.
-    Integration test for the above fix.
>bug
```release-note
Issue: Stork was not honoring locator volume labels correctly while scheduling pods.
User Impact: Occasionally, pod can not get scheduled if preferRemoteNodeOnly=true but later px volume gets updated with preferRemoteNodeOnly=false and no remote nodes are available for scheduling.
Resolution: With the fix, pod can still get scheduled on the node where the volume replica exists.
```
**Test**
1. Ran test manually.
2. …

PWX-35513: Fix for correctly updating the volume labels from the locator.

---

pkg/extender/extender.go
pkg/extender/extender_test.go

>bug
>unit-test
As discussed in [PWX-35512](https://portworx.atlassian.net/browse/PWX-35512), if for some reason a node received as part of the Prioritize request is not available to the driver, we should avoid scheduling pods on that node. This is achieved by assigning the node a 0 score so that this node is ignored by the k8s scheduler during scheduling.
No
Maybe
Yes, 23.11
I have added unit tests for both hyperconverged and anti-hyperconverged cases.
The QA can replicate the original issue to ensure that the proposed fix is working as expected. …

[PWX-35512] Preventing pods from being assigned on nodes not available to Volume Driver

---

Dockerfile

Upgrade aws-iam-authenticator to latest version to address Critical CVEs
No
Update existing CVE release note
Yes, 23.11
QA team will be responsible to test migration and backup flows for any regressions.

upgrade aws-iam-authenticator version to latest 0.6.14

---

pkg/apis/stork/v1alpha1/applicationbackup.go
pkg/apis/stork/v1alpha1/zz_generated.deepcopy.go

>bug
>feature
>improvement
>cleanup
api-change
>design
>documentation
>failing-test
>unit-test
**What this PR does / why we need it**:  We need API Changes in ApplicationBackup to add a map of CSI Drivers to their respective VolumeSnapshot that will be handy in case of csi based backup
**Does this PR change a user-facing CRD or CLI?**: CRD
We need API Changes in ApplicationBackup to add a map of CSI Drivers to their respective VolumeSnapshot that will be handy in case of csi based backup
**Is a release note needed?**: 
```release-note
Issue:
User Impact: user will now have to use **csiSnapshotClassMap** instead of **CsiSnapshotClassName** as that will deprecated to increase …
```

PB-5442: CRD Changes For ApplicationBackup CRD

---

pkg/applicationmanager/controllers/applicationbackup.go

>improvement
When the VM backup is taken, stork creates Rule CRs which are not automatically deleted, now changes are added in the `cleanupResources` function, which detects the rules created by stork and then deletes them.
```release-note
Issue:
User Impact:
Resolution
```
Attaching screenshots below for reference

PB-5381: Cleanup of rule resources upon completion

---

drivers/volume/csi/csi.go

For KDMP clean up we are removing creation of default VolumeSnapshotClass from stork. As we don’t know whether that particular csi driver has a capability of volumeSnapshot or not
User has to create a VolumeSnapshotClass if required by them.
>bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
- Removes creation of default VolumeSnapshotClass from stork
- Before updating the stork with latest changes, stork creating default VSC
- Deleted stork created VSC class, and restarted the stork with latest changes, stork did not create VSC by default.

feat: removed creation of default vsc from stork

---

drivers/volume/volume.go

improvement
Removes hard coded CSI driver in which case kdmp was selected. This is a part of series of changes for KDMP localsnapshot cleanup
no
no
no

PB-5430 :: Remove check for drivers without snapshot support

---

go.mod
go.sum
pkg/apis/stork/v1alpha1/applicationbackup.go
pkg/applicationmanager/controllers/applicationbackup.go
pkg/resourcecollector/virtualmachine.go
vendor/github.com/portworx/sched-ops/k8s/kubevirt/kubevirt.go
vendor/github.com/portworx/sched-ops/k8s/kubevirt/virtualmachine.go
vendor/github.com/portworx/sched-ops/k8s/openshift/securitycontextconstraints.go
vendor/github.com/portworx/sched-ops/k8s/storage/storageclass.go
vendor/modules.txt

>bug
feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
This PR implements PB-5061 kubevirt - phase 2 populate includeResource for VM backup. 
yes
This introduces new filed backupObjectType: VirtualMachine 
```release-note
Issue:
User Impact:
Resolution
```
no
no
The CR otuput which gets populated with IncludeResources with configMap and PVC

PB-5061: Kubevirt - Phase 2 Populate Resources for VM Backup in stork

---

test/integration_test/clusterdomain_test.go
test/integration_test/migration_backup_test.go
test/integration_test/migration_failover_failback_test.go
test/integration_test/migration_test.go

Modifying existing migrationSchedule integration tests to use storkctl to create migrationSchedule instead of torpedo's scheduler.
Have updated the following integration tests -> 
1. dailyScheduleTest
2. weeklyScheduleTest
3. intervalScheduleTest
4. monthlyScheduleTest
5. intervalScheduleCleanupTest
No
No
Yes, 24.2.0
Testing Details:
[Jenkins job successful run](https://jenkins.pwx.dev.purestorage.com/job/Users/job/omkar/job/omkar-storkctl-schedulepolicy/32/)

Adding storkctl migrationschedule command to migrationschedule IntegrationTests

---

pkg/resourcecollector/virtualmachine.go

bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
When there is more than one container for virt-launcher pod, freeze/thaw rule will fail to execute without container name.
This PR will ensure the autoExecRules are run on compute container. 
No
```release-note
Issue:
User Impact:
Resolution
```
issue
24.1.0

Add container name to vmAutoExecRules

---

pkg/snapshotter/snapshotter_csi.go

>bug
```
pb-5438: Resetting the pvc.Spec.Selector in the csi snapshotter  as it is dynamic provisioning.
```
No
Yes
```release-note
Issue: Restoring a PVC with label selector with CSI and KDMP backup variant will fail.
User Impact: User will not able to restore the backup taken from a static PVC with label selector for PV selection.
Resolution: Fixed the issue by removing the label selector from the restore PVC.
```
2.7.0

pb-5438: Resetting the pvc.Spec.Selector in the csi snapshotter  as it is dynamic provisioning.

---

.gitignore
drivers/volume/csi/csi.go
drivers/volume/kdmp/kdmp.go
drivers/volume/volume.go
pkg/applicationmanager/controllers/applicationbackup.go
pkg/snapshotter/options.go
pkg/snapshotter/snapshotter_csi.go

>bug
feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
This PR implements the changes we required for feature Refining Backup Variants in which we are now going to support only 3 drivers namely KDMP, CSI Native and Portworx. We have removed the support for cloud native drivers as most of the csi are matured enough to take volumeSnapshot that can be used for backup and those who doesn't will go into KDMP.
No
Yes
```release-note
Issue: Backup Confusion while taking backup 
User Impact: User will have CSI or KDMP …
```

PB-5434, PB-5559 : Refining Backup Variants

---

pkg/resourcecollector/priorityclass.go
pkg/resourcecollector/resourcecollector.go

bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
This PR fixes bug PB-4848 for px-backup to support kubevirt operator backup/restore using kubevirt namespace based backup and restore.
NO
```release-note
Issue:
User Impact:
Resolution
```
No
24.1.0

PB-4848: Support kubevirt operatore restore using kubevirt ns backup

---

drivers/volume/csi/csi.go

>bug
>feature
improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
We need this PR to make creation of CSI SnapshotClasses as optional, now user will have to pass the env variable `CREATE_DEFAULT_VOLUMESNAPSHOTCLASS` to create those. Default behaviour will be not to create any.
no
yes
```release-note
Issue: VolumeSnapshotClass was getting created for those CSI Drivers who doesn't support snapshot. Later creates issue when creating backup.
User Impact: Need to add env var to stork deployment if they want to create by default by …
```

PB-5689: Default Creation of VolumeSnapshotClass should be optional

---

drivers/volume/aws/aws.go
drivers/volume/azure/azure.go
drivers/volume/gcp/gcp.go
drivers/volume/linstor/linstor.go
drivers/volume/portworx/portworx.go
pkg/applicationmanager/controllers/applicationbackup.go
pkg/applicationmanager/controllers/applicationbackupschedule.go
pkg/applicationmanager/controllers/applicationrestore.go

improvement
This PR adds the namespace info in the logs for the cases when a backup/restore operation fails due to a certain volume/resource. Ref: [PB-5280](https://portworx.atlassian.net/browse/PB-5280)
No
No
```release-note
Issue:
User Impact:
Resolution
```
Yes
**Screenshorts**
Logs with `namespace` info alongwith the PVC details.
[PB-5280]: https://portworx.atlassian.net/browse/PB-5280?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: log namespace with the resource that causes backup to fail

---

test/integration_test/specs/kubevirt-fedora-multi-disks-wffc/fedora-multi-disks-wffc.yaml
test/integration_test/specs/kubevirt-fedora-multiple-disks/fedora-vm-multidisk.yaml

PX performs its KubeVirt-specific logic only if the volume is a KubeVirt volume based on the volume labels. When the volume is created via a dataVolume template such labels are automatically added to the PVC. However, if a PVC is added directly to the VM spec, no such labels are present and therefore no VPS is added to the PX volume.
This patch adds a label with "kubevirt" in key to the PVCs specified directly in the VM spec.
Note that the test is currently passing even without this label. That is because the namespace just happens to have "kubevirt" in the name and the namespace appears as one of the label values. If the same VM spec …

PWX-33044: add kubevirt label to the PVCs added directly to the VMs

---

go.mod
go.sum
vendor/github.com/portworx/sched-ops/k8s/kubevirt-dynamic/virtualmachineinstance.go
vendor/modules.txt

Pull in the bootOrder VMI fix from sched-ops repo.
Used branch "for-stork-23.11-kubevirt-ea" to work around the incompatibility below when vendoring in from the master:
k8s.go:5992:67: cannot use obj (variable of type *"k8s.io/api/policy/v1beta1".PodDisruptionBudget) as *"k8s.io/api/policy/v1".PodDisruptionBudget value in argument to k8sPolicy.CreatePodDisruptionBudget
>bug
no
```release-note
Issue:
User Impact:
Resolution
```
no

PWX-36256: handle no bootOrder in kubevirt vmi

---

cmd/stork/stork.go
pkg/action/actioncontroller.go
pkg/action/failback.go
pkg/apis/stork/v1alpha1/action.go
pkg/resourceutils/updatereplicas.go
pkg/schedule/schedule.go
pkg/schedule/schedule_test.go
pkg/utils/utils.go

feature
1. Added action CR reconciler workflow with respect to different actions and multiple stages.
2. Added the code for DeactivateDestination of failback action.
3. Unit tests
Tests:
Manually run following cases and results have been updated in the ticket.
```
1. With an old successful migration.
2. With the latest migration failed.
3. With migration is in progress.
4. With more namespaces in action CR with reference to migration schedule (not a subset).
5. With latest successful migration within the schedule policy interval range.
```

PWX-35855: Action CR reconciler changes with multiple stages.

---

pkg/applicationmanager/controllers/applicationclone.go
pkg/resourcecollector/networkpolicy.go
pkg/resourcecollector/resourcecollector.go

- Cloning from one namespace to another target namespace if there are resources pre-exist in the target namespace then stork pod crashes for a nil pointer dereference
- Added relevant nil check and passed an empty struct for any accidental nil pointer access in that path.
**What type of PR is this?** BUG
bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
**Is a release note needed?**: Yes
```release-note
Issue: Cloning application to a namespace which has the same resource in it can cause stork pod crash
User Impact: stork pod will keep restarting unless the duplicate …
```

pb-5861: application-clone cr apply caused stork pod crash

---

drivers/volume/aws/aws.go
drivers/volume/azure/azure.go
drivers/volume/csi/csi.go
drivers/volume/gcp/gcp.go
drivers/volume/kdmp/kdmp.go
drivers/volume/linstor/linstor.go
drivers/volume/mock/mock.go
drivers/volume/portworx/portworx.go
drivers/volume/volume.go
pkg/apis/stork/v1alpha1/applicationbackup.go
pkg/applicationmanager/controllers/applicationbackup.go
pkg/snapshotter/snapshotter_csi.go

>bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
**What this PR does / why we need it**: Before we are only allowed to force Direct KDMP on cluster level and not backup and backupschedule level now its on object level for users to take cross cloud backup restore
Yes
DirectKDMP  field added (bool -> default to false)
```release-note
Issue: Backup Based Direct KDMP was not possible
User Impact: User can now do a direct kdmp backup on backup level and not cluster level
Resolution: BackupSchedules can have direct kdmp and another schedule can have csi …
```

PB-5837 : DIRECT-KDMP changes from ApplicationBackup CR

---

pkg/applicationmanager/controllers/applicationbackup.go
pkg/resourcecollector/virtualmachine.go

bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
For VM backup if a namespace provided does not have VMs in it. The VM backup takes backup of full namespace. This PR fixes the issue by filtering out namespaces that do not have VMs to backup. 
Closes PB-5779
no
```release-note
Issue: VM Backup with namespace having no VMs will take full namespace backup
User Impact: Instead of VM only backup, all resources will be backed up. 
Resolution: If namespace does not have any VMs, then the namespace will be pruned out …
```

PB-5779: Fix no VMs in namespace issue for vm Backup in stork

---

cmd/stork/stork.go
pkg/action/action.go
pkg/action/failback.go
pkg/apis/stork/v1alpha1/action.go
pkg/migration/controllers/migrationschedule.go
pkg/storkctl/action.go
pkg/storkctl/action_test.go
pkg/storkctl/common.go
pkg/storkctl/migration.go
pkg/storkctl/migrationschedule.go
pkg/storkctl/storkctl.go
pkg/utils/utils.go
test/integration_test/common_test.go

>feature
>unit-test
To add storkctl perform failover cli command. 
This command creates an action CR with actionType:failover for which we will add logic in the ActionController to perform the actual failover.
Another change is that we will create static copy of migrationSchedules in remote cluster irrespective of autoSuspend value
Yes, it adds a new storkctl command `storkctl perform failover`
```
[root@olavangad-84-0 ~]# storkctl perform failover -h
Initiate failover of the given migration schedule
Usage:
storkctl perform failover [flags]
Flags:
--exclude-namespaces strings   Specify the comma-separated list of subset namespaces to be skipped during the failover. By …
```

[PWX-32202] storkctl perform failover CLI changes

---

pkg/applicationmanager/controllers/applicationbackup.go
pkg/applicationmanager/controllers/applicationrestore.go
pkg/utils/utils.go

- if you run Portworx in a namespace other than kube-system and not using the default 9001 start port
- if annotation is not set to portworx.io/portworx-proxy: "false"
>improvement
We don't want to backup NS having portworx csi and hence we were ignoring the NS having portworx-service installed.
We found out that if you run Portworx in a namespace other than kube-system and not using the default 9001 start port then portworx-proxy pods are deployed by default and it has another set of portworx-service installed which was masking the NS actually having portworx service
No
No …

PB-6013 :: Handling multiple ns having portworx-service

---

pkg/action/actioncontroller.go
pkg/action/failback.go
pkg/resourceutils/updatereplicas.go

PWX-35857: Also the rollback functionality where destination deactivated apps needs to be activated have been added.
In case of successful migration, apps in source will be activated.
feature
Handling multiple stages of Failback workflow.
1. Doing last mile migration
2. Activating apps in source.
3. If the last mile migration fails, do rollback by activating apps back in destination cluster.
Yes, 24.2.0
Test:
Following tests were run and results have been updated in respective tickets.
1. Doing a successful failover with last mile migration and activating apps in source.
2. …

PWX-35856: Lastmile migration in failback workflow

---

pkg/resourceutils/listResources.go
pkg/resourceutils/scaleDown.go

>feature
This PR deals with the methods required for scaling down applications during failover and failback. 
Note: These functions are not being used yet. The upcoming PR will use these methods.
No
No
Yes, 24.2.0
For failover, we will first find out the resources which will be activated in the destination cluster and scale down the corresponding resources in the source cluster.
To simulate this for testing I used the below code in one of the storkctl commands and verified that a deployment,replicaSet & a mongocommunitydb resource (CRD) are scaled down …

[PWX-36291] Helper functions for scaling down applications during failover/failback

---

pkg/snapshot/controllers/snapshotschedule.go

improvement
Doing GetAndUpdate the volumesnapshotschedule.
Getting the latest copy and doing update is one more api call but currently it does not affect each reconciler cycle .  It happens in those cycles where
1. New volumesnapshot need to be created
2. Pruning of previous snapshots are required.
Generally the policy cycles are much larger compared to reconciler cycle, hence it is ok to do one more api call when the updating is absolutely required.

PWX-35885: Doing update on latest copy of volumesnapshotschedule to avoid update failures not happening on latest version.

---

drivers/volume/kdmp/kdmp.go
vendor/github.com/portworx/kdmp/pkg/controllers/dataexport/reconcile.go

- if the StorageClass name has more than 63 characters we fail to deploy the corresponding pod
- use annotation for storing SC name in DataExport CR
>bug
This PR handles SC names with more than 64 char and succeeds the backups.
no
no
release-24.1.0
**Test Screenshots**:

PB-6115 Handling label validation for Data Export CR

---

pkg/action/failback.go
pkg/apis/stork/v1alpha1/action.go
pkg/storkctl/action.go
pkg/storkctl/action_test.go

>feature
>unit-test
Yes, adds a new storkctl command `storkctl perform failback`
```
[root@ip-10-13-194-37 ~]# storkctl perform failback -h
Initiate failback of the given migration schedule
Usage:
storkctl perform failback [flags]
Flags:
--exclude-namespaces strings   Specify the comma-separated list of subset namespaces to be skipped during the failback. By default, all namespaces part of the MigrationSchedule are failed back
-h, --help                         help for failback
--include-namespaces strings   Specify the comma-separated list of subset namespaces to be failed back. By default, all namespaces part of the MigrationSchedule are failed back
-m, …
```

[PWX-32203] Adding perform failback command and unit tests

---

drivers/volume/kdmp/kdmp.go
go.mod
go.sum
pkg/snapshotter/snapshotter_csi.go
vendor/github.com/portworx/kdmp/pkg/controllers/dataexport/reconcile.go
vendor/github.com/portworx/kdmp/pkg/controllers/resourceexport/reconcile.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiamaintenance/kopiamaintenance.go
vendor/github.com/portworx/kdmp/pkg/drivers/options.go
vendor/github.com/portworx/kdmp/pkg/drivers/rsync/rsync.go
vendor/github.com/portworx/kdmp/pkg/drivers/utils/utils.go
vendor/modules.txt

bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
we don't need to have "Use-default-volumesnapshotclass" as value while selecting default vsc in case of csi based backup
```release-note
Issue:
User Impact:
Resolution
```

PB-6285: Remove "Use-default-volumesnapshotclass" while using snapshotClassName

---

pkg/storkctl/clusterpair.go
pkg/storkctl/clusterpair_test.go

Also DisasterRecovery clusterpair mode gets added for async DR case in the clusterpair object.
bug
storkctl create clusterpair now will support multiple modes like `async-dr, sync-dr, migration, onetime-migration`
**Unit test**:
```
➜  stork git:(PWX-35982) ✗ go test -v -tags unittest -coverprofile=profile.out -covermode=atomic  github.com/libopenstorage/stork/pkg/storkctl -run TestCreateUniDirectionalClusterPairMissingParameters
=== RUN   TestCreateUniDirectionalClusterPairMissingParameters
--- PASS: TestCreateUniDirectionalClusterPairMissingParameters (0.01s)
PASS …
```

PWX-35982: Storkctl create clusterpair will support migration and onetime-migration as mode.

---

pkg/action/actioncontroller.go
pkg/action/failback.go
pkg/action/failover.go
pkg/storkctl/action.go
pkg/utils/utils.go

>feature
Added all the stages of failover handling to the action controller. 
Note: as of this PR, updateReplicas method used is incorrect because it uses the singleton clients to update/list resources while we should create the clients using given config since in failover's rollback stage we need to activate resources in remote cluster. Changes for fixing that will be taken up in the next PR.
Testing details for the scenarios covered with this PR are attached in the corresponding Jira. https://portworx.atlassian.net/browse/PWX-35853
No
No
Yes 24.2.0

[PWX-35853] Failover Controller all stages

---

pkg/snapshot/controllers/snapshotschedule.go
test/integration_test/snapshot_test.go

bug
Adding the last 4 digit of UID to volumesnapshot names to avoid name collision in case of long volumesnapshotschedule with similar names resulting in similar volumesnapshot names if time frequency matches.
no
```release-note
Issue: Similar volumesnapshot names were getting created if volumesnapshotschedule frequency matches and after trimming produces similar substrings.
User Impact: For one volume snapshot might not be taken and be already marked as successful.
Resolution: Adding a 4 digit randomness to the name to avoid name collision for volumesnapshots resulting from different volumesnapshotschedules.
``` …

PWX-35626: Add a last 4 digit UID string from volumesnapshotschedule to volumesnapshot name to avoid name collision.

---

test/integration_test/cmdexecutor_test.go

>bug
Retry logic is not working properly since integration test makes a call in an incorrect way. As a result we occasionally see CBT failures when command doesn't run within first check and retries don't happen.
No
No
Yes, TBD

PWX-36733 : resolve test flakiness

---

test/integration_test/kubevirt_hyperconv_test.go
test/integration_test/kubevirt_test.go

This integration test for Kubevirt does the following:
- Deploy few VMs on the cluster
- Loop through nodes and do the below
* Live migrate all the VMs on that node
* restart volume driver on that node (only once)
* wait for all attachements on that node to move to another node
* do verification for all the VMs that were running on this node
https://portworx.atlassian.net/browse/PTX-22872
no
no
no

Per node livemigration

---

test/integration_test/extender_test.go

cleanup
* Currently we don't update the test result status for preferRemoteNodeFalseHyperconvergenceTest
* So it always gets updated as `Failed` in testrail
no
no
no

update testrail for preferRemoteNodeFalseHyperconvergenceTest

---

pkg/action/actioncontroller.go
pkg/action/failback.go
pkg/action/failover.go
pkg/apis/stork/v1alpha1/action.go

feature
Waiting after making scaling down is apps is crucial for data integrity with last mile migration.
The current approach is to wait for consumer pods of migrated PVCs to become 0.
Here the max wait time after pods go down can go upto 1 minute and the timeout happens when in 3 successive iterations no pods go down effectively making it 15 mins.
no
no
no
**Test**:
Test results have been updated in ticket PWX-36466
1. Failover and failback for apps with deployments and sts.
2. Failover of apps hitting timeout with apps controlled by operator. …

PWX-36466: Wait for pods using volumes to go down after scaling down apps.

---

go.mod
go.sum
pkg/rule/rule.go
vendor/github.com/portworx/sched-ops/k8s/batch/batch.go
vendor/github.com/portworx/sched-ops/k8s/common/pod.go
vendor/github.com/portworx/sched-ops/k8s/core/pods.go
vendor/github.com/portworx/sched-ops/k8s/kubevirt/kubevirt.go
vendor/github.com/portworx/sched-ops/k8s/prometheus/alertmanagerconfig.go
vendor/github.com/portworx/sched-ops/k8s/prometheus/prometheus.go
vendor/github.com/portworx/sched-ops/k8s/storage/csidriver.go
vendor/github.com/portworx/sched-ops/k8s/storage/storage.go
vendor/github.com/portworx/sched-ops/k8s/tektoncd/pipeline.go
vendor/github.com/portworx/sched-ops/k8s/tektoncd/task.go
vendor/github.com/portworx/sched-ops/k8s/tektoncd/tektoncd.go
vendor/modules.txt

>bug
```
pb-6459: Excluding the pods that are in completed state, even if the pod
selector label matches, to run the rules.
```
no
```release-note
Issue: In some use-cases, completed pods are getting selected to run and execution of rule fails.
User Impact: If there are two matching pods, one in completed and another in running state, makes the rule execution to fail.
Resolution: Avoiding the pods selection to run the rules, if they are in completed state.
```
release-24.1.0 branch.
**Testing:**
Tested the fix on the QA setup as mentioned in the ticket RCA.
1. When we …

pb-6459: Excluding the pods that are in completed state, even if the pod selecor label matches, to run the rules.

---

pkg/action/failback.go
pkg/action/failover.go
pkg/apis/stork/v1alpha1/action.go
pkg/storkctl/action.go
pkg/storkctl/actionstatus.go
pkg/storkctl/actionstatus_test.go
pkg/storkctl/get.go
pkg/storkctl/perform.go

>feature
>unit-test
CLI command to get summary / status of failover actions.
Yes, adds new CLI commands `storkctl get failover` && `storkctl get failback`
No
Yes, 24.2.0
** Testing Details **:
```
[root@olavangad-92-0 ~]# kubectl describe action -n kube-system failover-ms-4-2024-04-02-135725
Name:         failover-ms-4-2024-04-02-135725
Namespace:    kube-system
Labels:       <none>
Annotations:  <none>
API Version:  stork.libopenstorage.org/v1alpha1
Kind:         Action
Metadata:
Creation Timestamp: …
```

PWX-32335 : get failover / failback cli changes

---

test/integration_test/kubevirt_hyperconv_test.go

* The `kubeVirtSimulateOCPUpgrade` test currently restarts PX even on master node where no VMs are scheduled and PX is not installed
* This is causing the test to fail when restarting PX on those nodes
* This PR will avoid PX restarts on master node
no
no
no

Check vms before restart px

---

pkg/applicationmanager/controllers/applicationbackup.go

>bug
```
pb-6530: updating the CR content with the rule names, in the case of autoExecRule option.
- In the case of autoExecRule option, we update the rule CR
names in the applicationbackup CR in the reconciler cycle, dynamically.
- Currently, we are not updating/persisting  the CR content initially.
This causes issue in runPreExecRule api, where we update and
read the CR content immediately. This client.Get actually reads from the
cache content and the rul CR name in the applicationbackup CR was coming
empty sometime. This makes the get rule call to fail with "resource name can not be empty."
```
No …

pb-6530: updating the CR content with the rule names, in the case of autoExecRule option.

---

pkg/applicationmanager/controllers/applicationbackup.go

>feature
When there all the PVCs to be backed up are in skipped state, then the backup is supposed to be in disabled state.
This PR implements the said above feature and also partial backup in case few PVCs are in failed or skipped state, after backing up of resources.
```release-note
Issue:
User Impact:
Resolution
```
**Scenario 1**: All the PVCs are kdmp and BL is in valid state:
**Scenario 2**: BL is in active state, KDMP and 1 non KDMP PVC is successful and 1 non-KDMP is in failed state, the backup taken is in partial state
**Scenario 3**: The BL is in Limited …

PB-6508: Backup to fail if all PVCs are in skipped state and making partial backup successful in backupResources stage

---

test/integration_test/kubevirt_test.go

* The kubevirt functional test jobs are failing with timeout error when downloading images for VM templates
* Eg. https://jenkins.pwx.dev.purestorage.com/job/Stork/view/Stork%20Cloud%20Jobs/job/stork-ocp-kubevirt-4-13/96/consoleFull
* Increase the timeout when downloading images for VM templates
* Increase the retry interval for the same to reduce redundant logs
no
no
no

increase timeout for VM images download

---

pkg/migration/controllers/resourcetransformation.go
pkg/migration/controllers/resourcetransformation_test.go

improvement
Now resourcetransformation is supported for CRs.
no
yes
```release-note
Issue: Resourcetransformation for CRs were not supported.
User Impact: It was blocking some of the necessary transformations for resources required in destination site.
Resolution: Now resourcetransformation for CRs is supported.
```
yes, 24.2.0
**Test**:
1. Transformed elasticsearch CR during migration.
2. Checked resourcetransformation for an invalid resource.
Test results have been updated in the ticket.
The integration test will be raised in another PR.

PWX-34790: Enabling support for resourcetransformation for all objects including CRs.

---

go.mod
go.sum
pkg/mock/kubevirt/kubevirt.ops.mock.go
test/integration_test/kubevirt_hyperconv_test.go
test/integration_test/specs/kubevirt-fedora-multi-disks-wffc/fedora-multi-disks-wffc.yaml
test/integration_test/specs/kubevirt-fedora-wait-first-consumer/fedora-vm-wait-first-consumer.yaml
test/integration_test/specs/kubevirt-windows-22k-server-wait-first-consumer/windows-vm.yaml
vendor/github.com/portworx/sched-ops/k8s/core/pods.go
vendor/github.com/portworx/sched-ops/k8s/kubevirt/virtualmachine.go
vendor/modules.txt

>bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
The tests were verifying the initial VMI only for the first VM in the list. For the remaining VMs, the VMI has changed due to the testing performed on the first VM. So, we end up verifying the second or third VMI. This caused a bug to escape.
Changed the tests to verify the initial VMI correctly and verifed that they fail on OCP 4.14. Then, added an annotation to turn off cdi population to make the tests pass.
Also, vendored in the latest sched-ops to handle empty Kind in GetPodsUsingPV.
no …

PWX-36885: verify initial VMI state correctly

---

test/integration_test/specs/elasticsearch/elasticsearch.yaml

extender job is failing in statefulsetTest due to ImagePullBackoff when trying to pull elasticsearch image. Have changede the image used.
No
No
No
Jenkins job to test whether issue is fixed in progress. Will merge PR post successful run
https://jenkins.pwx.dev.purestorage.com/job/Stork/view/Stork%2023.11.1-dev/job/extender-op-k8s-1-25-0/348

changing the image used for elasticsearch

---

test/integration_test/applicationbackup_test.go
test/integration_test/snapshot_test.go

1. For backup tests , wrong assertion for in backup sync test.
2. In snapshot tests, choosing a bigger interval time to avoid the possibility of next snapshot trigger which may lead for sometime the old snapshot is present before it gets pruned.
no
no
no
Test runs: 
https://jenkins.pwx.dev.purestorage.com/job/Stork/view/Stork%2023.11.1-dev/job/application-backup-k8s-1-28-0/2162/
https://jenkins.pwx.dev.purestorage.com/job/Stork/view/Stork%2023.11.1-dev/job/snapshot-csi-k8s-1-25/2496/

Integration test fixes for backup and snapshot tests.

---

test/integration_test/common_test.go
test/integration_test/kubevirt_hyperconv_test.go
test/integration_test/specs/kubevirt-fedora-multiple-disks-datavol-only/fedora-vm-multidisk-datavol-only.yaml

* Adding a new VM spec that uses only datavolume based root and datadisks, that don't use WFFC
* This way co-location will always be achieved
no
no
no

add new VM spec for datavolume based root and data-disk, without WFFC

---

pkg/action/drutils.go
pkg/action/failback.go
pkg/action/failover.go
pkg/storkctl/migration.go
pkg/utils/utils.go

>improvement
Update the ApplicationActivated status in all the relevant migrationschedules when scaling up or scaling down namespaces during failover / failback.
Here relevant migrationschedules are those which migrate resources from atleast one of the namespaces being failed over or failed back.
No
No
Yes, 24.2.0
**Testing Details**:
Have manually verified that only the relevant migrationSchedules are picked up and updated.

[PWX-36891] Updating ApplicationActivated to true/false in the migrationschedule 

---

pkg/action/failback.go

>bug
ActivateClusterDomain call was unreachable. Moved the block to appropriate place
No
No
Yes, 24.2.0

[PWX-36930] ActivateClusterDomain during failback in metro-dr setup

---

test/integration_test/migration_dr_actions_test.go
test/integration_test/migration_test.go
test/integration_test/storkctl_dr_action_test.go

Automated following cases.
1. [Failover] Perform failover of a subset of namespaces end to end
2. [Failover] Perform failover of all namespaces end to end
3. [Failover] Perform Failover when a migration is ongoing
no
yes, 24.2.0
**Test**
https://jenkins.pwx.dev.purestorage.com/job/Users/job/dipti/job/dipti-new-dr-workflow/3/

PWX-32337: Adding Failover workflow tests done with action CR.

---

test/integration_test/common_test.go
test/integration_test/migration_dr_actions_test.go

Added failback tests with reverse migration schedule created with different schedule policies.
no
no
yes, 24.2.0
**Test**
```
time="2024-04-22T18:35:42Z" level=info msg="#Result: PASS "
time="2024-04-22T18:35:42Z" level=info msg=------------------------
time="2024-04-22T18:35:42Z" level=warning msg="Skipping testrail update for this case, testID: 296302, testrun: 0"
2024/04/22 18:35:42 WARN: Skipping testrail update for this case, testID: 296302, testrun: 0
--- PASS: TestDRActions (3632.30s)
--- PASS: …
```

PWX-32340: Adding Failback workflow tests with new action workflow with different schedule policies for reverse migrationschedule.

---

pkg/apis/stork/v1alpha1/backuplocation.go
pkg/objectstore/azure/azure.go

>bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
It adds support to use AZURE environment variable in the azure
objectstore apis
- Depending upon the azure environment type (AZURE_CHINA/AZURE_PUBLIC), the corresponding storage domain should be framed so that azure objectstore apis can use them to upload objects to the bucket
**Does this PR change a user-facing CRD or CLI?**:No
```release-note
Issue:
User Impact:
Resolution
```
**Unit Testing**
- vendored these stork changes to px-backup
- …

Pb-6675-1: adds support to use AZURE environment variable in the azure objectstore apis

---

pkg/action/actioncontroller.go
pkg/action/drutils.go
test/integration_test/migration_dr_actions_test.go

>bug
Last Mile migration should only migrate the subset of namespaces being failed over / failed back, instead of all the namespaces part of the reference migration schedule.
No
No
Yes, 24.2.0
**Testing Details**:
Have manually tested partial failover and failbacks in sequence. LastMileMigration is picking up only the subset of namespaces being failed over / failed back.
Modified the existing subset of namespaces integration test as well and updated the PR 
https://jenkins.pwx.dev.purestorage.com/job/Users/job/dipti/job/dipti-new-dr-workflow/12/

[PWX-36989] LastMileMigration should migrate only subset of namespaces

---

drivers/volume/portworx/portworx.go
drivers/volume/portworx/portworx_test.go
pkg/cache/cache.go
pkg/monitor/monitor.go
pkg/resourcecollector/resourcecollector.go
test/integration_test/health_monitor_test.go

>improvement
- Instead of sending individual Inspect() requests for each volume in a pod send a single Enumerate() request with all volumes in it. This is also less intensive on the Portworx side.
- Modify the Transform function in the SharedInformerCache to only store pod volumes which are relevant for stork.
- Added a framework to unit test the Portworx driver. Added UTs for GetPodVolumes() implementation.
- Modify the health monitor integration test to use mysql spec that has two volumes.
No
```release-note
Improvement: The Portworx driver has optimized the API calls it makes to reduce the time taken for scheduling pods and monitoring …
```

PWX-36282: Improve the GetPodVolumes() implementation for the Portworx Driver.

---

pkg/applicationmanager/controllers/applicationrestore.go

>bug
This PR forces pxd driver to restore using driver.StartRestore irrespective of backuplocation type as we need to support secured portworx volume restore and the access token is known in stork. 
No
No
release-24.1.0
**Tests Screenshots**:
**Before Fix:**
**After Fix:**
> The extension of this fix and testing details of scenarios are covered in https://github.com/portworx/kdmp/pull/360

PB-6687 :: Handle restoring secured px volume

---

pkg/applicationmanager/controllers/applicationrestore.go

>bug
```
pb-6893: Avoid calling getPVNameMappings in the applyResources api, if
it is called from volume stage.
```
No
Issue: The restore of backup with mixed backup variant like (PXD, CSI) fails
User Impact: User was able to restore the backup which had more than one backup variant.
Resolution: Fixed the issue to allow the restore from multi variants of backup drivers.
```
Yes, 24.1.0 and 24.2.0
Testing:
Validated in two setup by restore a backup taking for PXD and CSI volume.

pb-6893: Avoid calling getPVNameMappings in the applyResources api, if it is called from volume stage.

---

pkg/applicationmanager/controllers/applicationrestore.go

>failing-test
This handles pvc creation as per reatin policy in case of nfs as BL and pxd as driver combination
No
No
release-24.1.0

PB-6687 :: Skipping pvc as per RetainPolicy in case of nfs and pxd

---

drivers/volume/volume.go
pkg/applicationmanager/controllers/applicationrestore.go
pkg/resourcecollector/persistentvolume.go

bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
**What this PR does / why we need it**: In case of Old Cloud Native Backups when we restore in 24.1.0 we were facing issue with cloud native backups as they were going as native csi and in resource phase we skip csi based pv and pvc because we apply them later on 
**Does this PR change a user-facing CRD or CLI?**: no 
```release-note
Issue:
User Impact:
Resolution
```

PB-6903: Fix Cloud Native Restore Path

---

Jenkinsfile

CBT build job will build and push image with the branch name instead of commit and the branch name is going to be as `PR-XXXX`

PTX-20693 Changed CBT to use Pure artifactory

---

pkg/applicationmanager/controllers/applicationbackup.go
pkg/applicationmanager/controllers/applicationbackupschedule.go
pkg/applicationmanager/controllers/applicationrestore.go

bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
We need to Migrate the CSISnapshotName to CSISnapshotMap in case "default" is given to convert and find the default VSC for all provisioner in case user has not updated the PX Backup to 2.7.0
no 
yes
```release-note
Issue:
User Impact:
Resolution
```
yes 24.2.1

PB-6908: Fix Default VSC CSISnapshotName to CSISnapshotMap Conversion

---

pkg/apis/stork/v1alpha1/applicationbackup.go

- If PSA is enabled and a volume is backed-up with a specific Uid/Gid then that value need to be preserved for getting used during restore process.
- This is needed for all the job PODS to inherit above valuec so that no permission denied issues appear while restoring from a file backup
**What type of PR is this?** feature
>bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
**What this PR does / why we need it**: This is needed to support PSA for backup and restore.
**Does this PR change a user-facing CRD or CLI?**: No, it updates the status of Application Backup CR
**Is a release note needed?**: Nope
```release-note
Issue:
User Impact:
Resolution
```
**Does …

pb-6910: add uid & gid in each volume for psa support

---

pkg/action/actioncontroller.go
pkg/action/drutils.go
pkg/action/failover.go

>bug
>improvement
In case update Action fails for any reason an error message is logged and we eventually retry. As seen in [migration volumes code path](https://purestorage.atlassian.net/browse/PWX-27015), this kind of logs may cause unnecessary confusion. So going ahead and removing the log.
No
No
Yes, 24.2.0
**Notes for reviewer**:
Please ignore the first commit during review. It's a simple moving of methods to utils file.

[PWX-37142] Removing error log in case update action fails

---

cmd/cmdexecutor/cmdexecutor.go

bug
If no pods not found by cmdexecutor it is going into endless loop. 
This PR adds retry while looking for pods and eventually error out if not found any pods.
https://purestorage.atlassian.net/browse/DS-9703
no
no

wait for pods and exit gracefully if no pods found by cmdexecutor

---

test/integration_test/specs/cassandra/cassandra.yaml
test/integration_test/specs/elasticsearch/elasticsearch.yaml
test/integration_test/specs/endpoint/mysql.yaml
test/integration_test/specs/mysql-1-pvc/mysql.yaml
test/integration_test/specs/mysql-2-pvc/mysql.yaml
test/integration_test/specs/mysql-cloudsnap-group-restore/mysql.yaml
test/integration_test/specs/mysql-cloudsnap-group/mysql.yaml
test/integration_test/specs/mysql-cloudsnap-restore/mysql.yaml
test/integration_test/specs/mysql-enc-pvc-rancher/mysql.yaml
test/integration_test/specs/mysql-enc-pvc/mysql.yaml
test/integration_test/specs/mysql-localsnap-rule/mysql-1.yaml
test/integration_test/specs/mysql-localsnap-rule/mysql-2.yaml
test/integration_test/specs/mysql-nearsync/mysql.yaml
test/integration_test/specs/mysql-repl-1/mysql.yaml
test/integration_test/specs/mysql-service-account/mysql.yaml
test/integration_test/specs/mysql-snap-group-fail/mysql.yaml
test/integration_test/specs/mysql-snap-restore/mysql.yaml
test/integration_test/specs/mysql-ss/mysql-ss.yaml
test/integration_test/specs/nearsync-cassandra/cassandra.yaml
test/integration_test/specs/networkpolicy/mysql.yaml
test/integration_test/specs/snapshot-storageclass/autosnapsched.yaml

>failing-test
Addresses [PWX-37280](https://purestorage.atlassian.net/browse/PWX-37280). The PX volume provisioning has been failing in the Bidirectional Migration test job latelya and it was suggested to replace the annotation `volume.beta.kubernetes.io/storage-class: "mysql-sc"` from the PVC and instead use the field `spec.storageClassName : "mysql-sc"`. Post this, the volume provisioning for the pvc is successful. It is better for us to remove the annotation since it is deprecated according to kubernetes [docs](https://kubernetes.io/docs/reference/labels-annotations-taints/#volume-beta-kubernetes-io-storage-class-deprecated).
No
**Is a release note …

pwx-37280 | test: use spec.storageClassName instead of annotation for storageclass

---

cmd/cmdexecutor/cmdexecutor.go

improvement
Added flag `fail-on-no-pods` to fail cmdexecutor if no pods found in the namespace with the given label selector.
https://purestorage.atlassian.net/browse/DS-9703
Testing Done:
with `-fail-on-no-pods` flag set and no pods found cmdexecutor will exit with fatal error.
```
time="2024-05-15T16:54:21Z" level=info msg="Running pod command executor: 99.9.9-6198e70ff"
time="2024-05-15T16:54:21Z" level=info msg="Using timeout: 86400 seconds"
time="2024-05-15T16:54:21Z" level=info msg="no pods found yet in namespace: pg1 with label selector: deployments.pds.portworx.com/pod-type=statefulset,role=master,pds/deployment-name=pg-samore-pg-1-vr7lln"
time="2024-05-15T16:54:36Z" level=info msg="no pods found yet in …
```

Added flag to fail cmdexecutor if no pods found

---

pkg/migration/controllers/migrationschedule.go

bug
Remote Migrationschedule static copy will get reconciled with the changes in the source side so that the newly added namespaces can get failed over as part of perform failover.
Kept the reconciling just before the triggering of migration as this is not very frequent operation and better to limit the remote calls to do the comparision.
no
no
yes, 24.2.0
Test:
1. Tested new migrationschedule
2. Old migration schedule getting updated
3. changes in migrationschedule is getting updated.
4. Perform failover for later added namespaces.
Results have …

PWX-37271: Reconciling the remote migration schedule with source side changes.

---

pkg/apis/stork/v1alpha1/applicationbackup.go

These data structure will be used by px-backup reconciler to sync value from CR to mongo object so that it can be used in restore path
>bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
```release-note
Issue:
User Impact:
Resolution
```

pb-6910: Added CR status with job security context setting

---

test/integration_test/migration_dr_actions_test.go

>failing-test
Fixes the following error in the `TestDRActions/testDRActionFailbackSubsetNamespacesTest` test when ran on the jenkins pipeline:
```
Action failback-reverse-failback-migration-schedule-subset-ns-2024-05-20-200910 status fields are: Completed;Failed;Failing the failback operation because the most recent migration, reverse-failback-migration-schedule-subset-ns-interval-2024-05-20-200724, was not completed within the scheduled policy duration;"
```
No
No
Yes, `release-24.2.0` branch.
**Pipeline runs**
- Testsuite run: …

fix: fix resetting the mock time in failback subset namespace test

---

pkg/apis/stork/v1alpha1/applicationbackup.go

- These data structure will be used by px-backup reconciler to sync value from CR to mongo object so that it can be used in restore path
>bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
```release-note
Issue:
User Impact:
Resolution
```

Add psa support in cr status if the application backup CR

---

test/integration_test/kubevirt_hyperconv_test.go

>bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
Ensure that the embedded n.StorageNode pointer is non-nil before dereferencing.
no
no
no

fix a nil pointer dereference error in the tests

---

Dockerfile

bug
Reverted the changes where we were removing unused lib directories in google-cloud-sdk directory after untaring.
no
```release-note
Issue:
User Impact:
Resolution
```
24.2.0
**Test**
https://jenkins.pwx.dev.purestorage.com/job/Stork/job/stork-gke-migration/35/
Also Manually verified by QA.

PWX-37292: Modifying dockerfile to keep /usr/lib files of gcloud sdk.

---

pkg/applicationmanager/controllers/applicationbackup.go

>bug
The reason message during partial success was not showing up, as all the messages were getting overwrriten with the success message as it is outside the loop. Removed that, now the messages shouldn't be overwritten and only the correct message should be displayed.
```release-note
Issue:
User Impact:
Resolution
```
Reason in case of partial success of backup:
Reason in case of success
Reason in case of failure

PB-7021: Fix the reason message being displayed during partial success of backup

---

pkg/utils/utils.go
test/integration_test/common_test.go
test/integration_test/migration_dr_actions_test.go
test/integration_test/migration_features_test.go
test/integration_test/migration_test.go
test/integration_test/operator_test.go
test/integration_test/stork-test-pod.yaml
test/integration_test/storkctl_dr_action_test.go
test/integration_test/test-deploy.sh

The PR adds integration test for the failover workflow in the Sync/Metro DR setup.
No
No
Yes, to `release-24.2.0` branch.
**Test runs**
- Pipeline run: https://jenkins.pwx.dev.purestorage.com/job/Users/job/strivedi/job/strivedi-cluster-domain/3/console
- Local run

pwx-34665 | test: add tests for failover workflow in sync dr

---

pkg/snapshot/controllers/snapshotschedule.go
test/integration_test/snapshot_test.go

>failing test
**What this PR does / why we need it**
In the `startVolumeSnapshot` function, we were fetching the latest copy of the `snapshotschedule` from the CR however in the `handle()` function which actually calls the `startVolumeSnapshot()` function, we were not persisting the updated default `reclaimPolicy` to `Delete` in the CR. Due to this, the `ownerReference` wasn't getting added to the `volumeSnapshot` resource. This PR adds the change to persist the changed default `reclaimPolicy` to the CR as soon as it's updated in the object.
No
No
Yes, `release-24.2.0` branch.
**Test run**
- Sample run from …

pwx-37435 | fix: update the snapshotschedule post adding default reclaim policy

---

pkg/storkctl/actionstatus.go
pkg/storkctl/actionstatus_test.go
pkg/storkctl/common_test.go

>improvement
Closes [PWX-37386](https://purestorage.atlassian.net/browse/PWX-37386). Adds the `--all-namespaces` flag for `get failover` and `get failback` commands in storkctl.
Yes, adds a flag to the `get failover/failback` commands.
No
**Screenshots**

pwx-37386 | chore: get action status for all namespaces

---

test/integration_test/common_test.go
test/integration_test/test-deploy.sh

>bug
>feature
improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
Reduced the duplicate logging. there were 12 log lines repeated. Reduced it to 6. 
https://jenkins.pwx.dev.purestorage.com/job/Stork/job/stork-ocp-kubevirt-4-13/171/consoleFull
Now thees 6 are because `kubectl logs stork-test  -n kube-system -f
for i in $(seq 1 100) ; do
test_status=$(kubectl get pod stork-test -n kube-system -o json | jq ".status.phase" -r)
if [ "$test_status" = "Running" ]; then
echo "Test is still running, status: $test_status"
kubectl logs stork-test  -n kube-system -f
else
sleep 5
break
fi
done` 
**Does this PR change a …

Fixing duplicate logging

---

pkg/applicationmanager/controllers/applicationbackup.go

>bug
Earlier when there were only non-PVC resources were present for the backup we were entering the loop `backup.Status.Volumes) == backup.Status.FailedVolCount` and failing the backup. Now the entry into this loop is changed and backup does not fail if only non-PVC resources are backed up
```release-note
Issue:
User Impact:
Resolution
```
After the fix: As it can be seen in the screenshot, we have taken backup of only non-PVC resources and backup is successful.
Before this PR:

PB-7173: Bug fix - Backup to not fail when there are non-PVC resources to be backed up

---

pkg/storkctl/snapshotschedule.go
pkg/storkctl/snapshotschedule_test.go
pkg/storkctl/storkctl.go
pkg/storkctl/update.go
test/integration_test/Dockerfile
test/integration_test/migration_dr_actions_test.go
test/integration_test/snapshot_test.go
test/integration_test/storkctl_snapshotschedule_test.go

>feature
Adds the `update volumesnapshotschedule` command to `storkctl` to update the PVC name in the specified `volumesnapshotschedule`.
Yes
Would be required to be cherry-picked later once the release branch is finalized.
**Pipeline run**
- `TestStorkCtl` pipeline run: https://jenkins.pwx.dev.purestorage.com/job/Users/job/strivedi/job/storkctl-test/3/
**Test run screenshots**
- Integration test:
- Unit test:

pwx-36876 | feat: add update command to modify volumesnapshotschedule pvc

---

test/integration_test/Dockerfile
test/integration_test/migration_test.go
test/integration_test/test-deploy.sh

>failing-test
Addresses [PWX-37596](https://purestorage.atlassian.net/browse/PWX-37596). Handles the failure of `kubectl log` command inside a retry loop and uses `--since` flag of `kubectl log` command to reduce duplication of logs.
No
No
No

pwx-37596 | fix: add kubectl log command to follow log in case of failure

---

pkg/cache/cache.go
pkg/extender/extender.go
pkg/mock/cache/cache.mock.go
pkg/monitor/monitor.go

>improvement
Reducing the load by not registering for watchers with kube-api-server for pod updates. 
Instead informer cache's event handling has been used.
no
<!--
yes, TBD
```release-note
Issue:
User Impact:
Resolution
```
yes, 24.2.2
**Test**:
```
➜  ~ ks get nodes -o wide
NAME                                   STATUS     ROLES           AGE   VERSION   INTERNAL-IP     EXTERNAL-IP   OS-IMAGE                KERNEL-VERSION                CONTAINER-RUNTIME
ip-10-13-192-122.pwx.purestorage.com   NotReady   <none>          84d   v1.28.0 …
```

PWX-37601: Using informer cache's event handling instead of native k8s watchers for pod monitoring and extender metrics.

---

pkg/snapshot/controllers/snapshotschedule.go

bug
As part of createvolumesnapshot the inmemory copy becomes stale as we a getandupdate and later prune function picks the stale copy. The fix is to avoid that.
no
```release-note
Issue:
User Impact:
Resolution
```
yes, 24.2.3

PWX-37845: Fixing the inmemory volumesnapshotschedule copy with the latest CR copy.

---

pkg/applicationmanager/controllers/applicationbackup.go

>bug
This PR fixes the bug PB-7346 - that is if the backup is in partial success state, then the clean up of backup from backuplocation by calling the `deleteBackup` function does not take place.
```release-note
Issue:
User Impact:
Resolution
```
As it can be seen from the below screenshots, when a backup schedule is set and the data export CR is created then the partial success status of backup remains in partial backup itself and does not move to failed due to `cloud backup missing files` as the clean up using `deleteBackup` does not take place now in case of partial …

PB-7346: Adding status check for partial backup as well for deletion of backup if backup is unsuccessful

---

Makefile

>improvement
Upgrade Go to v1.2.11 to fix https://github.com/advisories/GHSA-49gw-vxvf-fc2g reported in security assessment.
No
No
Yes, 24.2.3 and 24.3.0 branch.

chore: upgrade go to v1.21.11 for cve fix

---

Dockerfile

>security fix
Upgrades `aws-iam-authenticator` and `gcloud-cli` to the latest versions in order to address CVE-2024-24790
No
No
TBD

chore: upgrade aws-authenticator and gcloud-cli to latest version

---

cmd/stork/stork.go
pkg/webhookadmission/utils.go

bug
Creation of mutatingwebhook after each leader election.
CreateWebhookV1 to follow similar strategy of UpdateOrCreate instead of DeleteAndCreate.
no
```release-note
Issue:
User Impact:
Resolution
```
yes, 24.2.4
**Test**
```
➜  stork git:(release-24.2.3) ✗ ks get po -lname=stork -o wide
NAME                     READY   STATUS    RESTARTS   AGE   IP              NODE                                   NOMINATED NODE   READINESS GATES
stork-589dd8d8fc-b9cv5   1/1     Running   0          63s   10.233.80.227   ip-10-13-192-122.pwx.purestorage.com …
```

PWX-38021: Creation of mutatingwebhook after each leader election.

---

pkg/storkctl/clusterpair.go
test/integration_test/common_test.go
test/integration_test/operator_test.go
test/integration_test/storkctl_clusterpair_test.go

>feature
Adds support for NFS location while creating clusterpair for async DR.
Yes, adds support creating clusterpair with NFS in storkctl.
Yes, `release-24.4.0` branch.
**Pipeline run**
https://jenkins.pwx.dev.purestorage.com/job/Users/job/strivedi/job/storkctl-test/43/console

pwx-37485 | feat: add support for nfs backup location in async disaster recovery

---

pkg/snapshotter/snapshotter_csi.go

>bug
```
pb-7563: fixed the error handling in getting snapshot timeout value during kdmp csi restore.
```
no
```release-note
Issue: configmap way of setting the CSI snapshot timeout was broken.
User Impact: user were not able to change the default 30m, if the snapshot was taking more time.
Resolution: Fixed to take the value of snapshot timeout from the kdmp-config configmap.
```
23.3.0 branch.

pb-7563: fixed the error handling in getting snapshot timeout value during kdmp csi restore.

---

cmd/stork/stork.go
pkg/webhookadmission/utils.go
pkg/webhookadmission/webhook.go

bug
For cases where stork cmd runs without --driver, skip running CreateMutateWebhookRuntime even if webhook has been enabled. PX-Backup may run with above mode in non-px clusters.
no
no
yes, 24.2.4 and 24.3.0
**Test**:
In non-px cluster stork is running fine
```
[root@ip-10-13-11-25 ~]# kubectl -n kube-system get po -lname=stork
NAME                     READY   STATUS    RESTARTS   AGE
stork-5649dc48d8-r464p   1/1     Running   0          4m59s
stork-5649dc48d8-rwmd7   1/1     Running   0          5m11s
stork-5649dc48d8-vmrnm   1/1     Running …
```

PB-7579: Creation of webhook controller in runtime should be only if stork is running with a driver.

---

test/integration_test/kubevirt_hyperconv_test.go
test/integration_test/kubevirt_test.go
test/integration_test/specs/kubevirt-fedora-multi-disks-wffc-no-ppltr/fedora-multi-disks-wffc.yaml
test/integration_test/specs/kubevirt-fedora-multi-disks-wffc/fedora-multi-disks-wffc.yaml
test/integration_test/specs/kubevirt-fedora-wffc-no-ppltr/fedora-vm-wait-first-consumer.yaml
test/integration_test/specs/kubevirt-fedora-wffc/fedora-vm-wait-first-consumer.yaml
test/integration_test/specs/kubevirt-fedora-with-node-selector/fedora-vm-wait-first-consumer.yaml
test/integration_test/specs/kubevirt-templates/portworx/sc-sharedv4svc-nolock-wffc-no-clone.yaml
test/integration_test/specs/kubevirt-win-22k-wffc-no-ppltr/windows-vm.yaml
test/integration_test/specs/kubevirt-win-22k-wffc/windows-vm.yaml

>bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
Tests had become stale and had started failing.
- remove the test specs that don't conform to our recommended settings e.g. no WFFC
- separate out specs that use populators and the ones that don't
- special handling for the specs that use the populators to get around known issues
- use "copy" instead of "clone" in the specs since clones bypass the PreCreate() call where we do all the KubeVirt-related stuff
- for a single-disk VM, perform one initial live-migration to get VM to a bind-mounted state
- for a multi-disk VM, restart the VM to get …

PWX-37154: stabilize KubeVirt Hyperconvergence tests

---

test/integration_test/applicationbackup_test.go
test/integration_test/common_test.go
test/integration_test/migration_backup_test.go
test/integration_test/migration_dr_actions_test.go
test/integration_test/migration_features_test.go
test/integration_test/migration_stork_failures_test.go
test/integration_test/migration_test.go
test/integration_test/stork-test-pod.yaml
test/integration_test/test-deploy.sh

Modifies the migration tests for NFS based object store provider.
No
No
Yes, `release-24.4.0` branch.
**Pipeline runs**
- `TestMigration/testMigration` : https://jenkins.pwx.dev.purestorage.com/job/Users/job/strivedi/job/bidirectional-migration-clone/9/
- `TestDRActions` : https://jenkins.pwx.dev.purestorage.com/job/Users/job/strivedi/job/bidirectional-migration-clone/11/

pwx-37488 : modify existing migration tests for nfs objectstore provider

---

drivers/volume/portworx/portworx.go
drivers/volume/portworx/portworx_test.go

>bug
In GetPodVolumes while creating volume names list for the enumerateVolumes api call, we have to consider only the pod volumes which has PVC and are not WFFC.
no
yes, TBD
```release-note
Issue:
User Impact:
Resolution
```
yes, 24.2.5
**Test**:
Tested with strong hyperconvergence with annotation `preferLocalNodeOnly` and updated the ticket with the results.

PWX-38345: Put empty string check in volumeName while collecting the volumes for enumerate call in GetPodVolumes.

---

go.mod
go.sum
vendor/github.com/portworx/kdmp/pkg/drivers/nfsbackup/nfsbackup.go
vendor/github.com/portworx/kdmp/pkg/drivers/utils/utils.go
vendor/modules.txt

This fixes the GKE issue with respect to psa security context
bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
**What this PR does / why we need it**: In GKE environment while using its native file store to leverage NFS backup location, the volume is mounted with no write permission for group. Hence backup is failing. Hence this PR fixes the issue by running POD as root instead of non-root user. This will be the case till the time GKE fixes its file store.
```release-note
Issue:
User Impact:
Resolution
```
**Does this change need to be …

pb-7504: vendor kdmp master to stork master

---

go.mod
go.sum
vendor/github.com/portworx/kdmp/pkg/controllers/dataexport/reconcile.go
vendor/github.com/portworx/kdmp/pkg/controllers/resourceexport/reconcile.go
vendor/github.com/portworx/kdmp/pkg/drivers/utils/utils.go
vendor/modules.txt

Vendor kdmp master branch
This change adds support to pause the resource cleanup for specified time if the key is added to the kdmp-config map
```release-note
Issue:
User Impact:
Resolution
```

PB-7645: Vendor kdmp master to stork master

---

cmd/stork/stork.go
drivers/volume/portworx/portworx.go
drivers/volume/volume.go
pkg/webhookadmission/webhook.go

>improvement
Addresses https://purestorage.atlassian.net/browse/PWX-37111. The PR adds a stork argument to bypass the hack we did in order to live migrate a Kubevirt VM when the VM pod is running on a node where the pod’s sharedv4 volume is attached. The solution we implemented was that inside the virt-launcher container, we install our own `.so` file and intercept the `statfs` call made by `libvirtd`. If there is a PX volume underneath the VM disk’s file system, we return `nfs` as the file system type instead of `ext4` regardless of whether it is a bind-mount or nfs-mount.
We are making this change since RedHat is working on adding support for sharedv4 filesystems in libvirtd through the patch: …

pwx-37111: add stork argument to disable preloading statfs

---

test/integration_test/common_test.go
test/integration_test/dataexport_rsync_test.go

Attempts to fix the flakiness in `dataExportTest` CBT by waiting for one minute to get the volume id from the PVC. It was failing since in some of the test runs blank value of volume id was getting returned.

PWX-38560: add wait for fetching destination volume id in dataExportTest CBT

---

test/integration_test/common_test.go
test/integration_test/migration_dr_actions_test.go
test/integration_test/stork-test-pod.yaml
test/integration_test/test-deploy.sh

Addresses [PWX-38446](https://purestorage.atlassian.net/browse/PWX-38446). Validates the clusterdomain status for source and destination clusters post failback/failover in metro DR.
No
No
**Sample test run result**

pwx-38446: validate clusterdomain status in metro dr tests

---

test/integration_test/applicationbackup_test.go

>failing-test
Skips the NFS location in `applicationbackuprestore` test.
No
No
No

pwx-38616: skip nfs backuplocation while running applicationbackup test

---

Dockerfile

> security-fix
Upgrades gcloud-sdk version to `489.0.0` to fix gcloud-crc32 binary vulnerability. Sample run on my private image: https://aetos.pwx.purestorage.com/security/Stork/24-3-0/2024-08-26-13-07-11-855359
No
Yes
Yes, `24.3.0`.

pwx-38748: upgrade gcloud-sdk version to fix crc32 vuln

---

pkg/applicationmanager/controllers/applicationbackup.go

>bug
```
1) We we exit the reconciler cycle after determining the largeResource status and updating the largeResource flag in the applicationBackup CR.
2) When the control re-enter again, we again fetch all the resources with GetResources and proceed with the upload resource step.
3) In the case of large resource, it doubles up the backup completion time.
```
no.
```release-note
Issue: In the case of large resource, the resources fetched twice, which increase the backup completion time.
User Impact: Large resource Backup takes longer time.
Resolution: Avoid the double …
```

pb-7944: In the backupResources(), not returning  the reconciler cycle, after checking and updating the largeResource flag in the backup CR.

---

pkg/applicationmanager/controllers/applicationbackup.go
pkg/utils/utils.go

>improvement
If the largeResourceLimit is not hit but etcd server limit was hit we were not updating the ABCR and hence we kept backup in progress state forever. This PR identifies this error and fails out early and points customer towards to docs to configure large resource params
No
No
pxb-2.8.0
**Testing**
rather than getting stuck in loop forever we error as soon as we see a large resource error. Same can be verified via logs where earlier we kept on reconciling noe we exit from the loop 
**Earlier logs**
`time="2024-08-01T11:20:48Z" level=debug msg="Monitoring storage …

PB-7778 ::  Fail fast if large resource limit is breached for any component

---

Makefile
pkg/cache/cache.go
pkg/mock/cache/cache.mock.go
pkg/monitor/monitor.go
pkg/monitor/monitor_test.go

improvement
1. Filtering pods wrt node instead of getting all pods to work on and looping on those to filter out the pods running in offline node.
2. Batch delete of pods in a batch of 5.
3. Do a fresh check of node status before issuing batch delete.
4. Indexing spec.nodeName in informercache to filter out pods running on a node.
no
TBD
```release-note
Issue:
User Impact:
Resolution
```
no
**Test**:
UTs - 2 tests from current UT are failing as these need proper mocking of driver.InspectNode() . Will push the fix.
Manual test : 
pods running a node 
```
➜  stork …
```

Stork Health monitor improvements

---

drivers/volume/aws/aws.go
drivers/volume/azure/azure.go
drivers/volume/csi/csi.go
drivers/volume/gcp/gcp.go
drivers/volume/kdmp/kdmp.go
drivers/volume/mock/volume/driver.mock.go
drivers/volume/portworx/portworx.go
drivers/volume/volume.go
pkg/applicationmanager/controllers/applicationbackup.go

>improvement
**What this PR does / why we need it**: This PR contains the changes for performing the volume status retrieval in batches . Avoids timeout issue caused in px-backup in case of backups dealing with large number of volumes (in scale)
No
testing :

PB-7578: perform the volume status retrieval in batches

---

pkg/cache/cache.go
pkg/extender/extender.go
pkg/extender/extender_test.go
pkg/mock/cache/cache.mock.go
pkg/monitor/monitor.go
pkg/webhookadmission/webhook.go

improvement
Now informercache will keep the trimmed PVC information.
This will be useful to enhance performance in webhook, extender and monitor.
no
```release-note
Issue:
User Impact:
Resolution
```
**Test**
1. Tested with 100 pod deployments with webhook enabled and those using one RWO px volume.
2. Took down px in 3 nodes in a 9 node cluster to check if drivermonitor is working fine.
Integration test - https://jenkins.pwx.dev.purestorage.com/job/Users/job/strivedi/job/strivedi-extender/2/

PWX-37036: GetPersistentVolumeClaim needs to use cache in extender, webhook and monitor calls.

---

cmd/stork/stork.go

improvement
Closes [PWX-38383](https://purestorage.atlassian.net/browse/PWX-38383). Adds the `--controller-cache-sync-timeout` flag in stork for the user to tweak the value of cache sync timeout(default: 2 mins) of controllers according to the scale of operations in their cluster. Link to discussion as to why they kept 2 minutes as default: https://github.com/kubernetes-sigs/controller-runtime/pull/1247#discussion_r518110283.
Yes
Yes
No, directly being merged to release branch.

pwx-38383: make the controller cache sync timeout configurable

---

Makefile
pkg/monitor/monitor.go
pkg/monitor/monitor_test.go

improvement
Instead of evicting pods from all nodes where storage is offline, rate limiting the number of nodes from which pods need to evicted in parallel.
no
no
yes, 24.3.1
**Test**:
Tested manually in a 9 node cluster and with nodeBatchSizeForPodDeletion 2 and made the storage offline in 3 nodes.
Will add the UT.

PWX-38511: Ratelimiting the number of offline nodes from which pods need to be evicted.

---

go.mod
go.sum
vendor/github.com/portworx/kdmp/pkg/controllers/dataexport/reconcile.go
vendor/modules.txt

>bug
```
pb-7868: vendor lastest kdmp repo from master branch
```
no
```release-note
Issue: KDMP restore with nfs backuplocation of V4 fails.
User Impact: KDMP backup taken to the NFS v4 backuplocation is not usable.
Resolution: Pass mount option of V4 to fix the issue.
```
No

pb-7868: vendor lastest kdmp repo from master branch

---

test/integration_test/common_test.go
test/integration_test/snapshot_test.go

Closes [PWX-38744](https://purestorage.atlassian.net/browse/PWX-38744). Adds integration tests for the cleanup of snapshots in `Error` state.
No
No
No
**Test run screenshot and pipeline run**
Jenkins run: https://jenkins.pwx.dev.purestorage.com/job/Stork/view/Stork%2024.3.1-dev/job/snapshot-csi-k8s-1-25/2614/

pwx-38744 | test: add tests for errored snapshot cleanup

---

test/integration_test/common_test.go
test/integration_test/snapshot_test.go

Closes [PWX-38944](https://purestorage.atlassian.net/browse/PWX-38944). Tests snapshot creation with increased value of controller cache sync timeout.
**Test run screenshots**
Jenkins pipeline run: https://jenkins.pwx.dev.purestorage.com/job/Stork/view/Stork%2024.3.1-dev/job/snapshot-k8s-1-25-0/1781/

pwx-38944: test snapshot creation with increased controller cache sync timeout

---

drivers/volume/aws/aws.go

improvement
In some of the clusters we are seeing stork binary takes time to load the import modules and do their inits (like aws sdk go's Session creation). Till this gets root caused, adding an environment variable "SKIP_AWS_DRIVER_INIT" if set will skip the aws driver init.
Note: This should not be used with px-backup.
no
yes, 
```release-note
We can use SKIP_AWS_DRIVER_INIT="true" as environment variable to stork pod if stork init gets hung for a long time.
```
yes, 24.3.1, 24.3.2 and 24.3.3
**Test**:
```
➜  stork git:(PWX-39128) ✗ ks exec -it …
```

PWX-39128: Support env variable SKIP_AWS_DRIVER_INIT to skip the aws driver init in stork.

---

pkg/objectstore/s3/s3.go

Adding appropriate error check for IBM COS in case the bucket is unlocked
bug
Adds appropriate error check for IBM COS in case the bucket is unlocked
https://purestorage.atlassian.net/browse/PB-8360
**Does this PR change a user-facing CRD or CLI?**:no
**Is a release note needed?**:no
```release-note
Issue:
User Impact:
Resolution
```
**Does this change need to be cherry-picked to a release branch?**:yes, release-24.3.2, 24.3.3

PB-8360: Adding appropriate error check for IBM COS in case the bucket is unlocked

---

pkg/pvcwatcher/pvcwatcher.go
pkg/storkctl/snapshotschedule.go
test/integration_test/dataexport_rsync_test.go
test/integration_test/snapshot_restore_test.go
test/integration_test/snapshot_test.go
test/integration_test/stork-test-pod.yaml
test/integration_test/test-deploy.sh

bug
Adds the authentication related annotations in stork volumesnapshots in order to fix volume snapshotting in auth clusters.
No
No
Yes, `24.4.0` branch.
**Test run**
https://jenkins.pwx.dev.purestorage.com/job/Users/job/strivedi/job/snapshot-auth-cluster/22/
https://jenkins.pwx.dev.purestorage.com/job/Users/job/strivedi/job/snapshot-auth-cluster/17/

pwx-22735: add auth annotations in volumesnapshot

---

test/integration_test/kubevirt_hyperconv_test.go

>bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
failing-test
>unit-test
kubeVirtUpdatePXBlocked test stops the VM 2 minutes after detecting the expected failed migration. I am guessing that this 2 minutes window is sometimes too short for the operator to generate a FailedToEvict event causing intermittent failure with "Did not find FailedToEvictVM event" error.
Increase the interval to 5 minutes.
no
no
no

fix an intermittent test failure in kubeVirtUpdatePXBlocked test

---

pkg/action/drutils.go
pkg/action/drutils_test.go
pkg/resourcecollector/job.go
pkg/resourcecollector/resourcecollector.go
test/integration_test/migration_dr_actions_test.go
test/integration_test/migration_test.go
test/integration_test/specs/busybox-job/job.yaml
test/integration_test/specs/fio-job/job.yaml
test/integration_test/specs/fio-job/pvc.yaml
test/integration_test/specs/job-migration-template/migration.yaml

bug
Addresses [PWX-38924](https://purestorage.atlassian.net/browse/PWX-38924) and [PWX-38925](https://purestorage.atlassian.net/browse/PWX-38925).
- Resolves the job migration error:
```
batch/v1, Kind=Job ns32/fio-date: Error applying resource: Job.batch "fio-date" is invalid: [spec.template.metadata.labels[batch.kubernetes.io/controller-uid]: Invalid value: map[string]string{"batch.kubernetes.io/controller-uid":"50366a61-7049-4128-a5cb-20a56d364e04", "batch.kubernetes.io/job-name":"fio-date", "controller-uid":"310f3075-8bbd-4212-a5ea-e78b01da2e8f", "job-name":"fio-date"}: must be '310f3075-8bbd-4212-a5ea-e78b01da2e8f', spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"batch.kubernetes.io/cont …
```

PWX-38924, 38925: fixes for job resource migration and failover timeout

---

drivers/volume/portworx/portworx.go

bug
**What this PR does / why we need it**: https://purestorage.atlassian.net/browse/PB-8394
```release-note
Issue:
User Impact:
Resolution
```
**Does this change need to be cherry-picked to a release branch?**: yes, release-24.3.3
**Error**
**After fix**
volume of all the small backups in successful state after 2 hrs as well

PB-8394: skip status check of the backup if it has already failed or succedeed

---

test/integration_test/applicationbackup_test.go

Comments out the `TestApplicationBackup/preExecRuleTest` since it is flaky and has been failing consistently across jobs. Corresponding ticket to fix it: https://purestorage.atlassian.net/browse/PB-7097

test: comment out preExecRuleTest since it is flaky

---

drivers/volume/mock/mock.go
drivers/volume/portworx/portworx.go
drivers/volume/volume.go
pkg/extender/extender.go
pkg/extender/extender_test.go
pkg/monitor/monitor.go
pkg/monitor/monitor_test.go

bug
unit-test
1. DirectAccessVolumes need not to be considered while prioritizing nodes during scheduling.
2. Also if px becomes offline, the pods using only FADA volumes need not be deleted as part of health monitoring.
no
```release-note
Issue:
User Impact:
Resolution
```
yes, 24.4.0
Tests:
1. Wrt scheduling
```
1. The event like "time="2024-04-24T16:07:22Z" level=warning msg="Unable to schedule pod using volumes [pvc-86da355f-f0cc-4a94-8245-97d3ac46ccbc] in a hyperconverged …
```

PWX-37027: DirectAccessVolumes need not to be considered while prioritizing nodes during scheduling.

---

drivers/volume/csi/csi.go
pkg/applicationmanager/controllers/applicationbackup.go
pkg/snapshotter/snapshotter_csi.go

- Removing nil check of restore size as per external-snapshotter defaults to nil
- Getting object before removal of finalizer and updation
- Passing snapshot.jsnon restorSize as annotaion in VS
- If created VS.status.RestoreSize is nil then compare with annotaion to handle PB-3966
>bug
This PR caters recent change in the external snapshotter v4.0.0 and above, the default value of restore size in the volumesnapshot size is set to nil rather than 0. This change was causing our previous calls to fail. To address this, I have removed the nil check, once we create VS and VSC from downloaded object the status.RestoreSize is coming as nil for few CSI. We are passing restoreSize as annotation if created VS.status.RestoreSize is …

PB-8482 :: Handling pre-provisioned VSC restore

---

pkg/applicationmanager/controllers/applicationbackup.go

bug : https://purestorage.atlassian.net/browse/PB-8690
**What this PR does / why we need it**: As part batch processing the volume status , backupId is checked for all the volume drivers instead of pxd which causes the reconciler not to proceed further .This PR fixes by having the logic to process only for pxd volumes
Yes, needs to be cherry picked to 24.3.3 release

PB-8690: check backupId only for pxd volumes for the initial get backup status
