.travis.yml
drivers/volume/mock/mock.go
pkg/extender/extender.go
pkg/extender/extender_test.go
pkg/k8sutils/k8sutils.go

Unit tests

---

drivers/volume/mock/mock.go
drivers/volume/portworx/portworx.go
drivers/volume/volume.go

Convert hostname to lower case to match kubernetes hostnames

---

Dockerfile

Move the container to be based on atmoic

---

pkg/extender/extender.go
pkg/extender/extender_test.go

Check for short hostnames in extender by checking prefix

---

pkg/extender/extender.go
pkg/extender/extender_test.go

Also check for short hostnames in filter request

---

README.md
specs/stork-daemonset.yaml

Add instructions to use stork with default scheduler

---

drivers/volume/portworx/portworx.go

Portworx driver: Check other sources for provisioner

---

pkg/snapshot/snapshotprovisioner.go

The original PV could have been deleted.
Issue #57

Don't check source PV when restoring from snapshot

---

drivers/volume/portworx/portworx.go

Check PVC first for provisioner

---

drivers/volume/portworx/portworx.go
test/integration_test/snapshot_test.go
vendor/github.com/portworx/torpedo/drivers/scheduler/k8s/k8s.go

Also add snapshot name and namespace as labels when creating the
snapshot
Issue #67

Portworx: Use snapshot UID for snapshot name to make it unique

---

test/integration_test/snapshot_test.go

verify scheduled node only for mysql-data-1

---

test/integration_test/snapshot_test.go

Fix cloudsnap integration to check only data volumes in use

---

drivers/volume/portworx/portworx.go

For group snapshots, include UUID of parent volumesnapshot in child volumesnapshots

---

vendor/github.com/kubernetes-incubator/external-storage/snapshot/pkg/controller/snapshotter/snapshotter.go
vendor/vendor.json

Update vendor to allow error status conditions in failed volumesnapshots

---

pkg/extender/extender.go
pkg/extender/extender_test.go

If no driver nodes found in filter request return error

---

Dockerfile
cmd/stork/stork.go
pkg/monitor/monitor.go

Default is 120 seconds and minimum is 30 seconds
Also update version for upcoming release
Closes #91

Make the health-monitor interval configurable

---

drivers/volume/portworx/portworx.go
test/integration_test/specs/mysql-snap-group/group-snapshot.yaml

update group snapshot annotation keys

---

drivers/volume/portworx/portworx.go

Fixes #82
Example output when one attempts to create group snapshot on 1.2
```
kubectl describe volumesnapshot
Name:         mysql-snapshot
Namespace:    default
Labels:       SnapshotMetadata-PVName=pvc-b707813c-5ee3-11e8-8cb9-080027ee1df7
SnapshotMetadata-Timestamp=1527119320930117146
Annotations:  kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"volumesnapshot.external-storage.k8s.io/v1","kind":"VolumeSnapshot","metadata":{"annotations":{"portworx.selector/tier":"prod","portworx....
portworx.selector/tier=prod
portworx.selector/type=db
portworx/snapshot-type=local
API Version:  volumesnapshot.external-storage.k8s.io/v1
Kind:         VolumeSnapshot
Metadata:
Cluster Name:
Creation Timestamp:  2018-05-23T23:48:32Z
Generation:          0
Resource Version:    6084733
Self …
```

Ensure version check for group and cloud snapshot

---

test/integration_test/snapshot_test.go

retry inspect volumes for group snapshots

---

vendor/github.com/portworx/sched-ops/k8s/k8s.go
vendor/vendor.json

Update vendor to pull in sched-ops fix for validating snaps

---

drivers/volume/portworx/portworx.go

It's unnecessary and parent pv can always be deleted after a snapshot is taken.
Fixes #106 

don't enforce pv reference for describe of local snapshots

---

Makefile
cmd/stork/stork.go
drivers/volume/portworx/portworx.go
pkg/extender/extender.go

Also fix issues found by gosimple

Add gosimple checker

---

.gitignore
Dockerfile.cmdexecutor
Makefile
cmd/cmdexecutor/cmdexecutor.go
cmd/cmdexecutor/specs/cmdexecutor.yaml
help-cmdexecutor.md
pkg/cmdexecutor/cmdexecutor.go
pkg/version/version.go
test/integration_test/cmdexecutor_test.go
test/integration_test/common_test.go
test/integration_test/specs/mysql-no-persistence/mysql.yaml

Add an executor CLI for running async commands in pods

---

.travis.yml
drivers/volume/mock/mock.go
pkg/extender/extender.go
pkg/extender/extender_test.go

Extender: Also check node name to match driver nodes

---

test/integration_test/snapshot_test.go

The tests now explictly use the get snapshots call and also verify the volumesnapshot data

fix integration tests

---

pkg/snapshot/rule/rule.go
test/integration_test/specs/mysql-3d-snap/px-presnap-rule.yaml
test/integration_test/specs/mysql-failing-3d-snap/px-presnap-failing-rule.yaml
test/integration_test/specs/mysql-failing-3d-snap/px-presnap-unsupported-rule.yaml

overide default cmdexecutor for tests

---

Makefile
cmd/stork/stork.go
drivers/volume/mock/mock.go
drivers/volume/portworx/portworx.go
drivers/volume/volume.go
pkg/controller/controller.go
pkg/errors/errors.go
pkg/migration/controllers/clusterpair.go
pkg/migration/controllers/migration.go
pkg/migration/migration.go
vendor/github.com/portworx/sched-ops/k8s/k8s.go
vendor/vendor.json

Add controllers for pairing and migration

---

README.md
doc/snaps-3d.md
doc/snaps.md

Fixes #147
Also adds docs for snapshots across namespaces

Add docs for 3d snaps

---

drivers/volume/portworx/portworx.go
test/integration_test/specs/mysql-snap-group-a/mysql.yaml

Group snapshot should wait till all PVCs are bound

---

Dockerfile

Also use alpine instead to atomic and remove things added for
rhel registry

Add aws authenticator binary to the container

---

Makefile
pkg/extender/extender_test.go

Also exit with error in Makefile if unittest fails

Fix extender unittest

---

pkg/snapshot/controller.go

Leader election already happens in stork

Disable leader election for snapshot controller

---

pkg/storkctl/factory.go

This is needed to facilitate tests.

Add SetOutputFormat() to Factory interface

---

test/integration_test/specs/mysql-1-pvc/mysql.yaml

Signed-off-by: Ram Suradkar <ram.suradkar@portworx.com>

Add liveliness and readiness probe to mysql-1-pvc spec

---

cmd/stork/stork.go
pkg/migration/controllers/migration.go
pkg/migration/migration.go
pkg/rule/rule.go

Also add rule CRD register which was removed in code refactor

 Allow configuring an admin namespace that can migrate all other namespaces

---

test/integration_test/common_test.go
test/integration_test/specs/migration/migration.yaml

Jenkins job is still running on it, added it to get review till then

Add namespace to clusterpair and migration specs

---

test/integration_test/migration_test.go

Signed-off-by: Ram Suradkar <ram.suradkar@portworx.com>

Create mysql app before scheduling clusterpair

---

drivers/volume/portworx/portworx.go

Fix version regex in Portworx driver

---

pkg/groupsnapshot/controllers/groupsnapshot.go

validate pre and post checks in initial stage

---

pkg/rule/rule.go

check for nil annotations on rule

---

drivers/volume/portworx/portworx.go
pkg/groupsnapshot/controllers/groupsnapshot.go

Fix ready and pending snapshot conditions

---

pkg/groupsnapshot/controllers/groupsnapshot.go

The string compare check was incorrect previously causing the error
```
time="2019-02-15T05:00:58Z" level=info msg="Already processed groupSnapshot version (9674) higher than: 10008. Skipping event." 
```

Use version pkg to compare resource versions

---

test/integration_test/snapshot_test.go

For groupsnap scale test, first create all and then verify

---

test/integration_test/snapshot_test.go

In scale test, the setups being used for integration tests cannot handle that many fio pods.
Also added the context/namespace in some of the common points where the test fail. It helps in triaging to hunt down the namespace where the test failed.

Don't run fio load specs for scale test

---

drivers/volume/portworx/portworx.go
pkg/apis/stork/v1alpha1/clusterpair.go
pkg/apis/stork/v1alpha1/migration.go
pkg/migration/controllers/clusterpair.go
pkg/migration/controllers/migration.go
pkg/storkctl/activate.go
pkg/storkctl/deactivate.go
pkg/storkctl/migration.go
pkg/storkctl/migration_test.go
pkg/storkctl/storkctl.go

Also added subcommands to activate and deactivate migrated applications

Add option to skip pairing of storage in ClusterPair

---

drivers/volume/portworx/portworx.go

For statically created PVCs there might not be a storage class or annotations
with the provisioner. Looks at the volume source in that case to figure out
the owner
Bug
To check for PVC ownership the Portworx volume driver queries the storage class to figure out who provisioned the PVC. This causes issues when PVCs are manually bounded or if the storage class is deleted
No
```release-note
[Portworx] Fixed checked for ownership for statically created PVCs
```
Yes, 2.1

[Portworx] Don't rely on storage class to determine ownersip of PVC

---

Gopkg.lock
test/integration_test/extender_test.go
test/integration_test/specs/mysql-repl-1/mysql.yaml
vendor/github.com/portworx/torpedo/drivers/volume/portworx/portworx.go
vendor/github.com/portworx/torpedo/drivers/volume/portworx/schedops/dcos-schedops.go
vendor/github.com/portworx/torpedo/drivers/volume/portworx/schedops/k8s-schedops.go
vendor/github.com/portworx/torpedo/drivers/volume/portworx/schedops/schedops.go

We need this PR to automate integration test for this issue:
https://github.com/libopenstorage/stork/issues/291
No
No
```
No

New test for verify pvc ownership fix.

---

pkg/snapshot/snapshot.go

Bug
Snapshot controller needs to be started first so that it can register the CRD
No
No
No

 Start snapshot controller first

---

Gopkg.lock
Gopkg.toml
vendor/github.com/portworx/torpedo/drivers/volume/portworx/portworx.go
vendor/github.com/portworx/torpedo/drivers/volume/portworx/schedops/dcos-schedops.go
vendor/github.com/portworx/torpedo/drivers/volume/portworx/schedops/k8s-schedops.go
vendor/github.com/portworx/torpedo/drivers/volume/portworx/schedops/schedops.go

Use stork-2.1 branch
Vendor update
Fix from torpedo for node down
No
No
No

Update vendor for torpedo

---

drivers/volume/portworx/portworx.go

Signed-off-by: Aditya Dani <aditya@portworx.com>
>bug
- Get the service name and namespace from env variables.
- Find the ports which PX uses from kubernetes service.
No
```release-note
- Portworx's service name and namespace are configurable through environment variables to stork.
- Added support for Stork to work with Portworx running on custom ports configuration.
```
No

Allow configuring portworx service in stork

---

Makefile

Update version to 2.1.1

---

pkg/pvcwatcher/pvcwatcher.go
specs/stork-deployment.yaml

Spec update
The stork clusterrole was missing permissions for volumesnapshotschedules causing the controller to throw an error
No
No
No

Add missing permissions for volumesnapshot schedules

---

pkg/schedule/schedule.go
pkg/schedule/schedule_test.go

Bug
Added validation for interval policy before using the policy
No
No
No

Add validation for interval policy

---

pkg/pvcwatcher/pvcwatcher.go

This prevents the schedules from getting re-created if a user manually deletes
them
Bug
Prevents snapshot schedules from being re-created if a user deletes them
No
No
No

Add annotation in PVC after creating snapshot schedule through SC

---

specs/stork-deployment.yaml

Permission update
Health monitor does a watch on pods, we need to update the permissions for stork
No
No
No

Add pod watch permission required for health monitor

---

pkg/apis/stork/v1alpha1/clusterdomainsstatus.go
pkg/apis/stork/v1alpha1/clusterdomainupdate.go
pkg/client/clientset/versioned/typed/stork/v1alpha1/clusterdomainsstatus.go
pkg/client/clientset/versioned/typed/stork/v1alpha1/clusterdomainupdate.go
pkg/client/clientset/versioned/typed/stork/v1alpha1/fake/fake_clusterdomainsstatus.go
pkg/client/clientset/versioned/typed/stork/v1alpha1/fake/fake_clusterdomainupdate.go
pkg/client/clientset/versioned/typed/stork/v1alpha1/fake/fake_stork_client.go
pkg/client/clientset/versioned/typed/stork/v1alpha1/stork_client.go
pkg/client/informers/externalversions/stork/v1alpha1/clusterdomainsstatus.go
pkg/client/informers/externalversions/stork/v1alpha1/clusterdomainupdate.go
pkg/client/informers/externalversions/stork/v1alpha1/interface.go
pkg/client/listers/stork/v1alpha1/clusterdomainsstatus.go
pkg/client/listers/stork/v1alpha1/clusterdomainupdate.go
pkg/client/listers/stork/v1alpha1/expansion_generated.go

>feature
- Make ClusterDomain CRDs cluster scoped
- Update the generated code
Yes
No
No

Make ClusterDomain CRDs cluster scoped

---

Gopkg.lock
Gopkg.toml
vendor/github.com/portworx/torpedo/drivers/scheduler/k8s/k8s.go
vendor/github.com/portworx/torpedo/drivers/volume/portworx/portworx.go
vendor/github.com/portworx/torpedo/drivers/volume/portworx/schedops/k8s-schedops.go
vendor/github.com/portworx/torpedo/drivers/volume/portworx/schedops/schedops.go
vendor/github.com/portworx/torpedo/drivers/volume/volume.go

>bug
Update torpedo deps to the branch stork-2.2 in torpedo.
No
No
No

Add constraint on torpedo to branch stork-2.2

---

Makefile

Update version to 2.1.2

---

Gopkg.lock
Gopkg.toml
drivers/volume/portworx/portworx.go
pkg/snapshot/controllers/snapshotschedule.go
vendor/github.com/kubernetes-incubator/external-storage/snapshot/pkg/apis/crd/v1/types.go

Bug
Improvement
Helps track snapshots that were created through schedules. Drivers can use that information when creating snapshots
No
No
Partly. The following commits needs to be cherry-picked to 2.1
```
Vendor update for snapshot from external-storage
[Portworx] Fix cloudsnap status check
```

Add labels to scheduled snapshot descrbing the schedule

---

specs/stork-deployment.yaml

Add permissions for clusterdomain CRDs

---

Gopkg.lock
pkg/snapshot/controllers/snapshotschedule.go
test/integration_test/snapshot_test.go
vendor/github.com/portworx/sched-ops/k8s/k8s.go

Integration tests for snapshot schedules

---

specs/stork-deployment.yaml

Fix name in permission for cluster domain status object

---

drivers/volume/portworx/portworx.go
pkg/migration/controllers/clusterpair.go

Bug
No
No
Following commit needs to be cherry-picked
```
[Portworx] Return error if starting migration fails 
```

 [Portworx] Return error if starting migration fails

---

test/integration_test/snapshot_test.go
test/integration_test/specs/snapshot-storageclass/autosnapsched.yaml

Add integration test for snapshotschedule created using storageclass

---

pkg/clusterdomains/controllers/clusterdomainstatus.go

>bug
ClusterDomainsStatus CRD uses clusterID as Name. 
This PR removes any upper case letters or `_` from it so that Kubernetes will allow creating the resource with such a name
No
No
No

Normalize the clusterID before using it as a kubernetes resource name.

---

test/integration_test/snapshot_test.go
test/integration_test/specs/snapshot-storageclass/autosnapsched.yaml

Validate PVC before checking for auto created schedule

---

Gopkg.lock
pkg/clusterdomains/controllers/clusterdomainupdate.go
test/integration_test/clusterdomain_test.go
test/integration_test/common_test.go
test/integration_test/migration_test.go
test/integration_test/specs/mysql-clusterdomain-migration/migration.yaml
vendor/github.com/portworx/sched-ops/k8s/k8s.go

Integration tests for cluster domains
No
No
No

Cluster Domain integration tests

---

.travis.yml

Update travis for 2.2 branch

---

.travis.yml
Makefile

Also revert travis change which was merged to wrong branch
Update version
No
No
No

Bump version to 2.3.0

---

Dockerfile

Cleanup
Removes unrequired files from the container
No
No
2.0, 2.1, 2.2

Remove the test directory from google cloud sdk

---

Makefile

Bump version to 2.2.1

---

.travis.yml

Cleanup
Latest storkctl should be from the latest release
No
No
No

Update storkctl from master branch to master path instead of latest

---

drivers/volume/mock/mock.go
drivers/volume/portworx/portworx.go
drivers/volume/volume.go
pkg/extender/extender.go
test/integration_test/common_test.go

Also update portworx driver to populate both for the nodes
Improvement
No
No
2.2

Update node info to have storageID and schedulerID

---

test/integration_test/Dockerfile
test/integration_test/stork-test-pod.yaml

To generate separate xml files for stork integration tests and make them available on the jenkins host
No
No
2.2

Generate junit report for stork results.

---

test/integration_test/stork-test-pod.yaml

Format the gotestsum output in stork-test
No
No
```release-note
```
2.2, 2.1

Use standard-verbose for gotestsum output.

---

Dockerfile
Makefile

 Update version to 2.2.2

---

test/integration_test/extender_test.go

Use correct spec for extender integration test

---

drivers/volume/portworx/portworx.go

>bug
If stork crashes after invoking the driver to create a snapshot but before returning success back to the snapshot provisioner, then the snapshot is created in the backend. But stork will keep retrying to bind the snapshot and will fail since the snapshot with the same ID already exists.
no
```release-note
Add idempotency to local snapshot calls to handle crashes while a snapshot is being taken.
```
no

[Portworx] Add idempotency for local snapshots

---

cmd/stork/stork.go

Enhancement
No
```release-note
Updated the default admin namespace to `kube-system`
```
No, PR is for 2.2 branch. Already updated in master with a separate change.

Set the default admin namespace to kube-system

---

pkg/storkctl/clusterdomainupdate.go
pkg/storkctl/clusterdomainupdate_test.go

Cherrypick of PR #384 
```release-note
```

(CP)Add wait poll support for storkctl activate clusterdomain

---

Makefile

Bump version to 2.2.3

---

pkg/apis/stork/v1alpha1/applicationbackup.go
pkg/apis/stork/v1alpha1/backuplocation.go
pkg/apis/stork/v1alpha1/zz_generated.deepcopy.go
pkg/applicationmanager/controllers/applicationbackup.go
pkg/applicationmanager/controllers/applicationrestore.go
pkg/crypto/crypto.go
pkg/crypto/crypto_test.go

Update backup and restore controllers to use encryption key

---

drivers/volume/mock/mock.go
drivers/volume/portworx/portworx.go
drivers/volume/volume.go
pkg/apis/stork/v1alpha1/applicationclone.go
pkg/applicationmanager/applicationmanager.go
pkg/applicationmanager/controllers/applicationclone.go
pkg/log/log.go
pkg/log/log_test.go
pkg/resourcecollector/resourcecollector.go
pkg/resourcecollector/service.go

Feature
No
```release-note
Added support to clone applications between namespaces
* ApplicationClone objects are only allowed to be created in the admin namespace
for now
* First the volumes for all the PVC are cloned
* Then the resources are copied from the source to destination namespace
* ClusterRole is not copied since it is a cluster scoped object
* ClusterRoleBinding is merged to have same binding for both namespaces
```
No

Application clone controller

---

Makefile
drivers/volume/portworx/portworx.go
pkg/migration/controllers/migration.go
pkg/migration/controllers/migrationschedule.go
specs/stork-deployment.yaml

Enhancement
No
No
No, separate PR was sent for 2.2 branch

Fail migrations if domain is inactive

---

Gopkg.lock
pkg/apis/stork/v1alpha1/backuplocation.go
pkg/storkctl/applicationbackup.go
pkg/storkctl/applicationbackup_test.go
pkg/storkctl/applicationclone.go
pkg/storkctl/applicationclone_test.go
pkg/storkctl/applicationrestore.go
pkg/storkctl/applicationrestore_test.go
pkg/storkctl/backuplocation.go
pkg/storkctl/backuplocation_test.go
pkg/storkctl/create.go
pkg/storkctl/delete.go
pkg/storkctl/get.go
pkg/storkctl/migration.go
pkg/storkctl/migration_test.go
pkg/storkctl/schedulepolicy.go
vendor/github.com/portworx/sched-ops/k8s/k8s.go

Enhancement
Adds new subcommands to `storkctl`
Include with the feature release notes
No

Storkctl subcommands for applications crds

---

pkg/resourcecollector/resourcecollector.go

Enhancement
No
```release-note
Added support to collect OCP Template objects for migration and backup
```
2.2

Add support to collect Template objects

---

pkg/migration/controllers/migration.go

Bug
No
```release-note
Fixed issue with migrations when annotations were nil on application specs
```
2.2

Create annotations to store migration replicas if it doesn't exist

---

pkg/resourcecollector/resourcecollector.go

Don't skip delete for PV and PVCs when replacing

---

drivers/volume/mock/mock.go
drivers/volume/portworx/portworx.go
drivers/volume/volume.go
pkg/apis/stork/v1alpha1/snapshotrestore.go
pkg/apis/stork/v1alpha1/zz_generated.deepcopy.go
pkg/snapshot/controllers/snapshotrestore.go

>enhancement
Add inlace restore support for Portworx driver cloud snapshot  restore
No

Add inplace restore support for cloudsnapshots

---

cmd/stork/stork.go
pkg/apis/stork/v1alpha1/applicationbackup.go
pkg/apis/stork/v1alpha1/backuplocation.go
pkg/apis/stork/v1alpha1/zz_generated.deepcopy.go
pkg/applicationmanager/applicationmanager.go
pkg/applicationmanager/controllers/applicationbackup.go
pkg/applicationmanager/controllers/applicationrestore.go
pkg/applicationmanager/controllers/backupsync.go
pkg/log/log.go
pkg/log/log_test.go
pkg/resourcecollector/resourcecollector.go
pkg/storkctl/applicationbackup.go
pkg/storkctl/applicationbackup_test.go
test/integration_test/common_test.go

Enhancement
No
```release-note
* Backups will be synced from a BackupLocation if not already present on the cluster
```
No

Add controller to sync backups

---

test/integration_test/stork-test-pod.yaml

Add -t to test2json to add timestamps

---

Gopkg.lock
drivers/volume/portworx/portworx.go
pkg/k8sutils/k8sutils.go
vendor/github.com/kubernetes-incubator/external-storage/snapshot/pkg/apis/crd/v1/types.go

Support for Stork to work with PVs which where created by Portworx CSI Provisioner

Csi PX support

---

pkg/applicationmanager/controllers/applicationclone.go
pkg/applicationmanager/controllers/applicationrestore.go
pkg/extender/extender_test.go
pkg/migration/controllers/migration.go
pkg/storkctl/clusterpair_test.go
test/integration_test/common_test.go

Was causing the latest staticcheck to fail
Cleanup
No
No
2.2

Fix duplicate imports

---

specs/stork-daemonset.yaml
specs/stork-deployment.yaml

Needed for application restore
Permissions update
No
No
No

Update permissions for stork-role

---

Gopkg.lock
Gopkg.toml
pkg/applicationmanager/controllers/applicationclone.go
test/integration_test/applicationclone_test.go
test/integration_test/common_test.go
test/integration_test/snapshot_test.go
test/integration_test/specs/application-clone/appclone.yaml
vendor/github.com/portworx/sched-ops/k8s/k8s.go
vendor/github.com/portworx/torpedo/drivers/node/errors.go
vendor/github.com/portworx/torpedo/drivers/node/node.go
vendor/github.com/portworx/torpedo/drivers/node/node_registry.go
vendor/github.com/portworx/torpedo/drivers/node/ssh/ssh.go
vendor/github.com/portworx/torpedo/drivers/scheduler/errors.go
vendor/github.com/portworx/torpedo/drivers/scheduler/k8s/k8s.go
vendor/github.com/portworx/torpedo/drivers/scheduler/scheduler.go
vendor/github.com/portworx/torpedo/drivers/volume/portworx/errors.go
vendor/github.com/portworx/torpedo/drivers/volume/portworx/portworx.go
vendor/github.com/portworx/torpedo/drivers/volume/portworx/schedops/k8s-schedops.go
vendor/github.com/portworx/torpedo/drivers/volume/portworx/schedops/schedops.go
vendor/github.com/portworx/torpedo/drivers/volume/volume.go

 Add an integration test for application clone

---

Gopkg.toml
test/integration_test/backup_test.go
test/integration_test/common_test.go
test/integration_test/specs/mysql-1-pvc-backup/applicationbackup.yaml
test/integration_test/specs/mysql-restore/applicationrestore.yaml

Integration test for Backup and Restore of Apps
Test Backup and restore with replace policy delete.
No
No
```release-note
```
No
-->

Backup apps vols

---

Gopkg.lock
test/integration_test/common_test.go
test/integration_test/extender_test.go
test/integration_test/health_monitor_test.go
test/integration_test/snapshot_restore_test.go
test/integration_test/specs/mysql-2-pvc/mysql.yaml
test/integration_test/specs/mysql-localsnap-group/group-local-snapshot.yaml
test/integration_test/specs/mysql-snap-inplace-cloud-restore/mysql-snap-inplace-restore.yml
test/integration_test/specs/mysql-snap-inplace-group-restore/mysql-snap-inplace-group-restore.yml
test/integration_test/specs/mysql-snap-inplace-restore/mysql-snap-inplace-restore.yml
vendor/github.com/portworx/torpedo/drivers/node/node.go
vendor/github.com/portworx/torpedo/drivers/scheduler/k8s/k8s.go
vendor/github.com/portworx/torpedo/drivers/scheduler/scheduler.go
vendor/github.com/portworx/torpedo/drivers/volume/portworx/portworx.go
vendor/github.com/portworx/torpedo/drivers/volume/volume.go

Add integration test for inplace snapshot restore
No
```release-note
```

Add VolumeSnapshotInplaceRestore integration tests

---

pkg/applicationmanager/controllers/applicationclone.go
pkg/applicationmanager/controllers/applicationrestore.go
pkg/resourcecollector/resourcecollector.go

This can be used when resources need to be deleted before creating them again.
Deletion needs to be done for all the objects beforehand because there could be
resources that have dependencies on other resources. For example, a PVC can't be
deleted if a pod is using it.
Bug
No
No
No

Add API to resourcecollector package to delete objects

---

test/integration_test/common_test.go
test/integration_test/stork-test-pod.yaml
test/integration_test/test-deploy.sh

Cluster domain test

---

test/integration_test/common_test.go

>bug
Fixes issues where multiple cred creation fails cloud snapshot restore tests

Move snapshotrestore test before migration

---

test/integration_test/test-deploy.sh

Ability to add environment variables to stork deployment through integration test
deploy script.
No
No
No

Add env variables to stork deployment via integration tests.

---

pkg/snapshot/controllers/snapshotrestore.go

>bug
Add check to validate whether given snapshot is complete before performing
in place restore

Validate snapshot before inplace restore

---

pkg/migration/controllers/migration.go

- Role
- RoleBinding
- Ingress
Feature
No
```release-note
Added support to migrate the following additional resource
* Role
* RoleBinding
* Ingress
```
No

Add support to collect some additional resources

---

drivers/volume/portworx/portworx.go

Disable CS inplace restore feature

---

test/integration_test/applicationbackup_test.go
test/integration_test/specs/mysql-1-pvc-post-exec-missing-rule-backup/applicationbackup.yaml
test/integration_test/specs/mysql-1-pvc-post-exec-rule-backup/applicationbackup.yaml
test/integration_test/specs/mysql-1-pvc-post-exec-rule-backup/mysql-post-backup-rule.yaml
test/integration_test/specs/mysql-1-pvc-pre-exec-missing-rule-backup/applicationbackup.yaml
test/integration_test/specs/mysql-1-pvc-pre-exec-rule-backup/applicationbackup.yaml
test/integration_test/specs/mysql-1-pvc-pre-exec-rule-backup/mysql-pre-backup-rule.yaml

test application backup and restore with pre-exec rule.
No
No
No

Pre exec backup

---

test/integration_test/applicationbackup_test.go
test/integration_test/specs/mysql-1-pvc-post-exec-failing-rule-backup/applicationbackup.yaml
test/integration_test/specs/mysql-1-pvc-post-exec-failing-rule-backup/rule.yaml
test/integration_test/specs/mysql-1-pvc-pre-exec-failing-rule-backup/applicationbackup.yaml
test/integration_test/specs/mysql-1-pvc-pre-exec-failing-rule-backup/rule.yaml

Integration test to verify application backup with pre/post failing rules.
no
no
no

Failing rules backup

---

Gopkg.lock
Gopkg.toml
vendor/github.com/portworx/torpedo/drivers/node/node.go
vendor/github.com/portworx/torpedo/drivers/node/node_registry.go
vendor/github.com/portworx/torpedo/drivers/scheduler/k8s/k8s.go
vendor/github.com/portworx/torpedo/drivers/volume/portworx/portworx.go

Fixes test issue when creating rules
No
No
No

Vendor update for torpedo

---

test/integration_test/applicationbackup_test.go
test/integration_test/specs/mysql-1-pvc-label-selector-backup/applicationbackup.yaml
test/integration_test/specs/mysql-1-pvc/mysql.yaml

Test label selectors when backing up applications using stork.
no
no
no

Integration test for label selector.

---

Gopkg.lock
pkg/storkctl/factory.go
pkg/storkctl/migration.go
test/integration_test/common_test.go
test/integration_test/stork-test-pod.yaml
test/integration_test/test-deploy.sh
vendor/github.com/portworx/sched-ops/k8s/k8s.go
vendor/github.com/portworx/torpedo/drivers/node/node.go
vendor/github.com/portworx/torpedo/drivers/node/ssh/ssh.go
vendor/github.com/portworx/torpedo/drivers/scheduler/k8s/k8s.go
vendor/github.com/portworx/torpedo/drivers/volume/portworx/portworx.go
vendor/github.com/portworx/torpedo/drivers/volume/volume.go

Enable integration tests to use configurable provisioner for volumes
no
no
no

Provisioner flag

---

test/integration_test/applicationbackup_test.go
test/integration_test/specs/mysql-1-pvc-backup-sync/applicationbackup.yaml
test/integration_test/specs/mysql-restore-backup-sync/applicationrestore.yaml

https://portworx.atlassian.net/browse/STOR-75
No
No
No

Integration test for backup sync controller.

---

pkg/applicationmanager/controllers/applicationrestore.go

Create namespace mapping map in application restore if not present

---

pkg/migration/controllers/migration.go

Can't set custom types using SetNestedField
Bug
No
No
No

Convert reclaim policy to string before setting in unstructured object

---

test/integration_test/applicationbackup_test.go
test/integration_test/applicationclone_test.go
test/integration_test/clusterdomain_test.go
test/integration_test/cmdexecutor_test.go
test/integration_test/common_test.go
test/integration_test/extender_test.go
test/integration_test/health_monitor_test.go
test/integration_test/migration_test.go
test/integration_test/snapshot_restore_test.go
test/integration_test/snapshot_test.go
test/integration_test/stork-test-pod.yaml
test/integration_test/test-deploy.sh

Ability to run individual tests

Focus test

---

test/integration_test/common_test.go
test/integration_test/migration_test.go
test/integration_test/snapshot_restore_test.go
test/integration_test/snapshot_test.go

Cloudsnaps tests fail if they are run after the migration tests.
no
no
no

Order snapshot migration tests

---

drivers/volume/portworx/portworx.go

Bug
Received error:
```
Error preparing resource: error preparing PV resource pvc-1678c28f-da63-11e9-94db-000c2910432d: .spec.csi accessor error: contains non-string key in the map: map[attached:ATTACH_STATE_INTERNAL_SWITCH state:VOLUME_STATE_DETACHED readonly:false secure:false shared:false sharedv4:false storage.kubernetes.io/csiProvisionerIdentity:1568735171590-8081-pxd.portworx.com error: parent:] is of the type map[string]interface {}, expected string
```
No
No
Not sure, I do not think the CSI support has been released yet.

Fix CSI unstructured object access

---

test/integration_test/clusterdomain_test.go
test/integration_test/migration_test.go
test/integration_test/specs/cassandra-migration-startapps-false/migration.yaml

Add migration test with startapp flag set to false

---

test/integration_test/migration_test.go

The prune for migrations might still be in progress, so add retries
Failing-test
No
No
2.2

Fix race in migration schedule integration test

---

.travis.yml

Update travis for 2.3 branch

---

pkg/applicationmanager/controllers/applicationbackup.go

Cancel and fail backup if starting volume backup fails

---

test/integration_test/applicationbackup_test.go

Backup to Azure, S3 and Google in the backup and restore test.
no
no
no

Multi cloud backup

---

test/integration_test/clusterdomain_test.go

Wait till scale factor reduces to 0 before failover
No
No
No

Cluster domain tests: Wait till scale factor reduces to 0 before failover

---

pkg/migration/controllers/migration.go
pkg/resourcecollector/ingress.go
pkg/resourcecollector/resourcecollector.go
pkg/resourcecollector/role.go
pkg/resourcecollector/secret.go
pkg/resourcecollector/serviceaccount.go

Bug
No
```release-note
Added checks when collecting some resources for migration and backup
* Secrets: Ignore dockre cfg secrets created by ocp
* Ingress: Only collect namespaced scoped objects
* Role/RoleBinding: Ignore autocreated objects starting with "system:"
```
2.3

Resource collector fixes

---

test/integration_test/test-deploy.sh

Fix error with creation of stock-mock-time.

---

Makefile

Bump version to 2.3.1

---

Makefile

Version update

---

Makefile

Bump version on master to 2.4.0

---

Gopkg.lock
vendor/github.com/portworx/torpedo/drivers/scheduler/k8s/k8s.go
vendor/github.com/portworx/torpedo/drivers/scheduler/scheduler.go
vendor/github.com/portworx/torpedo/drivers/volume/portworx/portworx.go
vendor/github.com/portworx/torpedo/drivers/volume/portworx/schedops/k8s-schedops.go
vendor/github.com/portworx/torpedo/drivers/volume/volume.go

https://portworx.atlassian.net/browse/STOR-114
Also need to vendor in https://github.com/portworx/torpedo/pull/362
no
no
no

Add validation of volume snapshot restore.

---

README.md
examples/groupvolumesnapshots/cassandra-e2e/cassandra-ss.yaml
specs/stork-daemonset.yaml

api-change
Update api versions from v1beta to v1 since v1beta will be deprecated
no
no
no

Update API version to v1.

---

Dockerfile
Makefile

Security update
No
```release-note
Update base container and package to fix vulnerabilities detected by CVEs
```
2.3

Update google sdk and some python packages in container

---

test/integration_test/applicationbackup_test.go

**What type of PR is this?**documentation
In backup sync controller test, wait for backup to finish before proceeding with resync.
no

Wait backup completion

---

test/integration_test/test-deploy.sh

Stork integration tests currently fail to tail logs after certain failures.
This change should fix it.
no
no
no

If stork_test is running, tail pod logs.

---

test/integration_test/snapshot_restore_test.go

enable cs inplace restore integration tests

---

test/integration_test/snapshot_restore_test.go
test/integration_test/specs/mysql-cloudsnap-group-restore/group-cloud-snapshot.yaml
test/integration_test/specs/mysql-cloudsnap-group-restore/mysql.yaml
test/integration_test/specs/mysql-groupsnap-inplace-cloud-restore/mysql-groupsnap-inplace-restore.yml
test/integration_test/stork-test-pod.yaml
test/integration_test/test-deploy.sh

New test for *inplace* group cloudsnap restore 
no
no
no

Add test for group cloudsnap restore, flag to skip tests.

---

Gopkg.lock
vendor/github.com/portworx/torpedo/drivers/scheduler/errors.go
vendor/github.com/portworx/torpedo/drivers/scheduler/k8s/k8s.go
vendor/github.com/portworx/torpedo/drivers/scheduler/scheduler.go
vendor/github.com/portworx/torpedo/drivers/volume/portworx/portworx.go
vendor/github.com/portworx/torpedo/drivers/volume/portworx/schedops/k8s-schedops.go

Add vendor updates for groupvolumesnapshots with authenticated clusters
no
no
no

Add vendor updates for auth groupvolumesnapshot.

---

drivers/volume/portworx/portworx.go

- correct error msg for restore failure
- pass only one pool while doing haupdate
- add debugging for correct  poolids
Signed-off-by: Ram <ram.suradkar@portworx.com>
>bug
2.3.0
No
no
2.3.0

fixes for groupcsrestore

---

test/integration_test/snapshot_restore_test.go

Remove call to verifySnapshot for cloudsnap test

---

Gopkg.lock
test/integration_test/common_test.go
test/integration_test/stork-test-pod.yaml
test/integration_test/test-deploy.sh
vendor/github.com/portworx/torpedo/drivers/node/ssh/ssh.go
vendor/github.com/portworx/torpedo/drivers/scheduler/k8s/k8s.go
vendor/github.com/portworx/torpedo/drivers/scheduler/scheduler.go

Need to add volume_driver option in stork_test to 2.3 branch
no
no
no

Parameterize stork volume driver for integration tests.

---

test/integration_test/applicationbackup_test.go

Increase timeout for backup test

---

drivers/volume/portworx/portworx.go
pkg/apis/stork/v1alpha1/snapshotrestore.go
pkg/snapshot/controllers/snapshotrestore.go

Rename stage in VolumeSnapshotRestore

---

drivers/volume/portworx/portworx.go
pkg/clusterdomains/controllers/clusterdomainstatus.go
pkg/migration/controllers/migration.go
pkg/migration/controllers/migrationschedule.go
pkg/storkctl/common.go

>cherry-pick
cherry -pick of PR #527 
no
no
2.3

[portworx] bump px version for in place restore feature

---

Gopkg.lock
cmd/stork/stork.go
pkg/apis/stork/v1alpha1/migration.go
pkg/apis/stork/v1alpha1/zz_generated.deepcopy.go
pkg/applicationmanager/controllers/applicationbackup.go
pkg/applicationmanager/controllers/applicationclone.go
pkg/migration/controllers/migration.go
pkg/resourcecollector/clusterrole.go
pkg/resourcecollector/persistentvolume.go
pkg/resourcecollector/persistentvolumeclaim.go
pkg/resourcecollector/resourcecollector.go
test/integration_test/migration_test.go
test/integration_test/specs/mysql-migration-schedule-interval/migrationschedule.yaml
vendor/github.com/portworx/sched-ops/k8s/k8s.go

> Cherry-pick from master
Cherry-pick of PR #522 
no
no
2.3

Cleanup deleted objects from destination during migration

---

test/integration_test/applicationbackup_test.go
test/integration_test/common_test.go
test/integration_test/stork-test-pod.yaml
test/integration_test/test-deploy.sh

Scaled test for applicationbackups
no
no
no

Scaled integration test for app backup

---

drivers/volume/portworx/portworx.go

bug
Cherry pick of #530 
No
```release-note
NONE
```

Add stork secrets implementation based on lsecrets.Instance()

---

Makefile

Bump the version to 2.3.3

---

test/integration_test/applicationbackup_test.go

Backup sync tests are failing 
no
no
no

Increase wait time for backups to be synced

---

Gopkg.lock
cmd/stork/stork.go
pkg/webhookadmission/utils.go
pkg/webhookadmission/webhook.go
specs/stork-deployment.yaml
specs/stork-webhook.yaml
vendor/github.com/portworx/sched-ops/k8s/k8s.go

>feature
This PR adds mutating Webhook admission controller to stork, which allow stork to update application scheduler name to `stork` if application using volume by drivers supported by stork
No

Mutating Webhook to update application scheduler to stork

---

test/integration_test/applicationbackup_test.go

>bug
>feature
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
```release-note
```

Increase wait time for synced backups to appear on the destination

---

cmd/stork/stork.go

Init the schedule package even if driver isn't specified

---

README.md

[README] typo fix

---

pkg/apis/stork/v1alpha1/applicationbackup.go
pkg/apis/stork/v1alpha1/migration.go
pkg/migration/controllers/migrationschedule.go

Remove unused status types

---

drivers/volume/aws/aws.go
drivers/volume/azure/azure.go
drivers/volume/gcp/gcp.go
drivers/volume/portworx/portworx.go

Change driver init error message to debug

---

drivers/volume/aws/aws.go

Use constants to avoid typos
Bug
No
No
No

Fix duplicate tags being checked for aws driver

---

test/integration_test/test-deploy.sh

Adding changes for replacing full image names in the deploy script
no
no
no

Cherry pick image regex

---

Gopkg.lock
vendor/github.com/portworx/sched-ops/k8s/core/core.go
vendor/github.com/portworx/sched-ops/task/task.go

Fixes issue in integration test while checking for status
Bug
No
No
No

Vendor update for sched-ops

---

test/integration_test/applicationclone_test.go

Cherry-pick scaling down of cassandra 
no
no
no

Scale down cassandra

---

Gopkg.lock
test/integration_test/applicationbackup_test.go
test/integration_test/common_test.go
test/integration_test/specs/cassandra/cassandra.yaml
test/integration_test/specs/cassandra/gce/gke-sc.yaml
test/integration_test/specs/cassandra/portworx/px-sc.yaml
test/integration_test/specs/mysql-1-pvc/gce/gke-sc.yaml
test/integration_test/specs/mysql-1-pvc/mysql.yaml
test/integration_test/specs/mysql-1-pvc/portworx/px-sc.yaml
vendor/github.com/portworx/torpedo/drivers/volume/gce/gce.go

Stork integration tests for application backups will be able to run on the GCE platform
no
no
no

Cloud app backup

---

pkg/resourcecollector/resourcecollector.go

Improvement
No
```release-note
* Added support to collect CronJob for Migration, ApplicationBackup and ApplicationClone
```
2.3

Collect CronJob objects for migration, backup and clones

---

test/integration_test/applicationbackup_test.go

Update applicationbackupschedule test for new retain policy

---

test/integration_test/applicationbackup_test.go

Check for correct number of appplication backups in schedule test

---

test/integration_test/applicationbackup_test.go

Use correct API to delete backups in test

---

Gopkg.lock
test/integration_test/common_test.go
test/integration_test/specs/mysql-1-pvc/aws/aws-sc.yaml
test/integration_test/specs/mysql-1-pvc/azure/azure-sc.yaml
vendor/github.com/portworx/torpedo/drivers/volume/aws/aws.go
vendor/github.com/portworx/torpedo/drivers/volume/azure/azure.go
vendor/github.com/portworx/torpedo/drivers/volume/portworx/portworx.go

Start using azure, aws vol drivers from torpedo in stork tests
no
no
2.3

Vendor torp aks aws driver

---

test/integration_test/applicationbackup_test.go

Use correct type for length of backups in test

---

drivers/volume/portworx/portworx.go

[Portworx] Add progress info for backup and restore to reason

---

Gopkg.lock
Gopkg.toml
hack/update-deprecated-apis.sh
pkg/extender/extender_test.go
pkg/monitor/monitor_test.go
pkg/schedule/schedule_test.go
pkg/storkctl/common_test.go
test/integration_test/applicationbackup_test.go
vendor/github.com/portworx/sched-ops/k8s/core/configmaps.go
vendor/github.com/portworx/sched-ops/k8s/core/core.go
vendor/github.com/portworx/sched-ops/k8s/core/events.go
vendor/github.com/portworx/sched-ops/k8s/core/namespaces.go
vendor/github.com/portworx/sched-ops/k8s/core/nodes.go
vendor/github.com/portworx/sched-ops/k8s/core/persistentvolumeclaims.go
vendor/github.com/portworx/sched-ops/k8s/core/pods.go
vendor/github.com/portworx/sched-ops/k8s/core/secrets.go
vendor/github.com/portworx/sched-ops/k8s/core/serviceaccounts.go
vendor/github.com/portworx/sched-ops/k8s/core/services.go
vendor/github.com/portworx/sched-ops/k8s/stork/applicationbackuprestore.go

Add expected count for app backup schedule tests

---

test/integration_test/applicationbackup_test.go

Test app backup fails if backuplocation object is deleted
no
no
2.3

Integration test to delete backuplocation during app backup

---

test/integration_test/applicationbackup_test.go

Test two application backups taken simultaneously through stork
no
no
2.3

Integration to start app backup when another is in progress

---

pkg/apis/stork/v1alpha1/applicationbackup.go
pkg/apis/stork/v1alpha1/applicationrestore.go
pkg/apis/stork/v1alpha1/zz_generated.deepcopy.go
pkg/applicationmanager/controllers/applicationbackup.go
pkg/applicationmanager/controllers/applicationrestore.go

Yes, adds field in status
No
No

Add last update timestamp to backup and restore specs

---

test/integration_test/common_test.go
test/integration_test/test-deploy.sh

Replace vol driver in stork spec
no
no
2.3

Replace voldriver stork

---

.travis.yml
drivers/volume/portworx/portworx.go
pkg/applicationmanager/controllers/applicationbackupschedule.go
pkg/migration/controllers/clusterpair.go
pkg/migration/controllers/migration.go
pkg/migration/controllers/migrationschedule.go
pkg/resourcecollector/resourcecollector.go

Cherry-picks
No
Release note in PRs
No

Cherry pick for 2.3

---

test/integration_test/applicationbackup_test.go
test/integration_test/common_test.go
test/integration_test/stork-test-pod.yaml
test/integration_test/test-deploy.sh

Backup restore path needs to be configurable
no
no
2.3

Add parameter for path in backup location

---

drivers/volume/portworx/portworx.go
test/integration_test/specs/mysql-cloudsnap-group-restore/mysql.yaml
test/integration_test/specs/mysql-cloudsnap-restore/mysql.yaml

>bug
Fix in-place restore failure for volume which has repl >3
no
no
yes

[portworx] Fix in-place restore failure for repl >2 vols

---

pkg/storkctl/factory.go

Update sched-ops client for all packages

---

pkg/resourcecollector/resourcecollector.go

In case of objects created by operators, might still want to collect some
objects that are only created by the operator once
Feature
No
```release-note
* Added `stork.libopenstorage.org/skip-owner-ref-check` annotation which can be added to any resource created by operators. With the annotation, even if an object has an owner ref, the object will still be collected for Migration, Clone and Backup
* `stork.libopenstorage.org/skipresource` has been deprecated in favor of `stork.libopenstorage.org/skip-resource` and will be removed in a future release
```
2.3

Add annotation to collect objects that have an owner reference

---

test/integration_test/applicationbackup_test.go

Backups need to be deleted before backuplocation objects in sync controller tests
no
no
2.3

Fix backupsync cleanup

---

test/integration_test/clusterdomain_test.go
test/integration_test/common_test.go
test/integration_test/migration_test.go

Test migration to and from clusters
no
no
2.3

Integration test for migration & reverse migration between two clusters

---

pkg/schedule/cache.go

Check if schedule policy exists in cache

---

test/integration_test/applicationbackup_test.go
test/integration_test/common_test.go
test/integration_test/migration_backup_test.go

Integration test for application backup of a migrated app
no
no
2.3

Migration backup

---

drivers/volume/portworx/portworx.go
pkg/applicationmanager/controllers/applicationbackup.go

Misc fixes for app backup

---

drivers/volume/aws/aws.go

[AWS] Add backoff for snapshot API in case rates limit is hit

---

test/integration_test/applicationbackup_test.go
test/integration_test/clusterdomain_test.go
test/integration_test/common_test.go
test/integration_test/migration_backup_test.go
test/integration_test/migration_test.go

Cherry-pick fixes for application backup test and migration-backup test
no
no
no

Integration test for application backup of a migrated app

---

drivers/volume/volume.go
pkg/applicationmanager/controllers/applicationrestore.go
pkg/migration/controllers/migration.go

Bug
No
No
```
During migration cattle specific annotations from the Namespace are removed
```
2.4

Misc fixes

---

drivers/volume/aws/aws.go

[AWS] Retry snaps for internal errors

---

pkg/applicationmanager/controllers/applicationbackup.go
pkg/resourcecollector/persistentvolume.go
pkg/resourcecollector/resourcecollector.go

Skip PV restore if bound to a PVC that shouldn't be restored

---

Gopkg.lock
drivers/volume/portworx/portworx.go
vendor/github.com/libopenstorage/openstorage/cluster/cluster.go
vendor/github.com/libopenstorage/openstorage/pkg/grpcserver/grpcutil.go

>api-change
PX driver has update api for cloudsnap restore. This PR add support for new api changes
no
no
2.4.1

[portworx] API update for CS restore

---

drivers/volume/volume.go
pkg/applicationmanager/controllers/applicationbackup.go

During backup skip PVCs with unsupported drivers

---

Makefile

Update version to 2.3.4

---

test/integration_test/test-deploy.sh

The modified regex allows to run sub-test e.g `TestApplicationBackup/backySyncControllerTest`
no
no
no

Change regex to pick individual focussed test

---

Dockerfile
Makefile

> enhancement
Change docker base image for stork from alpine to UBI-8
no
```release-note
```
yes, 2.4.1

change base docker image to redhat-ubi8

---

drivers/volume/aws/aws.go
drivers/volume/azure/azure.go
drivers/volume/gcp/gcp.go

Enhancement
No
```release-note
Added support to backup PVCs using CSI drivers for AWS, GCP and Azure
```
2.4

Add CSI provisioner name check for gcp, azure and aws

---

pkg/resourcecollector/resourcecollector.go

Fix check for preparing jobs during restore

---

drivers/volume/aws/aws.go

[AWS] Use correct volume id for CSI

---

test/integration_test/test-deploy.sh

`jq` install was failing in the test-deploy script
no
no
2.4

Add apt-get update to deploy script

---

pkg/webhookadmission/webhook.go

>bug
Instead of pod/deploy/statefulset namespace, use admission review request namespace to get volume information
no
no
2.4.2

Use admission review request namespace to get volume info

---

pkg/migration/controllers/migration.go
pkg/resourcecollector/resourcecollector.go
pkg/storkctl/migration.go

Will be used during Migration, ApplicationClone and ApplicationBackup
Enhancement
No
```release-note
Added support to collect Couchbase CRs
```
2.4

Add support to collect couchbase CRs

---

test/integration_test/health_monitor_test.go

Test this fix:  https://github.com/libopenstorage/stork/releases/tag/v2.3.4
no
no
2.4

Integration test to check health check fix

---

pkg/applicationmanager/controllers/applicationbackup.go

bug
In backupVolumes() and backupResources(), removed the CR updates that can lead to "object has be modified error" as two updates happens in the same cycle of reconciler.
no
no
Need to check on this.
**Testing:**
CR content:
```
root@central-branch-howler-0 ~]# kubectl describe applicationbackup
Name:         backup14-4f3e7f8
Namespace:    default
Labels:       <none>
Annotations:  portworx.io/backup-name: backup14
portworx.io/backup-uid: 4f3e7f83-be32-47f0-af5f-e23c85924308
portworx.io/backuplocation-name: backuplocation6
portworx.io/cluster-name: cluster1 …
```

Removed CR updates that leads to "object has be modified error".

---

pkg/applicationmanager/controllers/applicationbackup.go
pkg/applicationmanager/controllers/applicationrestore.go

bug
successfully is misspelled in couple of reason string. Corrected it.
No.
No.
Need to check on it.

corrected the typo in the failure reason.

---

pkg/applicationmanager/controllers/applicationbackup.go

Cherry picked https://github.com/libopenstorage/stork/pull/650 PR to 2.4 branch

[cherry picking to 2.4]: Removed CR updates that leads to "object has be modified error"

---

Makefile

Bump version to 2.4.3

---

pkg/applicationmanager/controllers/applicationrestore.go

Skip downloading CRDs in ApplicationRestore if not uploaded

---

test/integration_test/applicationbackup_test.go

Fix expected backup count for scheduled interval backup tests

---

pkg/snapshot/rule.go

Ignore empty pre and post exec rules

---

test/integration_test/specs/elasticsearch/portworx/sc.yaml
test/integration_test/specs/mysql-2-pvc/portworx/sc.yaml
test/integration_test/specs/mysql-repl-1/linstor/linstor-sc.yaml
test/integration_test/specs/mysql-repl-1/mysql.yaml
test/integration_test/specs/mysql-repl-1/portworx/sc.yaml

Add some missing storage classes in integration tests

---

Gopkg.lock
pkg/applicationmanager/controllers/applicationbackup.go
pkg/applicationmanager/controllers/applicationclone.go
pkg/applicationmanager/controllers/applicationrestore.go
pkg/storkctl/applicationbackup_test.go
pkg/storkctl/applicationbackupschedule_test.go
pkg/storkctl/applicationclone_test.go
pkg/storkctl/applicationrestore_test.go
pkg/storkctl/backuplocation_test.go
pkg/storkctl/clusterpair_test.go
pkg/storkctl/groupsnapshot_test.go
pkg/storkctl/migration_test.go
pkg/storkctl/migrationschedule_test.go
pkg/storkctl/snapshot_test.go
pkg/storkctl/snapshotschedule_test.go
test/integration_test/applicationbackup_test.go
vendor/github.com/portworx/sched-ops/k8s/apps/apps.go
vendor/github.com/portworx/sched-ops/k8s/apps/deployments.go
vendor/github.com/portworx/sched-ops/k8s/apps/replicasets.go
vendor/github.com/portworx/sched-ops/k8s/core/namespaces.go
vendor/github.com/portworx/torpedo/drivers/scheduler/k8s/k8s.go
vendor/github.com/portworx/torpedo/drivers/volume/portworx/portworx.go
vendor/github.com/portworx/torpedo/drivers/volume/portworx/schedops/k8s-schedops.go

> enhancement
- Keep namespace metadata for application backups, restore and clones
no
no
2.4
Note: this has cherry-pick changes from https://github.com/libopenstorage/stork/pull/668 since we went ahead and merged bug fixes earlier

Keep namespace metadata for application backups, restore and clones

---

pkg/resourcecollector/resourcecollector.go

>bug
For older stork version application registration crd will not be present, this will cause issue for middleware while pulling resources
no
no
2.4.3

ignore if appregistration cr is not present on cluster

---

pkg/resourcecollector/resourcecollector.go

cherry pick of https://github.com/libopenstorage/stork/pull/674

[Cherry pick] Added fix to not to wait for the re-created resources in DeleteResources API.

---

test/integration_test/common_test.go

Cherry-pick of unique bucket creation
no
no
no

Create new bucket for stork integration tests

---

drivers/volume/portworx/portworx.go

feature
Adds support for apps issuer: `apps.portworx.io` if px >= 2.6
Otherwise, use old `stork.openstorage.io` 
No
No
Stork release for px 2.6

[Portworx] Add check for PX version check for jwt issuer

---

drivers/volume/portworx/portworx.go

bug
fixes bug where we were expecting PX to be up when stork portworx driver is being initialized. 
No
```release-note
none
```
2.5.x

 [Portworx] Move jwtIssuer to be configurable env var 

---

pkg/resourcecollector/resourcecollector.go

Improvement
No
```release-note
Added support to collect LimitRange for Migration/ApplicationBackup/ApplicationClone
```
No

Add support to collect LimitRange for Migration/ApplicationBackup/Clone

---

LICENSE

>documentation
Update copyright year to 2020 in LICENSE
no
no
no

Update copyright to 2020

---

pkg/applicationmanager/controllers/applicationbackup.go

Bug
Computing total backup size before uploading metadata.json file as part of backup.
No
No
No

Computing total backup size before uploading metadata.json file

---

pkg/apis/stork/v1alpha1/applicationbackup.go

Set Group to core fif empty when creating object map

---

pkg/resourcecollector/resourcecollector.go

Skip types in resource collector for forbidden errors

---

drivers/volume/portworx/portworx.go

Reverts libopenstorage/stork#714

Revert "Add authentication labels to volume"

---

Makefile

cleanup
Change stork version to 2.4.5
No
No
No

Update stork version to 2.4.5

---

pkg/resourcecollector/resourcecollector.go

Check for permission error when processing objects in resource collector

---

drivers/volume/csi/csi.go

bug
Adds additional info to restore info object.
No
No
2.6.0

[CSI] Add restoreInfo for initial restore and during status check

---

pkg/resourcecollector/resourcecollector.go

Fetch ApplicationRegistration only once when preparing resources

---

pkg/dbg/dbg.go

feature
Added log level change step in SIGUSR1 singal handler of dbg pkg. With this changes, we can dynamically change the log level to debug or trace and collect the collect the logs from the customer setup for debugging.
No
No
2.5 
Testing:
Unit tested the changes with the px-backup

Added log level change step in SIGUSR1 singal handler of dbg pkg.

---

drivers/volume/csi/csi.go

bug
- On CSI restore, we used to remove all kubernetes.io annotations
- We must only remove bind-completed and bound-by-controller as there
are other valid kubernetes.io annotations
No
No
No

[CSI] Only remove bind-completed and bound-by-controller annotations

---

drivers/volume/csi/csi.go

bug
Appends backup UID to the end of each snapshot.
This makes it harder for different backups to conflict with each other.
This was spotted because an orphaned Snapshot was not cleaned up (before #739 merged) 
No
No

[CSI] Make VolumeSnapshot objects unique per backup request

---

drivers/volume/csi/csi.go

bug
Fix CSI Backup to correctly cleanup on failures
No
No
No

[CSI] Fix CSI Backup to correctly cleanup on failures

---

drivers/volume/csi/csi.go

bug
* Improves GetBackupStatus to handle cleanup and success states better
* Adds deletion retry if deletion timestamp went away
* Cleanup timeout after 5min from point of deletion 
No
No
No

[CSI] Fix multi-namespace backups

---

drivers/volume/csi/csi.go

[CSI] Make the last part of the backup name unique

---

pkg/applicationmanager/controllers/applicationrestore.go

bug
IncludeResource filtering need to applied before deleting resources for CSI driver case.
No
No
2.6
**Testing:**
Testing on Bhavana's pure setup, where it was reproduced.

Applying IncludeResource filter before deleting resources for CSI driver

---

drivers/volume/csi/csi.go

feature
Adds default volumesnapshotclasses to be created when stork starts up
No
None
2.6

[CSI] Add creation of default VolumeSnapshot classes

---

pkg/applicationmanager/controllers/applicationbackup.go

[Cherry-pick 2.6]: Added retry logic, while updating the ApplicationBackupStageApplications status to CR.

---

test/integration_test/applicationbackup_test.go

Use path from updated backup when checking for deletion

---

pkg/applicationmanager/controllers/applicationbackup.go

bug
Fixed the issue in updating the volume status, when all the volumes are successful.
No
No
yes, To 2.6 branch

Fixed the issue in updating volumeInfo, when all volumes are successful.

---

drivers/volume/portworx/portworx.go

bug
Corrected the error handling, while calling CloudBackupCreate api.
No
no
No
**Testing:**
Currently testing the patch on bhavana's setup. 10 backups went through fine, with out any issue.

stor-338: Corrected the error handling, while calling CloudBackupCreate api.

---

Gopkg.lock
pkg/storkctl/snapshot.go
vendor/github.com/kubernetes-incubator/external-storage/snapshot/pkg/controller/snapshotter/snapshotter.go

Bug
No
```release-note
* Fixed issue with failed snapshots being retried
* Printing correct error state for snapshots
```
2.6

Update vendor for snapshot and print correct status

---

pkg/applicationmanager/controllers/applicationbackup.go

bug
Reduce the backupVolumeBatchCount value to 3 from 10, to avoid timeout failures.
If batch is 10 and if there are more failures in CloudBackupCreate() and retried, the CR is not getting updated with the progress for more than 30 mints. This makes the px-backup to mark the backup with timeout failure.
No
Yes, 2.6 branch.
**Testing:**
Validated that there is not much difference in the time taken to complete the StartBackup for 15 volume, irrespective of whether volumebatch count is 10 or 3.
With volumebatch count of 10:time="2021-02-03T07:11:05Z" level=info msg="sivakumar total time taken for …

Reduce the backupVolumeBatchCount value to 3 from 10, to avoid timeout failure.

---

pkg/metrics/applicationbackup.go
pkg/metrics/applicationbackup_test.go
pkg/metrics/metrics.go
pkg/metrics/migration.go
vendor/github.com/portworx/sched-ops/k8s/stork/applicationbackuprestore.go
vendor/github.com/portworx/sched-ops/k8s/stork/migration.go
vendor/github.com/portworx/sched-ops/k8s/stork/stork.go

>enhancement
add metrics support for backup/migration schedules
no
no
2.6.2

stor-331: add metrics support for backup/migration schedules

---

test/integration_test/migration_test.go
test/integration_test/snapshot_test.go

Cherry-pick from 2.6
https://github.com/libopenstorage/stork/commit/8234becdac1a62953b547bdf9f453c68e3eb2dd3
no
no
no

Add sec annotations to create mig method, check for auth in tests

---

pkg/apis/stork/v1alpha1/applicationbackup.go
pkg/applicationmanager/controllers/applicationbackup.go
pkg/resourcecollector/resourcecollector.go

Signed-off-by: Prashanth Kumar <prkumar@purestorage.com>
Enhancement.
Enhancement to support backing up of only particular resource types.
Yes
None
Yes for 2.6.3

Adding support for fetching resources based on requested resource types

---

pkg/webhookadmission/utils.go
pkg/webhookadmission/webhook.go

>bug
Configure Side-Effects for stork web hook controller 
no
no
2.6.3

configure side-effect parameter for stork webhook

---

pkg/applicationmanager/controllers/applicationregistration.go

>enhancement
User has to manually create appreg entry for newly registered CRD, this PR will add support to watch newly registered CRD and create auto `ApplicationRegistration` resource for same
no
no
2.6.3

Detect newly registered crd and create appreg entry in stork

---

pkg/apis/stork/v1alpha1/applicationbackup.go
pkg/applicationmanager/controllers/applicationbackup.go
pkg/resourcecollector/resourcecollector.go

[Cherry pick: 2.6]  Adding support for fetching resources based on requested resource types

---

test/integration_test/common_test.go
test/integration_test/migration_test.go

Integration test for clusterpair failures
no
no
2.6

Clusterpair failures

---

test/integration_test/common_test.go
test/integration_test/migration_test.go

Cherry-pick of cluster pair failure tests
no
no
no

Clusterpair failure tests

---

specs/grafana/stork_application_metrics.json
specs/grafana/stork_migration_metrics.json

>enhancement
Update stork grafana dashboard with recent metrics change name #816 
no
no
no

Update grafana dashboard for changed metrics name

---

.travis.yml

failing-test
Travis build are failing due to inaccessible ubuntu repos
no
no
2.6

Update the ubuntu repo in travis yaml file

---

test/integration_test/snapshot_test.go

Scaled test for cloudsnap. Since we have been seeing some issues for customers with large number of cloudsnaps, we need this test to catch cloudsnap related issues.
no
no
2.6

Add scaled cloudsnapshot test

---

Dockerfile

Signed-off-by: Jose Rivera <jose@portworx.com>
cleanup
Fixes security vulnerability in some of the packages. By not installing 'yum' the vulnerabilities in the dependent packages disappear since the packages are not installed.
no
no
no

Cherry pick cve fix from master: f16f61ba

---

pkg/migration/controllers/migration.go

>bug
Fixes issue where  pvc specs are  updated only on  first migration and consecutive migration schedules skips pvc spec update
no
yes
-->
```
Target PVC's does not reflect source size when updated
```
yes, 2.6

Migrate updated PVC specs each time

---

go.mod
go.sum
pkg/metrics/metrics.go
pkg/metrics/volumesnapshotschedule.go
vendor/github.com/portworx/sched-ops/k8s/core/core.go
vendor/github.com/portworx/sched-ops/k8s/core/nodes.go
vendor/github.com/portworx/sched-ops/k8s/stork/snapshotschedule.go
vendor/github.com/portworx/sched-ops/k8s/stork/stork.go
vendor/modules.txt

adding counter metrics for error/ready/pending volume snapshot.

[STOR-383] add metrics for volume snapshot schedule

---

pkg/applicationmanager/controllers/applicationbackup.go
pkg/resourcecollector/resourcecollector.go

Enhancement
Orginal PR https://github.com/libopenstorage/stork/pull/848 was approved but due to the three-way merge git issue, there are some changes that are getting silently merged. Hence creating a new one
User can choose to backup all resources in one namespace and selected resources
in another namespace.
No
Yes
Yes, 2.6.4

Backing up selected resource and all resoucres of given namespace

---

test/integration_test/common_test.go
test/integration_test/migration_test.go

Integration test for: https://portworx.atlassian.net/browse/STOR-340
no
no
2.6

Integration test for creating reverse clusterpair using storkctl

---

cmd/stork/stork.go

>enhancement
Store stork version in ConfigMap, so application using stork will able to make decision about enable/disable certain feature depending on stork version
no
no
yes, 2.6

stor-419: store stork version in configmap

---

pkg/applicationmanager/controllers/applicationbackup.go
pkg/migration/controllers/migration.go
pkg/storkctl/migration.go

>bug
use inflect pluraliser rules to list and update CR's via storkctl
no
no
2.6.4

Fix storkctl activate/deactivate MongoDB CRs

---

pkg/applicationmanager/controllers/applicationbackup.go

>bug
Collect respective PV objects when PVC are passed as `resourceTypes` in backup CR
no
```release-note
For application backup CR no need to pass PV object for custom resource type backup,  user has to specify only `PersistentVolumeClaim` and its respective PV will be backed up
```
eg. 
```
Options:
Post Exec Rule:
Pre Exec Rule:
Reclaim Policy:  Retain
Resource Types:
ConfigMap
PersistentVolumeClaim
Selectors:            <nil>
Skip Service Update:  false
```

stor-439: Backup respective pv object for pvc resourcetypes

---

pkg/migration/controllers/migration.go

>bug
Migration failing intermittently when run with `startApplication` set to true
no
no
2.6.4

stor-435: Migration failing, pvc already exists

---

pkg/resourcecollector/networkpolicy.go

>bug
Handles nil check  while collecting NetworkPolicy resource with IPBlock set/unser
no
no
2.6.4

handle nil check for networkpolicy ipblock

---

pkg/snapshot/controllers/snapshotrestore.go

Signed-off-by: Aditya Dani <aditya@portworx.com>
>bug
- Force deleting the pods immediately deletes the pod objects from k8s etcd,
which gives a false indication to stork that the pods have been deleted. The
subsequent restore call fails since the underlying PVC is not yet detached by k8s.
No
Yes
```release-note
Issue: In-place VolumeSnapshotRestore issued a "force" delete of the pods using the PVC that needs to be restored. The "force" delete of the pods gave a false indication that the PVC is not being used by any apps. The subsequent Restore command used to fail since the volume was still in use.
User Impact: In-place …
```

Do not force delete pods in VolumeSnapshotRestore.

---

specs/prometheus/role.yaml

cleanup
Fix the prometheus ClusterRoleBinding spec.
No
No
No

Fix the ClusterRoleBinding in prometheus specs.

---

pkg/migration/controllers/migrationschedule.go

bug
https://portworx.atlassian.net/browse/STOR-281
no
no
2.6

Add auth annotations to migrations triggered by migrationschedules

---

drivers/volume/kdmp/kdmp.go

bug
stor-506: Added worked around to delete the dataexport CR at the end, when all the snapshots are completed.
no
no
2.7

stor-506: Added worked around to delete the dataexport CR at the end, when all the snapshots are completed.

---

drivers/volume/portworx/portworx.go

bug
stor-510: Not classifying proxy-volume as pxd, even if protworx provisioner annotation is set
no
no
No
**Testing:**
Tested from px-backup:

stor-510: Not classifying proxy-volume as pxd, even if protworx provisioner annotation is set

---

drivers/volume/aws/aws.go
drivers/volume/azure/azure.go
drivers/volume/csi/csi.go
drivers/volume/gcp/gcp.go
drivers/volume/kdmp/kdmp.go
drivers/volume/portworx/portworx.go
drivers/volume/volume.go
pkg/applicationmanager/controllers/applicationbackup.go
pkg/applicationmanager/controllers/applicationrestore.go

>bug
>cleanup
no
not yet decided
**Note** : 
- tested single ns backup and restore by deleting resources
- multiple-namespace backup and restore to different namespaces

Add CleanupBackup/Restore object volume driver api

---

go.mod
go.sum
vendor/github.com/kubernetes-incubator/external-storage/snapshot/pkg/client/client.go
vendor/modules.txt

>bug
>feature
Add plural forms as short names for VolumeSnapshots and VolumeSnapshotDatas
Yes
No - Will reuse the original PR's release note.
Yes - 2.7

STOR-398-v2: Add plural forms as short names for VolumeSnapshots and VolumeSnapshotDatas

---

pkg/migration/controllers/migration.go

>bug
STOR-537: While migrating pv objects to DR site, stork change PX ID with restore pvc name. This PR add fix to read and modify PV objects
It also address skipping of pv object updation for UID if pvc object has not changed since last migration. 
no
no, should be part of earlier migration fix PR
yes, 2.7
**Notes:** 
Restarted failed integration jobs
```
time="2021-10-22T08:38:36Z" level=info msg="[mysql-enc-pvc] Validated Service: mysql-service"
time="2021-10-22T08:38:36Z" level=info msg="[mysql-enc-pvc] Destroyed Service: mysql-service"
2021/10/22 08:38:36 app mysql is …
```

STOR-537: Reverse Migration is failing for PX PV objects

---

test/integration_test/migration_test.go
test/integration_test/specs/pvc-migration/migration.yaml
test/integration_test/specs/pvc-no-app/portworx/px-sc.yaml
test/integration_test/specs/pvc-no-app/pvc.yaml

Integration test: volume only migration with includeVolumes: true option

---

drivers/volume/kdmp/kdmp.go

> bug
```
pb-1997: Added check not to intialize the snapshot class in the DE, if
CSI does not support snapshot or cases where we want to skip CSI and
take generic backup (proxy-volume)
```
no
no
2.8

pb-1997: Added check not to intialize the snapshot class in the DE for couple of unsupported cases.

---

go.mod
go.sum
vendor/github.com/portworx/kdmp/pkg/controllers/dataexport/reconcile.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiabackup/kopiabackup.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiabackup/kopiabackuplive.go
vendor/github.com/portworx/kdmp/pkg/drivers/options.go
vendor/github.com/portworx/kdmp/pkg/drivers/utils/common.go
vendor/modules.txt

Vendor changes for kdmp from master branch
Vendor changes for kdmp from master branch
no
no
2.8 branch

vendor kdmp changes from master branch

---

go.mod
go.sum
vendor/github.com/portworx/kdmp/pkg/controllers/dataexport/reconcile.go
vendor/modules.txt

>bug
>feature
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
```release-note
```

vendoring in latest kdmp changes.

---

drivers/volume/kdmp/kdmp.go
pkg/snapshotter/snapshotter_csi.go

>bug
>feature
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
```release-note
```

Fixing volumesnapshot name and handling already exists for volumesnapshot and content.

---

drivers/volume/kdmp/kdmp.go
pkg/snapshotter/snapshotter.go
pkg/snapshotter/snapshotter_csi.go

>bug
feature
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
Support for restore using local snapshots in generic backup if available.
```release-note
```
2 restores , one was latest which was restored using local snapshot and the other prev one was restored as a generic restore.

[STOR-513]: Support for restore using local snapshots in generic backup.

---

go.mod
go.sum
vendor/github.com/portworx/kdmp/pkg/controllers/dataexport/reconcile.go
vendor/github.com/portworx/kdmp/pkg/drivers/drivers.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiabackup/kopiabackup.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiabackup/kopiabackuplive.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiadelete/kopiadelete.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiamaintenance/kopiamaintenance.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiarestore/kopiarestore.go
vendor/github.com/portworx/kdmp/pkg/drivers/resticbackup/resticbackup.go
vendor/github.com/portworx/kdmp/pkg/drivers/resticbackup/resticbackuplive.go
vendor/github.com/portworx/kdmp/pkg/drivers/resticrestore/resticrestore.go
vendor/github.com/portworx/kdmp/pkg/drivers/rsync/rsync.go
vendor/github.com/portworx/kdmp/pkg/drivers/utils/common.go
vendor/github.com/portworx/kdmp/pkg/drivers/utils/utils.go
vendor/modules.txt

vendor kmdp master changes

---

go.mod
go.sum
vendor/github.com/portworx/kdmp/pkg/controllers/dataexport/reconcile.go
vendor/github.com/portworx/kdmp/pkg/drivers/drivers.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiabackup/kopiabackup.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiadelete/kopiadelete.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiamaintenance/kopiamaintenance.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiarestore/kopiarestore.go
vendor/github.com/portworx/kdmp/pkg/drivers/resticbackup/resticbackup.go
vendor/github.com/portworx/kdmp/pkg/drivers/resticrestore/resticrestore.go
vendor/github.com/portworx/kdmp/pkg/drivers/rsync/rsync.go
vendor/github.com/portworx/kdmp/pkg/drivers/utils/utils.go
vendor/modules.txt

- Bug
- 
vendoring latest kdmp changes for fixing pb-2073
No
No
yes, 2.8

vendor update from kdmp master

---

cmd/stork/stork.go
drivers/volume/kdmp/kdmp.go

-Task
Change kopia executor to 1.0.0
No
No
No

Change kopia executor to 1.0.0

---

cmd/stork/stork.go

Task
Updating kopia  release image
Np
No
No

Updated kopia image tag

---

drivers/volume/csi/csi.go
drivers/volume/kdmp/kdmp.go
drivers/volume/volume.go

bug
```
pb-2098: Added google file and azure file check to default to KDMP
driver.
- Removed IsDriverWithoutSnapshotSupport and
isCSISnapshotClassRequired.
- Added a IsCSIDriverWithoutSnapshotSupport common API in volume pkg
and adding it in kdmp and csi driver.
- Also added csiDriverWithOutSnapshotKey configmap field to get user
input for driver that does not support snapshot.
```
no
No
no
**Testing:**
Verified the configmap field csiDriverWithOutSnapshotKey by setting it to efs by removed the efs case for testing purpose.
The backup was successful with the kdmp driver. …

pb-2098: Added google file and azure file check to default to KDMP driver.

---

go.mod
go.sum
vendor/github.com/portworx/kdmp/pkg/drivers/kopiabackup/kopiabackup.go
vendor/modules.txt

> bug
pb-2101: vendor latest from master kdmp branch.
no
2.8

pb-2101: vendor latest from master kdmp branch.

---

go.mod
go.sum
vendor/github.com/portworx/kdmp/pkg/controllers/dataexport/reconcile.go
vendor/modules.txt

Vendor changed for kdmp from master branch

pb-2113: vendor changes for kdmp from master branch.

---

go.mod
go.sum
vendor/github.com/portworx/kdmp/pkg/controllers/dataexport/reconcile.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiabackup/kopiabackuplive.go
vendor/github.com/portworx/kdmp/pkg/drivers/options.go
vendor/modules.txt

- Ehancement
vendor update for kdmp
No
No
yes, 2.8

vendor update for kdmp

---

drivers/volume/kdmp/kdmp.go
go.mod
go.sum
vendor/github.com/portworx/kdmp/pkg/controllers/dataexport/reconcile.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiabackup/kopiabackup.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiabackup/kopiabackuplive.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiadelete/kopiadelete.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiamaintenance/kopiamaintenance.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiarestore/kopiarestore.go
vendor/github.com/portworx/kdmp/pkg/drivers/options.go
vendor/github.com/portworx/kdmp/pkg/drivers/utils/utils.go
vendor/github.com/portworx/kdmp/pkg/jobratelimit/jobratelimit.go
vendor/modules.txt

- Enhancement
PB-2128
No
No, as this is not user visible.
Yes, 2.8

 Passing kdmp-config map name for kdmp job delete

---

go.mod
go.sum
vendor/github.com/portworx/kdmp/pkg/controllers/dataexport/reconcile.go
vendor/modules.txt

>bug
pb-2131: vendor latest kdmp from the master branch.
no
no
2.8

pb-2131: vendor latest kdmp from the master branch.

---

test/integration_test/common_test.go
test/integration_test/migration_failover_failback_test.go
test/integration_test/stork-test-pod.yaml
test/integration_test/test-deploy.sh

scaled failover failback test

---

pkg/snapshotter/snapshotter_csi.go

bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
In case of filestores, the snapshot size usually is the whole filestore size.
pvc creation from snapshot fails if the pvc size is less than the snapshot size.
Hence making the restored pvc size same as that of the snapshot size if available in volumesnapshot.
```release-note
Issue:
User Impact:
Resolution
```
**Test**
Tested following scenarios
1. backup on both disk …

[PB-2143]: Making pvc size same as csi snapshot size to avoid the clone failure.

---

go.mod
go.sum
vendor/github.com/portworx/kdmp/pkg/controllers/dataexport/dataexport.go
vendor/modules.txt

bug
Vendor changes for kdmp from master branch
no
no
2.8

pb-2149: vendor changes for kdmp from master branch

---

drivers/volume/aws/aws.go
drivers/volume/gcp/gcp.go
drivers/volume/kdmp/kdmp.go
drivers/volume/volume.go

Bug
- As part of kdmp restore, it is made sure that kdmp job pod
and the restore PV's are created in the same zone
No
```release-note
Issue:  Backup of sts app taken having multiple PVC's across zones fails to restore on the same region or different region
User Impact:   When a restore is performed, app pods fail to come up a few of the PV's could be in a different zone for each replica set of the app. Now user can do a successful restore of the same.
Resolution:  Added support to make sure all PV's are in the same node as the pod is running
```
Yes, 2.8
**Manual Test**
- …

Multi zone support generic backup support for aws/gke

---

go.mod
go.sum
vendor/github.com/portworx/kdmp/pkg/controllers/dataexport/reconcile.go
vendor/modules.txt

vendor change for KDMP from master branch.
vendor change for KDMP from master branch.
no
no
2.8

pb-2113: vendor change for kdmp from master branch.

---

go.mod
go.sum
pkg/snapshotter/snapshotter_csi.go
vendor/github.com/portworx/kdmp/pkg/controllers/dataexport/reconcile.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiabackup/kopiabackup.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiarestore/kopiarestore.go
vendor/github.com/portworx/kdmp/pkg/drivers/resticbackup/resticbackup.go
vendor/github.com/portworx/kdmp/pkg/drivers/resticrestore/resticrestore.go
vendor/modules.txt

>bug
>feature
>improvement
cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
vendoring in latest kdmp 
```release-note
Issue:
User Impact:
Resolution
```

vendoring in latest kdmp 

---

go.mod
go.sum
vendor/github.com/portworx/kdmp/pkg/drivers/kopiabackup/kopiabackup.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiabackup/kopiabackuplive.go
vendor/modules.txt

vendor changes for kdmp from master branch.
vendor changes for kdmp from master branch.
no
no
2.8

pb-2162: vendor changes for the kdmp master branch

---

test/integration_test/migration_test.go
test/integration_test/specs/mongo-op-migration/migration.yaml
test/integration_test/specs/mongo-operator/manager/manager.yaml
test/integration_test/specs/mongo-operator/mongodbcommunity.mongodb.com_mongodbcommunity.yaml
test/integration_test/specs/mongo-operator/rbac/role.yaml
test/integration_test/specs/mongo-operator/rbac/role_binding.yaml
test/integration_test/specs/mongo-operator/rbac/role_binding_database.yaml
test/integration_test/specs/mongo-operator/rbac/role_database.yaml
test/integration_test/specs/mongo-operator/rbac/service_account.yaml
test/integration_test/specs/mongo-operator/rbac/service_account_database.yaml

https://portworx.atlassian.net/browse/PTX-5032
2.9

Mongo operator - migration test

---

test/integration_test/common_test.go
test/integration_test/migration_stork_failures_test.go
test/integration_test/migration_test.go

https://portworx.atlassian.net/browse/PTX-5031
no
no
2.9

Separate out migration and snapshot tests and run all tests

---

pkg/extender/extender.go
pkg/extender/extender_test.go

>improvement
- A node if in Degraded state will return half of the score they would
originally return based on the node/zone/rack/region priority.
- If a volume has a replica on a node but the node is in Degraded state
stork will give it a score of rackPriority / 2. This is done since
a pod running on that node is not really hyperconverged and should be
score similar to any another node in the same rack.
- Added UTs for scenarios where a node needs to be scored based on
zone/region/node/rack but is in Degraded state.
No
```release-note
Improvement: Stork scheduler will now …
```

PWX-22606: Give low scores to nodes which are in Degraded state.

---

test/integration_test/migration_failover_failback_test.go
test/integration_test/migration_test.go
test/integration_test/specs/rabbitmq-migration/migration.yaml
test/integration_test/specs/rabbitmq-operator/rabbitmq-operator.yaml

https://portworx.atlassian.net/browse/PTX-5033
no
no
no

Rabbitmq operator

---

pkg/objectstore/s3/s3.go

Added a function to objectstore package to extract object lock info from
a S3 bucket.
**What type of PR is this?** feature
>enhancement
**What this PR does / why we need it**: Need to operate on the object lock configuration set for a S3 bucket. Hence this API will provide the same.
**Is a release note needed?**: yes
```release-note
Issue: objectlock config reading API not implemented
User Impact: object lock feature usage will be hampered 
Resolution : Added the API which uses corresponding S3 APIs 
```

pb-2178: Obtain object-lock info for S3 bucket

---

pkg/applicationmanager/controllers/applicationbackupschedule.go

>bug
```
pb-2236: Added logic to force full backup for locked period backup from schedulebackup
- Starting of every day time slot, forcing to have first backup of schedulebackup to
full backup always.
- This is to take care, if the incremental backup was overlapping between two day's
time slot and avoid having incremental backup as first backup in starting of day.
```
No
Since we are not going to claim the object lock support in direct stork backup, we will not release note it. 
no
Testing:
For testing reduced dayInSec to 900 sec ( 15 mints) and tested that it takes fully …

pb-2236: Added logic to force full backup for locked period backup from schedulebackup.

---

go.mod
go.sum
vendor/github.com/portworx/kdmp/pkg/drivers/utils/utils.go
vendor/modules.txt

Vendor KDMP repo from master branch

pb-2292: vendor kdmp repo from master branch

---

go.mod
go.sum
vendor/github.com/portworx/kdmp/pkg/drivers/kopiabackup/kopiabackup.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiabackup/kopiabackuplive.go
vendor/modules.txt

>bug
```
pb-2323: vendoring latest kdmp repo from master branch.
```
no
no
2.10

pb-2323: vendoring latest kdmp repo from master branch.

---

test/integration_test/common_test.go

Fix cluster pairing error on auth-enabled clusters in integration tests.
no
no
2.9

Get token to be passed to generate cluster pair method, for auth-enabled clusters

---

go.mod
go.sum
vendor/github.com/portworx/kdmp/pkg/drivers/drivers.go
vendor/github.com/portworx/kdmp/pkg/drivers/utils/utils.go
vendor/modules.txt

Vendor changes of latest kemp repo from master branch.

pb-2330: vendoring latest kdmp repo from master branch

---

go.mod
go.sum
vendor/github.com/portworx/kdmp/pkg/drivers/utils/common.go
vendor/modules.txt

vendor latest kdmp changes from master branch.

vendoring latest kdmp changes from master branch

---

pkg/snapshotter/snapshotter_csi.go

>bug
pb-2081
no
We are already release noting the original restore failure as part of pb-2081.
2.10

pb-2081: Added retry logic to wait for the volumesnapshot status update, before accessing restoreSize.

---

drivers/volume/portworx/portworx.go

improvement
- The Portworx driver was getting the migration status for all the volumes from all the ClusterPairs in every GetMigrationStatus() call. This turned out to be expensive on the PX side. 
- Instead pass on the taskID and the clusterID for which Stork needs a MigrationStatus and PX will return the status accordingly. 
No
Yes
```release-note
Issue: While fetching the migration status for volumes from the Portworx Driver, stork would request the status for all volumes from all cluster pairs.
User Impact: Getting migration status for all volumes from all cluster …
```

PWX-23703: Explicitly pass migration taskID to get the CloudMigrateStatus for Portworx Driver

---

specs/stork-deployment.yaml
specs/stork-scheduler.yaml
test/integration_test/test-deploy.sh

Reverts libopenstorage/stork#982

Revert "Stork scheduler support with k8s 1.22"

---

README.md

>documentation
minor typo fix
no
no
no

Removed apos

---

drivers/volume/csi/csi.go

- fix the variable scope related issue in the restore logic of CSI backup.
- changed the switch case to have right type assertion check
bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
**What this PR does / why we need it**: This fixes a regression introduced in the restore path of CSI backups by the pb-2328
```release-note
Issue:
User Impact:
Resolution
```
**Does this change need to be cherry-picked to a release branch?**: 2.11
Unit test : 
Backup path 
view JSON's outcome: …

pb-2867: fix restore path issue for CSI backups

---

pkg/applicationmanager/controllers/applicationbackup.go

Fixed a v1beta1 based getCRD call which will fail for k8s-1.22 or more
because these APIs are removed in k8s-1.22 onwards.
bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
**What this PR does / why we need it**: We are calling v1beta1 based CRD get calls which doesn't exist in k8s 1.22 onwards. Hence we need to call appropriate API based on k8s version. 
```release-note
Issue:
User Impact:
Resolution
```
**Comment for …

pb-3002: call v1 version CRD API for k8s 1.22 or more.

---

pkg/objectstore/s3/s3.go

>improvement
```
pb-3000: Added debug statement in GetObjLockInfo api
```
no
no
2.11

pb-3000: Added debug statement in GetObjLockInfo api

---

pkg/log/log.go
pkg/migration/controllers/migration.go
pkg/migration/controllers/resourcetransformation.go
pkg/migration/migration.go
pkg/resourcecollector/resourcecollector.go

>enhancement
Add controller for `ResourceTransformation` CR, controller -
- create namespace with prefix stork-test + transformation namespace to validate resources
- validate transformation spec inputs
- patch resource in namespace with transformation specs
- dry-run updated resources
no
yes. will add release not to final PR for this feature
```release-note
Issue:
User Impact:
Resolution
```
2.12

PWX-26192: Add controller for Resourcetransformation CR

---

Dockerfile

>improvement
Update the google SDK version to 399
No
Yes
```release-note
Improvement: Update the google SDK used by the stork container to version 399
```
Yes - 2.12

Update google SDK to version 399

---

how ed4bac3825565902733b151138c32367231e48b3
pkg/apis/stork/v1alpha1/backuplocation.go
pkg/applicationmanager/controllers/applicationbackup.go
pkg/objectstore/nfs/nfs.go
pkg/objectstore/objectstore.go

- added NFS type to stork v1alpha1 APIs
- added objectlock specific API for for NFS
- skipped bucket exist check in Application backup
controller specifically for NFS scenario
>bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
```release-note
Issue:
User Impact:
Resolution
```

pb-2939: enable NFS type backuplocation

---

cmd/stork/stork.go

>bug
Fixes the following nil panic where two goroutines try to add to the same map managed by the apimachinery scheme package.
goroutine 1
```
fatal error: concurrent map read and map write
goroutine 145 [running]:
runtime.throw({0x33dfb9d, 0x40af7d})
/home/travis/.gimme/versions/go1.17.11.linux.amd64/src/runtime/panic.go:1198 +0x71 fp=0xc000a4d8c8 sp=0xc000a4d898 pc=0x434c91
runtime.mapaccess2(0x2e56880, 0xc000ae9c40, 0xc000ae9c40)
/home/travis/.gimme/versions/go1.17.11.linux.amd64/src/runtime/map.go:469 +0x205 fp=0xc000a4d908 sp=0xc000a4d8c8 pc=0x40e7c5
k8s.io/apimachinery/pkg/runtime.(*Scheme).ObjectKinds(0xc00042e460, {0x3892ee8, 0xc000ae9c40}) …
```

Start the controller manager before starting any kubernetes watches

---

pkg/applicationmanager/controllers/applicationbackup.go

>bug
```
pb-3132: Added logic to call post exec rule after volume backup, if it
is a generic backup.
- If the backup volume list had only non-kdmp volumes, trigger the
post exec rule after the startbackup API.
- If the backup volume list had only kdmp volumes or mix of both
kdmp and non-kdmp volume, we will call the post exec rule, once the volume backup is completed.
```
no
```release-note
Issue: Post exec rule for the generic backup are getting executed before the backup completion.
User Impact: Since post exec rule is executed before snapshot, some times, the backup/snapshot or app level consistent.
Resolution: Calling the post exec rule …
```

pb-3132: Added logic to call post exec rule after volume backup, if it is a generic backup

---

pkg/resourcecollector/clusterrole.go

>bug
```
pb-3122: Added logic to include clusterRole, if it is bind to a Rolebinding at namespace level.
```
No
```release-note
Issue: ClusterRole are not backed up, if it bind to rolebinding at namespace level.
User Impact: Customer will not able to back up the clusterRole, if it bind to a rolebinding at namespace level
Resolution: Add logic to include clusterRole even if it is bind to rolebinding at namespace level
```
2.12
**Tested on the QA setup**

pb-3122: Added logic to include clusterRole, if it is bind to a Rolebinding at namespace level.

---

go.mod
go.sum
pkg/resourcecollector/persistentvolumeclaim.go
pkg/resourcecollector/secret.go
pkg/utils/utils.go
vendor/github.com/portworx/torpedo/drivers/scheduler/k8s/k8s.go
vendor/k8s.io/component-helpers/storage/volume/helpers.go
vendor/k8s.io/component-helpers/storage/volume/pv_helpers.go
vendor/k8s.io/utils/pointer/pointer.go
vendor/modules.txt

>bug
```
pb-3124: Added check for both beta and v1 version of StorageProvisioner
annotation
```
no
no. It is a PR to address the review comments of below PR:
https://github.com/libopenstorage/stork/pull/1179
https://github.com/libopenstorage/stork/pull/1178
2.12

pb-3124: Added check for both beta and v1 version of StorageProvisioner annotation

---

pkg/applicationmanager/controllers/applicationrestore.go

bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test

PB-3155: Updating the success status in application restore CR from resource export CR.

---

pkg/applicationmanager/controllers/applicationbackup.go
pkg/applicationmanager/controllers/applicationrestore.go

>bug
feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test

PB-3144: Not creating namespaces for nfs backuplocation type in controller.

---

pkg/apis/stork/v1alpha1/backuplocation.go

>feature
```
Changes required in backuplocation CR definition of NFS type.
```
Yes, now backuplocation CRD will have nfs type 
NA. Will add a feature description. Also it is a EA release only
No

Changes required in backuplocation CR definition of NFS type.

---

go.mod
go.sum
vendor/github.com/portworx/kdmp/pkg/controllers/dataexport/reconcile.go
vendor/modules.txt

bug
Vendoring 1.2.3 kdmp latest.

Vendoring 1.2.3 kdmp latest.

---

drivers/volume/portworx/portworx.go

>bug
```
pb3206: Not returning error if the storageclass is missing on destination cluster
```
no
No, will be covered with pb-3174
yes. 2.12
Testing
Started the failing jenkins job with the  fixed image:
https://jenkins.pwx.dev.purestorage.com/job/Stork/view/Stork%202.12-dev%20%20C7/job/2.12-backup-k8s-1-23-0/376/console

pb3206: Not returning error if the storageclass is missing on destination cluster.

---

Makefile

Update version to 2.12.1
Update version to 2.12.1
No
No
PR for 2.12

Update version to 2.12.1

---

pkg/applicationmanager/controllers/applicationbackup.go
pkg/utils/utils.go

Bug
Appended restore backup with nfs for jobs
No
No
No

 Appended restore backup with nfs for jobs

---

pkg/migration/controllers/resourcetransformation.go

bug
Fixed resourcequota object transfomation validation.
```release-note
Issue: Resource transformation for ResourceQuota was failing with 'server could not find the requested resource'
User Impact: Resource transformation of ResourceQuota would be failing during migrations.
Resolution:  Api calls with right resource kind solved the issue and ResourceQuota can be transformed.
```
Test:
====
Describe of resource transformation validation 
```
kubectl -n es18 describe resourcetransformation limit-range-resource-quota-rt
Name: …
```

PWX-27505: validateTransformResource to use the default ruleset instead of calling pluralize directly.

---

pkg/applicationmanager/controllers/applicationrestore.go

```
pb-3312: Added steps to delete the resourceexport CR, when restore fails
with timeout value.
```
no
no
no
Testing:
Tested restore after removing the resource.json file and checked that RE, Job and job pods are getting deleted.

pb-3312: Added steps to delete the resourceexport CR, when restore fails with timeout value.

---

pkg/applicationmanager/controllers/applicationrestore.go

Signed-off-by: Kesavan Thiruvenkadasamy <kthiruvenkadasamy@purestorage.com>
>bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
```release-note
Issue:
User Impact:
Resolution
```

[PB-3220] - fixed error message in restore

---

test/integration_test/extender_test.go
test/integration_test/specs/test-sv4-svc-repl1-prefer-remote-only/portworx/px-sc.yaml
test/integration_test/specs/test-sv4-svc-repl1-prefer-remote-only/test-sv4-svc-repl1-prefer-remote-only.yaml
test/integration_test/specs/test-sv4-svc-repl1/portworx/px-sc.yaml
test/integration_test/specs/test-sv4-svc-repl1/test-sv4-svc-repl1.yaml

Integration tests for Antihyperconvergence of sharedv4 service pods
no
no
yes 2.12.2

PWX-27585: Adding integration tests for antihyperconvergence

---

test/integration_test/extender_test.go
test/integration_test/health_monitor_test.go
test/integration_test/specs/test-sv4-svc-repl1-prefer-remote-only/portworx/px-sc.yaml
test/integration_test/specs/test-sv4-svc-repl1-prefer-remote-only/test-sv4-svc-repl1-prefer-remote-only.yaml
test/integration_test/specs/test-sv4-svc-repl1/portworx/px-sc.yaml
test/integration_test/specs/test-sv4-svc-repl1/test-sv4-svc-repl1.yaml

Antihyperconvergence integration tests
CSI Pod Monitoring integration tests
no
no
no

Cherry pick integration test changes 2.12.2

---

Makefile
test/integration_test/Dockerfile
test/integration_test/test-deploy.sh

Adding a new jenkins pipeline that will build stork. This will be used for CBT as well as releasing stork.
no
no
no

Docker and Makefile changes for Stork CBT

---

.travis.yml

Increase travis wait time since we are now running some commands inside docker containers.
no
no
2.12

Increase wait time for inactivity for travis

---

Makefile

Updating version to 2.12.3
**What this PR does / why we need it:**
Update Stork container image to fix vulnerability issues 
**Does this PR change a user-facing CRD or CLI?:**
no
**Is a release note needed?:**
yes
**ReleaseNotes**
Following vulnerabilities are addressed in the stork: CVE-2022-43680, CVE-2022-3821, CVE-2022-35737, CVE-2021-46848

Update version to 2.12.3

---

Dockerfile

Signed-off-by: Jose Rivera <jose@portworx.com>
Vulnerability fix update pks.   
>bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
```release-note
Issue:
User Impact:
Resolution
```

Update libxml for vulnerability fixes.

---

Makefile

ntegration-test
https://portworx.atlassian.net/browse/PWX-28448
no
no
yes

build binaries inside container

---

Dockerfile

Reverting this change as it is breaking travis.

Revert "PWX-28818: Update libxml for vulnerability fixes"

---

Makefile

> branch update
Update the release version to 23.2.0
no
no
no

Updating release version to 23.2.0

---

pkg/resourcecollector/resourcecollector.go

>bug
This PR has the right fix for checking storkcache.Instance() nil check.

PB-3514: Modified storkcache.Instance() nil check.

---

Dockerfile
Makefile

>improvement
Fixing libksba  vulnerability issue CVE-2022-47629
https://portworx.atlassian.net/browse/PWX-28231
no
```release-note
Fixing libksba  vulnerability issue CVE-2022-47629
```
yes

PWX-28231: Fixing libksba  vulnerability issue CVE-2022-47629

---

Dockerfile

>improvement
Update google sdk version to fix vulnerabilities
<!--
If yes, explain why the change is needed and paste some example output of the new change.
If no, just write no.
na
yes 23.2/23.2.1

PWX-29170: Updating google cloud sdk to fix vulnerability issues.

---

pkg/applicationmanager/controllers/applicationbackup.go

>bug
```
pb-3554: Modified the status message if zero namespace is selected for namespace selector.
```
No
Not needed it is just message change
23.2 branch

pb-3554: Modified the status message if zero namespace is selected for namespace selector.

---

drivers/volume/kdmp/kdmp.go

feature
Enabling csi snapshot path for generic backups with nfs backuplocation.

PB-3453: Enabling csi snapshot for generic backup for nfs backuplocation.

---

cmd/stork/stork.go
pkg/storkctl/clusterpair.go
pkg/storkctl/factory.go

>improvement
https://portworx.atlassian.net/browse/PWX-29068 
yes
storkctl create clusterpair -h
yes
```release-note
Improving storkctl create clusterpair help output
```
yes 23.3
**Note for reviewer**:

PWX-29068: Improving storkctl create clusterpair help output.

---

go.mod
go.sum
vendor/modules.txt

**What this PR does / why we need it**: Security fix - upgraded rancher pkg to fix critical issues
**Fixed**
CVE-2022-31249 Critical github.com/rancher/wrangler
CVE-2022-43756 High github.com/rancher/wrangler

Security fix - upgraded rancher pkg to fix critical issues

---

go.mod
go.sum
pkg/snapshotter/snapshotter_csi.go
vendor/github.com/portworx/kdmp/pkg/controllers/dataexport/reconcile.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiabackup/kopiabackuplive.go
vendor/modules.txt

>bug
```
pb-3633: fixed the v1/v1beta1 version call for volumesnapshot get in RestoreVolumeClaim()
```
no
NA.
23.2 branch

pb-3633: fixed the v1/v1beta1 version call for volumesnapshot get in RestoreVolumeClaim()

---

drivers/volume/portworx/portworx.go

improvement
Need to support taking generic backup for px volumes.
**Test**:
1. Tested with default px volume backups.
2. Tested with px volume backups with the flag set and backups were generic backups.

Enabling support for explicitily taking generic backup for px volumes.

---

pkg/resourcecollector/resourcecollector.go

improvement
More crds plurals need to be added to ruleset.

PWX-29480: Adding more crds to ruleset for IBM wkc.

---

cmd/stork/stork.go
go.mod
go.sum
pkg/applicationmanager/controllers/applicationbackup.go
pkg/k8sutils/k8sutils.go
vendor/github.com/portworx/kdmp/pkg/controllers/dataexport/reconcile.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiabackup/kopiabackup.go
vendor/github.com/portworx/kdmp/pkg/version/version.go
vendor/modules.txt

**What this PR does / why we need it**: Added changes to create config map to hold info on custom admin namespace
**Testing SS:**

PB-3579 - Added changes to create config map to hold info on custom admin namespace

---

.travis.yml
Makefile

> Create 23.3.0 release branch
> Create 23.3.0 release branch
no
no
no

Updating release version to 23.3.0

---

test/integration_test/migration_test.go
test/integration_test/specs/mysql-service-acc-migration-schedule/migrationschedule.yaml
test/integration_test/specs/mysql-service-acc-migration-schedule/schedulepolicy.yaml
test/integration_test/specs/mysql-service-account/aws/aws-sc.yaml
test/integration_test/specs/mysql-service-account/azure/azure-sc.yaml
test/integration_test/specs/mysql-service-account/gce/gke-sc.yaml
test/integration_test/specs/mysql-service-account/linstor/linstor-sc.yaml
test/integration_test/specs/mysql-service-account/mysql.yaml
test/integration_test/specs/mysql-service-account/portworx/px-sc.yaml

https://portworx.atlassian.net/browse/PWX-29221
no
no
no

integration test for service and service account updates

---

pkg/applicationmanager/controllers/applicationbackup.go

>bug
Need to update backup CR after resource upload is successful in NFS backup location case.

Need to update the backup CR after resource completion is successful.

---

pkg/applicationmanager/controllers/applicationrestore.go

>bug
```
pb-3794: Moved the volume total size update along with resource stage change update.
```
no
```release-note
Issue: The total volume size in the restore CR is missing some time, if the CR update fails intermittently..
User Impact: The total size of the restored volume was missing in the restore CR.
Resolution: The total size of the restored volume will be updated always in the restore CR.
```
23.3.1

pb-3794: Moved the volume total size update along with resource stage change update.

---

.travis.yml
Makefile

release version update 
release version update 
no
no
no

Updating release version to 23.4.0

---

go.mod
go.sum
vendor/github.com/portworx/kdmp/pkg/version/version.go
vendor/modules.txt

>bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
```release-note
Issue:
User Impact:
Resolution
```

vendor latest kdmp master

---

cmd/stork/stork.go
drivers/volume/portworx/portworx.go
pkg/action/action.go
pkg/log/log.go
pkg/storkctl/action.go
pkg/storkctl/storkctl.go

cleanup
Yes, change `storkctl perform` to `storkctl do` as it more generally expresses the intent
No
No

cleanup changes

---

go.mod
go.sum
pkg/applicationmanager/controllers/applicationbackup.go
pkg/snapshotter/snapshotter.go
pkg/snapshotter/snapshotter_csi.go
vendor/github.com/portworx/kdmp/pkg/apis/kdmp/v1alpha1/resourcebackup.go
vendor/github.com/portworx/kdmp/pkg/apis/kdmp/v1alpha1/resourceexport.go
vendor/github.com/portworx/kdmp/pkg/apis/kdmp/v1alpha1/zz_generated.deepcopy.go
vendor/github.com/portworx/kdmp/pkg/client/clientset/versioned/clientset.go
vendor/github.com/portworx/kdmp/pkg/client/clientset/versioned/scheme/register.go
vendor/github.com/portworx/kdmp/pkg/client/clientset/versioned/typed/kdmp/v1alpha1/kdmp_client.go
vendor/github.com/portworx/kdmp/pkg/controllers/dataexport/reconcile.go
vendor/github.com/portworx/kdmp/pkg/controllers/resourceexport/reconcile.go
vendor/github.com/portworx/kdmp/pkg/drivers/drivers.go
vendor/github.com/portworx/kdmp/pkg/drivers/driversinstance/driversinstance.go
vendor/github.com/portworx/kdmp/pkg/drivers/nfsbackup/nfsbackup.go
vendor/github.com/portworx/kdmp/pkg/drivers/nfscsirestore/nfscsirestore.go
vendor/modules.txt

PB-3576: CSI snapshotter to support local file upload and download for NFS backuplocation.

---

pkg/applicationmanager/controllers/applicationbackup.go
pkg/applicationmanager/controllers/applicationrestore.go

>bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
```release-note
Issue:
User Impact:
Resolution
```

PB-3841 : Resource Count Fix for ApplicationBackupCR

---

.travis.yml
Makefile

release version update
release version updating to 23.5.0 .

Updating release version to 23.5.0

---

go.mod
go.sum
pkg/applicationmanager/controllers/applicationrestore.go
vendor/github.com/portworx/kdmp/pkg/apis/kdmp/v1alpha1/resourcebackup.go
vendor/github.com/portworx/kdmp/pkg/apis/kdmp/v1alpha1/resourceexport.go
vendor/github.com/portworx/kdmp/pkg/controllers/resourceexport/reconcile.go
vendor/github.com/portworx/kdmp/pkg/executor/common.go
vendor/modules.txt

**What type of PR is this?** Feature
>bug
feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
**What this PR does / why we need it**: This enabled the large resource based backup and restore to happen for NFS backup location.
```release-note
Issue:
User Impact:
Resolution
```
Unit test Result:
Restore show status:

pb-3842: Support large Resource for NFS backuplocation

---

pkg/migration/controllers/migration.go

>bug
Incorrect err being logged when applying v1 vrd
no
no
yes 23.5-dev

Fixing error message when applying CRDs.

---

pkg/storkctl/action.go
pkg/storkctl/storkctl.go

Renamed 'storkctl do' -> 'storkctl trigger'

---

.travis.yml

**What type of PR is this?**bug
>bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
**What this PR does / why we need it**: created image with name 23.5.0-nfs-dev
```release-note
Issue:
User Impact:
Resolution
```

Changed travis.yml to push chnages to 23.5.0-nfs-dev image

---

test/integration_test/applicationbackup_test.go
test/integration_test/applicationclone_test.go
test/integration_test/cmdexecutor_test.go
test/integration_test/migration_backup_test.go
test/integration_test/migration_failover_failback_test.go
test/integration_test/migration_stork_failures_test.go
test/integration_test/migration_test.go
test/integration_test/snapshot_restore_test.go
test/integration_test/snapshot_test.go

Auto update snapshot, restore and clone tests in testrail
no
no
no

auto update testrail for clone and snap tests

---

test/integration_test/migration_test.go

Migration tests are failing due to an unrelated change.
no
no
no

fix test for namespace selector

---

test/integration_test/cmdexecutor_test.go
test/integration_test/common_test.go

Add Command executor tests to CBT since there has been a lot of code churn in command executor recently.
no
no
no

add command  test executor to CBT

---

pkg/snapshot/controllers/snapshotschedule.go

>improvement
Avoiding unnecessary update to volumesnapshotschedule if there is no change as part of pruning of old volumesnapshots.
```release-note
Issue: Update calls were happening to the volumesnapshotschedule in each 10 seconds even if there is no new update.
User Impact: With lots of volumesnapshotschedules running, it is unnecessary load on api-server.
Resolution: Avoiding updates if there is no change to volume snapshot list as part pf pruning.
```
Test:
1. Manual test run has been updated in ticket.
2. Snapshot integration test successful …

PWX-30987: Update the volumesnapshotSchedule CR if there is a change to the snapshot list as part of pruning.

---

test/integration_test/common_test.go

fix log line for testrail

---

pkg/applicationmanager/controllers/applicationrestore.go
pkg/k8sutils/k8sutils.go

Added a missed patch for pb-3791 of 23.5 to master
**What type of PR is this?** 
>bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
**What this PR does / why we need it**: Added the missed patch of pb-3791 which was present in 23.5 but got missed in master due to merge of NFS branch. added the same.
```release-note
Issue:
User Impact:
Resolution
```
**Does this change need to be cherry-picked to a release branch?**: 23.6

pb-3791: added pb-3791 missed patch from 23.5

---

pkg/storkctl/clusterpair.go

>improvement
Clusterpair creation to create credential secret and backuplocation for use.
yes
```
Example with s3 objectstore.
➜  ~ ./storkctl create clusterpair cp-new -p s3 -n kube-system --s3-access-key ***** --s3-secret-key ***** --s3-region us-east-1 --s3-endpoint *******
--src-kube-file /tmp/src.config --dest-kube-file /tmp/dest.config --src-ip ****** --dest-ip ********
Using PX-Service Endpoint of DR cluster to create clusterpair...
Creating PX-Service Endpoint of DR cluster to create clusterpair...
Backuplocation cp-new added successfully on source cluster in namespace kube-system
ClusterPair cp-new created successfully on source …
```

PWX-30576: Create clusterpair to support secret and backuplocations creation with required cloud credentials.

---

pkg/applicationmanager/controllers/applicationrestore.go

**What this PR does / why we need it**: fix to handle project annotations/labels for the px-backup created namespace.
Add all labels/annotations from Namespace.json except project labels/annotations when not found in the namespace which is not created by px-backup.
With retain policy, project labels/annotations should not be applied to the namespace with no projects. Applies to a scenario where project association is removed by the user after taking the backup with project on a namespace

PB-3919 : fix to handle Rancher project annotations/labels for the px-backup created namespace

---

test/integration_test/common_test.go

* Stork integration test requires `TEST_MODE=true` environment to be set
* For operator installs, stork spec inside the `storagecluster` object needs to be updated for this to take effect
no
no
no

set TEST_MODE=true environment variable for stork in storage cluster

---

pkg/storkctl/clusterpair.go

improvement
```
1. Automatically detecting px endpoints if portworx-api service is loadbalancer type 
2. Required --src-ep and --dest-ep for other portworx-api service type other than loadbalancer.
3. Making --src-ip, --dest-ip, --src-port and --dest-port as deprecated parameters.
```
Ex:
1. When portworx-api service is clusterIP.
➜  stork git:(PWX-30578) ✗ bin/linux/storkctl create clusterpair cp-new18 -p s3 -n kube-system --s3-access-key ***** --s3-secret-key ***** --s3-region us-east-1 --s3-endpoint *****--src-kube-file /tmp/dipti5.config --dest-kube-file /tmp/dipti7.config --src-ep 10.13.193.173:9001 --dest-ep 10.13.194.125:9001
Creating Secret and Backuplocation in …

PWX-30578: Setting px endpoints in storage options in both source and dest clusterpairs if portworx api service type is loadbalancer or clusterIP.

---

pkg/storkctl/clusterpair.go

>improvement
Creating clusterpair for sync dr without storage options with --mode parameter.
**Test**
```
➜  stork git:(PWX-30579) ✗ bin/linux/storkctl create clusterpair cp-sync1 --src-kube-file /tmp/diptis1.config --dest-kube-file /tmp/diptis2.config --mode async
error: supported mode value : sync-dr
➜  stork git:(PWX-30579) ✗ bin/linux/storkctl create clusterpair cp-sync1 --src-kube-file /tmp/diptis1.config --dest-kube-file /tmp/diptis2.config --mode sync-dr -n kube-system
ClusterPair cp-sync1 created successfully. Direction Source -> Destination
Cluster pair cp-sync1 …
```

PWX-30579: Creating clusterpair for sync dr without storage options with --mode parameter.

---

test/integration_test/common_test.go
test/integration_test/migration_test.go
test/integration_test/stork-test-pod.yaml
test/integration_test/test-deploy.sh

https://portworx.atlassian.net/browse/PTX-18640
no
no
no

Bidirectional cluster pair integration test changes - PWX-30580

---

.travis.yml
Makefile

Updating release version to 23.7.0

---

test/integration_test/clusterdomain_test.go
test/integration_test/common_test.go
test/integration_test/migration_backup_test.go
test/integration_test/migration_failover_failback_test.go
test/integration_test/migration_stork_failures_test.go
test/integration_test/migration_test.go

migration tests to switch between bidirectional/regular clusterpairs

---

pkg/storkctl/clusterpair.go

improvement
Help and error message changes for usage improvement.

PWX-32496: Changing help message and error message to json key file path for google accounts in clusterpair creation.

---

pkg/applicationmanager/controllers/applicationbackup.go

>bug
```
pb-4208: Added debug statement to print the largeResourceSizeLimit value used
```
no
NA
23.7.1 and 23.7.2 branch

pb-4208: Added debug statement to print the largeResourceSizeLimit value used

---

go.mod
go.sum
vendor/github.com/portworx/kdmp/pkg/controllers/dataexport/reconcile.go
vendor/github.com/portworx/kdmp/pkg/controllers/resourceexport/reconcile.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiabackup/kopiabackup.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiadelete/kopiadelete.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiarestore/kopiarestore.go
vendor/github.com/portworx/kdmp/pkg/drivers/nfscsirestore/nfscsirestore.go
vendor/github.com/portworx/kdmp/pkg/drivers/rsync/rsync.go
vendor/github.com/portworx/kdmp/pkg/drivers/utils/common.go
vendor/github.com/portworx/kdmp/pkg/executor/common.go
vendor/github.com/portworx/kdmp/pkg/version/version.go
vendor/modules.txt

>bug
```
vendor latest kdmp repo from the master branch
```
no
No
no
Note: 
The latest changes from kdmp has directly vendor to the stork release branch from the corresponding KDMP release branch. It was missed for the master branch.

vendor latest kdmp repo from the master branch

---

go.mod
go.sum
vendor/github.com/portworx/kdmp/pkg/controllers/dataexport/reconcile.go
vendor/modules.txt

> Uncomment only one and also add the corresponding label in the PR: clean up
>bug
>feature
>improvement
cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
**What this PR does / why we need it**: this is a vendor commit
```release-note
Issue:
User Impact:
Resolution
```

vendored kdmp master to stork master

---

go.mod
go.sum
vendor/github.com/portworx/kdmp/pkg/executor/common.go
vendor/modules.txt

vendor changes
```
pb-4322: vendored latest kdmp repo from master branch
```
no
na.
23.7.2 branch ( from 1.2.8 branch)

pb-4322: vendored latest kdmp repo from master branch

---

Dockerfile
Makefile
drivers/volume/portworx/portworx.go
test/integration_test/px_statfs_webhook_test.go

bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
cherry-pick PWX-33267 to 23.8
no
no
no

cherry-pick of PWX-33267 to 23.8

---

pkg/resourcecollector/resourcecollector.go
pkg/resourcecollector/virtualmachine.go

>bug
feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
This PR implements feature that enables Kubevirt VMs for px-backup and restore. 
no
```release-note
Issue:
User Impact:
Resolution
```
None
no

PB-4302: Implement automatic resource transformation for Kubevirt

---

pkg/storkctl/clusterpair.go

>improvement
Error message improvement to use the flag "--use-existing-objectstorelocation <name>"
**Test**
➜  stork git:(23.7.3) ✗ ./storkctl create clusterpair uni-cp1 -n mongodb --src-kube-file /tmp/dipti7.config --dest-kube-file /tmp/dipti5.config --s3-access-key **** --s3-secret-key **** --s3-endpoint ***.purestorage.com --s3-region us-east1 -p s3 -u
Destination portworx endpoint is 10.13.192.154:9001
error: objectstoreLocation uni-cp1 already exists in source cluster …

PWX-33569: Explicitily mention to use "--use-existing-objectstorelocation <name>" in error messages.

---

pkg/apis/stork/v1alpha1/backuplocation.go

>bug
```
Made sse in backuplocation CR to be public by changing it to SSE
```
no
NA ( will add once the full support is added)
23.8.0

Made sse in backuplocation CR to be public by changing it to SSE

---

test/integration_test/common_test.go
test/integration_test/migration_failover_failback_test.go
test/integration_test/migration_test.go
test/integration_test/stork-test-pod.yaml
test/integration_test/test-deploy.sh

Running Stork test with Unidirectional Pairing
Local Run -
--- PASS: TestMigration (2087.03s)
--- PASS: TestMigration/testMigration (2008.49s)
--- PASS: TestMigration/testMigration/statefulsetTest (532.92s)
--- PASS: TestMigration/testMigration/statefulsetStartAppFalseTest (939.39s)
--- PASS: TestMigration/testMigration/statefulsetRuleTest (528.34s)
--- PASS: TestMigration (1924.43s)
--- PASS: TestMigration/testMigration (1845.88s)
--- PASS: TestMigration/testMigration/labelSelectorTest (927.49s)
--- PASS: TestMigration/testMigration/labelExcludeSelectorTest (910.99s)
New test -
--- PASS: TestMigration (426.84s)
--- PASS: TestMigration/testMigration (346.96s)
--- PASS: …

New Unidirectional Testing Changes

---

pkg/applicationmanager/controllers/applicationrestore.go

>bug
```
pb-4449: Fixed the issue of namespaceMapping getting overwritten in the volume
stage update.
```
No
```release-note
Issue: If the namespace mapping is not mentioned in the applicationrestore CR, the restore succeeds but volumes/resources are not getting restored.
User Impact: The user is forced to specify the namespacemapping, even if they was want to use source namespace by default.
Resolution: Fixed the issue of namespaceMapping getting overwritten in the volume restore stage.
```
23.8 branch
Tested:
```
[root@ip-10-13-196-168 ~]# cat ar.yaml
apiVersion: …
```

pb-4449: Fixed the issue of namespaceMapping getting overwritten in the volume.

---

pkg/apis/stork/v1alpha1/backuplocation.go

>improvement
```
```
no
Will add release note as a feature.
23.9 branch

pb-4278: added change to fetch and update the sse from secret to the backuplocation CR

---

pkg/applicationmanager/controllers/applicationbackup.go

>improvement
```
pb-4290: Added changes to pass sse type to the bucket.NewWriter for S3
bucket.
```
No, Will add it as feature support documentation.
No, Will add it as feature support documentation.
23.9 branch.
**Testing:**
Add the details in the px-backup depended PR: 
https://github.com/portworx/px-backup/pull/1337
**More details:**
https://pkg.go.dev/gocloud.dev/blob#WriterOptions
https://github.com/google/go-cloud/blob/master/blob/example_test.go#L407
**Note:** Similar changes is need for CSI driver path. Will take it in separate PR. …

pb-4290: Added changes to pass sse type to the bucket.NewWriter for S3 bucket.

---

test/integration_test/common_test.go
test/integration_test/migration_features_test.go

Tests for stash strategy feature in migration.
Successful run - https://jenkins.pwx.dev.purestorage.com/job/Users/job/dipti/job/diptistorkcustom/5/

PWX-33339: Stashstrategy integration tests for mongodb and kafka operator.

---

test/integration_test/common_test.go
test/integration_test/migration_features_test.go

Does multiple migrations and check for objecthash check happens and stash ConfigMap does not get always recreated.
Also added failback tests.
**Test**
https://jenkins.pwx.dev.purestorage.com/job/Users/job/dipti/job/diptistorkcustom/11/console
https://jenkins.pwx.dev.purestorage.com/job/Users/job/dipti/job/diptistorkcustom/17/console
All tests run - https://jenkins.pwx.dev.purestorage.com/job/Users/job/dipti/job/diptistorkcustom/20/

PWX-33339: Stashstrategy tests with multiple migrations and checking for the resource getting reused.

---

pkg/applicationmanager/controllers/applicationbackup.go
pkg/utils/utils.go

>bug
```
- Restrict backup of namespace where portworx is installed in case of all namespaces i.e. *
- Restrict backup of namespace where portworx is installed in case of label-selector
- Allow backup of namespace where portworx is installed in case API is specifically passing it i.e. namsespace=kube-system in API call
```
no
```release-note
Issue: #PB-3046
User Impact: User will not be able to backup namespace where portworx is installed if tried with label-selector or all namespace
Resolution: If user wants to backup namespace where portworx is installed the one needs to pass it specifically as namsespace=kube-system in API calls
``` …

PB-3046 :: Restrict portworx ns backup

---

go.mod
go.sum
vendor/github.com/portworx/kdmp/pkg/controllers/dataexport/reconcile.go
vendor/github.com/portworx/kdmp/pkg/executor/common.go
vendor/modules.txt

>bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
```release-note
Issue:
User Impact:
Resolution
```
**Does this change need to be cherry-picked to a release branch?**: Yes to 23.0.9

PB-4606: Vendor KDMP Changes

---

go.mod
go.sum

fix vendor for go mod tidy changes

---

drivers/volume/portworx/portworx.go

>bug
```
pb-4683: Added fix to pass the destination namespace in locator to PX,
if ns mapping is passed.
- Added checks such the destination namespace value will be
passed in the locator namespacelabel map, if it is present.
- Similarly added fix for the storageclass map, where the values
will be passed only the sc mapping provided.
```
No
```release-note
Issue: Restore of RWX portworx volume to a different namespace fails.
User Impact: User will not be able to restore the backup with RWX portworx volume to a different namespace in different destination cluster. …
```

pb-4683: Added fix to pass the destination namespace in locator to PX, if ns mapping is passed.

---

test/integration_test/kubevirt_test.go

If PVC templates exist, don't wait for importer pods to be triggered,
no
no
23.10

skip waiting for importer pods, if template PVCs already exist

---

test/integration_test/kubevirt_test.go
test/integration_test/specs/kubevirt-fedora/fedora-vm.yaml
test/integration_test/specs/kubevirt-templates/windows/windows-template-pvc.yaml
test/integration_test/specs/kubevirt-windows-22k-server/windows-vm.yaml

https://portworx.atlassian.net/browse/PTX-20950
no
no
23.10.0

deploy and validate windows 2022 server kubevirt VM

---

test/integration_test/common_test.go
test/integration_test/migration_test.go

This PR is needed for stork cloud jobs to run migration tests on AKS/GKE
Test Run on AKS - https://jenkins.pwx.dev.purestorage.com/job/Stork/view/Stork%20Cloud%20Jobs/job/stork-aks-migration/1/

PTX-20723 - Stork Cloud Jobs fix

---

test/integration_test/kubevirt_test.go
test/integration_test/specs/kubevirt-fedora-wait-first-consumer/fedora-vm-wait-first-consumer.yaml
test/integration_test/specs/kubevirt-templates/portworx/sc-sharedv4svc-nolock-wait-first-consumer.yaml
test/integration_test/specs/kubevirt-windows-22k-server-wait-first-consumer/windows-vm.yaml

Verifying: https://github.com/kubevirt/containerized-data-importer/blob/main/doc/waitforfirstconsumer-storage-handling.md
https://portworx.atlassian.net/browse/PTX-20952
no
no
no

specs for wait for first consumer

---

test/integration_test/kubevirt_hyperconv_test.go
test/integration_test/kubevirt_test.go

>bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
no
no
no

add windows VM to KubeVirt hyperconvergence tests

---

test/integration_test/applicationbackup_test.go

Changed backup tests sequence
Passed Job - https://jenkins.pwx.dev.purestorage.com/job/Stork/view/Stork%2023.8-dev/job/backup-k8s-1-25-0/1129/consoleText

Changed backup tests sequence

---

pkg/migration/controllers/migration.go

>bug
[PWX-34708](https://portworx.atlassian.net/browse/PWX-34708)
To carry forward the appropriate replicas value in case of multi-DR
For now we have only fixed the bug for normal application resources and CRs with suspend options defined.
Changes for CRs with stashStrategy enabled will be taken up separately.
No
Yes, TBD
Yes, 23.11.0
Have manually tested my changes in a setup of 3 clusters with ASYNC-ASYNC relationship. (Metro or Async should not matter from code point of view)
Have tested that correct annotation is carried forward for following cases …

[PWX-34708] Support multi-DR for normal application resources and CRs with suspend options

---

pkg/storkctl/migrationschedule.go

>improvement
Adding support for new migrationSchedule param `ExcludeResourceTypes` as part of storkctl create migrationschedule cli
Yes
```
[root@ip-10-13-192-45 configs]# storkctl create migrationschedule -h
Create a migration schedule
Usage:
storkctl create migrationschedules [flags]
Aliases:
migrationschedules, migrationschedule
Flags:
--admin-cluster-pair string            Specify the name of the admin ClusterPair used to migrate cluster-scoped resources, if the ClusterPair is present in a non-admin namespace
--annotations stringToString           Add required annotations to the resource in comma-separated key value pairs. key1=value1,key2=value2,...  (default []) …
```

[PWX-35097]Adding ExcludeResourceTypes param in storkctl create migrationschedule

---

pkg/applicationmanager/controllers/applicationbackup.go

- The post exec rule is not executed if the backup has portworx volume in it. Fixed it by moving out of a "if" check.
>bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
**What this PR does / why we need it**: post exec rule were not executed if a backup has portworx volume in it. Hence it is  fixed now.
**Is a release note needed?**: No , Since this regerasssion happened due to a bug fix in  unrelased 23.9 branch and no other branch has this issue. 
```release-note
Issue:
User Impact:
Resolution
```
**Does this change need to be cherry-picked to a release branch?**: 23.9 …

pb-4978: fixed execution miss of post-exec rule during backup

---

test/integration_test/common_test.go
test/integration_test/specs/storkctl-specs/migrationschedule/custom-async-migration-schedule.yaml
test/integration_test/specs/storkctl-specs/migrationschedule/custom-sync-migration-schedule.yaml
test/integration_test/specs/storkctl-specs/migrationschedule/default-async-migration-schedule.yaml
test/integration_test/specs/storkctl-specs/migrationschedule/default-sync-migration-schedule.yaml
test/integration_test/storkctl_migrationschedule_test.go
test/integration_test/storkctl_schedulepolicy_test.go

In this PR, we add integration tests for testing creation of migrationschedules using storkctl cli.
No
No
Yes, stork 23.11.0
Have run a jenkins job and verified that TestStorkCtlSchedulePolicy and TestStorkCtlMigrationSchedule tests are passing
https://jenkins.pwx.dev.purestorage.com/job/Users/job/omkar/job/omkar-storkctl-schedulepolicy/23
```
--- PASS: TestStorkCtlMigrationSchedule (32.00s)
21:02:06      --- PASS: TestStorkCtlMigrationSchedule/createDefaultAsyncMigrationScheduleTest (7.04s)
21:02:06      --- PASS: …
```

[PWX-32336]: adding integration tests for validating storkctl create migrationschedule changes

---

.travis.yml
Makefile
drivers/volume/kdmp/kdmp.go
go.mod
go.sum
pkg/applicationmanager/controllers/applicationbackup.go
pkg/migration/controllers/migration.go
test/integration_test/operator_test.go
vendor/github.com/portworx/kdmp/pkg/controllers/dataexport/reconcile.go
vendor/modules.txt

>bug
```
pb-5019: vendoring kdmp repo from master branch
```
no
no - Will add it for original bug pb-4872
23.9.1 and 23.11

pb-5019: vendoring kdmp repo from master branch

---

test/integration_test/kubevirt_hyperconv_test.go
test/integration_test/kubevirt_test.go
test/integration_test/specs/kubevirt-fedora-multi-disks-wffc/fedora-multi-disks-wffc.yaml
test/integration_test/specs/kubevirt-templates/fedora/fedora-template-pvc-rootdisk.yaml
test/integration_test/specs/kubevirt-templates/portworx/sc-sharedv4svc-nolock-wait-first-consumer.yaml
test/integration_test/specs/kubevirt-templates/portworx/sc-sharedv4svc-nolock.yaml
test/integration_test/specs/kubevirt-windows-22k-server-wait-first-consumer/windows-vm.yaml
test/integration_test/specs/kubevirt-windows-22k-server/windows-vm.yaml

>bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
Refactored the existing hyperconvergence tests to add multi-volume VMs and verify that:
1. PVCs for the same VM should have replicas on the same nodes
2. Volumes for the same VM should be attached to the same replica node after the failover
no
no
no

PWX-34632: tests for KubeVirt pvc co-location of replicas and attachment

---

test/integration_test/migration_test.go
test/integration_test/specs/exclude-multiple-resourcetypes-migration/migration.yaml
test/integration_test/specs/exclude-nonexisting-resourcetype-migration/migration.yaml
test/integration_test/specs/exclude-resourcetype-deployment/migration.yaml
test/integration_test/specs/exclude-resourcetype-migration/migration.yaml
test/integration_test/specs/exclude-resourcetype-pvc/migration.yaml
test/integration_test/specs/exclude-resourcetype-selector/migration.yaml

Tests for the newly added excludeResourceType parameter.
**Test**
`
Ran the tests locally and following is the result.
--- PASS: TestMigration (2742.82s)
--- PASS: TestMigration/testMigration (2661.95s)
--- PASS: TestMigration/testMigration/excludeResourceTypeTest (461.22s)
--- PASS: TestMigration/testMigration/excludeResourceTypePVCTest (437.38s)
--- PASS: TestMigration/testMigration/excludeMultipleResourceTypesTest (416.45s)
--- PASS: TestMigration/testMigration/excludeResourceTypesWithSelectorsTest (439.33s)
--- PASS: …

PWX-34441: Integration tests for excludeResourceType parameter.

---

test/integration_test/migration_test.go

Cleaning up destination namespaces after migration tests.
**Test Run**
https://jenkins.pwx.dev.purestorage.com/job/Stork/view/Stork%2023.11-dev/job/Bidirectional-Migration/78/

PWX-35383: Cleaning up destination namespaces after migration tests.

---

pkg/action/action.go
pkg/apis/stork/v1alpha1/action.go
pkg/storkctl/action.go
test/integration_test/common_test.go

api-change
ActionCR changes with new failover and failback operations.

PWX-35851: Changes to actionCR definition for accommodating failover and failback actions.

---

pkg/applicationmanager/controllers/applicationbackup.go

>feature
When the VM backup is taken, stork creates Rule CRs which are not automatically deleted, now changes are added in the cleanupResources function, which detects the rules created by stork and then deletes them.
```release-note
Issue:
User Impact:
Resolution
```

PB-5381: When the cleanupResources function is called, then the rule CRs created by stork for VM backup are deleted/cleaned up as well.

---

go.mod
go.sum
vendor/github.com/portworx/kdmp/pkg/controllers/dataexport/reconcile.go
vendor/github.com/portworx/kdmp/pkg/controllers/resourceexport/reconcile.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiabackup/kopiabackup.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiadelete/kopiadelete.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiamaintenance/kopiamaintenance.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiarestore/kopiarestore.go
vendor/github.com/portworx/kdmp/pkg/drivers/nfsbackup/nfsbackup.go
vendor/github.com/portworx/kdmp/pkg/drivers/nfscsirestore/nfscsirestore.go
vendor/github.com/portworx/kdmp/pkg/drivers/nfsdelete/nfsdelete.go
vendor/github.com/portworx/kdmp/pkg/drivers/nfsrestore/nfsrestore.go
vendor/github.com/portworx/kdmp/pkg/drivers/utils/utils.go
vendor/modules.txt

bug: #PB-4572
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
Added display of jobpod logs,events and description in case of job failure scenarios.
no
```release-note
Issue:
User Impact:
Resolution
```
no

Vendor kdmp changes for adding job podlogs,events and description

---

go.mod
go.sum
vendor/github.com/portworx/kdmp/pkg/controllers/dataexport/reconcile.go
vendor/github.com/portworx/kdmp/pkg/controllers/resourceexport/reconcile.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiabackup/kopiabackup.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiadelete/kopiadelete.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiamaintenance/kopiamaintenance.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiarestore/kopiarestore.go
vendor/github.com/portworx/kdmp/pkg/drivers/nfsbackup/nfsbackup.go
vendor/github.com/portworx/kdmp/pkg/drivers/nfscsirestore/nfscsirestore.go
vendor/github.com/portworx/kdmp/pkg/drivers/nfsdelete/nfsdelete.go
vendor/github.com/portworx/kdmp/pkg/drivers/nfsrestore/nfsrestore.go
vendor/github.com/portworx/kdmp/pkg/drivers/utils/utils.go
vendor/modules.txt

bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
Vendoring 1.2.11 changes to 24.1.0 branch
no
no

Vendor kdmp 1.2.11 changes to 24.1.0

---

Makefile

* As part of the travis cleanup, we need to move the `make test` command that runs unit tests, inside a docker container
no
no
no

move make test inside a docker container

---

go.mod
go.sum
vendor/github.com/portworx/kdmp/pkg/controllers/dataexport/reconcile.go
vendor/modules.txt

>bug
```
pb-5438: vendoring kdmp repo from master branch
```
no
no
24.1.0

pb-5438: vendoring kdmp repo from master branch

---

pkg/applicationmanager/controllers/applicationbackup.go

fix
This PR reverts the switch case block introduced as part of 15cc00444 since in switch case, a `break` statement for the `for` loop had to be added for the `Failed` status case and in order to do that we had to add a `label` to the loop and then break that. This was introducing a `goto` statement like workflow in the code which is not a widely accepted practice and can introduce bugs/regression.
No

fix: revert the switch block introduced in `15cc00444`

---

pkg/aetosutils/dashboardutils.go
pkg/buildinfo/buildinfo.go
pkg/log/log.go
pkg/restutil/restutil.go
test/integration_test/common_test.go
test/integration_test/health_monitor_test.go
test/integration_test/stork-test-pod.yaml
test/integration_test/test-deploy.sh
vendor/github.com/portworx/torpedo/pkg/stats/stats.go

https://aetos.pwx.purestorage.com/resultSet/testSetID/542577 
The test fail is suppose to fail since I introduced the error for testing.

Adding aetos support to stork

---

test/integration_test/common_test.go
vendor/github.com/portworx/torpedo/pkg/stats/stats.go

https://jenkins.pwx.dev.purestorage.com/job/Users/job/Aniket/job/stork_test/12/console

Fixing the vendoring issue

---

test/integration_test/common_test.go

>bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
```release-note
Issue:
User Impact:
Resolution
```

Fixing nil pointer in stork CBT

---

pkg/aetosutils/dashboardutils.go

Remove print statements not required in the pod logs
no
no
no

removing logs that are not required

---

pkg/aetosutils/dashboardutils.go

cleanup
Fixing the unused variable.
no
no
no

Removing unused variable

---

test/integration_test/common_test.go
test/integration_test/kubevirt_hyperconv_test.go
test/integration_test/kubevirt_test.go
test/integration_test/stork-test-pod.yaml
test/integration_test/test-deploy.sh

* Add scaling for existing tests with respect to kubevirt VMs being deployed
* Create `ClusterRole` and `ClusterRoleBinding` dynamically for datavolume permissions
no
no 
no

Scale kubevirt

---

pkg/extender/extender_test.go
pkg/mock/kubevirt/kubevirt.ops.mock.go
pkg/mock/osd/driver.mock.go

Since CBTs do not rebase PRs with master, even though CBT passed on a branch, once merged it failed on master.
Fixing the static check problems. 
Also fixed a flaky UT
No
No
No

Fix staticcheck and flaky UT failures

---

Dockerfile

improvement
Reducing stork image size by removing unused  google-cloud-sdk contents.
no
```release-note
Issue: Stork image size was too big (appx. 3.8G).
User Impact: Image download was taking longer time.
Resolution: Optimized the stork image size to 1.64G.
```
yes, 24.2.0
**Test**:
https://jenkins.pwx.dev.purestorage.com/job/Stork/view/Stork%20Cloud%20Jobs/job/stork-gke-migration/27/

PWX-36622: Optimize stork image by removing unused contents from google-cloud-sdk.

---

go.mod
go.sum
vendor/github.com/portworx/kdmp/pkg/controllers/dataexport/reconcile.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiamaintenance/kopiamaintenance.go
vendor/github.com/portworx/kdmp/pkg/drivers/options.go
vendor/github.com/portworx/kdmp/pkg/drivers/rsync/rsync.go
vendor/github.com/portworx/kdmp/pkg/drivers/utils/utils.go
vendor/modules.txt

Vendoring
Vendored kdmp 1.2.11 .
no
no
no

Vendoring 1.2.11 kdmp to stork 24.1.0 .

---

go.mod
go.sum
vendor/github.com/portworx/kdmp/pkg/controllers/dataexport/reconcile.go
vendor/modules.txt

>bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
- Vendor master kdmp for fixing bug PB-6351: KDMP backup will fail, if the pvc name is more than 63 char as we them as labels.
```release-note
Issue:
User Impact:
Resolution
```

vendor master kdmp

---

pkg/applicationmanager/controllers/applicationbackup.go

>improvement
Earlier partial success was not happening for NFS location, now it is happening for NFS location as well.
```release-note
Issue:
User Impact:
Resolution
```

PB-6138: Making partial success work with NFS location as well

---

test/integration_test/kubevirt_hyperconv_test.go

When restarting PX on the node, we were not waiting for PX to become ready. This was causing the test to fail intermittently because PX was down on 2 nodes at the same time.
no
no

PWX-36526: wait for px to be ready after restart

---

pkg/action/actioncontroller.go
pkg/action/drutils.go
pkg/action/failback.go
pkg/action/failover.go
pkg/apis/stork/v1alpha1/action.go
pkg/storkctl/action.go
pkg/storkctl/action_test.go

>feature
Make changes wrt metro-dr in failover and failback.
No
No
Yes, 24.2.0

PWX-36485 : action controller dr changes wrt metro-dr

---

test/integration_test/migration_test.go

Signed-off-by:  Diptiranjan
no
no
no
**Test**
https://jenkins.pwx.dev.purestorage.com/job/Stork/view/Stork%2023.11.1-dev/job/migration-op-k8s-1-25-0/112/

PWX-36868: Integration test fix for right assert wrt number of migrations.

---

pkg/storkctl/actionstatus_test.go
test/integration_test/storkctl_dr_action_test.go
test/integration_test/storkctl_migrationschedule_test.go

Adds required util functions to perform failover/failback actions and get failover/failback status.
No
No
Yes, 24.2.0
**Testing Details**:
Have run the tests locally.
[Jenkins job URL](https://jenkins.pwx.dev.purestorage.com/job/Users/job/omkar/job/action/2)

DR workflow automation for CLI commands

---

test/integration_test/kubevirt_hyperconv_test.go

>bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
- set fix-vps job frequency to 1 minute to reduce the test run time
- use the typed client directly
no
no
no

fixed a couple of TODOs in kubevirt hyperconvergence tests

---

pkg/action/failback.go
pkg/action/failover.go

>bug
Move the status of the CR to InProgress from Initial when we enter the processing for each stage
No
No
Yes, 24.2.0

Move action status to In-Progress from Initial

---

test/integration_test/storkctl_dr_action_test.go

>bug
The current parsing logic is inaccurate. Have fixed the logic to handle all cases successfully.
No
No
Yes, 24.2.0

fixing the get action status parsing

---

drivers/volume/kdmp/kdmp.go

bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
For Direct KDMP if the snapshot taken is larger than the PVC size, then restore will fail with error no space left to write on device. This was handled for CSI based backup/restore by updating the PVC size to match the size of the snapshot.
This PR addresses the same by implementing it in KDMP for direct KDMP case. 
no
```release-note
Issue:  Restore of PVC from backup for which the snapshot size was greater the PVC fails. 
User Impact: Restore failure …
```

fix: PB-4394 KDMP restore of a PVC which is completely full fails

---

pkg/snapshotter/snapshotter_csi.go

bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
For CSI snapshots that take more than 5 mins to take snapshot, there is no configurable way to change the timeout.
This PR makes use of SNAPSHOT_TIMEOUT in kdmp-config for timeout settings and change the default timeout to 30mins. 
no
```release-note
Issue:
User Impact:
Resolution
```
no

fix: PB-6814 Backup with CSI with offload fails on OCP with cephfs intermittently

---

pkg/applicationmanager/controllers/applicationbackup.go

bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
This PR fixes PB-6598. For vm backup we make inmemory objectMap from includeResource. When stork restarts this memory is lost. Hence, we need to re populate this. 
no
```release-note
Issue:
User Impact:
Resolution
```
Unit tested this by restarting stork at various stages of applicationBackup.

fix: PB-6598 Scheduled VM backup intermittently takes zero resource backup

---

pkg/applicationmanager/controllers/applicationrestore.go

>failing-test
Revert PB-6687 related changes
No
release-24.1.0, release-24.2.0

PB-6899 :: Revert PB-6687 related changes

---

test/integration_test/applicationbackup_test.go

add automated testrail updates for test cases missed out

---

go.mod
go.sum
vendor/github.com/portworx/kdmp/pkg/controllers/dataexport/reconcile.go
vendor/github.com/portworx/kdmp/pkg/executor/common.go
vendor/modules.txt

>bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
**What this PR does / why we need it**: It vendors latest 1.2.12 changes to stork 2.7.1-pxb
**Does this PR change a user-facing CRD or CLI?**:no
**Is a release note needed?**:no
```release-note
Issue:
User Impact:
Resolution
```

PB-6862-vendor: vendor 1.2.12 kdmp to stork 2.7.1-pxb

---

pkg/apis/stork/v1alpha1/backuplocation.go
pkg/applicationmanager/controllers/applicationrestore.go
pkg/objectstore/azure/azure.go

>bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
**What this PR does / why we need it**: It will push the changes from 2.7.1-pxb to the master stork
```release-note
Issue:
User Impact:
Resolution
```

PB-6862-master: Merge changes from 2.7.1-pxb stork master

---

pkg/log/log.go

>bug
>feature
improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
**What this PR does / why we need it**: 
This PR removes the duplicate logging in stork tests/ 
no
no
no

Adding fix to remove duplicate logging

---

go.mod
go.sum
vendor/github.com/portworx/kdmp/pkg/controllers/dataexport/reconcile.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiamaintenance/kopiamaintenance.go
vendor/github.com/portworx/kdmp/pkg/drivers/options.go
vendor/github.com/portworx/kdmp/pkg/executor/common.go
vendor/github.com/portworx/kdmp/pkg/version/version.go
vendor/modules.txt

>bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
**What this PR does / why we need it**: it vendors 1.2.12 kdmp branch to the release-24.2.1 stork
**Does this PR change a user-facing CRD or CLI?**:no
```release-note
Issue:
User Impact:
Resolution
```

PB-6862-release: vendor 1.2.12 kdmp branch to the release-24.2.1 stork

---

go.mod
go.sum
vendor/github.com/portworx/kdmp/pkg/controllers/dataexport/reconcile.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiadelete/kopiadelete.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiamaintenance/kopiamaintenance.go
vendor/github.com/portworx/kdmp/pkg/drivers/options.go
vendor/github.com/portworx/kdmp/pkg/executor/common.go
vendor/modules.txt

>bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
**What this PR does / why we need it**: to vendor kdmp master to stork master
**Does this PR change a user-facing CRD or CLI?**:na
**Is a release note needed?**:na
```release-note
Issue:
User Impact:
Resolution
```
**Does this change need to be cherry-picked to a release branch?**:na

PB-6862-vendor-kdmp: vendor kdmp master to stork master

---

Makefile

>bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
It fixes the release version for build pipeline
```release-note
Issue:
User Impact:
Resolution
```

Fix for release version

---

Makefile
drivers/volume/csi/csi.go
drivers/volume/kdmp/kdmp.go
drivers/volume/portworx/portworx.go
go.mod
go.sum
pkg/apis/stork/v1alpha1/applicationbackup.go
pkg/applicationmanager/controllers/applicationbackup.go
pkg/applicationmanager/controllers/applicationbackupschedule.go
pkg/applicationmanager/controllers/applicationrestore.go
pkg/utils/utils.go
vendor/modules.txt

Enhancement
Adds support for Partial Success backup
No
No
Yes
Note: As part of release notes, we will add this

Support for Partial Success Backup

---

test/integration_test/migration_dr_actions_test.go

Addresses PWX-36986. Adds tests for the following cases:
1. [[Failback] Perform failback of an app whose number of replicas have been modified in secondary after failover. ](https://portworx.testrail.net/index.php?/cases/view/257160)
2. [[Failback] Perform failback of a subset of namespaces which have been activated after failover.](https://portworx.testrail.net/index.php?/cases/view/257159)
No
No
**Test runs**
- Pipeline run: https://jenkins.pwx.dev.purestorage.com/blue/organizations/jenkins/Stork%2Fapplication-backup-24-1/detail/application-backup-24-1/2242/pipeline
- Local run:

pwx-36986 | test: add failback integration tests for new dr workflow

---

pkg/extender/extender.go
pkg/extender/extender_test.go

>bug
>feature
improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
If the operator has added "unschedulable" annotation on a node, exclude that node from the filter response.
no
no
24.2.1

PWX-37335: honor operator's unschedulable annotation

---

pkg/applicationmanager/controllers/applicationrestore.go

>bug
```
pb-7035: fixed issue in the check to route the PXD/NFS to not nfs logic for restore.
```
No
NA. 
24.2.1 branch
**Testing:
Validate restore of following cases:**
1) restore from backup with CSI/PXD from NFS BL.
2) restore from backup with KDMP/PXD from NFS BL.
3) restoring from backup CSI/PXD from NFS BL with restoring only PXD and only CSI.

pb-7035: fixed issue in the check to route the PXD/NFS to not nfs logic for restore.

---

test/integration_test/migration_dr_actions_test.go

No
No
`release-24.2.0` branch
**Test runs**
- Pipeline run: https://jenkins.pwx.dev.purestorage.com/job/Users/job/strivedi/job/strivedi-cluster-domain/3/console
- Local run

pwx-34666 | test: add tests for failback workflow in sync dr

---

pkg/applicationmanager/controllers/applicationbackup.go

Update backup cr status to failed status if backup failed to get started by portworx driver
bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
**What this PR does / why we need it**: 
**RCA**
**Situation** - Before running the post exec rule, we check if the snapshot id is populated for every volume
**Bug** - If the snapshot id is not populated, we return nil at this point and we keep looping in the `volume in Progress` until the snapshot id is populated.
In case where the backup fails in the inital stages only, before the backup starts (because of wrong credential or may be any other reason), we will keep looping in the in …

 PB-6976: Update backup cr status to failed status if backup failed to get started by portworx driver

---

pkg/extender/extender.go
pkg/extender/extender_test.go

>bug
>feature
improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
If the operator has added "unschedulable" annotation on a node, exclude that node from the filter response.
no
no
no

[cherry-pick] PWX-37335: honor operator's unschedulable annotation (#1778)

---

test/integration_test/kubevirt_hyperconv_test.go

>bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
This avoid intermittent failures due to VMI flippping to "not ready" for a very short time.
no
no
no

PWX-37154: handle transient "not ready" condition in the VMI

---

pkg/applicationmanager/controllers/applicationrestore.go

bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
**What this PR does / why we need it**: When taking Cloud Based CSI Backup such azure, gce, aws the csi based backup in case of replcace in default restore was going in pending state upon find the root cause the removeCSIVolumeBeforeApply was replacing the csi based pvc to default way. 
```release-note
Issue:
User Impact:
Resolution
```
ApplicationBackup
```
kind: ApplicationBackup …
```

PB-7158, PB-7159: Fix Handling of Cloud Based CSI Backups

---

pkg/apis/stork/v1alpha1/applicationbackup.go

This reverts commit 81de2400f2b1237f718759de197261905eef48de.
>bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
**What this PR does / why we need it**: This change of PSA going to 2.7.2 due to adding some extra use case pertaining to rancher environment. 
**Is a release note needed?**: No 
```release-note
Issue:
User Impact:
Resolution
```
**Does this change need to be cherry-picked to a release branch?**: No 
This is reverting a commit which. is never utilized certain data structure in the current code since that code will be moved to 2.7.2 release

Revert "pb-6910: add uid & gid in each volume for psa support"

---

pkg/utils/utils.go

>bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
**What this PR does / why we need it**: fix a static error in code
```release-note
Issue:
User Impact:
Resolution
```

fixed a static code error related PSA

---

pkg/utils/utils.go

- If backup is taken without psa enabled and restored in a psa environment then application backup CR won't have jobsecurityContext in its volumeinfo
- This caused the function to return user as root instead of undefinedId this caused the securityContext to get added and job pod failed
- handled the root user defination exclusively when deciding whether to add security context or not
>bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
**What this PR does / why we need it**: if backup taken in a release where in no spa feature present then we need to handle the restore path how to deal with the securityContext
**Does this PR change …

pb-7392: handled upgrade issues with psa

---

Makefile
drivers/volume/kdmp/kdmp.go
go.mod
go.sum
pkg/applicationmanager/controllers/applicationbackupschedule.go
pkg/utils/utils.go
vendor/github.com/portworx/kdmp/pkg/controllers/dataexport/reconcile.go
vendor/modules.txt

Feature
Code changes to pass dynamic kdmp path as part of bkp schedule
No
No
No

Pb 6857: Code changes to pass dynamic kdmp path as part of bkp schedule

---

test/integration_test/common_test.go
test/integration_test/migration_test.go

>improvement
Increases the timeout in integration tests to 15 minutes from 10 minutes.
No
No
No

test: increase timeouts in integration tests

---

go.mod
go.sum
vendor/github.com/portworx/kdmp/pkg/drivers/nfsbackup/nfsbackup.go
vendor/github.com/portworx/kdmp/pkg/drivers/nfsrestore/nfsrestore.go
vendor/github.com/portworx/kdmp/pkg/drivers/utils/utils.go
vendor/modules.txt

>bug
```
vendor kdmp repo from master branch
```
no
no
24.3.0

vendor kdmp repo from master branch

---

test/integration_test/extender_test.go
test/integration_test/specs/test-mysql-1-pvc-strong-hyperconvergence/mysql.yaml
test/integration_test/specs/test-mysql-1-pvc-strong-hyperconvergence/portworx/px-sc.yaml
test/integration_test/specs/test-mysql-2-pvc-strong-hyperconvergence/mysql.yaml
test/integration_test/specs/test-mysql-2-pvc-strong-hyperconvergence/portworx/sc.yaml

StronghyperconvergenceTests with pods using one and two pvcs. 
no
no
no
**Test**:
```
time="2024-08-01T13:50:38Z" level=warning msg="Skipping testrail update for this case, testID: 300007, testrun: 0"
--- PASS: TestExtender (328.36s)
--- PASS: TestExtender/stronghypeconvergenceTest (91.01s)
--- PASS: TestExtender/stronghypeconvergenceTest#01 (230.94s)
```
https://jenkins.pwx.dev.purestorage.com/job/Users/job/strivedi/job/extender-fork/2/

PWX-38384: Strong hyperconvergence tests with stork as scheduler.

---

test/integration_test/snapshot_test.go

Closes [PWX-38027](https://purestorage.atlassian.net/browse/PWX-38027). Adds integration test for modifying the retain value in the schedule policy for volumesnapshotschedule and then verifying if the expected amount of snapshots are present while the non-expected ones are pruned.
No
No
**Test run**
```
--- PASS: TestSnapshot (594.27s)
--- PASS: TestSnapshot/testSnapshot (589.25s)
--- PASS: TestSnapshot/testSnapshot/scheduleTests (584.23s)
--- PASS: TestSnapshot/testSnapshot/scheduleTests/updateRetainValueTest (580.84s)
--- PASS: TestSnapshot/testSnapshotRestore (5.02s)
PASS
time="2024-08-03T21:59:47Z" level=info …
```

pwx-38027: test for modifying retain values in schedule policy of snapshotschedule

---

go.mod
go.sum
test/integration_test/common_test.go
vendor/github.com/portworx/sched-ops/k8s/core/core.go
vendor/github.com/portworx/sched-ops/k8s/core/persistentvolumeclaims.go
vendor/github.com/portworx/sched-ops/k8s/core/serviceaccounts.go
vendor/github.com/portworx/sched-ops/k8s/kdmp/dataexport.go
vendor/github.com/portworx/sched-ops/k8s/kubevirt-dynamic/kubevirt.go
vendor/github.com/portworx/sched-ops/k8s/kubevirt-dynamic/virtualmachineinstance.go
vendor/github.com/portworx/sched-ops/k8s/kubevirt-dynamic/virtualmachineinstancemigration.go
vendor/github.com/portworx/sched-ops/k8s/kubevirt/virtualmachine.go
vendor/modules.txt

bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
This is to pull in the fix for kubevirt GetVirtualMachineInstance.
no
```release-note
Issue:
User Impact:
Resolution
```
yes

PWX-38532: vendor in sched-ops

---

go.mod
go.sum
test/integration_test/common_test.go
vendor/github.com/portworx/sched-ops/k8s/core/core.go
vendor/github.com/portworx/sched-ops/k8s/core/persistentvolumeclaims.go
vendor/github.com/portworx/sched-ops/k8s/core/serviceaccounts.go
vendor/github.com/portworx/sched-ops/k8s/kdmp/dataexport.go
vendor/github.com/portworx/sched-ops/k8s/kubevirt-dynamic/kubevirt.go
vendor/github.com/portworx/sched-ops/k8s/kubevirt-dynamic/virtualmachineinstance.go
vendor/github.com/portworx/sched-ops/k8s/kubevirt-dynamic/virtualmachineinstancemigration.go
vendor/github.com/portworx/sched-ops/k8s/kubevirt/virtualmachine.go
vendor/modules.txt

bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
This is to pull in the fix for kubevirt GetVirtualMachineInstance.
no
```release-note
Issue:
User Impact:
Resolution
```
no

[cherry-pick] PWX-38532: vendor in sched-ops

---

go.mod
go.sum
vendor/github.com/portworx/kdmp/pkg/controllers/dataexport/reconcile.go
vendor/github.com/portworx/kdmp/pkg/controllers/resourceexport/reconcile.go
vendor/github.com/portworx/kdmp/pkg/drivers/drivers.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiabackup/kopiabackup.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiarestore/kopiarestore.go
vendor/github.com/portworx/kdmp/pkg/drivers/nfsbackup/nfsbackup.go
vendor/github.com/portworx/kdmp/pkg/drivers/nfscsirestore/nfscsirestore.go
vendor/github.com/portworx/kdmp/pkg/drivers/nfsrestore/nfsrestore.go
vendor/github.com/portworx/kdmp/pkg/drivers/utils/utils.go
vendor/modules.txt

>bug
>feature
>improvement
>cleanup
>api-change
>design
>documentation
>failing-test
>unit-test
**What this PR does / why we need it**: to vendor latest changes from kdmp branch 1.2.15 to stork branch pxb-2.8.0
**Does this PR change a user-facing CRD or CLI?**:no
**Is a release note needed?**:no
```release-note
Issue:
User Impact:
Resolution
```
**Does this change need to be cherry-picked to a release branch?**:no

Vendor latest changes from kdmp branch 1.2.15 to stork branch pxb-2.8.0

---

go.mod
go.sum
vendor/github.com/portworx/kdmp/pkg/version/version.go
vendor/modules.txt

Vendor
Vendor which consist of version change to 1.2.15 in version.go
```release-note
Issue:
User Impact:
Resolution
```

Vendor kdmp 1.2.15 with version change

---

test/integration_test/common_test.go
test/integration_test/health_monitor_test.go
test/integration_test/specs/busybox-1-pvc/aws/aws-sc.yaml
test/integration_test/specs/busybox-1-pvc/azure/azure-sc.yaml
test/integration_test/specs/busybox-1-pvc/busbox.yaml
test/integration_test/specs/busybox-1-pvc/gce/gke-sc.yaml
test/integration_test/specs/busybox-1-pvc/linstor/linstor-sc.yaml
test/integration_test/specs/busybox-1-pvc/portworx/px-sc.yaml

Adding integration tests to test halth monitoring with multi number of pods to execute pod deletion in batches path.
no
no
no

PWX-39043: Adding stopDriverTestScale to cover the pod deletion in batches path.

---

drivers/volume/volume.go
pkg/monitor/monitor_test.go

bug
unit-test
Currently stork has the logic of removing the duplicate offline nodes if there exists an online node with same IP.
Extending this logic to check wrt to schedulerID and remove any duplicate offline nodes.
no
yes
```release-note
Issue: Stork health monitor was considering stale node entries which have storage offline for pod eviction.
User Impact:  Pods were getting evicted from an online node if this node gets repaired and come with a different IP address.
Resolution: Storage offline nodes will not get considered for pod evictions if there exists another node with storage status as online but with …
```

PWX-36167: Duplicate offline nodes should be excluded for pod eviction if another online node exists with same scheduler ID.

---

pkg/applicationmanager/controllers/applicationbackup.go

bug
This PR makes sure that the failed volume count is updated correctly in the application backup
We intialize the variable again, after getting the correct number, we try to update the CR then itself
```release-note
Issue:
User Impact:
Resolution
```

PB-8316: Making sure for failed vol delete count is initialized and updated correctly

---

drivers/volume/aws/aws.go
drivers/volume/azure/azure.go
drivers/volume/csi/csi.go
drivers/volume/gcp/gcp.go
drivers/volume/kdmp/kdmp.go
drivers/volume/mock/volume/driver.mock.go
drivers/volume/portworx/portworx.go
drivers/volume/volume.go
pkg/applicationmanager/controllers/applicationbackup.go
pkg/utils/utils.go

**What type of PR is this?** merging pxb-2.8.0 changes to master 
```release-note
Issue:
User Impact:
Resolution
```
**Does this change need to be cherry-picked to a release branch?**: 
yea, cherry pick to release-24.3.3

Merging pxb-2.8.0 changes to master 

---

go.mod
go.sum
vendor/github.com/portworx/kdmp/pkg/controllers/dataexport/reconcile.go
vendor/github.com/portworx/kdmp/pkg/controllers/resourceexport/reconcile.go
vendor/github.com/portworx/kdmp/pkg/drivers/drivers.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiabackup/kopiabackup.go
vendor/github.com/portworx/kdmp/pkg/drivers/kopiarestore/kopiarestore.go
vendor/github.com/portworx/kdmp/pkg/drivers/nfsbackup/nfsbackup.go
vendor/github.com/portworx/kdmp/pkg/drivers/nfscsirestore/nfscsirestore.go
vendor/github.com/portworx/kdmp/pkg/drivers/nfsrestore/nfsrestore.go
vendor/github.com/portworx/kdmp/pkg/drivers/utils/utils.go
vendor/modules.txt

vendor
**What this PR does / why we need it**: vendor kdmp master to stork master
```release-note
Issue:
User Impact:
Resolution
```

PB-7476: vendor kdmp master to stork master

---

test/integration_test/common_test.go
test/integration_test/migration_dr_actions_test.go

Adds couple of required CBT tests and removes a test since it uses the old way of DR. That test is being run in integration tests pipeline periodically.
No
No
No

test: modify cbt tests
